### ISSUE TITLE
"npm profile enable-2fa auth-only" returns EBADKEY

### ISSUE THREAD

**Issue by jakobrosenberg** [npm/cli#1044]
Running ``npm profile enable-2fa auth-only`` returns the following error:
```
PS C:\sandbox> npm profile enable-2fa auth-only
npm notice profile Enabling two factor authentication for auth-only
npm password:
npm ERR! code EBADKEY
npm ERR! invalid config key requested: auth

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jakob\AppData\Roaming\npm-cache\_logs\2020-03-22T07_12_26_365Z-debug.log
```

The entire log can be seen here
<details>

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'profile',
1 verbose cli   'enable-2fa',
1 verbose cli   'auth-only'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose npm-session 5e0135765733f1fc
5 notice profile Enabling two factor authentication for auth-only
6 info profile Determine if tfa is pending
7 http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 444ms
8 verbose stack Error: invalid config key requested: auth
8 verbose stack     at BadKeyError (C:\Users\jakob\AppData\Roaming\nvm\v12.14.1\node_modules\npm\node_modules\figgy-pudding\index.js:93:23)
8 verbose stack     at pudGet (C:\Users\jakob\AppData\Roaming\nvm\v12.14.1\node_modules\npm\node_modules\figgy-pudding\index.js:101:5)
8 verbose stack     at FiggyPudding.get (C:\Users\jakob\AppData\Roaming\nvm\v12.14.1\node_modules\npm\node_modules\figgy-pudding\index.js:27:12)
8 verbose stack     at Object.get (C:\Users\jakob\AppData\Roaming\nvm\v12.14.1\node_modules\npm\node_modules\figgy-pudding\index.js:159:16)
8 verbose stack     at C:\Users\jakob\AppData\Roaming\nvm\v12.14.1\node_modules\npm\lib\profile.js:251:18
8 verbose stack     at processImmediate (internal/timers.js:439:21)
8 verbose stack From previous event:
8 verbose stack     at C:\Users\jakob\AppData\Roaming\nvm\v12.14.1\node_modules\npm\lib\profile.js:245:57
8 verbose stack From previous event:
8 verbose stack     at enable2fa (C:\Users\jakob\AppData\Roaming\nvm\v12.14.1\node_modules\npm\lib\profile.js:242:6)
8 verbose stack     at EventEmitter.profileCmd (C:\Users\jakob\AppData\Roaming\nvm\v12.14.1\node_modules\npm\lib\profile.js:71:14)
8 verbose stack     at Object.commandCache.<computed> (C:\Users\jakob\AppData\Roaming\nvm\v12.14.1\node_modules\npm\lib\npm.js:156:13)
8 verbose stack     at EventEmitter.<anonymous> (C:\Users\jakob\AppData\Roaming\nvm\v12.14.1\node_modules\npm\bin\npm-cli.js:131:30)
8 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:76:11)
9 verbose cwd C:\Users\jakob\sandbox\svelte\dev\svelte-filerouter
10 verbose Windows_NT 10.0.18363
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "profile" "enable-2fa" "auth-only"
12 verbose node v12.14.1
13 verbose npm  v6.13.4
14 error code EBADKEY
15 error invalid config key requested: auth
16 verbose exit [ 1, true ]
```

</details>

**Comment by jakobrosenberg** [comment]
Got it working by first disabling 2fa.

According to the docs, the command should "_Change_ 2FA modes for your user account", but that seems to only work if it has been disabled first.

Either the command should allow changing of 2FA mode or the first word "Change" should be replaced with "Enable" (maybe helped by a more descriptive error).
