### ISSUE TITLE
[BUG] 503 error on `npm dist-tag add` (Service Unavailable)

### ISSUE THREAD

**Issue by davidgilbertson** [npm/cli#1061]
# What / Why
I'm trying to add a dist tag to a release. I'm using the same steps I have previously on the same npm version, and am able to publish. So I guess the issue is somewhere in the infrastructure, rather than a bug in the cli code or related to authentication. (Apologies if this is the wrong repo to log the issue.)

I am logged in:
```
$ npm whoami
davidgilbertson
```

And my package has these tags:
```
$ npm dist-tag ls react-recollect

latest: 5.1.4
next: 5.1.6
```

But if I run the following, it hangs for several minutes:
```
$ npm dist-tag add react-recollect@5.1.6 latest
```

Then after a while creates a log file:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'dist-tag',
1 verbose cli   'add',
1 verbose cli   'react-recollect@5.1.6',
1 verbose cli   'latest'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose npm-session 664377ed3864616e
5 verbose dist-tag add latest to react-recollect@5.1.6
6 http fetch GET 200 https://registry.npmjs.org/-/package/react-recollect/dist-tags 328ms
7 http fetch PUT 503 https://registry.npmjs.org/-/package/react-recollect/dist-tags/latest 221214ms attempt #3
8 verbose stack Error: 503 Service Unavailable - PUT https://registry.npmjs.org/-/package/react-recollect/dist-tags/latest - Service Unavailable
8 verbose stack     at C:\Users\david\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15
8 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
9 verbose statusCode 503
10 verbose pkgid react-recollect@5.1.6
11 verbose cwd C:\web\npm\react-recollect
12 verbose Windows_NT 10.0.18362
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "dist-tag" "add" "react-recollect@5.1.6" "latest"
14 verbose node v12.14.0
15 verbose npm  v6.13.4
16 error code E503
17 error 503 Service Unavailable - PUT https://registry.npmjs.org/-/package/react-recollect/dist-tags/latest - Service Unavailable
18 verbose exit [ 1, true ]
```

I also tried a different tag/release, same issue:
```
$ npm dist-tag add react-recollect@3.0.0 three
```

I've tried with a few other versions and the issue's the same. I'm on Windows 10 and:
```
$ npm version
{
  'react-recollect': '5.1.6',
  npm: '6.13.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.39.2',
  node: '12.14.0',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.7.299.13-node.16',
  zlib: '1.2.11'
}
```

## Who

* n/a

## References

* n/a

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
