### ISSUE TITLE
[BUG] npm ci fails with Cannot find module 'validate-npm-package-name'

### ISSUE THREAD

**Issue by Dyasik** [npm/cli#1157]
## What / Why
Running `npm ci` occasionally fails with error `Cannot find module 'validate-npm-package-name'`. See full log below.
Running `npm ci` right after that finishes successfully.
Note: `npm ci` is run by `gradle`.

## When
It happens after I switch between Git branches, but I can't tell if it happens every time you switch the branch.

## Full error log

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/denis/Projects/piano-vx-18/website/.gradle/nodejs/node-v10.15.1-darwin-x64/bin/node',
1 verbose cli   '/Users/denis/Projects/piano-vx-18/website/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'ci' ]
2 info using npm@6.7.0
3 info using node@v10.15.1
4 verbose npm-session 2b3b3671ee9a5a19
5 info prepare initializing installer
6 verbose prepare starting workers
7 verbose prepare installation prefix: /Users/denis/Projects/piano-vx-18/website
8 verbose prepare using package-lock.json
9 warn prepare removing existing node_modules/ before installation
10 verbose checkLock verifying package-lock data
11 verbose teardown shutting down workers.
12 info teardown Done in 0s
13 verbose stack Error: Cannot find module 'validate-npm-package-name'
13 verbose stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
13 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
13 verbose stack     at Module.require (internal/modules/cjs/loader.js:637:17)
13 verbose stack     at require (internal/modules/cjs/helpers.js:22:18)
13 verbose stack     at Result.setName (/Users/denis/Projects/piano-vx-18/website/node_modules/npm/node_modules/npm-package-arg/npa.js:115:51)
13 verbose stack     at new Result (/Users/denis/Projects/piano-vx-18/website/node_modules/npm/node_modules/npm-package-arg/npa.js:107:23)
13 verbose stack     at Function.resolve (/Users/denis/Projects/piano-vx-18/website/node_modules/npm/node_modules/npm-package-arg/npa.js:54:15)
13 verbose stack     at Object.keys.forEach.name (/Users/denis/Projects/piano-vx-18/website/node_modules/npm/node_modules/lock-verify/index.js:26:26)
13 verbose stack     at Array.forEach (<anonymous>)
13 verbose stack     at Promise.all.then.result (/Users/denis/Projects/piano-vx-18/website/node_modules/npm/node_modules/lock-verify/index.js:25:25)
14 verbose cwd /Users/denis/Projects/piano-vx-18/website
15 verbose Darwin 19.3.0
16 verbose argv "/Users/denis/Projects/piano-vx-18/website/.gradle/nodejs/node-v10.15.1-darwin-x64/bin/node" "/Users/denis/Projects/piano-vx-18/website/node_modules/npm/bin/npm-cli$
17 verbose node v10.15.1
18 verbose npm  v6.7.0
19 error code MODULE_NOT_FOUND
20 error Cannot find module 'validate-npm-package-name'
21 verbose exit [ 1, true ]
```

**Comment by Dyasik** [comment]
How it happened to me today:

- switched to another branch;
- (refreshed Gradle project);
- removed package-lock.json;
- run `npm i` successfully;
- run Gradle task which runs `npm ci`;
- Cannot find module 'validate-npm-package-name'.

**Comment by sk8Guerra** [comment]
I'm also having this issue, but when building it with `travis-ci` to publish a new npm package version:

```js
$ npm ci 
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'validate-npm-package-name'
npm ERR! A complete log of this run can be found in:
```

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
