### ISSUE TITLE
[BUG] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by alysia-dillon** [npm/cli#1172]
Created a sandbox React app for Firebase and used the command `npm i` to reinitialize repo in hopes to troubleshoot after adding in the Firebase config code. It was very early on in the environment build and ended up with this output below:

```
user@admins-MacBook-Pro react-sandbox % npm i
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN rm not removing /Users/user/Sites/react-sandbox/node_modules/.bin/jest as it wasn't installed by /Users/user/Sites/react-sandbox/node_modules/jest
npm WARN rm not removing /Users/user/Sites/react-sandbox/node_modules/.bin/rimraf as it wasn't installed by /Users/user/Sites/react-sandbox/node_modules/rimraf
npm WARN rm not removing /Users/user/Sites/react-sandbox/node_modules/.bin/semver as it wasn't installed by /Users/user/Sites/react-sandbox/node_modules/semver
npm WARN rm not removing /Users/user/Sites/react-sandbox/node_modules/.bin/mkdirp as it wasn't installed by /Users/user/Sites/react-sandbox/node_modules/mkdirp
npm WARN rm not removing /Users/user/Sites/react-sandbox/node_modules/.bin/json5 as it wasn't installed by /Users/user/Sites/react-sandbox/node_modules/json5

> fsevents@1.2.12 install /Users/user/Sites/react-sandbox/node_modules/jest-haste-map/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:39:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LaunchServices.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/IconsCore.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/OSServices.h:29:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/CSIdentity.h:43:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:51:10: fatal error: 
      'Security/cssmaci.h' file not found
#include <Security/cssmaci.h>
         ^~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:51:10: note: 
      did not find header 'cssmaci.h' in framework 'Security' (loaded from
      '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks')
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Sites/react-sandbox/node_modules/jest-haste-map/node_modules/fsevents
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> fsevents@1.2.12 install /Users/user/Sites/react-sandbox/node_modules/watchpack/node_modules/fsevents
> node-gyp rebuild


> fsevents@1.2.12 install /Users/user/Sites/react-sandbox/node_modules/webpack-dev-server/node_modules/fsevents
> node-gyp rebuild


> core-js@2.6.11 postinstall /Users/user/Sites/react-sandbox/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```

**Comment by isaacs** [comment]
What version of npm are you using?  It'd be in the first few lines of the `npm-debug.log` file that's generated.

I'm confident that this specific failure is fixed in the latest npm release.  Please update.  If you already _have_ the latest npm release, then it's something else, but we still need the debug log.
