### ISSUE TITLE
[BUG] <Failed to build standalone app   err: Error: yarn exited with non-zero code: 1>

### ISSUE THREAD

**Issue by almoret** [npm/cli#1224]
Hi guys.

I trying to generate an apk with turtle-cli typing the following commands:

expo publish
export EXPO_USERNAME=[USERNAME]
export EXPO_PASSWORD=[PASSWORD]
export EXPO_ANDROID_KEYSTORE_PASSOWRD=[KEYSTORE PASSWORD]
export EXPO_ANDROID_KEY_PASSWORD=[KEYSTORE PASSWORD]

turtle build:android --keystore-path credentials/carambolah.keystore -t apk --keystore--alias br.com.moonwalk.[project_name]

But, im facing the following error:

Apr 30 15:36:03 turtle[5158] ERROR: Failed to build standalone app
  err: Error: yarn exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:286:20)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at maybeClose (internal/child_process.js:982:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Socket.emit (events.js:198:13)
      at Socket.EventEmitter.emit (domain.js:448:20)
      at Pipe._handle.close (net.js:606:12)
      ...
      at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@57.8.30/src/detach/ExponentTools.ts:100:19)
      at _installNodeModules (/usr/local/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:106:23)
  platform: "android"
MacBook-Air-de-Alex:react-new-app alexmoret$ expo diagnostics

  Expo CLI 3.20.0 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.20.0

Anyone, can help me?

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
