### ISSUE TITLE
[BUG] npm ERR! Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by totszwai** [npm/cli#1257]
# What / Why
Cannot perform `npm install` without deleting `package-lock.json`

## When
Happens all the time when there is a package somehow generated a broken package-lock.json file with empty dependency blob `{}`

For example, in `package-lock.json` file:

```
            "repeat-string": "^1.6.1",
            "to-regex-range": "^2.1.0"
          }
        },
        "fsevents": {},   <== THIS will cause the error
        "is-glob": {
          "version": "4.
```

## Where
```
18 verbose stack TypeError: Cannot read property 'match' of undefined
18 verbose stack     at tarballToVersion (/home/eto/.nvm/versions/node/v10.20.1/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
18 verbose stack     at inflatableChild (/home/eto/.nvm/versions/node/v10.20.1/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
18 verbose stack     at BB.each (/home/eto/.nvm/versions/node/v10.20.1/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
```

### Current Behavior
User must delete `package-lock.json` before running `npm install`

### Expected Behavior
The `inflate-shrinkwrap.js` should handle corner case more gracefully.

The code at `inflate-shrinkwrap.js:87`, should probably check for whether `tb` exists before calling match.
```
function tarballToVersion (name, tb) {
  const registry = quotemeta(npm.config.get('registry') || '')
    .replace(/https?:/, 'https?:')
    .replace(/([^/])$/, '$1/')
  let matchRegTarball
  if (name) {
    const nameMatch = quotemeta(name)
    matchRegTarball = new RegExp(`^${registry}${nameMatch}/-/${nameMatch}-(.*)[.]tgz$`)
  } else {
    matchRegTarball = new RegExp(`^${registry}(.*)?/-/\\1-(.*)[.]tgz$`)
  }
  const match = tb.match(matchRegTarball)
  if (!match) return
  return match[2] || match[1]
}
```

A suggested fix might be this, but it would cause more downstream error:
```
  if (tb) {
    const match = tb.match(matchRegTarball)
    if (match) {
      return match[2] || match[1]
    }
  }
```
But it would ended up causing:
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for fsevents@undefined.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.

The root cause and the fix for this issue, is probably during `npm i` it should do a check on the generated `package-lock.json` instead.

**Comment by paddor** [comment]
Any updates on this? This bug is driving me insane.

**Comment by ljharb** [comment]
Have you tried with the latest npm@7?

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is reproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
