### ISSUE TITLE
"ENOVERSIONS: No valid versions available" for Github #semver: dependency

### ISSUE THREAD

**Issue by cyberbiont** [npm/cli#1258]
I have a devDependency installed from Github
```json
"devDependencies": {
"configs-students": "git+https://git@github.com/cyberbiont/configs-students#semver:^0.0.1",
}
```
After I have edited repository on Github and bumped version to `0.1.0` I expected that running 
`npm i configs-students` or `npm i configs-students -D` would update the package to the latest version.

However, I get this in console:
```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for configs-students
```

Node 14.2.0
npm 6.14.4

Here is the complete debug log
```log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'configs-students'
1 verbose cli ]
2 info using npm@6.13.1
3 info using node@v13.3.0
4 verbose npm-session c5ec24fb40aa963c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for configs-students@git+https://git@github.com/cyberbiont/configs-students.git#semver:^0.0.1 No valid versions available for configs-students
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 3056ms
10 verbose type range
11 verbose stack configs-students: No valid versions available for configs-students
11 verbose stack     at pickManifest (C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\npm-pick-manifest\index.js:39:11)
11 verbose stack     at C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\pacote\lib\fetchers\git.js:144:9
11 verbose stack     at tryCatcher (C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
11 verbose stack     at Promise._settlePromise (C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
11 verbose stack     at Promise._fulfillPromises (C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:674:14)
11 verbose stack     at Promise._settlePromises (C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\bluebird\js\release\promise.js:700:18)
11 verbose stack     at _drainQueueStep (C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
11 verbose stack     at _drainQueue (C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
11 verbose stack     at Async._drainQueues (C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\ProgramData\nvm\v13.3.0\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at processImmediate (internal/timers.js:444:21)
12 verbose cwd E:\Projects\Info\Action\Danit\@\JS\JS 1-2\tasks\task-js--prompt
13 verbose Windows_NT 10.0.18363
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "configs-students"
15 verbose node v13.3.0
16 verbose npm  v6.13.1
17 error code ENOVERSIONS
18 error No valid versions available for configs-students
19 verbose exit [ 1, true ]
```

Is there any workarounds to keep dependency updated aside from publishing it as npm package?

**Comment by ljharb** [comment]
That syntax refers to a github tag. Did you create the tag for the new version?

**Comment by cyberbiont** [comment]
Yes, I tagged the release... 
But the combination of  #semver:^0.0.1 and 0.1.0 release tag didn't work. 

I just have figured it out. Seems like versions prior to 1.0.0 are considered 'initial development' in semver and ^ operator doesn't actually work with them.

When I moved to 1.0.0 release tag and #semver:* I was able to update.

**Comment by cyberbiont** [comment]
It's still unclear to me, why I cannot fetch dependency using git+ssh:// rather than git+https//
I am using integrated ssh-agent on Windows, and I am able to connect with `ssh git@github` command, but I get `Permission denied (publickey)` when using npm. 
But I think it should be another issue
