### ISSUE TITLE
[BUG] an error occurred when i try to install traojs

### ISSUE THREAD

**Issue by BruceWW** [npm/cli#1268]
# What / Why
### the error occurred when use the command line "npm install -g @ tarojs/cli"
`npm ERR! Linux 4.15.0-1065-aws`
`npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@tarojs/cli"`
`npm ERR! node v8.10.0`
`npm ERR! npm  v3.5.2`
`npm ERR! code EMISSINGARG`

`npm ERR! typeerror Error: Missing required argument #1`
`npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)`
`npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)`
`npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)`
`npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7`
`npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50`
`npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12`
`npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)`
`npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)`
`npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)`
`npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50`
`npm ERR! typeerror This is an error with npm itself. Please report this error at`:
`npm ERR! typeerror     []([](<http://github.com/npm/npm/issues>`))

[and this is the debug log ](http://www.mie-i-nuo.win/npm-debug.log)

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is reproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
