### ISSUE TITLE
[BUG] prepare script with npm i and local dependencies fails when installing as git dependency (ENOENT in _cacache)

### ISSUE THREAD

**Issue by dmnsgn** [npm/cli#1390]
# What / Why

With the following folder structure:
```bash
.
├── README.md
├── app
├── builder
├── cli
├── dist
├── electron
├── lib
├── node_modules
├── package-lock.json
└── package.json
```

The root `package.json` has no dependencies (only devDeps) and contains a prepare script that is `cd`ing into each folder (`app`, `builder`, `cli` and `lib`) and running `npm install` 
```json
"prepare": "cd builder && npm i --production && cd ../lib && npm i --production && cd ../app && npm i --production && cd ../cli && npm i --production && npm run build:app"
```
The different packages are depending on each other to some extent (eg. cli contains `"lib": "file:../lib"`) and all have empty `.npmignore` file in them.

Running `npm install` (which also run prepare) locally will install without any issue. But installing from git will fail with issue:
```bash
npm ERR! prepareGitDep npm ERR! enoent This is related to npm not being able to find a file.
```

<details>
  <summary>Full log here</summary>

```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'github:my-org-name/my-package-name#branch-to-install'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose npm-session 21f8b667dc9da802
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose prepareGitDep github:my-org-name/my-package-name#branch-to-install: installing devDeps and running prepare script.
8 error prepareGitDep 1>
8 error prepareGitDep > core-js@3.6.5 postinstall /Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/node_modules/core-js
8 error prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
8 error prepareGitDep
8 error prepareGitDep [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
8 error prepareGitDep
8 error prepareGitDep [96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
8 error prepareGitDep [96m>[94m https://opencollective.com/core-js [0m
8 error prepareGitDep [96m>[94m https://www.patreon.com/zloirock [0m
8 error prepareGitDep
8 error prepareGitDep [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
8 error prepareGitDep
8 error prepareGitDep
8 error prepareGitDep > core-js-pure@3.6.5 postinstall /Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/node_modules/core-js-pure
8 error prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
8 error prepareGitDep
8 error prepareGitDep
8 error prepareGitDep > ejs@3.1.3 postinstall /Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/node_modules/ejs
8 error prepareGitDep > node --harmony ./postinstall.js
8 error prepareGitDep
8 error prepareGitDep Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)
8 error prepareGitDep
8 error prepareGitDep
8 error prepareGitDep > electron@9.0.2 postinstall /Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/node_modules/electron
8 error prepareGitDep > node install.js
8 error prepareGitDep
8 error prepareGitDep
8 error prepareGitDep > my-package-name@1.0.0-alpha.2.0.2 prepare /Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b
8 error prepareGitDep > cd builder && npm i --production && cd ../lib && npm i --production && cd ../app && npm i --production && cd ../cli && npm i --production && npm run build:app
8 error prepareGitDep
8 error prepareGitDep
8 error prepareGitDep > fsevents@1.2.13 install /Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/builder/node_modules/watchpack-chokidar2/node_modules/fsevents
8 error prepareGitDep > node install.js
8 error prepareGitDep
8 error prepareGitDep   SOLINK_MODULE(target) Release/.node
8 error prepareGitDep   CXX(target) Release/obj.target/fse/fsevents.o
8 error prepareGitDep   SOLINK_MODULE(target) Release/fse.node
8 error prepareGitDep added 657 packages from 272 contributors and audited 657 packages in 8.936s
8 error prepareGitDep
8 error prepareGitDep 20 packages are looking for funding
8 error prepareGitDep   run `npm fund` for details
8 error prepareGitDep
8 error prepareGitDep found 0 vulnerabilities
8 error prepareGitDep
8 error prepareGitDep added 3 packages from 2 contributors and audited 3 packages in 0.395s
8 error prepareGitDep found 0 vulnerabilities
8 error prepareGitDep
8 error prepareGitDep
8 error prepareGitDep > fsevents@1.2.13 install /Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/app/node_modules/nodes-builder/node_modules/watchpack-chokidar2/node_modules/fsevents
8 error prepareGitDep > node install.js
8 error prepareGitDep
8 error prepareGitDep   SOLINK_MODULE(target) Release/.node
8 error prepareGitDep   CXX(target) Release/obj.target/fse/fsevents.o
8 error prepareGitDep   SOLINK_MODULE(target) Release/fse.node
8 error prepareGitDep
8 error prepareGitDep > core-js@3.6.5 postinstall /Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/app/node_modules/core-js
8 error prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
8 error prepareGitDep
8 error prepareGitDep added 769 packages from 1209 contributors and audited 771 packages in 10.431s
8 error prepareGitDep
8 error prepareGitDep 23 packages are looking for funding
8 error prepareGitDep   run `npm fund` for details
8 error prepareGitDep
8 error prepareGitDep found 0 vulnerabilities
9 error prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
9 error prepareGitDep npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
9 error prepareGitDep npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
9 error prepareGitDep npm WARN nodes-lib@1.0.0-alpha.2.0.2 No repository field.
9 error prepareGitDep
9 error prepareGitDep npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
9 error prepareGitDep npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/hot/poll.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/PrefetchDependency.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/util/Queue.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/node/ReadFileCompileWasmTemplatePlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/optimize/RemoveEmptyChunksPlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/optimize/RemoveParentModulesPlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireContextDependency.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireContextDependencyParserPlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireContextPlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireEnsureDependenciesBlock.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireEnsureDependenciesBlockParserPlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireEnsureDependency.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireEnsureItemDependency.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireEnsurePlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireHeaderDependency.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireIncludeDependency.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireIncludeDependencyParserPlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireIncludePlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/RequireJsStuffPlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireResolveContextDependency.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireResolveDependency.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireResolveDependencyParserPlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/dependencies/RequireResolveHeaderDependency.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/logging/runtime.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/util/Semaphore.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/util/SetHelpers.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/hot/signal.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/performance/SizeLimitsPlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/util/SortableSet.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/util/StackedSetMap.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/logging/truncateArgs.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/webpack-c06ef3d2/lib/web/WebEnvironmentPlugin.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/jpeg2000.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/jpegxr.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/js-regexp-lookbehind.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/json.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/justify-content-space-evenly.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/kerning-pairs-ligatures.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/keyboardevent-charcode.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/keyboardevent-code.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/keyboardevent-getmodifierstate.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/keyboardevent-key.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/keyboardevent-location.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/keyboardevent-which.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/lazyload.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/let.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/link-icon-png.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/link-icon-svg.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/link-rel-dns-prefetch.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/link-rel-modulepreload.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/link-rel-preconnect.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/link-rel-prefetch.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/link-rel-preload.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/link-rel-prerender.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/loading-lazy-attr.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/localecompare.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/magnetometer.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/matchesselector.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/matchmedia.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/mathml.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/maxlength.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/media-attribute.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/media-fragments.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/media-session-api.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/mediacapture-fromelement.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/mediarecorder.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/mediasource.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/menu.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/meta-theme-color.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/meter.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/regions/MG.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/regions/MH.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/midi.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/features/minmaxwh.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/regions/MK.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/regions/ML.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/regions/MM.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/regions/MN.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/regions/MO.js'
9 error prepareGitDep npm WARN tar ENOENT: no such file or directory, open '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/caniuse-lite-045b44f1/data/regions/MP.js'
9 error prepareGitDep npm ERR! code ENOENT
9 error prepareGitDep npm ERR! syscall rename
9 error prepareGitDep npm ERR! path /Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/@babel/helper-plugin-utils-403cf904
9 error prepareGitDep npm ERR! dest /Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/builder/node_modules/@babel/helper-plugin-utils
9 error prepareGitDep npm ERR! errno -2
9 error prepareGitDep npm ERR! enoent ENOENT: no such file or directory, rename '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/cli/node_modules/.staging/@babel/helper-plugin-utils-403cf904' -> '/Users/myusername/.npm/_cacache/tmp/git-clone-f170fd0b/builder/node_modules/@babel/helper-plugin-utils'
9 error prepareGitDep npm ERR! enoent This is related to npm not being able to find a file.
9 error prepareGitDep npm ERR! enoent
9 error prepareGitDep
9 error prepareGitDep npm ERR! A complete log of this run can be found in:
9 error prepareGitDep npm ERR!     /Users/myusername/.npm/_logs/2020-06-04T09_44_19_720Z-debug.log
9 error prepareGitDep npm ERR! code ELIFECYCLE
9 error prepareGitDep npm ERR! errno 254
9 error prepareGitDep npm ERR! my-package-name@1.0.0-alpha.2.0.2 prepare: `cd builder && npm i --production && cd ../lib && npm i --production && cd ../app && npm i --production && cd ../cli && npm i --production && npm run build:app`
9 error prepareGitDep npm ERR! Exit status 254
9 error prepareGitDep npm ERR!
9 error prepareGitDep npm ERR! Failed at the my-package-name@1.0.0-alpha.2.0.2 prepare script.
9 error prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
9 error prepareGitDep
9 error prepareGitDep npm ERR! A complete log of this run can be found in:
9 error prepareGitDep npm ERR!     /Users/myusername/.npm/_logs/2020-06-04T09_44_19_984Z-debug.log
10 silly fetchPackageMetaData error for github:my-org-name/my-package-name#branch-to-install premature close
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 54110ms
13 verbose stack Error: premature close
13 verbose stack     at PassThrough.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
13 verbose stack     at PassThrough.emit (events.js:327:22)
13 verbose stack     at emitCloseNT (internal/streams/destroy.js:81:10)
13 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:83:21)
14 verbose cwd /Users/myusername/Projects/my-test-project
15 verbose Darwin 19.4.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "github:my-org-name/my-package-name#branch-to-install"
17 verbose node v14.4.0
18 verbose npm  v6.14.5
19 error premature close
20 verbose exit [ 1, true ]
```
</details>

## When

* When installing from GitHub (possibly any git): `npm i github:my-org-name/my-package-name#branch-to-install`

## Where

* n/a

### Current Behavior

* Fails to run npm install in subfolders

### Steps to Reproduce

* n/a

### Expected Behavior

* Prepare script to run npm install in subfolder and symlink the local packages (`file:../app`) correctly

## Who

* n/a

## References

* Possibly related to:
- https://github.com/npm/cli/issues/459
- https://github.com/npm/cli/issues/1287
- https://github.com/npm/cli/issues/321
- https://github.com/npm/cli/issues/1287

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
