### ISSUE TITLE
23 error This is probably not a problem with npm. There is likely additional logging output above.

### ISSUE THREAD

**Issue by aliscie** [npm/cli#1449]
I'm a beginner and I have no idea why this error happened
it accure when I say ` create-react-app myappname`
even when I use `sudo npm` or `npx` or `sudo npm` `sudo npx`

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle myapp@0.1.0~prestart: myapp@0.1.0
6 info lifecycle myapp@0.1.0~start: myapp@0.1.0
7 verbose lifecycle myapp@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle myapp@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/apple/myapp/node_modules/.bin:/opt/anaconda3/bin://anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle myapp@0.1.0~start: CWD: /Users/apple/myapp
10 silly lifecycle myapp@0.1.0~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle myapp@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle myapp@0.1.0~start: Failed to exec start script
13 verbose stack Error: myapp@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid myapp@0.1.0
15 verbose cwd /Users/apple/myapp
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v14.4.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error myapp@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the myapp@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by ChaboCode** [comment]
Have you tried to do `npm i -g create-react-app` and then `create-react-app myapp`? What OS are you running?

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
