### ISSUE TITLE
[QUESTION] npm ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by Pranomvignesh** [npm/cli#1453]
# What / Why
When I tried installing a recently updated package ... I am getting an error like this

`npm ERR! code EINTEGRITY`
`npm ERR! sha512-VXJ7jSkaONZFcAb9PzpwCb4kv60SMMPhbljvso9muXH4/cx3jaxC0lVk+DUcalaUPkWZzaUhggJhs5EqJMiovg== integrity checksum failed when using sha512: wanted sha512-VXJ7jSkaONZFcAb9PzpwCb4kv60SMMPhbljvso9muXH4/cx3jaxC0lVk+DUcalaUPkWZzaUhggJhs5EqJMiovg== but got sha512-mqE42GAVzFwCQQjO428cEuOPATV1EZ5uzARBWScng6sCawbualjMatgPiu9149OsVn6OzJL0F3Lk1KwsmOjR5Q==. (4767924 bytes)`

I tried all the methods from [stackoverflow](https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0)

Still i am getting the same issue

# How
I created a new folder and tried installing the package with empty cache but i still throws error
<img width="1680" alt="EIntegrityErrorTerminalOutput" src="https://user-images.githubusercontent.com/29809906/85366274-a3478b80-b544-11ea-8da4-c969fbfeb07e.png">

> I have hidden package name and local registry name as it is private

This is the log file's output
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '<package-name>',
1 verbose cli   '--registry',
1 verbose cli   '<local-registry>',
1 verbose cli   '--cache',
1 verbose cli   '/tmp/empty-npm-cache'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose npm-session 8fed52b7a56fc90c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 <local-registry>/<package-name> 568ms (from cache)
8 silly fetchPackageMetaData error for <package-name> sha512-VXJ7jSkaONZFcAb9PzpwCb4kv60SMMPhbljvso9muXH4/cx3jaxC0lVk+DUcalaUPkWZzaUhggJhs5EqJMiovg== integrity checksum failed when using sha512: wanted sha512-VXJ7jSkaONZFcAb9PzpwCb4kv60SMMPhbljvso9muXH4/cx3jaxC0lVk+DUcalaUPkWZzaUhggJhs5EqJMiovg== but got sha512-4lOcV8jFlP1Ak6TEJcBk7KxerMX1uqn0n1Gya9WyI8y6M/LuYWAGk8Nn0ygsMfGKrmj3pZ4Z5VqCc1yHIckinQ==. (1939980 bytes)
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 137950ms
11 verbose stack Error: sha512-VXJ7jSkaONZFcAb9PzpwCb4kv60SMMPhbljvso9muXH4/cx3jaxC0lVk+DUcalaUPkWZzaUhggJhs5EqJMiovg== integrity checksum failed when using sha512: wanted sha512-VXJ7jSkaONZFcAb9PzpwCb4kv60SMMPhbljvso9muXH4/cx3jaxC0lVk+DUcalaUPkWZzaUhggJhs5EqJMiovg== but got sha512-4lOcV8jFlP1Ak6TEJcBk7KxerMX1uqn0n1Gya9WyI8y6M/LuYWAGk8Nn0ygsMfGKrmj3pZ4Z5VqCc1yHIckinQ==. (1939980 bytes)
11 verbose stack     at Transform.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:328:19)
11 verbose stack     at Transform.emit (events.js:327:22)
11 verbose stack     at endReadableNT (_stream_readable.js:1221:12)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
12 verbose cwd /Users/vignesh-6596/Documents/homeFiles/testFolder
13 verbose Darwin 17.7.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "<package-name>" "--registry" "<local-registry> "--cache" "/tmp/empty-npm-cache"
15 verbose node v12.18.1
16 verbose npm  v6.14.5
17 error code EINTEGRITY
18 error sha512-VXJ7jSkaONZFcAb9PzpwCb4kv60SMMPhbljvso9muXH4/cx3jaxC0lVk+DUcalaUPkWZzaUhggJhs5EqJMiovg== integrity checksum failed when using sha512: wanted sha512-VXJ7jSkaONZFcAb9PzpwCb4kv60SMMPhbljvso9muXH4/cx3jaxC0lVk+DUcalaUPkWZzaUhggJhs5EqJMiovg== but got sha512-4lOcV8jFlP1Ak6TEJcBk7KxerMX1uqn0n1Gya9WyI8y6M/LuYWAGk8Nn0ygsMfGKrmj3pZ4Z5VqCc1yHIckinQ==. (1939980 bytes)
19 verbose exit [ 1, true ]

```

> node version =>  v12.18.1
> npm version => v6.14.5

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
