### ISSUE TITLE
[BUG] Add s390x arch support

### ISSUE THREAD

**Issue by guimard** [npm/cli#1455]
# What / Why
Hi,

after some test, s390x is well supported excepted in listed test:
```diff
--- a/test/tap/legacy-platform-all.js
+++ b/test/tap/legacy-platform-all.js
@@ -36,6 +36,7 @@
         'arm64',
         'mips',
         'ia32',
+        's390x',
         'x64',
         'sparc'
       ]

```

**Comment by guimard** [comment]
When running tests on a s390x machine, I found this kind of errors:
```
Error: Failed to replace env in config: ${prefix}
    at /home/yadd/cli-6.14.5/lib/config/core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (/home/yadd/cli-6.14.5/lib/config/core.js:411:12)
    at parseField (/home/yadd/cli-6.14.5/lib/config/core.js:389:7)
    at /home/yadd/cli-6.14.5/lib/config/core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (/home/yadd/cli-6.14.5/lib/config/core.js:328:23)
    at ConfigChain.addString (/home/yadd/cli-6.14.5/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/home/yadd/cli-6.14.5/lib/config/core.js:316:10)
    at /home/yadd/cli-6.14.5/node_modules/graceful-fs/graceful-fs.js:123:16
test/tap/00-verify-ls-ok.js ........................... 4/5
```

**Comment by LocutusOfBorg** [comment]
shouldn't we also add ppc64el?

**Comment by guimard** [comment]
Sadly ppc64el gives the same kind of errors

**Comment by guimard** [comment]
Hi, it looks like it was a Debian/Node.js issue. npm works fine with s390x, ppc64 and ppc64el

**Comment by ljharb** [comment]
Make sure npm isn’t installed separately, npm only ships with node.

**Comment by guimard** [comment]
@ljharb: sure

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
