### ISSUE TITLE
[BUG] publish error http fetch put 404 on  npm v 6.14.5 node v 14.5.0

### ISSUE THREAD

**Issue by masx200** [npm/cli#1489]
# What / Why

> 
publish error http fetch put 404 on  npm v 6.14.5 node v 14.5.0

http fetch PUT 404 https://registry.npmjs.org/@masx200%2fbaidupcs-batch-upload

package.json
```json
{
    "publishConfig": {
        "registry": "https://registry.npmjs.org"
    },
    "name": "@masx200/baidupcs-batch-upload",
    "bin": "./lib/cli.js",
    "main": "./lib/index.js",
    "version": "1.1.5",
    "types": "./lib/index.d.ts",
    "module": "./lib/index.js",
    "type": "module",
    "scripts": {
        "watch": "tsc --watch",
        "build": "tsc",
        "prettier": "prettier */**/*.ts *.js --write *.json *.md",
        "start": "node --experimental-modules --experimental-json-modules ./lib/cli.js "
    },
    "dependencies": {
        "@masx200/async-task-current-limiter": "^1.0.8",
        "find": "^0.3.0",
        "fs-extra": "^8.1.0"
    },
    "license": "MIT",
    "devDependencies": {
        "@types/find": "^0.2.1",
        "@types/fs-extra": "^8.0.1",
        "@types/node": "^13.7.1",
        "prettier": "^1.19.1",
        "tslib": "^1.10.0",
        "typescript": "^3.8.3"
    },
    "keywords": [],
    "author": "masx200 <34191203+masx200@users.noreply.github.com>",
    "description": "使用baidupcs-go,百度网盘批量上传图片",
    "repository": "git+https://github.com/masx200/baidupcs-batch-upload.git",
    "bugs": {
        "url": "https://github.com/masx200/baidupcs-batch-upload/issues"
    },
    "homepage": "https://github.com/masx200/baidupcs-batch-upload#readme"
}

```

## When

* n/a

## Where

* n/a

## How
```shell
npm publish
```
### Current Behavior

*

```txt

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.5.0
4 verbose npm-session e6a19ff930e81ffd
5 verbose publish [ '.' ]
6 info lifecycle @masx200/baidupcs-batch-upload@1.1.5~prepublish: @masx200/baidupcs-batch-upload@1.1.5
7 info lifecycle @masx200/baidupcs-batch-upload@1.1.5~prepare: @masx200/baidupcs-batch-upload@1.1.5
8 info lifecycle @masx200/baidupcs-batch-upload@1.1.5~prepublishOnly: @masx200/baidupcs-batch-upload@1.1.5
9 info lifecycle @masx200/baidupcs-batch-upload@1.1.5~prepack: @masx200/baidupcs-batch-upload@1.1.5
10 info lifecycle @masx200/baidupcs-batch-upload@1.1.5~postpack: @masx200/baidupcs-batch-upload@1.1.5
11 notice
12 notice package: @masx200/baidupcs-batch-upload@1.1.5
13 notice === Tarball Contents ===
14 notice 274B  .gitattributes
14 notice 1.1kB LICENSE
14 notice 136B  lib/argsobj.js
14 notice 610B  lib/cli.js
14 notice 187B  lib/execbaidupcs.js
14 notice 245B  lib/findfiles.js
14 notice 1.4kB lib/index.js
14 notice 422B  lib/limiter.js
14 notice 600B  lib/parse-args.js
14 notice 1.7kB lib/uploadfile.js
14 notice 19B   .prettierrc.json
14 notice 1.4kB package.json
14 notice 824B  tsconfig.json
14 notice 1.6kB README.md
14 notice 55B   lib/argsobj.d.ts
14 notice 136B  lib/argsobj.ts
14 notice 205B  lib/baidupcsupload.d.ts
14 notice 33B   lib/cli.d.ts
14 notice 1.2kB lib/cli.ts
14 notice 196B  lib/execbaidupcs.d.ts
14 notice 271B  lib/execbaidupcs.ts
14 notice 89B   lib/findfiles.d.ts
14 notice 343B  lib/findfiles.ts
14 notice 124B  lib/index.d.ts
14 notice 2.3kB lib/index.ts
14 notice 139B  lib/limiter.d.ts
14 notice 626B  lib/limiter.ts
14 notice 92B   lib/parse-args.d.ts
14 notice 870B  lib/parse-args.ts
14 notice 99B   lib/uploadfile.d.ts
14 notice 1.8kB lib/uploadfile.ts
14 notice 42B   success-log/0.txt
14 notice 36B   success-log/1.txt
14 notice 33B   error-log/6.txt
14 notice 227B  error-log/7.txt
14 notice 106B  error-log/8.txt
14 notice 3.7kB error-log/baidupcs-go-error-0.txt
14 notice 630B  error-log/baidupcs-go-error-1.txt
14 notice 541B  error-log/baidupcs-go-error-2.txt
14 notice 57B   error-log/baidupcs-go-error-3.txt
14 notice 147B  error-log/baidupcs-go-error-4.txt
14 notice 565B  error-log/baidupcs-go-error-5.txt
14 notice 544B  help.txt
14 notice 3.7kB pnpm-lock.yaml
15 notice === Tarball Details ===
16 notice name:          @masx200/baidupcs-batch-upload
16 notice version:       1.1.5
16 notice package size:  9.4 kB
16 notice unpacked size: 29.5 kB
16 notice shasum:        d40c9cf1f57ebfa8aaaae728f8edae8646ff0fee
16 notice integrity:     sha512-TovLok/Sg8DIs[...]1mzQOHauz5J0w==
16 notice total files:   44
17 notice
18 http fetch PUT 404 https://registry.npmjs.org/@masx200%2fbaidupcs-batch-upload 1508ms
19 verbose stack Error: 404 Not Found - PUT https://registry.npmjs.org/@masx200%2fbaidupcs-batch-upload - Not found
19 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15
19 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
20 verbose statusCode 404
21 verbose pkgid @masx200/baidupcs-batch-upload@1.1.5
22 verbose cwd C:\Documents\GitHub\baidupcs-batch-upload
23 verbose Windows_NT 10.0.19041
24 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
25 verbose node v14.5.0
26 verbose npm  v6.14.5
27 error code E404
28 error 404 Not Found - PUT https://registry.npmjs.org/@masx200%2fbaidupcs-batch-upload - Not found
29 error 404
30 error 404 '@masx200/baidupcs-batch-upload@1.1.5' is not in the npm registry.
31 error 404 You should bug the author to publish it (or use the name yourself!)
32 error 404 Note that you can also install from a
33 error 404 tarball, folder, http url, or git url.
34 verbose exit [ 1, true ]
```
### Steps to Reproduce

* n/a

### Expected Behavior

*

```txt
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose npm-session 01251cb92320416a
5 verbose publish [ '.' ]
6 info lifecycle @masx200/baidupcs-batch-upload@1.1.5~prepublish: @masx200/baidupcs-batch-upload@1.1.5
7 info lifecycle @masx200/baidupcs-batch-upload@1.1.5~prepare: @masx200/baidupcs-batch-upload@1.1.5
8 info lifecycle @masx200/baidupcs-batch-upload@1.1.5~prepublishOnly: @masx200/baidupcs-batch-upload@1.1.5
9 info lifecycle @masx200/baidupcs-batch-upload@1.1.5~prepack: @masx200/baidupcs-batch-upload@1.1.5
10 info lifecycle @masx200/baidupcs-batch-upload@1.1.5~postpack: @masx200/baidupcs-batch-upload@1.1.5
11 notice
12 notice package: @masx200/baidupcs-batch-upload@1.1.5
13 notice === Tarball Contents ===
14 notice 274B  .gitattributes
14 notice 1.1kB LICENSE
14 notice 136B  lib/argsobj.js
14 notice 610B  lib/cli.js
14 notice 187B  lib/execbaidupcs.js
14 notice 245B  lib/findfiles.js
14 notice 1.4kB lib/index.js
14 notice 422B  lib/limiter.js
14 notice 600B  lib/parse-args.js
14 notice 1.7kB lib/uploadfile.js
14 notice 18B   .prettierrc.json
14 notice 1.4kB package.json
14 notice 824B  tsconfig.json
14 notice 1.6kB README.md
14 notice 55B   lib/argsobj.d.ts
14 notice 136B  lib/argsobj.ts
14 notice 205B  lib/baidupcsupload.d.ts
14 notice 33B   lib/cli.d.ts
14 notice 1.2kB lib/cli.ts
14 notice 196B  lib/execbaidupcs.d.ts
14 notice 271B  lib/execbaidupcs.ts
14 notice 89B   lib/findfiles.d.ts
14 notice 343B  lib/findfiles.ts
14 notice 124B  lib/index.d.ts
14 notice 2.3kB lib/index.ts
14 notice 139B  lib/limiter.d.ts
14 notice 626B  lib/limiter.ts
14 notice 92B   lib/parse-args.d.ts
14 notice 870B  lib/parse-args.ts
14 notice 99B   lib/uploadfile.d.ts
14 notice 1.8kB lib/uploadfile.ts
14 notice 42B   success-log/0.txt
14 notice 36B   success-log/1.txt
14 notice 33B   error-log/6.txt
14 notice 227B  error-log/7.txt
14 notice 106B  error-log/8.txt
14 notice 3.7kB error-log/baidupcs-go-error-0.txt
14 notice 630B  error-log/baidupcs-go-error-1.txt
14 notice 541B  error-log/baidupcs-go-error-2.txt
14 notice 57B   error-log/baidupcs-go-error-3.txt
14 notice 147B  error-log/baidupcs-go-error-4.txt
14 notice 565B  error-log/baidupcs-go-error-5.txt
14 notice 544B  help.txt
14 notice 3.6kB pnpm-lock.yaml
15 notice === Tarball Details ===
16 notice name:          @masx200/baidupcs-batch-upload
16 notice version:       1.1.5
16 notice package size:  9.3 kB
16 notice unpacked size: 29.3 kB
16 notice shasum:        878d6901fc6126937b617e1f9e2fb00f6438bb88
16 notice integrity:     sha512-jByQSr09GfWcz[...]dOXy8r+fKqzcA==
16 notice total files:   44
17 notice
18 http fetch PUT 403 https://registry.npmjs.org/@masx200%2fbaidupcs-batch-upload 1532ms
19 verbose stack Error: 403 Forbidden - PUT https://registry.npmjs.org/@masx200%2fbaidupcs-batch-upload - You cannot publish over the previously published versions: 1.1.5.
19 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15
19 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
20 verbose statusCode 403
21 verbose pkgid @masx200/baidupcs-batch-upload@1.1.5
22 verbose cwd D:\Documents\GitHub\baidupcs-batch-upload
23 verbose Windows_NT 10.0.19041
24 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
25 verbose node v14.4.0
26 verbose npm  v6.14.5
27 error code E403
28 error 403 403 Forbidden - PUT https://registry.npmjs.org/@masx200%2fbaidupcs-batch-upload - You cannot publish over the previously published versions: 1.1.5.
29 error 403 In most cases, you or one of your dependencies are requesting
29 error 403 a package version that is forbidden by your security policy.
30 verbose exit [ 1, true ]
```

## Who

* n/a

## References

* n/a

**Comment by JarvisStriker** [comment]
same issue. there is no clear answer anywhere

**Comment by masx200** [comment]
You can use "yarn publish" to solve this problem

**Comment by bameyrick** [comment]
I'm having a similar issue trying to get travis-ci to publish for me. Having also looked at #2040 and #2146 which seem related I haven't been able to find a solution. I tried updating my authentication token multiple times in my travis config incase this is the issue, however this has not resolved the issue and I would expect to get a 401 or 403 if travis could not authenticate correctly.

### Current Behavior

```
$ npm publish .
npm notice 📦  viewport-details@2.0.0
npm notice === Tarball Contents === 
npm notice 2.9kB   dist/index.js  
npm notice 1.6kB   package.json   
npm notice 135.0kB yarn.lock      
npm notice 3.0kB   README.md      
npm notice 1.5kB   dist/index.d.ts
npm notice === Tarball Details === 
npm notice name:          viewport-details                        
npm notice version:       2.0.0                                   
npm notice package size:  59.3 kB                                 
npm notice unpacked size: 144.0 kB                                
npm notice shasum:        2923e56ac2f954d7b465a207ad715a61cae96aca
npm notice integrity:     sha512-M3PFOrxAYo4uM[...]xp1ucmP+EXy1w==
npm notice total files:   5                                       
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/viewport-details - Not found
npm ERR! 404 
npm ERR! 404  'viewport-details@2.0.0' is not in tnpm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
(An example of a full build log can be seen here: https://travis-ci.com/github/bameyrick/viewport-details/jobs/499073487#L267)

### Expected Behavior

I would expect this package to be published to the registry.

### Steps To Reproduce
n/a

### Environment
- OS: Ubuntu 16.04.6 LTS
- Node: 12.18.3
- npm: 6.14.6

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
