### ISSUE TITLE
pathspec 'master' did not match any file(s) known to git

### ISSUE THREAD

**Issue by edem** [npm/cli#1514]
Everything is ok on 7/10, but this error happens on 7/11. I didn't update anything? Could anyone help me?
$ npm i
npm ERR! code 1
npm ERR! Command failed: git checkout master
npm ERR! error: pathspec 'master' did not match any file(s) known to git
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/edemchen/.npm/_logs/2020-07-11T16_44_30_865Z-debug.log

I tried to create a new project, run "npm i", pass.
But for my real project, each branch is suffering this issue. ( in Mac OS )

Then I clone the same project on Windows 10 and run "npm i" :

D:\{project path}>npm i
Unhandled rejection Error: Command failed: C:\Program Files\Git\cmd\git.EXE checkout masters2-mobile\node_modules\.stag
error: pathspec 'master' did not match any file(s) known to git.
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2020-07-11T21_33_43_135Z-debug.log

It showed me :
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
That why I report it here.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
