### ISSUE TITLE
Unexpected token p in JSON at position 4

### ISSUE THREAD

**Issue by gkucmierz** [npm/cli#1518]
# Why
> I have error, that cant explain

## Where
  * npm public registry

## Who
  * @gkucmierz

## References
  * Related to https://www.npmjs.com/package/social-links

<img width="551" alt="Zrzut ekranu 2020-07-13 o 16 49 29" src="https://user-images.githubusercontent.com/739084/87318844-2a2acb00-c529-11ea-8f06-a29e3abea6a1.png">

**Detailed error** /Users/gkucmierz/.npm/_logs/2020-07-13T14_49_13_743Z-debug.log

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose npm-session f6b530e0cda43ac6
5 verbose publish [ '.' ]
6 info lifecycle social-links@1.0.3~prepublish: social-links@1.0.3
7 info lifecycle social-links@1.0.3~prepare: social-links@1.0.3
8 verbose lifecycle social-links@1.0.3~prepare: unsafe-perm in lifecycle true
9 verbose lifecycle social-links@1.0.3~prepare: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/gkucmierz/workspace/social-links/node_modules/.bin:/Users/gkucmierz/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
10 verbose lifecycle social-links@1.0.3~prepare: CWD: .
11 silly lifecycle social-links@1.0.3~prepare: Args: [ '-c', 'npm run build' ]
12 silly lifecycle social-links@1.0.3~prepare: Returned: code: 0  signal: null
13 info lifecycle social-links@1.0.3~prepublishOnly: social-links@1.0.3
14 info lifecycle social-links@1.0.3~prepack: social-links@1.0.3
15 info lifecycle social-links@1.0.3~postpack: social-links@1.0.3
16 notice
17 notice 📦  social-links@1.0.3
18 notice === Tarball Contents ===
19 notice 1.4kB package.json
19 notice 1.7kB README.md
19 notice 850B  lib/main.d.ts
19 notice 868B  lib/main.d.ts.map
19 notice 6.8kB lib/main.js
19 notice 5.0kB lib/main.js.map
19 notice 50B   lib/main.spec.d.ts
19 notice 112B  lib/main.spec.d.ts.map
19 notice 6.1kB lib/main.spec.js
19 notice 5.0kB lib/main.spec.js.map
20 notice === Tarball Details ===
21 notice name:          social-links
21 notice version:       1.0.3
21 notice package size:  5.2 kB
21 notice unpacked size: 27.9 kB
21 notice shasum:        8c2d91d12c63b504cf5bed1825a27be365bfc3c1
21 notice integrity:     sha512-dvA5v0XakG02B[...]DiSrGMTio7Gnw==
21 notice total files:   10
22 notice
23 verbose getPublishConfig { registry: 'https://npm.pkg.github.com/' }
24 silly mapToRegistry name social-links
25 silly mapToRegistry using default registry
26 silly mapToRegistry registry https://npm.pkg.github.com/
27 silly mapToRegistry data { type: 'tag',
27 silly mapToRegistry   registry: true,
27 silly mapToRegistry   where: undefined,
27 silly mapToRegistry   raw: 'social-links',
27 silly mapToRegistry   name: 'social-links',
27 silly mapToRegistry   escapedName: 'social-links',
27 silly mapToRegistry   scope: undefined,
27 silly mapToRegistry   rawSpec: '',
27 silly mapToRegistry   saveSpec: null,
27 silly mapToRegistry   fetchSpec: 'latest',
27 silly mapToRegistry   gitRange: undefined,
27 silly mapToRegistry   gitCommittish: undefined,
27 silly mapToRegistry   hosted: undefined }
28 silly mapToRegistry uri https://npm.pkg.github.com/social-links
29 verbose publish registryBase https://npm.pkg.github.com/
30 silly publish uploading /var/folders/mf/8ss4ry693cv6mm7x81b1skch0000gn/T/npm-7658-c5709cae/tmp/fromDir-61d55e27/package.tgz
31 verbose request uri https://npm.pkg.github.com/social-links
32 verbose request sending authorization for write operation
33 info attempt registry request try #1 at 16:49:10
34 verbose request using bearer token for auth
35 verbose request id 93cb9387ab6c8080
36 http request PUT https://npm.pkg.github.com/social-links
37 http 404 https://npm.pkg.github.com/social-links
38 verbose bad json 404 page not found
39 error registry error parsing json
40 verbose headers { date: 'Mon, 13 Jul 2020 14:49:13 GMT',
40 verbose headers   'content-type': 'text/plain; charset=utf-8',
40 verbose headers   'content-length': '19',
40 verbose headers   'x-content-type-options': 'nosniff',
40 verbose headers   'x-github-request-id': 'EBBF:9AA2:19AFA5:21B98E:5F0C7468' }
41 error publish Failed PUT 404
42 verbose stack SyntaxError: Unexpected token p in JSON at position 4
42 verbose stack 404 page not found
42 verbose stack
42 verbose stack     at JSON.parse (<anonymous>)
42 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:243:23)
42 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
42 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:185:22)
42 verbose stack     at Request.emit (events.js:182:13)
42 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1161:10)
42 verbose stack     at Request.emit (events.js:182:13)
42 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1083:12)
42 verbose stack     at Object.onceWrapper (events.js:273:13)
42 verbose stack     at IncomingMessage.emit (events.js:187:15)
42 verbose stack     at endReadableNT (_stream_readable.js:1094:12)
42 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
43 verbose cwd /Users/gkucmierz/workspace/social-links
44 verbose Darwin 19.3.0
45 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
46 verbose node v10.15.0
47 verbose npm  v6.4.1
48 error Unexpected token p in JSON at position 4
48 error 404 page not found
49 verbose exit [ 1, true ]
```

What I did wrong?
[package.json](https://github.com/gkucmierz/social-links/blob/master/package.json) seems to look good

**Comment by ljharb** [comment]
Looks like you're getting an error from the github package registry. Does it work if you publish it to the actual npm registry?

**Comment by gkucmierz** [comment]
I am trying to execute command:
```bash
npm publish
```

I assume it should publish files to npm registry.

**Comment by ljharb** [comment]
Yes, but your `publishConfig` is set to a nonstandard registry, and that registry (which is not npm) seems to be what's producing the error.

**Comment by ljharb** [comment]
Also I think the Github Package Registry only supports scoped package names, so `social-links` just wouldn't work there?

**Comment by gkucmierz** [comment]
Thank you 🙏  I solved it.
