### ISSUE TITLE
[BUG] <Network connection problem when using "DNS OVER HTTPS" or "DOH">

### ISSUE THREAD

**Issue by drmirk** [npm/cli#1536]
# What / Why

> Client network socket disconnected before secure TLS connection was established

## When

* I use "Simple DNSCrypt" for DOH with Cloudfare. After installing Nodejs, I tried to install puppeteer. 

Debug log
[2020-07-18T18_37_40_401Z-debug.log](https://github.com/npm/cli/files/4942321/2020-07-18T18_37_40_401Z-debug.log)
:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'puppeteer'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.5.0
4 verbose config Skipping project config: C:\Users\drmirk/.npmrc. (matches userconfig)
5 verbose npm-session e97462d9d8d268e8
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for puppeteer@latest request to https://registry.npmjs.org/puppeteer failed, reason: Client network socket disconnected before secure TLS connection was established
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 115496ms
11 verbose type system
12 verbose stack FetchError: request to https://registry.npmjs.org/puppeteer failed, reason: Client network socket disconnected before secure TLS connection was established
12 verbose stack     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
12 verbose stack     at ClientRequest.emit (events.js:314:20)
12 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:469:9)
12 verbose stack     at TLSSocket.emit (events.js:314:20)
12 verbose stack     at emitErrorNT (internal/streams/destroy.js:100:8)
12 verbose stack     at emitErrorCloseNT (internal/streams/destroy.js:68:3)
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
13 verbose cwd C:\Users\drmirk
14 verbose Windows_NT 10.0.19041
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "puppeteer"
16 verbose node v14.5.0
17 verbose npm  v6.14.5
18 error code ECONNRESET
19 error errno ECONNRESET
20 error network request to https://registry.npmjs.org/puppeteer failed, reason: Client network socket disconnected before secure TLS connection was established
21 error network This is a problem related to network connectivity.
21 error network In most cases you are behind a proxy or have bad network settings.
21 error network
21 error network If you are behind a proxy, please make sure that the
21 error network 'proxy' config is set properly.  See: 'npm help config'
22 verbose exit [ 1, true ]
```

**Comment by drmirk** [comment]
I disabled DOH and then "puppeteer" installed successfully. I have reenabled DOH, and it seems npm is working without any problem. So, maybe it was a problem in my end.

Sorry!
