### ISSUE TITLE
[BUG] `npm token` broken`

### ISSUE THREAD

**Issue by isaacs** [npm/cli#1695]
```
0 verbose cli [ '/usr/local/bin/node', '/Users/isaacs/dev/npm/cli', 'token' ]
1 info using npm@7.0.0-beta.5
2 info using node@v14.8.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/Users/isaacs/dev/npm/cli/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/isaacs/dev/npm/cli/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/isaacs/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 5ms
18 verbose npm-session e5ff1908ec8388c0
19 timing npm:load Completed in 12ms
20 info token getting list
21 http fetch GET 200 https://registry.npmjs.org/-/npm/v1/tokens 244ms
22 timing command:token Completed in 245ms
23 verbose stack TypeError: Cannot read property 'forEach' of undefined
23 verbose stack     at generateTokenIds (/Users/isaacs/dev/npm/cli/lib/token.js:68:10)
23 verbose stack     at /Users/isaacs/dev/npm/cli/lib/token.js:128:5
24 verbose cwd /Users/isaacs/dev/npm/cli
25 verbose Darwin 19.6.0
26 verbose argv "/usr/local/bin/node" "/Users/isaacs/dev/npm/cli" "token"
27 verbose node v14.8.0
28 verbose npm  v7.0.0-beta.5
29 error Cannot read property 'forEach' of undefined
30 verbose exit [ 1, undefined ]
```

**Comment by isaacs** [comment]
Fixed in latest v7 beta release https://github.com/npm/cli/commit/10fcff73a3381ea5e6dcb03888679ae4b501d2f0
