### ISSUE TITLE
[BUG] Can not repeat install directory

### ISSUE THREAD

**Issue by kingecg** [npm/cli#1808]
### Current Behavior:
install some directory and re-install again. npm report type error
6512 error typeerror Error: Argument #2: Expected object but got null
6512 error typeerror     at prepareAction (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/lib/install/actions.js:183:3)
6512 error typeerror     at /Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/lib/install/actions.js:152:16
6512 error typeerror     at Array.reduce (<anonymous>)
6512 error typeerror     at runSerial (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/lib/install/actions.js:150:29)
6512 error typeerror     at doReverseSerial (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/lib/install/actions.js:146:3)
6512 error typeerror     at Array.<anonymous> (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
6512 error typeerror     at LOOP (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
6512 error typeerror     at /Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
6512 error typeerror     at /Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/lib/install/actions.js:131:5
6512 error typeerror     at tryCatcher (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
6512 error typeerror     at Promise.successAdapter [as _fulfillmentHandler0] (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/bluebird/js/release/nodeify.js:23:30)
6512 error typeerror     at Promise._settlePromise (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
6512 error typeerror     at Promise._settlePromise0 (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
6512 error typeerror     at Promise._settlePromises (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
6512 error typeerror     at _drainQueueStep (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
6512 error typeerror     at _drainQueue (/Users/chengguang/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
6513 error typeerror This is an error with npm itself. Please report this error at:
6513 error typeerror     <https://npm.community>
6514 verbose exit [ 1, true ]

### Expected Behavior:
can re-install
### Steps To Reproduce:

1. prepare some directory as deps. I prepared 50 directories.
2. create a new dir(target) and run 'npm init' in it
3. list prepared directory into dependencies
4. run 'npm i' in target
5. run 'npm i' in target again

### Environment:

- OS: osx
- Node: 12.8
- npm: 6.14.6

**Comment by kingecg** [comment]
it seems something overflow caused this bug. when I reduce directory count to 9, I can't reproduce this problem

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
