### ISSUE TITLE
[BUG] npm show fails if keywords is a string

### ISSUE THREAD

**Issue by Kelvur** [npm/cli#1913]
### Current Behavior:
When I execute `npm show ${package}` the output is

```
npm ERR! (packument.keywords || []).map is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/miguelosorio/.npm/_logs/2020-10-07T07_55_18_257Z-debug.log
```

### Expected Behavior:

Npm should print the ${package} information, even if keyworks has a incorrect type

### Steps To Reproduce:

1. Go to a proyect where the package.keywords is a string, Ejem: 

```
// This are the keyworks of the ${package} failing
"keywords": "[\"uiverse\", \"core\"]",
```

2. Publish that package
3. Execute `npm show ${package}`

```
npm ERR! (packument.keywords || []).map is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/miguelosorio/.npm/_logs/2020-10-07T07_55_18_257Z-debug.log
```

This is part of the log
```
8 verbose stack TypeError: (packument.keywords || []).map is not a function
8 verbose stack     at BB.try (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/lib/view.js:236:44)
8 verbose stack     at tryCatcher (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
8 verbose stack     at Function.Promise.attempt.Promise.try (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/method.js:39:29)
8 verbose stack     at prettyView (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/lib/view.js:211:16)
8 verbose stack     at BB.all.results.map (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/lib/view.js:198:28)
8 verbose stack     at Array.map (<anonymous>)
8 verbose stack     at packument.catch.then.data (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/lib/view.js:198:17)
8 verbose stack     at tryCatcher (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
8 verbose stack     at Promise._settlePromiseFromHandler (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
8 verbose stack     at Promise._settlePromise (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
8 verbose stack     at Promise._settlePromise0 (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
8 verbose stack     at Promise._settlePromises (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
8 verbose stack     at _drainQueueStep (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
8 verbose stack     at _drainQueue (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
8 verbose stack     at Async._drainQueues (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
8 verbose stack     at Immediate.Async.drainQueues (/home/miguelosorio/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
```

### Environment:

- OS: Ubuntu 20.04
- Node: 8.17.0
- npm: 6.13.4

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
