### ISSUE TITLE
[BUG] "Maximum call stack size exceeded" error when a dependency of a circular dependency package could not be installed

### ISSUE THREAD

**Issue by lux01** [npm/cli#1918]
### Current Behavior:
When installing a package which includes packages with circular dependencies and a normal dependency of one of the circular dependencies could not be installed, `npm ERR! Maximum call stack size exceeded` is shown and no other diagnostics are reported.

For example consider the following tree:

```
consumer@1.0.0 /tmp/circual-deps/consumer
└─┬ library-a@1.0.1
  ├─┬ library-b@1.0.0
  │ └── library-a@1.0.1 deduped
  └── missing-lib@1.0.0
```

If `missing-lib` could not be installed, for example the `npm-shrinkwrap.json` specifies a version which has been pulled from the registry, then `npm install` will fail:

```
$ npm i
npm WARN consumer@1.0.0 No description
npm WARN consumer@1.0.0 No repository field.

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-10-07T14_09_57_254Z-debug.log
```

The log file shows that the error is due to recursively calling `failedDependency`:

```
81 verbose stack RangeError: Maximum call stack size exceeded
81 verbose stack     at RegExp.test (<anonymous>)
81 verbose stack     at isDepOptional (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:432:45)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:441:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
81 verbose stack     at failedDependency (/usr/local/Cellar/node@10/10.22.1/lib/node_modules/npm/lib/install/deps.js:457:9)
82 verbose cwd /tmp/circular-deps/consumer
83 verbose Darwin 19.6.0
84 verbose argv "/usr/local/Cellar/node@10/10.22.1/bin/node" "/usr/local/opt/node@10/bin/npm" "i"
85 verbose node v10.22.1
86 verbose npm  v6.14.6
```

This would appear to be the same symptom as #377.

### Expected Behavior:
`npm install` reports an appropriate error saying that `missing-lib` could not be installed, and continues processing (i.e. so other missing modules or install errors can be reported).

### Steps To Reproduce:
This recreate assumes a local package registry has been setup on `https://localhost:4873`, for example by using [Verdaccio](https://verdaccio.org/). I originally discovered this issue when using my company's Artifactory based npm repository. Each of the steps that publishes a module assumes that the `package-lock.json` has been deleted before publishing

1. Create and publish module `missing-lib@1.0.0`
2. Create and publish one of the circular modules `library-a@1.0.0` which depends on `missing-lib@^1.0.x`
3. Create and publish module `library-b@1.0.0` which depends on `library-a@^1.0.x`.
4. Publish `library-a@1.0.1` which depends on `library-b@^1.0.x`.
5. Create a package `consumer` which consumes `library-a@^1.0.x`.
6. Run `npm install` for `consumer` to produce the dependency tree shown above.
7. Shrinkwrap `consumer` using `npm shrinkwrap`
8. Delete `consumer`'s `node_modules` and the `.npm` cache
9. Unpublish `missing-lib@1.0.0` from the registry (for Verdaccio this can be done by deleting the folder `~/.local/share/verdaccio/storage/missing-lib` for example)
10. Run `npm install` for `consumer` to observe the reported error.

### Environment:
I've recreated this in two separate environments:

- OS: macOS 10.15.7 and Ubuntu (x86_64) 20.04.1
- Node: v10.22.1 and v14.13.0
- npm: v6.14.6 and v6.14.8

**Comment by zmzimpl** [comment]
Same here. How can I fix it?
The machine environments:
- OS: Window10
- Node: v12.14.9
- NPM: 6.14.8

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
