### ISSUE TITLE
[BUG] missing env variable `$npm_config_argv` in script using `npm run <command> ...`

### ISSUE THREAD

**Issue by kaizhu256** [npm/cli#1995]
### Current Behavior:

my travis-ci build https://travis-ci.com/github/kaizhu256/node-utility2/builds/191223014 failed after upgrading to npm v7.0.2 (nodejs v15.0.0).

this was because build-script failed to JSON.parse `process.env.npm_config_argv` expected from npm when running
`npm run postinstall/start/test`

### Expected Behavior:

`npm run <command> <arg1> <arg2> ...`

should pass env-var `$npm_config_argv` to `<command>`

### Steps To Reproduce:

ex. steps to reproduce the behavior:
1. In this environment...
linux

2. With this config...
```json
/*
 *package.json
 */
{
    "scripts": {
        "test": "node test.js"
    }
}
```

```js
/*
 * test.js
 */
console.log(process.env.npm_config_argv);
```

3. Run `npm run test foo bar`

4. See error...

output from npm v6.14.6:
`{"remain":["foo","bar"],"cooked":["run","test","foo","bar"],"original":["run","test","foo","bar"]}`

output from npm v7.0.2:
`undefined`

### Environment:

os: debian buster
node: 15.0.0
npm: 7.0.2

**Comment by isaacs** [comment]
Yep.  That was [removed on purpose](https://github.com/npm/rfcs/blob/latest/implemented/0021-reduce-lifecycle-script-environment.md).

What is your test trying to do?  Can you instead look at `npm_command` or one of the other environment variables that are set now?

**Comment by rever67697** [comment]
useful

**Comment by OrangeDog** [comment]
`npm_command` doesn't list any arguments, so not very useful at all.

**Comment by Andrew-Dyachenko** [comment]
I got the same issue after upgrade from NPM `6` to `8`.
Need to get page name from `npm_config_argv` when I starting it with Parcel and NPM `8`

```json
"scripts": {
    "start": "node start.js"
}
```
**start.js**
```js
const execSync = require('child_process').execSync;

const arg = process.argv[2];
console.log('Starting layout => ', arg || 'index');

try {
    execSync(`parcel templates/pages/${arg ? arg : 'index' }.pug`, {stdio:[0, 1, 2]});
}
catch (error) {
    console.log('error: ', error);
}
```

**index.pug**
```pug
- const mode = process.env.NODE_ENV;
- const pageName = JSON.parse(process.env.npm_config_argv).original[2];
-
    let appendBodyClassModificator = true;

    switch (pageName) {
        case undefined:
            appendBodyClassModificator = false;
            break;
        case 'index':
            switch (mode) {
                case 'production':
                    appendBodyClassModificator = true;
                    break;
                default:
                    appendBodyClassModificator = false;
                    break;
            }
            break;
        default:
            appendBodyClassModificator = true;
            break;
    }

    const bodyClassModificator = appendBodyClassModificator ? 'body--' + pageName : '';

block index
    doctype html
    html(lang='en' dir='ltr')
        block head
            head
                meta(charset='UTF-8')
                meta(name='viewport' content='width=device-width initial-scale=1.0')
                meta(http-equiv='X-UA-Compatible' content='ie=edge')
                title=pageName ? pageName.toUpperCase() : 'INDEX PAGE'

                if mode === 'development'
                    link(rel='stylesheet' href='../../assets/styles/index.scss')

                if cssPath !== null
                    link(rel='stylesheet' href=`${cssPath ? cssPath : `../../assets/styles/pages/${pageName}.scss`}`)

                if mode === 'development'
                    script(type='module' src='../../assets/js/index.js')

                if jsPath !== null
                    script(type='module' src=`${jsPath ? jsPath : `../../assets/js/pages/${pageName}/${pageName}.js`}`)

        block body
            body#body.body(class=bodyClassModificator)
```

After upgrade from NPM `6` to NPM `8` there is an error occured:

`npm run start`

```bash
Server running at http://localhost:1234
🚨 Build failed.

@parcel/transformer-pug: Unexpected token u in JSON at position 0

  SyntaxError: Unexpected token u in JSON at position 0
  at JSON.parse (<anonymous>)
  at eval (eval at wrap (/Users/andrey/Sites/main-site/src/client/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:8:23)
  at template (eval at wrap (/Users/andrey/Sites/main-site/src/client/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:652:7)
  at Object.transform (/Users/andrey/Sites/main-site/src/client/node_modules/@parcel/transformer-pug/lib/PugTransformer.js:77:19)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Transformation.runTransformer (/Users/andrey/Sites/main-site/src/client/node_modules/@parcel/core/lib/Transformation.js:617:5)
  at async Transformation.runPipeline (/Users/andrey/Sites/main-site/src/client/node_modules/@parcel/core/lib/Transformation.js:366:36)
  at async Transformation.runPipelines (/Users/andrey/Sites/main-site/src/client/node_modules/@parcel/core/lib/Transformation.js:244:40)
  at async Transformation.run (/Users/andrey/Sites/main-site/src/client/node_modules/@parcel/core/lib/Transformation.js:170:19)
  at async Child.handleRequest (/Users/andrey/Sites/main-site/src/client/node_modules/@parcel/workers/lib/child.js:217:9)
```
