### ISSUE TITLE
[BUG] TypeError: Cannot read property 'matches' of undefined

### ISSUE THREAD

**Issue by gloriaJun** [npm/cli#2118]
### Current Behavior:
Can not install packages after adding ` "@storybook/react": "^6.0.28"` module.
> It was installed normally when **yarn** was used. but **npm** doesn't

```bash
3283 http fetch GET 304 https://registry.npmjs.org/@babel%2fcore 37ms (from cache)
3284 silly fetch manifest gatsby@^2.0.0
3285 http fetch GET 304 https://registry.npmjs.org/gatsby 90ms (from cache)
3286 silly fetch manifest react@^16.4.2
3287 http fetch GET 200 https://registry.npmjs.org/react 4ms (from cache)
3288 silly fetch manifest react-dom@^16.4.2
3289 http fetch GET 304 https://registry.npmjs.org/react-dom 30ms (from cache)
3290 silly fetch manifest gatsby@^2.24.79
3291 http fetch GET 304 https://registry.npmjs.org/gatsby 84ms (from cache)
3292 silly placeDep ROOT @hapi/joi@15.1.1 OK for: gatsby@2.25.1 want: ^15.1.1
3293 silly placeDep ROOT @mikaelkristiansson/domready@1.0.10 OK for: gatsby@2.25.1 want: ^1.0.10
3294 silly placeDep ROOT @nodelib/fs.walk@1.2.4 OK for: gatsby@2.25.1 want: ^1.2.4
3295 silly placeDep node_modules/gatsby @pieh/friendly-errors-webpack-plugin@1.7.0-chalk-2 OK for: gatsby@2.25.1 want: 1.7.0-chalk-2
3296 silly placeDep node_modules/gatsby webpack@4.44.2 OK for: @pieh/friendly-errors-webpack-plugin@1.7.0-chalk-2 want: ^2.0.0 || ^3.0.0 || ^4.0.0
3297 silly placeDep ROOT @pmmmwh/react-refresh-webpack-plugin@0.4.3 OK for: gatsby@2.25.1 want: ^0.4.1
3298 silly placeDep ROOT react-refresh@0.8.3 OK for: @pmmmwh/react-refresh-webpack-plugin@0.4.3 want: >=0.8.3 <0.10.0
3299 timing idealTree Completed in 13958ms
3300 timing command:install Completed in 13962ms
3301 verbose stack TypeError: Cannot read property 'matches' of undefined
3301 verbose stack     at Arborist.[canPlaceDep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1284:15)
3301 verbose stack     at Arborist.[placeDep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:36)
3301 verbose stack     at Arborist.[placeDep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1212:41)
3301 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:766:46
3301 verbose stack     at Array.map (<anonymous>)
3301 verbose stack     at Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:766:8)
3301 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:202:7)
3301 verbose stack     at async Promise.all (index 1)
3301 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:121:5)
3301 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:40:5)
3302 verbose cwd /Volumes/data/mio/gloria-tilog
3303 verbose Darwin 19.6.0
3304 verbose argv "/usr/local/Cellar/node/15.0.1/bin/node" "/usr/local/bin/npm" "install"
3305 verbose node v15.0.1
3306 verbose npm  v7.0.3
3307 error Cannot read property 'matches' of undefined
3308 verbose exit 1
```

### Expected Behavior:

Install packages successfully.

### Steps To Reproduce:

1. packages.json
```
"dependencies": {
    "@emotion/core": "^10.1.1",
    "@emotion/styled": "^10.0.27",
    "@tailwindcss/typography": "^0.2.0",
    "clipboard": "^2.0.6",
    "gatsby": "^2.24.49",
    "gatsby-image": "^2.4.16",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.4",
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^11.0.0",
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "@mdx-js/mdx": "^1.6.16",
    "@mdx-js/react": "^1.6.19",
    "@svgr/webpack": "^5.4.0",
    "@types/react-helmet": "^6.1.0",
    "circular-dependency-plugin": "^5.2.0",
    "gatsby-plugin-alias-imports": "^1.0.5",
    "gatsby-plugin-codegen": "^1.2.14",
    "gatsby-plugin-emotion": "^4.3.10",
    "gatsby-plugin-manifest": "^2.4.24",
    "gatsby-plugin-mdx": "^1.2.35",
    "gatsby-plugin-offline": "^3.2.24",
    "gatsby-plugin-postcss": "^3.0.4",
    "gatsby-plugin-purgecss": "^5.0.0",
    "gatsby-plugin-react-helmet": "^3.3.10",
    "gatsby-plugin-sharp": "^2.6.28",
    "gatsby-plugin-svgr": "^2.0.2",
    "gatsby-plugin-typescript": "^2.4.18",
    "gatsby-remark-images": "^3.3.26",
    "gatsby-remark-prismjs": "^3.5.10",
    "gatsby-source-filesystem": "^2.3.25",
    "gatsby-transformer-sharp": "^2.5.13",
    "prismjs": "^1.21.0",
    "prop-types": "^15.7.2",
    "react-helmet": "^6.1.0",
    "ts-node": "^9.0.0",
    "twin.macro": "^1.9.0",
    "@storybook/react": "^6.0.28"
  }
```
2. remove `node_modules`, `package-lock.json`
2. execute `npm install`

### Environment:

- OS: Mac 10.15.7
- node v15.0.1
- npm 7.0.3
- yarn 1.22.10

**Comment by ljharb** [comment]
Please try npm v7.0.8? update: v7.0.9?

**Comment by pedrolamas** [comment]
This is the same basically the same issue as https://github.com/npm/cli/issues/1989

**Comment by isaacs** [comment]
Fixed in latest npm v7.  `npm i -g npm@7`

**Comment by paddor** [comment]
> Fixed in latest npm v7. `npm i -g npm@7`

Is a backport to 6.x possible?
