### ISSUE TITLE
[BUG] NPM install error

### ISSUE THREAD

**Issue by TimurDela** [npm/cli#2180]
### Current Behavior:

```
npm install --save-dev webpack-dev-server
```
gives
```
npm ERR! code ERESOLVE
npm ERR! Cannot read property 'length' of undefined
```
### Expected Behavior:

install package webpack-dev-server
### Environment:

- OS: Ubuntu 20.04
- Node: 16.0.0-nightly20201113f03f7cbd35
- npm: 7.0.8

See full log below

```
0 verbose cli [
0 verbose cli   '/snap/node/3302/bin/node',
0 verbose cli   '/snap/node/3302/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--save-dev',
0 verbose cli   'webpack-dev-server'
0 verbose cli ]
1 info using npm@7.0.8
2 info using node@v16.0.0-nightly20201113f03f7cbd35
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/snap/node/3302/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/xxx/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:~.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/snap/node/3302/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session 1e2c1a27d1d9b774
20 timing npm:load Completed in 13ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 461ms
23 timing idealTree:userRequests Completed in 4ms
24 silly idealTree buildDeps
25 silly fetch manifest webpack-dev-server@*
26 timing arborist:ctor Completed in 0ms
27 http fetch GET 304 https://registry.npmjs.org/webpack-dev-server 437ms (from cache)
28 silly fetch manifest webpack@^5.4.0
29 http fetch GET 304 https://registry.npmjs.org/webpack 43ms (from cache)
30 silly placeDep ROOT webpack-dev-server@3.11.0 OK for: hmi@1.0.0 want: *
31 silly fetch manifest ansi-html@0.0.7
32 silly fetch manifest bonjour@^3.5.0
33 silly fetch manifest chokidar@^2.1.8
34 silly fetch manifest compression@^1.7.4
35 silly fetch manifest connect-history-api-fallback@^1.6.0
36 silly fetch manifest debug@^4.1.1
37 silly fetch manifest del@^4.1.1
38 silly fetch manifest html-entities@^1.3.1
39 silly fetch manifest http-proxy-middleware@0.19.1
40 silly fetch manifest import-local@^2.0.0
41 silly fetch manifest internal-ip@^4.3.0
42 silly fetch manifest ip@^1.1.5
43 silly fetch manifest is-absolute-url@^3.0.3
44 silly fetch manifest killable@^1.0.1
45 silly fetch manifest loglevel@^1.6.8
46 silly fetch manifest opn@^5.5.0
47 silly fetch manifest p-retry@^3.0.1
48 silly fetch manifest portfinder@^1.0.26
49 silly fetch manifest schema-utils@^1.0.0
50 silly fetch manifest selfsigned@^1.10.7
51 silly fetch manifest semver@^6.3.0
52 silly fetch manifest serve-index@^1.9.1
53 silly fetch manifest sockjs@0.3.20
54 silly fetch manifest sockjs-client@1.4.0
55 silly fetch manifest spdy@^4.0.2
56 silly fetch manifest url@^0.11.0
57 silly fetch manifest webpack-dev-middleware@^3.7.2
58 silly fetch manifest webpack-log@^2.0.0
59 silly fetch manifest ws@^6.2.1
60 http fetch GET 304 https://registry.npmjs.org/ansi-html 87ms (from cache)
61 http fetch GET 304 https://registry.npmjs.org/is-absolute-url 109ms (from cache)
62 http fetch GET 304 https://registry.npmjs.org/bonjour 190ms (from cache)
63 http fetch GET 304 https://registry.npmjs.org/killable 186ms (from cache)
64 http fetch GET 304 https://registry.npmjs.org/compression 209ms (from cache)
65 http fetch GET 304 https://registry.npmjs.org/del 212ms (from cache)
66 http fetch GET 304 https://registry.npmjs.org/debug 214ms (from cache)
67 http fetch GET 304 https://registry.npmjs.org/connect-history-api-fallback 216ms (from cache)
68 http fetch GET 304 https://registry.npmjs.org/internal-ip 215ms (from cache)
69 http fetch GET 304 https://registry.npmjs.org/import-local 216ms (from cache)
70 http fetch GET 304 https://registry.npmjs.org/chokidar 223ms (from cache)
71 http fetch GET 304 https://registry.npmjs.org/http-proxy-middleware 235ms (from cache)
72 http fetch GET 304 https://registry.npmjs.org/html-entities 238ms (from cache)
73 http fetch GET 304 https://registry.npmjs.org/opn 239ms (from cache)
74 http fetch GET 304 https://registry.npmjs.org/p-retry 240ms (from cache)
75 http fetch GET 304 https://registry.npmjs.org/loglevel 243ms (from cache)
76 http fetch GET 304 https://registry.npmjs.org/portfinder 245ms (from cache)
77 http fetch GET 304 https://registry.npmjs.org/ip 253ms (from cache)
78 http fetch GET 304 https://registry.npmjs.org/schema-utils 249ms (from cache)
79 http fetch GET 304 https://registry.npmjs.org/serve-index 255ms (from cache)
80 http fetch GET 304 https://registry.npmjs.org/sockjs 255ms (from cache)
81 http fetch GET 304 https://registry.npmjs.org/semver 257ms (from cache)
82 http fetch GET 304 https://registry.npmjs.org/selfsigned 265ms (from cache)
83 http fetch GET 304 https://registry.npmjs.org/sockjs-client 264ms (from cache)
84 http fetch GET 304 https://registry.npmjs.org/url 264ms (from cache)
85 http fetch GET 304 https://registry.npmjs.org/spdy 267ms (from cache)
86 http fetch GET 304 https://registry.npmjs.org/webpack-dev-middleware 266ms (from cache)
87 http fetch GET 304 https://registry.npmjs.org/webpack-log 270ms (from cache)
88 http fetch GET 304 https://registry.npmjs.org/ws 269ms (from cache)
89 timing idealTree:#root Completed in 801ms
90 silly fetch manifest webpack@^4.43.0
91 http fetch GET 304 https://registry.npmjs.org/webpack 47ms (from cache)
92 silly placeDep ROOT ansi-html@0.0.7 OK for: webpack-dev-server@3.11.0 want: 0.0.7
93 silly placeDep ROOT bonjour@3.5.0 OK for: webpack-dev-server@3.11.0 want: ^3.5.0
94 silly placeDep node_modules/webpack-dev-server chokidar@2.1.8 OK for: webpack-dev-server@3.11.0 want: ^2.1.8
95 silly placeDep ROOT compression@1.7.4 OK for: webpack-dev-server@3.11.0 want: ^1.7.4
96 silly placeDep ROOT connect-history-api-fallback@1.6.0 OK for: webpack-dev-server@3.11.0 want: ^1.6.0
97 silly placeDep node_modules/webpack-dev-server debug@4.2.0 OK for: webpack-dev-server@3.11.0 want: ^4.1.1
98 silly placeDep ROOT del@4.1.1 OK for: webpack-dev-server@3.11.0 want: ^4.1.1
99 silly placeDep ROOT html-entities@1.3.1 OK for: webpack-dev-server@3.11.0 want: ^1.3.1
100 silly placeDep ROOT http-proxy-middleware@0.19.1 OK for: webpack-dev-server@3.11.0 want: 0.19.1
101 silly placeDep ROOT import-local@2.0.0 OK for: webpack-dev-server@3.11.0 want: ^2.0.0
102 silly placeDep ROOT internal-ip@4.3.0 OK for: webpack-dev-server@3.11.0 want: ^4.3.0
103 silly placeDep ROOT ip@1.1.5 OK for: webpack-dev-server@3.11.0 want: ^1.1.5
104 silly placeDep ROOT is-absolute-url@3.0.3 OK for: webpack-dev-server@3.11.0 want: ^3.0.3
105 silly placeDep ROOT killable@1.0.1 OK for: webpack-dev-server@3.11.0 want: ^1.0.1
106 silly placeDep ROOT loglevel@1.7.0 OK for: webpack-dev-server@3.11.0 want: ^1.6.8
107 silly placeDep ROOT opn@5.5.0 OK for: webpack-dev-server@3.11.0 want: ^5.5.0
108 silly placeDep ROOT p-retry@3.0.1 OK for: webpack-dev-server@3.11.0 want: ^3.0.1
109 silly placeDep ROOT portfinder@1.0.28 OK for: webpack-dev-server@3.11.0 want: ^1.0.26
110 silly placeDep node_modules/webpack-dev-server schema-utils@1.0.0 OK for: webpack-dev-server@3.11.0 want: ^1.0.0
111 silly placeDep ROOT selfsigned@1.10.8 OK for: webpack-dev-server@3.11.0 want: ^1.10.7
112 silly placeDep node_modules/webpack-dev-server semver@6.3.0 OK for: webpack-dev-server@3.11.0 want: ^6.3.0
113 silly placeDep ROOT serve-index@1.9.1 OK for: webpack-dev-server@3.11.0 want: ^1.9.1
114 silly placeDep ROOT sockjs@0.3.20 OK for: webpack-dev-server@3.11.0 want: 0.3.20
115 silly placeDep ROOT sockjs-client@1.4.0 OK for: webpack-dev-server@3.11.0 want: 1.4.0
116 silly placeDep ROOT spdy@4.0.2 OK for: webpack-dev-server@3.11.0 want: ^4.0.2
117 silly placeDep ROOT url@0.11.0 OK for: webpack-dev-server@3.11.0 want: ^0.11.0
118 silly placeDep node_modules/webpack-dev-server webpack-dev-middleware@3.7.2 OK for: webpack-dev-server@3.11.0 want: ^3.7.2
119 timing idealTree Completed in 1375ms
120 timing command:install Completed in 1377ms
121 verbose stack Error: unable to resolve dependency tree
121 verbose stack     at Arborist.[failPeerConflict] (/snap/node/3302/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1020:25)
121 verbose stack     at Arborist.[placeDep] (/snap/node/3302/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1096:30)
121 verbose stack     at Arborist.[placeDep] (/snap/node/3302/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1232:41)
121 verbose stack     at /snap/node/3302/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:772:46
121 verbose stack     at Array.map (<anonymous>)
121 verbose stack     at Arborist.[buildDepStep] (/snap/node/3302/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:772:8)
121 verbose stack     at async Arborist.buildIdealTree (/snap/node/3302/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:203:7)
121 verbose stack     at async Promise.all (index 1)
121 verbose stack     at async Arborist.reify (/snap/node/3302/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:121:5)
121 verbose stack     at async install (/snap/node/3302/lib/node_modules/npm/lib/install.js:38:5)
122 verbose cwd /home/timur/repos/c4-development/ctrl_sys/scada/HMI_frontend
123 verbose Linux 5.4.0-53-generic
124 verbose argv "/snap/node/3302/bin/node" "/snap/node/3302/bin/npm" "install" "--save-dev" "webpack-dev-server"
125 verbose node v16.0.0-nightly20201113f03f7cbd35
126 verbose npm  v7.0.8
127 error code ERESOLVE
128 verbose stack TypeError: Cannot read property 'length' of undefined
128 verbose stack     at explainDependents (/snap/node/3302/lib/node_modules/npm/lib/utils/explain-dep.js:68:19)
128 verbose stack     at explainFrom (/snap/node/3302/lib/node_modules/npm/lib/utils/explain-dep.js:95:5)
128 verbose stack     at explainEdge (/snap/node/3302/lib/node_modules/npm/lib/utils/explain-dep.js:87:5)
128 verbose stack     at /snap/node/3302/lib/node_modules/npm/lib/utils/explain-dep.js:59:18
128 verbose stack     at Array.map (<anonymous>)
128 verbose stack     at explainDependents (/snap/node/3302/lib/node_modules/npm/lib/utils/explain-dep.js:59:6)
128 verbose stack     at explainNode (/snap/node/3302/lib/node_modules/npm/lib/utils/explain-dep.js:13:3)
128 verbose stack     at explainEresolve (/snap/node/3302/lib/node_modules/npm/lib/utils/explain-eresolve.js:24:24)
128 verbose stack     at report (/snap/node/3302/lib/node_modules/npm/lib/utils/explain-eresolve.js:59:10)
128 verbose stack     at module.exports (/snap/node/3302/lib/node_modules/npm/lib/utils/error-message.js:24:24)
129 verbose cwd ./
130 verbose Linux 5.4.0-53-generic
131 verbose argv "/snap/node/3302/bin/node" "/snap/node/3302/bin/npm" "install" "--save-dev" "webpack-dev-server"
132 verbose node v16.0.0-nightly20201113f03f7cbd35
133 verbose npm  v7.0.8
134 error Cannot read property 'length' of undefined
135 verbose exit 1
```

_N.B._ I first filled an issue [on the developers' page](https://github.com/webpack/webpack-dev-server/issues/2834) but they answered this was an npm issue.

**Comment by ljharb** [comment]
Can you try with npm v7.0.11?

**Comment by GeorgeFuller** [comment]
I had the same issue. I had to remove some existing versions of web-pack from dependencies and delete node_modules to get this working.

**Comment by TimurDela** [comment]
> Can you try with npm v7.0.11?

When I run `sudo npm -g upgrade npm`, something is downloaded but `npm -v` still says v7.0.8

**Comment by ljharb** [comment]
@TimurDela use `npm install -g npm@7`. only use `sudo` if you're not using nvm.

**Comment by TimurDela** [comment]
I had to revert to node v15.2.1 and npm v6.14.8
Now it works

**Comment by ljharb** [comment]
@TimurDela were you unable to get it working on npm v7.0.11 or v7.0.12?

**Comment by TimurDela** [comment]
I could not revert npm to v7 without downgrading node as well

**Comment by ljharb** [comment]
`npm install -g npm@7` should do it, perhaps with sudo if that fails?

**Comment by TimurDela** [comment]
it did download something but `npm -v` showed that nothing had been installed.
