### ISSUE TITLE
[BUG] "deprecations must be strings" Deprecations fails consistently

### ISSUE THREAD

**Issue by joshgoebel** [npm/cli#2282]
### Current Behavior:

```
% npm deprecate highlight.js@"10.4.0" 'Potential vulnerability. Please upgrade to @latest'                        2.7.1
npm ERR! code E400
npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/highlight.js - deprecations must be strings

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jgoebel/.npm/_logs/2020-12-03T17_42_25_899Z-debug.log
```

### Expected Behavior:

The package should be deprecated or a USEFUL error condition should be shown.  **If there is some throttling taking place, it should be clearly stated.**  I was able to deprecated 5 prior versions immediately before this with 0 issues, but this last version just gives this meaningless error over and over.  

In the past I've worked around this by switching to a VPN in a different country, which makes even less sense.

### Steps To Reproduce:

As shown above.

### Environment:

```
% npm -v                                                                                                          
6.14.8
% node -v                                                                                                         
v14.8.0
% uname -a                                                                                                        
Darwin mbpr15-4.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64
```

Mac OS Mohave.

### Log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/jgoebel/.brew/Cellar/node/14.8.0/bin/node',
1 verbose cli   '/Users/jgoebel/.brew/bin/npm',
1 verbose cli   'deprecate',
1 verbose cli   'highlight.js@10.4.0',
1 verbose cli   'Potential vulnerability. Please upgrade to @latest'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.8.0
4 verbose npm-session 5c067fda5cec93df
5 http fetch GET 200 https://registry.npmjs.org/highlight.js?write=true 297ms
6 http fetch PUT 400 https://registry.npmjs.org/highlight.js 1896ms
7 verbose stack Error: 400 Bad Request - PUT https://registry.npmjs.org/highlight.js - deprecations must be strings
7 verbose stack     at /Users/jgoebel/.brew/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15
7 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
8 verbose statusCode 400
9 verbose pkgid highlight.js@10.4.0
10 verbose cwd /Users/jgoebel/work/highlight.js
11 verbose Darwin 18.7.0
12 verbose argv "/Users/jgoebel/.brew/Cellar/node/14.8.0/bin/node" "/Users/jgoebel/.brew/bin/npm" "deprecate" "highlight.js@10.4.0" "Potential vulnerability. Please upgrade to @latest"
13 verbose node v14.8.0
14 verbose npm  v6.14.8
15 error code E400
16 error 400 Bad Request - PUT https://registry.npmjs.org/highlight.js - deprecations must be strings
17 verbose exit [ 1, true ]
```

**Comment by ljharb** [comment]
What about `npm deprecate highlight.js@10.4.0 'Potential vulnerability. Please upgrade to @latest'`? (no quotes around the version number)

Have you tried with npm v7?

**Comment by joshgoebel** [comment]
It's not the command, these exact commands all worked moments before:

```
npm deprecate highlight.js@"10.3.x" 'Potential vulnerability. Please upgrade to @latest'
npm deprecate highlight.js@"10.2.x" 'Potential vulnerability. Please upgrade to @latest'
npm deprecate highlight.js@"10.1.2" 'Potential vulnerability. Please upgrade to @latest'
```

**After failing 5-10 times consistently switching my VPN to Paris, France immediately resolves the issue.**

It's like the server does some sort of throttling but can't just be honest about it - which would prevent a lot of frustration.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Comment by pipobscure** [comment]
Please reopen. This is still happening in v7 and requiring manual resubmission looses history.

**Comment by darcyclarke** [comment]
Closing: This seems to be either a server-side bug or a network problem. Something in transport is messing with the query string. The fact this goes away when you switch networks/VPN is a good sign of that. There's not much we can do on the CLI-side to account for this. If you're able to consistently reproduce across on a different network but with similar command args/env, please let us know.

**Comment by pipobscure** [comment]
@darcyclarke you obvs didn't read the comment fully. Turning on a VPN (or any change of public IP) fixes it. This doesn't indicate a network issue but rather something in caching on the server or client.

I can consistently reproduce this without any VPN (same env as above) all it takes is waiting 15 mins (or there about) and retrying to fix it.

Please don't just close this.

**Comment by joshgoebel** [comment]
Let's assume for a moment it is a server issue. If so, where should that issue be raised so it can be resolved?  This is a long lived issue that has been broken for quite some time in my experience.

**Comment by tfrijsewijk** [comment]
Still an issue: It appears as if it's not possible to deprecate several versions of the same package in sequence. I have 4 packages with identical versioning. I had to deprecate two versions accross all 4 packages.

I was unable to deprecate `package-a@1.0.0` followed by `package-a@2.0.0`, but when I deprecated a package in between it worked:

❌ 
```sh
npm deprecate package-a@1.0.0 "not working"
npm deprecate package-a@2.0.0 "not working" # Error
npm deprecate package-b@1.0.0 "not working"
npm deprecate package-b@2.0.0 "not working" # Error
```

✅ 
```sh
npm deprecate package-a@1.0.0 "not working"
npm deprecate package-b@1.0.0 "not working"
npm deprecate package-c@1.0.0 "not working"
npm deprecate package-d@1.0.0 "not working"
npm deprecate package-a@2.0.0 "not working"
npm deprecate package-b@2.0.0 "not working"
npm deprecate package-c@2.0.0 "not working"
npm deprecate package-d@2.0.0 "not working"
```
