### ISSUE TITLE
Error when running 'npx cypress open'

### ISSUE THREAD

**Issue by LiamJones-87** [npm/cli#2318]
When running 'npx cypress open' I get the following error:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'cypess@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\lijones\\AppData\\Roaming\\npm-cache\\_npx\\25140',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose npm-session 3bfdfffbba720423
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/cypess 977ms
8 http fetch GET 404 https://registry.npmjs.org/cypess 844ms
9 silly fetchPackageMetaData error for cypess@latest 404 Not Found - GET https://registry.npmjs.org/cypess - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 1878ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/cypess - Not found
12 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:117:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
13 verbose statusCode 404
14 verbose pkgid cypess@latest
15 verbose cwd C:\Work\Repos\TestTools\UOL Automation
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cypess@latest" "--global" "--prefix" "C:\\Users\\lijones\\AppData\\Roaming\\npm-cache\\_npx\\25140" "--loglevel" "error" "--json"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/cypess - Not found
22 error 404
23 error 404 'cypess@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

This was working previously but since Tuesday I've ben getting the above error. I've made no changes to my repo.

Environment:
- OS: Windows 10
- Node: 14.15.1
- npm: 6.14.8
- Cypress: 5.6.0

**Comment by LiamJones-87** [comment]
Not an issue - typo.
