### ISSUE TITLE
[BUG] Error: getaddrinfo EAI_FAIL http://epi:1234@127.0.0.1:5984

### ISSUE THREAD

**Issue by hamiltonsalazar** [npm/cli#2328]
### Current Behavior:

I'm new using npm. I'm implementing a class project, I've followed the installation instructions to the letter but when i try to run the project it was break.

Error:

> cajero_app@1.0.0 start C:\Users\hamil\Google Drive\UNAL - MinTIC\Ciclo 3\proyecto_ciclo3\cajero_ui\cajero_app
> npm run dev

> cajero_app@1.0.0 dev C:\Users\hamil\Google Drive\UNAL - MinTIC\Ciclo 3\proyecto_ciclo3\cajero_ui\cajero_app
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 

> 10% building modules 1/2 modules 1 active ...ode_modules\webpack\hot\dev-server.jsevents.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: getaddrinfo EAI_FAIL http://epi:1234@127.0.0.1:5984
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
> Emitted 'error' event on Server instance at:
>     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1500:12)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:17) {
>   errno: -3004,
>   code: 'EAI_FAIL',
>   syscall: 'getaddrinfo',
>   hostname: 'http://epi:1234@127.0.0.1:5984'
> }
> 
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! cajero_app@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the cajero_app@1.0.0 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! cajero_app@1.0.0 start: `npm run dev`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the cajero_app@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\hamil\AppData\Roaming\npm-cache\_logs\2020-12-11T11_49_13_559Z-debug.log

I don't know why this mentions to `http://epi:1234@127.0.0.1:5984`, it's my connection with CouchDB, mi usser, password, address and port.

### Expected Behavior:

-Project running.

### Steps To Reproduce:

I only want to run a simple project with `npm run start` or  `npm start `

### Environment:

- OS: Windows 10 Pro 1909
- Node: v14.15.1
- npm: 6.14.8

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
