### ISSUE TITLE
[BUG] npm install on root of workplaces issues EBADPLATFORM error

### ISSUE THREAD

**Issue by Choongkyu** [npm/cli#2412]
### Current Behavior:
When following the [documentation on workplaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces), I get this error:
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-24T19_27_34_887Z-debug.log
exiting dev mode because first build failed: unable to stream build output: The command '/bin/sh -c npm i' returned a non-zero code: 1
```

### Expected Behavior:
Not to get this error

### Steps To Reproduce:
Following this project structure:
```
+-- package-lock.json
+-- package.json
`-- workspace-a
   `-- package.json
`-- library
   `-- package.json
```

With this in my root `package.json`
```
{
  "name": "my-workspaces-powered-project",
  "workspaces": [
    "workspace-a",
    "library",
  ]
}
```
on Docker
1. run `npm i` (in root)
2. see error

on Arch Linux
1. run `npm i` (in root)
2. don't see error
3. run `npm i` again (in root)
4. see error

fsevents is not explicitly included as a dependency on my `package.json` files

### Environment:
- OS: Arch Linux 5.9.14-arch1-1 (also node:alpine latest image from docker)
- Node: 15.4.0 (installed through nvm on Arch Linux)
- npm: 7.0.15

The log is as follows:
```
0 verbose cli [
0 verbose cli   '/home/user/.nvm/versions/node/v15.4.0/bin/node',
0 verbose cli   '/home/user/.nvm/versions/node/v15.4.0/bin/npm',
0 verbose cli   'i'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.4.0
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:/home/user/.nvm/versions/node/v15.4.0/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/user/code/monorepo/.npmrc Completed in 0ms
9 timing config:load:project Completed in 4ms
10 timing config:load:file:/home/user/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/home/user/.nvm/versions/node/v15.4.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 verbose npm-session 68ceb47419fb7473
20 timing npm:load Completed in 19ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 495ms
23 timing idealTree:userRequests Completed in 0ms
24 silly idealTree buildDeps
25 timing idealTree:#root Completed in 0ms
26 timing idealTree:auth Completed in 0ms
27 timing idealTree:common Completed in 0ms
28 timing idealTree:buildDeps Completed in 2ms
29 timing idealTree:fixDepFlags Completed in 0ms
30 timing idealTree Completed in 501ms
31 timing command:install Completed in 503ms
32 verbose stack Error: Unsupported platform
32 verbose stack     at checkPlatform (/home/user/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/npm-install-checks/index.js:35:25)
32 verbose stack     at Arborist.[checkPlatform] (/home/user/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:235:5)
32 verbose stack     at /home/user/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:228:33
32 verbose stack     at async Arborist.buildIdealTree (/home/user/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:212:7)
32 verbose stack     at async Promise.all (index 1)
32 verbose stack     at async Arborist.reify (/home/user/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:123:5)
32 verbose stack     at async install (/home/user/.nvm/versions/node/v15.4.0/lib/node_modules/npm/lib/install.js:38:3)
33 verbose pkgid fsevents@2.1.3
34 verbose cwd /home/user/code/monorepo
35 verbose Linux 5.9.14-arch1-1
36 verbose argv "/home/user/.nvm/versions/node/v15.4.0/bin/node" "/home/user/.nvm/versions/node/v15.4.0/bin/npm" "i"
37 verbose node v15.4.0
38 verbose npm  v7.3.0
39 error code EBADPLATFORM
40 error notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
41 error notsup Valid OS:    darwin
41 error notsup Valid Arch:  undefined
41 error notsup Actual OS:   linux
41 error notsup Actual Arch: x64
42 verbose exit 1

```

**Comment by Choongkyu** [comment]
this may have been related to some stale `package-lock.json`s. Removing them and `node_module` folders and then manually uninstalling `fsevents` cleared the issue for me.
