### ISSUE TITLE
[BUG] Error installing - Cannot read property version of undefined 

### ISSUE THREAD

**Issue by joewood** [npm/cli#2435]
### Current Behavior:

When installing **abcjs** npm version 7.3 reports "Cannot read property "version" of "undefined" 

### Expected Behavior:
It should install (version 6 does)

### Steps To Reproduce:
MacOS, default npm config:

```bash
$ npm install abcjs
npm ERR! Cannot read property 'version' of undefined
```

Log:
```
1 info using npm@7.3.0
2 info using node@v12.14.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/joewood/Documents/beyond-the-piano/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/joewood/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session 602aaed1ead22ede
20 timing npm:load Completed in 21ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 563ms
23 timing idealTree:userRequests Completed in 2ms
24 silly idealTree buildDeps
25 silly fetch manifest abcjs@*
26 http fetch GET 200 https://registry.npmjs.org/abcjs 9ms (from cache)
27 silly placeDep ROOT abcjs@5.12.0 OK for: beyond-the-piano@0.1.0 want: *
28 silly fetch manifest abcjs@5.11.0
29 silly fetch manifest midi@git+https://github.com/paulrosen/MIDI.js.git#abcjs
30 http fetch GET 200 https://registry.npmjs.org/abcjs 37ms (from cache)
31 timing idealTree:#root Completed in 5128ms
32 silly placeDep node_modules/abcjs abcjs@5.11.0 OK for: abcjs@5.12.0 want: 5.11.0
33 silly placeDep ROOT midi@0.4.2 OK for: abcjs@5.12.0 want: git+https://github.com/paulrosen/MIDI.js.git#abcjs
34 silly fetch manifest abcjs@5.10.3
35 http fetch GET 200 https://registry.npmjs.org/abcjs 3ms (from cache)
36 silly timing Tried to end timer that doesn't exist: idealTree:#root
37 timing idealTree:buildDeps Completed in 5138ms
38 timing idealTree:fixDepFlags Completed in 17ms
39 timing idealTree Completed in 5741ms
40 timing reify:loadTrees Completed in 5741ms
41 timing reify:diffTrees Completed in 45ms
42 silly reify moves {}
43 timing reify:retireShallow Completed in 0ms
44 timing reify:createSparse Completed in 0ms
45 timing reify:loadBundles Completed in 0ms
46 timing reify:unpack Completed in 8ms
47 timing reify:unretire Completed in 0ms
48 timing build:queue Completed in 0ms
49 timing build:deps Completed in 0ms
50 timing build Completed in 0ms
51 timing reify:build Completed in 0ms
52 timing reify:trash Completed in 0ms
53 timing command:install Completed in 5823ms
54 verbose stack TypeError: Cannot read property 'version' of undefined
54 verbose stack     at Arborist.[saveIdealTree] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:810:33)
54 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:126:39
54 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:123:5)
54 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
55 verbose cwd /Users/joewood/Documents/beyond-the-piano
56 verbose Darwin 19.6.0
57 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "abcjs"
58 verbose node v12.14.1
59 verbose npm  v7.3.0
60 error Cannot read property 'version' of undefined
61 verbose exit 1
```

### Environment:

NodeJS: 12.14.1
npm: 7.3.0
MacOS 
No npmrc (default config)

### Additional Info

The package.json for abcjs is [here](https://github.com/paulrosen/abcjs/blob/master/package.json). The only suspicious entry here is the package dependency as a git branch.

**Comment by darcyclarke** [comment]
Hey @joewood, apologize for not getting to this sooner. I tried to replicate your issue but couldn't. I believe we've likely solved whatever the problem was with installing git deps. If you can try the latest version of npm (ie. `npm i -g npm` currently `v8.5.5`) & confirm, that would be great. I'm going to close this for now but we can reopen if you're still experiencing issues on the latest version.
