### ISSUE TITLE
[BUG] npmrc based authentication no longer works for scoped repositories

### ISSUE THREAD

**Issue by Stono** [npm/cli#2624]
### Current Behavior:
With the following `.npmrc`:
```
always-auth = true
strict-ssl = false
email = devs@us.co.uk
@at:registry = https://ourprivateregistry.jfrog.io/us/api/npm/NPM_GROUP/
//ourprivateregistry.jfrog.io/us/api/npm/NPM_GROUP/:_auth=token
```

And a package:
```
 cat package.json 
{
  "name": "@at/platform-logger",
```

And an `npm packed`:
```
pm notice 
npm notice 📦  @at/platform-logger@1.0.0
npm notice === Tarball Contents === 
...
```

`npm publish` on v7 fails:

```
[root@b04f3bce3023 app]# npm publish --verbose
npm verb cli [ '/usr/bin/original_node', '/usr/bin/npm', 'publish', '--verbose' ]
npm info using npm@7.5.2
npm info using node@v14.15.4
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/usr/local/autotrader/app/.npmrc Completed in 1ms
npm timing config:load:project Completed in 2ms
npm timing config:load:file:/root/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/usr/etc/npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 8ms
npm verb npm-session 9ab48ed525781b60
npm timing npm:load Completed in 19ms
npm verb publish [ '.' ]
npm timing command:publish Completed in 11ms
npm verb stack Error: This command requires you to be logged in.
npm verb stack     at publish_ (/usr/lib/node_modules/npm/lib/publish.js:89:27)
npm verb stack     at async publish (/usr/lib/node_modules/npm/lib/publish.js:43:19)
npm verb cwd /usr/local/autotrader/app
npm verb Linux 4.19.121-linuxkit
npm verb argv "/usr/bin/original_node" "/usr/bin/npm" "publish" "--verbose"
npm verb node v14.15.4
npm verb npm  v7.5.2
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm verb exit 1
npm timing npm Completed in 168ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-04T21_13_21_277Z-debug.log
```

However on `v6`, it's fine:
```
root@b04f3bce3023 app]# npm i -g npm@6

removed 60 packages, changed 194 packages, and audited 436 packages in 7s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[root@b04f3bce3023 app]# npm publish
npm notice 
npm notice 📦  @at/platform-logger@1.0.0
npm notice === Tarball Contents === 
...
npm notice === Tarball Details === 
npm notice name:          @at/platform-logger                     
npm notice version:       1.0.0                                   
npm notice package size:  4.7 kB                                  
npm notice unpacked size: 11.2 kB                                 
npm notice shasum:        26bb74793c3b111156610a84cb524ca385380ea2
npm notice integrity:     sha512-bcmkNOKPi5jkp[...]hdfKWLWnWa8Lw==
npm notice total files:   17                                      
npm notice 
+ @at/platform-logger@1.0.0
```

I logged out `registry` on line 89, and it appears to be picking the wrong one: `https://registry.npmjs.org/` rather than `ourpivateregistry.jfrog.io` which led me to believe `@at:registry = https://ourprivateregistry.jfrog.io/us/api/npm/NPM_GROUP/` wasn't working.

However that **does** work when doing `npm install` (we're authing and pulling @at packages fine) just not publish.

### Expected Behavior:
There's nothing in the docs that i can see about changes in `.npmrc` for `v7` so i'd expect this to still work

### Environment:
  - Node: v14.15.4
  - NPM:  7.5.2

**Comment by darcyclarke** [comment]
@stono sorry you're running into this. We should have this fixed in the next release (ie. `7.5.3`) ~Monday.

If you want to solve this temporarily, check out @wraithgar's [answer here](https://github.com/npm/cli/issues/2567#issuecomment-772076506)
