### ISSUE TITLE
[BUG] Node 8.9.4 is installed but npm not working

### ISSUE THREAD

**Issue by denzelWashington** [npm/cli#2652]
I'm getting the same problem too.
I have **node 8.9.4** installed but when i run in jenkinsfile `npm -v `, im getting this error 

```
TypeError: Cannot destructure property `stat` of 'undefined' or 'null'.
    at Object.<anonymous> (***********************/node_modules/npm/node_modules/@npmcli/node-gyp/lib/index.js:2:29)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (**********************/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:4:55)
    at Module._compile (module.js:643:30)
**********************************/node_modules/npm/node_modules/@npmcli/config/lib/index.js:163
      throw new Error('call config.load() before reading values')
```
 
i have downgraded npm to **npm@latest-6** but doesn't work for me

**Comment by ljharb** [comment]
npm 7 requires node 10, so on node 8, you can't run `npm install -g npm`. At this point you probably have to reinstall node itself.

If you're using nvm, you can use `nvm install-latest-npm` to avoid this; otherwise atm you'd have to know to run `npm install -g npm@6`.

**Comment by ljharb** [comment]
Actually, closing this in favor of #2623.
