### ISSUE TITLE
[BUG] npm install fails with 'ERR! subset is not a function'

### ISSUE THREAD

**Issue by stuart-little** [npm/cli#3046]
### Current Behavior:

In an empty directory, I am running `npm init` and then `npm install btoa`. The result:

```
npm ERR! subset is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     $HOME/.npm/_logs/2021-04-08T02_14_13_931Z-debug.log
```

### Expected Behavior:
The package installing without issue. 

### Steps To Reproduce:
1. I am running `node v15.14.0` and `npm 7.8.0` on `Arch Linux` downloaded from its repo.  
2. THis is a new project. There are no config files, no `npmrc`, etc.
3. `npm init` (pressing `Enter` throughout) and `npm i <anything>` (`btoa` was just an example)
4. I always receive errors of the form described above, RE: `subset` not being a function.

### Environment:
- OS: `Arch Linux x86_64`
- Node: 15.14.0
- npm: 7.8.0

**Additional info:**
That log file I am directed to reads
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'btoa' ]
1 info using npm@7.8.0
2 info using node@v15.14.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:$HOME/tmp/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:$HOME/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 5ms
18 timing npm:load:configload Completed in 5ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 1ms
21 timing npm:load:cleanupLog Completed in 1ms
22 timing npm:load:configScope Completed in 1ms
23 timing npm:load:projectScope Completed in 0ms
24 timing npm:load Completed in 9ms
25 timing config:load:flatten Completed in 2ms
26 timing arborist:ctor Completed in 1ms
27 timing idealTree:init Completed in 6ms
28 timing idealTree:userRequests Completed in 4ms
29 silly idealTree buildDeps
30 silly fetch manifest btoa@*
31 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
32 http fetch GET 304 https://registry.npmjs.org/btoa 202ms (from cache)
33 silly placeDep ROOT btoa@1.2.1 OK for: tmp@1.0.0 want: *
34 timing idealTree:#root Completed in 211ms
35 timing idealTree:node_modules/btoa Completed in 0ms
36 timing idealTree:buildDeps Completed in 212ms
37 timing idealTree:fixDepFlags Completed in 0ms
38 timing idealTree Completed in 223ms
39 timing reify:loadTrees Completed in 223ms
40 timing reify:diffTrees Completed in 1ms
41 silly reify mark retired [
41 silly reify   '$HOME/tmp/node_modules/btoa',
41 silly reify   '$HOME/tmp/node_modules/.bin/btoa'
41 silly reify ]
42 silly reify moves {
42 silly reify   '$HOME/tmp/node_modules/btoa': '$HOME/tmp/node_modules/.btoa-P9sTT313',
42 silly reify   '$HOME/tmp/node_modules/.bin/btoa': '$HOME/tmp/node_modules/.bin/.btoa-3qiYACmK'
42 silly reify }
43 timing reify:retireShallow Completed in 2ms
44 timing reify:createSparse Completed in 0ms
45 timing reify:loadBundles Completed in 0ms
46 timing reifyNode:node_modules/btoa Completed in 12ms
47 timing reify:unpack Completed in 12ms
48 timing reify:unretire Completed in 0ms
49 timing build:queue Completed in 0ms
50 timing build:link:node_modules/btoa Completed in 1ms
51 timing build:link Completed in 1ms
52 timing build:deps Completed in 2ms
53 timing build Completed in 2ms
54 timing reify:build Completed in 2ms
55 timing reify:trash Completed in 2ms
56 timing command:install Completed in 252ms
57 verbose stack TypeError: subset is not a function
57 verbose stack     at Arborist.[saveIdealTree] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:956:37)
57 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:138:39
57 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
57 verbose stack     at async Install.install (/usr/lib/node_modules/npm/lib/install.js:140:5)
58 verbose cwd $HOME/tmp
59 verbose Linux 5.10.25-1-lts
60 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "btoa"
61 verbose node v15.14.0
62 verbose npm  v7.8.0
63 error subset is not a function
64 verbose exit 1
```
So you can see the failure occurs when the installation tries to run 
```
/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js
```
which in turn, as I've checked, defines
```
const {subset} = require('semver')
```
I can install modules globally to `/usr/lib/node_modules` just fine, with `sudo npm install -g <module>`.

**Comment by stuart-little** [comment]
Actually, simply installing the [latest LTS](https://nodejs.org/en/download/) and removing all traces of the version installed through my package manager works out fine. 

I think this may have had to do with the many quirks of how `Arch Linux` packages these things (I've had trouble before with their own version of [ghc](https://www.haskell.org/ghc/) for instance). 

So at this point I don't know that this is actually a problem here, "upstream". For what it's worth, there's an [SO thread](https://stackoverflow.com/questions/66995902/npm-install-fails-with-subset-is-not-a-function) too.

**Comment by nlf** [comment]
yeah this sounds like somehow your package manager ended up installing old versions of modules for some reason.. since it works correctly when you installed node and npm yourself outside of the package manager, i agree with you that this is unlikely to be a problem here and is almost definitely a packaging issue in Arch.

if you discover otherwise, do feel free to reopen this issue, but i think we don't have anything to fix here.
