### ISSUE TITLE
[BUG] Stuck in same failed error state with npm installs

### ISSUE THREAD

**Issue by ruluva** [npm/cli#3128]
### Current Behavior:
Tried to do a fresh install by removing existing node_modules, and kept getting an error during the install:

```
6550 verbose stack Error: command failed
6550 verbose stack     at ChildProcess.<anonymous> (/Users/ruluva/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
6550 verbose stack     at ChildProcess.emit (events.js:315:20)
6550 verbose stack     at maybeClose (internal/child_process.js:1048:16)
6550 verbose stack     at Socket.<anonymous> (internal/child_process.js:439:11)
6550 verbose stack     at Socket.emit (events.js:315:20)
6550 verbose stack     at Pipe.<anonymous> (net.js:673:12)
6551 verbose pkgid playwright@1.9.2
6552 verbose cwd /Users/ruluva/development/ROOT_PROJECT
6553 verbose Darwin 20.3.0
6554 verbose argv "/Users/ruluva/.nvm/versions/node/v14.15.4/bin/node" "/Users/ruluva/.nvm/versions/node/v14.15.4/bin/npm" "i"
6555 verbose node v14.15.4
6556 verbose npm  v7.9.0
6557 error code 1
6558 error path /Users/ruluva/development/ROOT_PROJECT/packages/experiences/SUB_PACKAGE/node_modules/playwright
6559 error command failed
6560 error command sh -c node install.js
6561 error /Users/ruluva/development/ROOT_PROJECT/packages/experiences/SUB_PACKAGE/node_modules/https-proxy-agent/dist/agent.js:37
6561 error class HttpsProxyAgent extends agent_base_1.Agent {
6561 error                                            ^
6561 error
6561 error TypeError: Class extends value undefined is not a constructor or null
6561 error     at Object.<anonymous> (/Users/ruluva/development/ROOT_PROJECT/packages/experiences/SUB_PACKAGE/node_modules/https-proxy-agent/dist/agent.js:37:44)
6561 error     at Module._compile (internal/modules/cjs/loader.js:1063:30)
6561 error     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
6561 error     at Module.load (internal/modules/cjs/loader.js:928:32)
6561 error     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
6561 error     at Module.require (internal/modules/cjs/loader.js:952:19)
6561 error     at require (internal/modules/cjs/helpers.js:88:18)
6561 error     at Object.<anonymous> (/Users/ruluva/development/ROOT_PROJECT/packages/experiences/SUB_PACKAGE/node_modules/https-proxy-agent/dist/index.js:5:33)
6561 error     at Module._compile (internal/modules/cjs/loader.js:1063:30)
6561 error     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```
It looked like it was the playwright package causing it. I had to remove the package from the sub package in order for it to succeed. After an initial successful install, adding it back seemed to work.

### Expected Behavior:
Install without issue

### Steps To Reproduce:
1) Removed all node_modules
2) Tried install

Attempted to clear the cache as well
Also tried out npm ci

### Environment:
Mac OS 11.2.3
Node 14.15.4
NPM 7.9.0

**Comment by wraithgar** [comment]
This does not appear to be an npm bug, but something related to https-proxy-agent.  This issue may be related https://github.com/TooTallNate/node-https-proxy-agent/issues/92
