### ISSUE TITLE
`npm view` giving error if dist tag has `/` in it

### ISSUE THREAD

**Issue by dyapasrikanth** [npm/cli#3180]
I am trying to get the url of the tarball of a particular dist-tag version with `npm view`, where I want to download the package for other purpose.

Assume that I have project branches **fix/bug1**, **fix-bug1** & I could able to publish the packages with dist-tags **fix/bug1**, **fix-bug1**  with different version numbers respectively & json will look like this.

```
{
  "_id": "@test/pkg1",
  "_rev": "1-0",
  "name": "@test/pkg1",
  "dist-tags": {
    "fix/bug1": "0.0.2-fix-bug.1619994832921.0",
    "fix-bug1": "0.0.2-fix-bug.1219994832922.0",
    "latest": "0.0.1"
  },
  "versions": {
    "0.0.2-fix-bug.1619994832921.0": {
      "name": "@test/pkg1",
      "version": "0.0.2-fix-bug.1619994832921.0",
      "homepage": ".",
      "dist": {
        "tarball": "https://localhost:443/artifactory/api/npm/NPM-SHARED-build/@test/pkg1/-/@test/pkg1-0.0.2-fix-bug.1619994832921.0.tgz",
        "shasum": "75f5845c618e24310af6b415a3ed8181c921b355"
      },
    "0.0.2-fix-bug.1219994832922.0": {
      "name": "@test/pkg1",
      "version": "0.0.2-fix-bug.1219994832922.0",
      "homepage": ".",
      "dist": {
        "tarball": "https://localhost:443/artifactory/api/npm/NPM-SHARED-build/@test/pkg1/-/@test/pkg1-0.0.2-fix-bug.1219994832922.0.tgz",
        "shasum": "75f5845c618e24310af6b415a3ed8181c921b352"
      }
}

```
I am having issue to access tarball url of dist-tag which having **/** in its name.
**Current behaviour**

```
$ npm view @test/pkg1@fix-bug1 dist.tarball
https://localhost:443/artifactory/api/npm/NPM-SHARED-build/@test/pkg1/-/@test/pkg1-0.0.2-fix-bug.1219994832922.0.tgz
```
```
$ npm view @test/pkg1@fix/bug1 dist.tarball
npm ERR! Not implemented yet.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p763532/.npm/_logs/2021-05-03T00_45_24_122Z-debug.log
```

**Expected behaviour**

```
$ npm view @test/pkg1@fix/bug1 dist.tarball
https://localhost:443/artifactory/api/npm/NPM-SHARED-build/@test/pkg1/-/@test/pkg1-0.0.2-fix-bug.1619994832921.0.tgz
```

Environment
```
$ node --version
10.16.3
$ npm --version
6.9.0
```

Its same in latest version as well
```
$ node --vesion
v14.16.1
$ npm --version
6.14.12
```

**Comment by dyapasrikanth** [comment]
Verbose logs

```
npm info it worked if it ends with ok
npm verb cli [ '/Users/Srikanth/.nvm/versions/node/v10.16.3/bin/node',
npm verb cli   '/Users/Srikanth/.nvm/versions/node/v10.16.3/bin/npm',
npm verb cli   'view',
npm verb cli   '@test/pkg1@fix/bug1',
npm verb cli   'dist.tarball',
npm verb cli   '--verbose' ]
npm info using npm@6.9.0
npm info using node@v10.16.3
npm verb npm-session bb9bd40e3a2ef7ec
npm verb stack Error: Not implemented yet.
npm verb stack     at Object.packument (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/pacote/lib/fetchers/git.js:25:22)
npm verb stack     at Object.Fetcher#packument [as packument] (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/genfun/lib/genfun.js:15:38)
npm verb stack     at packument (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/pacote/lib/fetch.js:17:18)
npm verb stack     at pinflight (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/pacote/packument.js:23:12)
npm verb stack     at /Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24
npm verb stack     at Promise._execute (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/bluebird/js/release/debuggability.js:313:9)
npm verb stack     at Promise._resolveFromExecutor (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:483:18)
npm verb stack     at new Promise (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:79:10)
npm verb stack     at _inflight (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)
npm verb stack     at /Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14
npm verb stack     at tryCatcher (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromiseCtx (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
npm verb stack     at _drainQueueStep (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:142:12)
npm verb stack     at _drainQueue (/Users/Srikanth/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
npm verb cwd /Users/Srikanth/workspace/spa-forms
npm verb Darwin 20.3.0
npm verb argv "/Users/Srikanth/.nvm/versions/node/v10.16.3/bin/node" "/Users/Srikanth/.nvm/versions/node/v10.16.3/bin/npm" "view" "@test/pkg1@fix/bug1" "dist.tarball" "--verbose"
npm verb node v10.16.3
npm verb npm  v6.9.0
npm ERR! Not implemented yet.
npm verb exit [ 1, true ]
npm timing npm Completed in 562ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Srikanth/.npm/_logs/2021-05-03T00_47_23_444Z-debug.log
```

**Comment by darcyclarke** [comment]
npm \`v6\` is no longer in active development; We will continue to push security releases to \`v6\` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is reproducible on \`v7\`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
