### ISSUE TITLE
[BUG] `npm install` fails with npm ERR! Cannot read property 'sourceReference' of null

### ISSUE THREAD

**Issue by blimmer** [npm/cli#3194]
### Current Behavior:

I get a failure when running `npm install` without an existing `package-lock.json` with a specific `package.json` file.

The failure I get is:

```
npm ERR! Cannot read property 'sourceReference' of null
```

From the debug log, here's the stack trace:

```
10602 verbose stack TypeError: Cannot read property 'sourceReference' of null
10602 verbose stack     at Arborist.[placeDep] (/Users/blimmer/.asdf/installs/nodejs/16.1.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1462:44)
10602 verbose stack     at /Users/blimmer/.asdf/installs/nodejs/16.1.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:905:46
10602 verbose stack     at Array.map (<anonymous>)
10602 verbose stack     at Arborist.[buildDepStep] (/Users/blimmer/.asdf/installs/nodejs/16.1.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:905:8)
10602 verbose stack     at async Arborist.buildIdealTree (/Users/blimmer/.asdf/installs/nodejs/16.1.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
10602 verbose stack     at async Promise.all (index 1)
10602 verbose stack     at async Arborist.reify (/Users/blimmer/.asdf/installs/nodejs/16.1.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:135:5)
10602 verbose stack     at async Install.install (/Users/blimmer/.asdf/installs/nodejs/16.1.0/lib/node_modules/npm/lib/install.js:137:5)
```

Here's the full debug log: https://github.com/blimmer/npm-bug-report/blob/main/debug.log

### Expected Behavior:

I expect `npm install` to succeed and create a `package-lock.json` file.

### Steps To Reproduce:

1. Use [this](https://github.com/blimmer/npm-bug-report/blob/main/package.json) `package.json` file
2. Run `npm i`

I've created a sample repository [here](https://github.com/blimmer/npm-bug-report) with a [GitHub action](https://github.com/blimmer/npm-bug-report/actions/workflows/npm-install.yml) to show the failure.

### Environment:

OS: Mac OS 11.3.1 and Ubuntu latest
Node: 16.1.0
npm: 7.11.2

**Comment by blimmer** [comment]
I traced it down to the `@nivo/core` and `@nivo/line` dependencies. Here's a passing branch from my sample repo: https://github.com/blimmer/npm-bug-report/pull/1

**Comment by blimmer** [comment]
Ah, OK, so I can't straight-up `npm install` these dependencies in a new repo:

```
 12:24:18  /tmp/foo  npm i --save @nivo/core @nivo/line
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@">= 16.8.4 < 18.0.0" from @nivo/core@0.69.0
npm WARN   node_modules/@nivo/core
npm WARN     @nivo/core@"*" from the root project
npm WARN     5 more (@nivo/tooltip, @nivo/line, @nivo/annotations, ...)
npm WARN   4 more (@nivo/line, @nivo/recompose, @nivo/annotations, @nivo/axes)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@">= 16.8.4 <= 17.0.0" from @nivo/colors@0.69.0
npm WARN node_modules/@nivo/colors
npm WARN   @nivo/colors@"0.69.0" from @nivo/line@0.69.1
npm WARN   node_modules/@nivo/line
npm WARN   1 more (@nivo/annotations)
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.2
npm WARN node_modules/react-spring/node_modules/react
npm WARN   peer react@">=16.8" from @react-spring/konva@9.1.2
npm WARN   node_modules/react-spring/node_modules/@react-spring/konva
npm WARN     @react-spring/konva@"~9.1.2" from react-spring@9.1.2
npm WARN     node_modules/react-spring
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"16.8.x" from react-konva@16.8.6
npm WARN node_modules/react-spring/node_modules/react-konva
npm WARN   peer react-konva@">=16.8" from @react-spring/konva@9.1.2
npm WARN   node_modules/react-spring/node_modules/@react-spring/konva
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: konva@7.2.5
npm WARN node_modules/konva
npm WARN   peer konva@">=2.6" from @react-spring/konva@9.1.2
npm WARN   node_modules/react-spring/node_modules/@react-spring/konva
npm WARN     @react-spring/konva@"~9.1.2" from react-spring@9.1.2
npm WARN     node_modules/react-spring
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer konva@"^3.2.3" from react-konva@16.8.6
npm WARN node_modules/react-spring/node_modules/react-konva
npm WARN   peer react-konva@">=16.8" from @react-spring/konva@9.1.2
npm WARN   node_modules/react-spring/node_modules/@react-spring/konva
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.2
npm WARN node_modules/react-spring/node_modules/react
npm WARN   peer react@">=16.8" from @react-spring/konva@9.1.2
npm WARN   node_modules/react-spring/node_modules/@react-spring/konva
npm WARN     @react-spring/konva@"~9.1.2" from react-spring@9.1.2
npm WARN     node_modules/react-spring
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"17.0.1" from react-native@0.64.1
npm WARN node_modules/react-spring/node_modules/react-native
npm WARN   peer react-native@">=0.58" from @react-spring/native@9.1.2
npm WARN   node_modules/react-spring/node_modules/@react-spring/native
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react-dom@17.0.2
npm ERR! node_modules/react-spring/node_modules/react-dom
npm ERR!   peerOptional react-dom@">=17.0" from @react-three/fiber@6.0.19
npm ERR!   node_modules/react-spring/node_modules/@react-three/fiber
npm ERR!     peer @react-three/fiber@">=6.0" from @react-spring/three@9.1.2
npm ERR!     node_modules/react-spring/node_modules/@react-spring/three
npm ERR!       @react-spring/three@"~9.1.2" from react-spring@9.1.2
npm ERR!       node_modules/react-spring
npm ERR!         react-spring@"9.1.2" from @nivo/core@0.69.0
npm ERR!         node_modules/@nivo/core
npm ERR!         4 more (@nivo/tooltip, @nivo/line, @nivo/annotations, @nivo/axes)
npm ERR!   peer react-dom@">=16.13" from react-use-measure@2.0.4
npm ERR!   node_modules/react-spring/node_modules/react-use-measure
npm ERR!     react-use-measure@"^2.0.4" from @react-three/fiber@6.0.19
npm ERR!     node_modules/react-spring/node_modules/@react-three/fiber
npm ERR!       peer @react-three/fiber@">=6.0" from @react-spring/three@9.1.2
npm ERR!       node_modules/react-spring/node_modules/@react-spring/three
npm ERR!         @react-spring/three@"~9.1.2" from react-spring@9.1.2
npm ERR!         node_modules/react-spring
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-dom@"16.8.x" from react-konva@16.8.6
npm ERR! node_modules/react-spring/node_modules/react-konva
npm ERR!   peer react-konva@">=16.8" from @react-spring/konva@9.1.2
npm ERR!   node_modules/react-spring/node_modules/@react-spring/konva
npm ERR!     @react-spring/konva@"~9.1.2" from react-spring@9.1.2
npm ERR!     node_modules/react-spring
npm ERR!       react-spring@"9.1.2" from @nivo/core@0.69.0
npm ERR!       node_modules/@nivo/core
npm ERR!       4 more (@nivo/tooltip, @nivo/line, @nivo/annotations, @nivo/axes)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/blimmer/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blimmer/.npm/_logs/2021-05-05T18_24_31_659Z-debug.log
```

It looks like they're aware of the issue on the `@nivo` side: https://github.com/plouc/nivo/issues/1462

Is there a way to bubble this error up, instead of the `npm ERR! Cannot read property 'sourceReference' of null` message? That would save folks some time when upgrading.

**Comment by itamardavidyan** [comment]
I Also got this error:

```
✗ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.0" from the root project
npm ERR!   peer react@">= 16.8.4 < 18.0.0" from @nivo/calendar@0.69.0
npm ERR!   node_modules/@nivo/calendar
npm ERR!     @nivo/calendar@"^0.69.0" from the root project
npm ERR!   25 more (@nivo/core, @nivo/line, @nivo/pie, @react-hook/hover, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 16.8.4 <= 17.0.0" from @nivo/colors@0.69.0
npm ERR! node_modules/@nivo/line/node_modules/@nivo/colors
npm ERR!   @nivo/colors@"0.69.0" from @nivo/line@0.69.1
npm ERR!   node_modules/@nivo/line
npm ERR!     @nivo/line@"^0.69.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/itamard/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/itamard/.npm/_logs/2021-05-20T04_14_55_630Z-debug.log

**Comment by ljharb** [comment]
@itamardavidyan that's not related to this issue. the issue there is that `@nivo/colors` does not work with react 17, so you have to either upgrade that, or downgrade react, because the two can't live in the same dep tree.

**Comment by juanguerra1976** [comment]
Hi guys!

I'm experiencing the same issue while trying to install react-animated-numbers package:

react-animated-numbers

As I can see it also includes react-spring 🤔 

Could be something related to that?

Thanks.

**Comment by juanguerra1976** [comment]
Hi guys!

I'm experiencing the same issue while trying to install the following package:

[https://www.npmjs.com/package/react-animated-numbers](url)

As I can see it also includes react-spring 🤔

Could be something related to that?

Thanks.

**Comment by dineshshaw** [comment]
> Hi guys!
> 
> I'm experiencing the same issue while trying to install the following package:
> 
> [https://www.npmjs.com/package/react-animated-numbers](url)
> 
> As I can see it also includes react-spring 🤔
> 
> Could be something related to that?
> 
> Thanks.

same here

**Comment by chucklu** [comment]
Run command `npm ls -g --depth 0`, got a similar error info.
Cannot read property 'package' of null， not sure if it's the same issue.
> 29 verbose stack TypeError: Cannot read property 'package' of null
> 29 verbose stack     at Link.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\node.js:704:35)
> 29 verbose stack     at Node.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\node.js:770:20)
> 29 verbose stack     at Node.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\node.js:770:20)
> 29 verbose stack     at Node.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\node.js:578:22)
> 29 verbose stack     at Node.set parent [as parent] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\node.js:1212:15)
> 29 verbose stack     at new Node (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\node.js:212:17)
> 29 verbose stack     at Arborist.[newNode] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\load-actual.js:304:9)
> 29 verbose stack     at C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\load-actual.js:266:68
> 29 verbose stack     at async Promise.all (index 0)
> 29 verbose stack     at async Arborist.[findMissingEdges] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\load-actual.js:428:7)
> 30 verbose cwd C:\workspace\\production\vueSrc
> 31 verbose Windows_NT 10.0.19042
> 32 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\clu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "ls" "-g" "--depth" "0"
> 33 verbose node v14.17.5
> 34 verbose npm  v8.1.2
> 35 error Cannot read property 'package' of null
> 36 verbose exit 1

**Comment by GitPopcorn** [comment]
> Run command `npm ls -g --depth 0`, got a similar error info. Cannot read property 'package' of null， not sure if it's the same issue.
> 
> > 29 verbose stack TypeError: Cannot read property 'package' of null
> > 29 verbose stack     at Link.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:704:35)
> > 29 verbose stack     at Node.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:770:20)
> > 29 verbose stack     at Node.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:770:20)
> > 29 verbose stack     at Node.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:578:22)
> > 29 verbose stack     at Node.set parent [as parent] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:1212:15)
> > 29 verbose stack     at new Node (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:212:17)
> > 29 verbose stack     at Arborist.[newNode] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\arborist\load-actual.js:304:9)
> > 29 verbose stack     at C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\arborist\load-actual.js:266:68
> > 29 verbose stack     at async Promise.all (index 0)
> > 29 verbose stack     at async Arborist.[findMissingEdges] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\arborist\load-actual.js:428:7)
> > 30 verbose cwd C:\workspace\production\vueSrc
> > 31 verbose Windows_NT 10.0.19042
> > 32 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Users\clu\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "ls" "-g" "--depth" "0"
> > 33 verbose node v14.17.5
> > 34 verbose npm  v8.1.2
> > 35 error Cannot read property 'package' of null
> > 36 verbose exit 1

Got the same issue, have you solved it?

**Comment by GitPopcorn** [comment]
> Run command `npm ls -g --depth 0`, got a similar error info. Cannot read property 'package' of null， not sure if it's the same issue.
> 
> > 29 verbose stack TypeError: Cannot read property 'package' of null
> > 29 verbose stack     at Link.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:704:35)
> > 29 verbose stack     at Node.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:770:20)
> > 29 verbose stack     at Node.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:770:20)
> > 29 verbose stack     at Node.set root [as root] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:578:22)
> > 29 verbose stack     at Node.set parent [as parent] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:1212:15)
> > 29 verbose stack     at new Node (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\node.js:212:17)
> > 29 verbose stack     at Arborist.[newNode] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\arborist\load-actual.js:304:9)
> > 29 verbose stack     at C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\arborist\load-actual.js:266:68
> > 29 verbose stack     at async Promise.all (index 0)
> > 29 verbose stack     at async Arborist.[findMissingEdges] (C:\Users\clu\AppData\Roaming\npm\node_modules\npm\node_modules@npmcli\arborist\lib\arborist\load-actual.js:428:7)
> > 30 verbose cwd C:\workspace\production\vueSrc
> > 31 verbose Windows_NT 10.0.19042
> > 32 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Users\clu\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "ls" "-g" "--depth" "0"
> > 33 verbose node v14.17.5
> > 34 verbose npm  v8.1.2
> > 35 error Cannot read property 'package' of null
> > 36 verbose exit 1

Alright, I update some global dependencies (precisely, the babel-cli) and solve it.
