### ISSUE TITLE
[BUG] Cannot read property 'spec' of undefined when using npm install --prefix + tmpdir on mac 

### ISSUE THREAD

**Issue by nguerrera** [npm/cli#3256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

This *might* be a duplicate of https://github.com/npm/cli/issues/3021, but the repro is different, and hopefully easier to diagnose.

### Current Behavior

`npm install --prefix <tmpdir> <package>` fails on Mac OS

where `<tmpdir>` is the result of `fs.mkdtempSync(path.join(os.tmpdir(), "repro")`

```
npm ERR! Cannot read property 'spec' of undefined

55 verbose stack TypeError: Cannot read property 'spec' of undefined
55 verbose stack     at Arborist.[saveIdealTree] (/Users/nicholg/.npm/g/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:959:62)
55 verbose stack     at /Users/nicholg/.npm/g/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:139:39
55 verbose stack     at async Arborist.reify (/Users/nicholg/.npm/g/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:135:5)
55 verbose stack     at async Install.install (/Users/nicholg/.npm/g/lib/node_modules/npm/lib/install.js:137:5)
```

<details>

```
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node@14/14.17.0/bin/node',
0 verbose cli   '/Users/nicholg/.npm/g/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--prefix',
0 verbose cli   '/var/folders/pt/zgtgnf1n5sl7_vw3n7dqvm5w0000gn/T/reproXMRg76',
0 verbose cli   'leftpad-i18n'
0 verbose cli ]
1 info using npm@7.13.0
2 info using node@v14.17.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/Users/nicholg/.npm/g/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/var/folders/pt/zgtgnf1n5sl7_vw3n7dqvm5w0000gn/T/reproXMRg76/.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/nicholg/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/var/folders/pt/zgtgnf1n5sl7_vw3n7dqvm5w0000gn/T/reproXMRg76/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:setTitle Completed in 3ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 16ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 18ms
30 timing idealTree:userRequests Completed in 2ms
31 silly idealTree buildDeps
32 silly fetch manifest leftpad-i18n@*
33 http fetch GET 304 https://registry.npmjs.org/leftpad-i18n 171ms (from cache)
34 silly placeDep ROOT leftpad-i18n@1.1.0 OK for:  want: *
35 timing idealTree:#root Completed in 178ms
36 timing idealTree:node_modules/leftpad-i18n Completed in 0ms
37 timing idealTree:buildDeps Completed in 180ms
38 timing idealTree:fixDepFlags Completed in 0ms
39 timing idealTree Completed in 201ms
40 timing reify:loadTrees Completed in 202ms
41 timing reify:diffTrees Completed in 0ms
42 silly reify moves {}
43 timing reify:retireShallow Completed in 0ms
44 timing reify:createSparse Completed in 0ms
45 timing reify:loadBundles Completed in 0ms
46 silly audit bulk request { 'leftpad-i18n': [ '1.1.0' ] }
47 timing reify:unpack Completed in 0ms
48 timing reify:unretire Completed in 1ms
49 timing build:queue Completed in 0ms
50 timing build:deps Completed in 0ms
51 timing build Completed in 0ms
52 timing reify:build Completed in 0ms
53 timing reify:trash Completed in 0ms
54 timing command:install Completed in 219ms
55 verbose stack TypeError: Cannot read property 'spec' of undefined
55 verbose stack     at Arborist.[saveIdealTree] (/Users/nicholg/.npm/g/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:959:62)
55 verbose stack     at /Users/nicholg/.npm/g/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:139:39
55 verbose stack     at async Arborist.reify (/Users/nicholg/.npm/g/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:135:5)
55 verbose stack     at async Install.install (/Users/nicholg/.npm/g/lib/node_modules/npm/lib/install.js:137:5)
56 verbose cwd /Users/nicholg/q
57 verbose Darwin 20.4.0
58 verbose argv "/usr/local/Cellar/node@14/14.17.0/bin/node" "/Users/nicholg/.npm/g/bin/npm" "install" "--prefix" "/var/folders/pt/zgtgnf1n5sl7_vw3n7dqvm5w0000gn/T/reproXMRg76" "leftpad-i18n"
59 verbose node v14.17.0
60 verbose npm  v7.13.0
61 error Cannot read property 'spec' of undefined
62 verbose exit 1
```

</details>

### Expected Behavior

Installation succeeds as it does if I downgrade to npm 6.x.

### Steps To Reproduce

Using environment described below, create a repro.js file with the following:

```js
const { spawnSync } = require("child_process");
const { mkdtempSync } = require("fs");
const { tmpdir } = require("os");
const { join } = require("path");

const dir = mkdtempSync(join(tmpdir(), "repro"));
console.log(`> npm install --prefix ${dir} "leftpad-i18n"\n`);
spawnSync("npm", ["install", "--prefix", dir, "leftpad-i18n" ], {
  stdio: "inherit",
});
```

Then run it:
> node repro.js

### Environment

- OS: mac OS Big Sur 11.3.1
- Node: 14.17.0
- npm: 7.13.0

**Comment by wraithgar** [comment]
I don't get the same error in `v7.18.1` but I do get what I would consider buggy behavior.   The package.json and package-lock.json files are created, but there is no `node_modules` directory. 

This does NOT happen if I pass a `prefix` that is in my home directory.

```
> fs.mkdtempSync(path.join(os.tmpdir(), "repro")
... )
'/var/folders/83/96hs_64s4wzg1n_q8x9wp9mm0000gp/T/reproX99iFq'
```

```sh
~/D/n/scratch $ npm i  --prefix=/var/folders/83/96hs_64s4wzg1n_q8x9wp9mm0000gp/T/reproX99iFq abbrev

up to date, audited 6 packages in 520ms

found 0 vulnerabilities
~/D/n/scratch $ ls -al /var/folders/83/96hs_64s4wzg1n_q8x9wp9mm0000gp/T/reproX99iFq
total 16
drwx------    4 wraithgar  staff   128 Jun 18 14:25 ./
drwx------@ 101 wraithgar  staff  3232 Jun 18 14:29 ../
-rw-r--r--    1 wraithgar  staff  2021 Jun 18 14:31 package-lock.json
-rw-r--r--    1 wraithgar  staff    51 Jun 18 14:25 package.json
```

**Comment by G-Rath** [comment]
I can produce this behaviour locally in a non-tmp directory using this script:

```
#!/usr/bin/env bash

rm -rf fresh4

mkdir fresh4

cd fresh4

npm init -y
npm install ssri

mkdir subpack
npm init -y --prefix subpack
npm install ssri --prefix subpack

npm install ./subpack

npm ls --all
```

```
npm ERR! Cannot read property 'spec' of undefined                                                                                                                                                                                                                                                                                                                                                                                                                                       npm ERR! A complete log of this run can be found in:                                                                                                                                                                                        npm ERR!     /home/g-rath/.npm/_logs/2021-06-25T03_33_17_578Z-debug.log
```

```
57 verbose stack TypeError: Cannot read property 'spec' of undefined
57 verbose stack     at Arborist.[saveIdealTree] (/home/g-rath/.nodenv/versions/16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:939:44)
57 verbose stack     at Arborist.reify (/home/g-rath/.nodenv/versions/16.0.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:137:31)
57 verbose stack     at async Install.install (/home/g-rath/.nodenv/versions/16.0.0/lib/node_modules/npm/lib/install.js:150:5)
58 verbose cwd /c/Users/G-Rath/workspace/npm-workspaces/fresh4
59 verbose Linux 4.4.0-19041-Microsoft
60 verbose argv "/home/g-rath/.nodenv/versions/16.0.0/bin/node" "/home/g-rath/.nodenv/versions/16.0.0/bin/npm" "install" "./subpack"
61 verbose node v16.0.0
62 verbose npm  v7.19.0
63 error Cannot read property 'spec' of undefined
64 verbose exit 1
```

This is running the latest npm (7.19.0) on Node 16.0.0, from a standard directory and also from my home directory.
This doesn't happen if I don't use `--prefix`.

I figure this will be the same underlying issue - let me know if you'd like more info or a new issue to be created :)

**Comment by wraithgar** [comment]
Still can't reproduce this locally. The example from the last comment breaks because `npm init` does not use the `--prefix` param, if you cd into `subpack` and run `npm init` and do the rest of the example it works fine.

If this is still an issue please open a new issue, using the latest npm, with steps to reproduce.
