### ISSUE TITLE
[BUG] Unable to install a package with a caret range

### ISSUE THREAD

**Issue by SiddharthShyniben** [npm/cli#3373]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I am unable to install a package (`@jest/core`) With a caret range (`@jest/core@^27.0.1`). When I do so, I get the `notarget` error.

### Debug Log

```log
    0 verbose cli [
    0 verbose cli   '/Users/apple/.nvm/versions/node/v16.3.0/bin/node',
    0 verbose cli   '/Users/apple/.nvm/versions/node/v16.3.0/bin/npm',
    0 verbose cli   'i',
    0 verbose cli   '@jest/core@^27.0.1'
    0 verbose cli ]
    1 info using npm@7.11.2
    2 info using node@v16.3.0
    3 timing npm:load:whichnode Completed in 1ms
    4 timing config:load:defaults Completed in 2ms
    5 timing config:load:file:/Users/apple/.nvm/versions/node/v16.3.0/lib/node_modules/npm/npmrc Completed in 2ms
    6 timing config:load:builtin Completed in 2ms
    7 timing config:load:cli Completed in 2ms
    8 timing config:load:env Completed in 0ms
    9 timing config:load:file:/Users/apple/Sites/Projects/npm-bug-test/.npmrc Completed in 0ms
    10 timing config:load:project Completed in 1ms
    11 verbose config init.author.name Use `--init-author-name` instead.
    12 verbose config init.author.email Use `--init-author-email` instead.
    13 verbose config init.author.url Use `--init-author-url` instead.
    14 verbose config init.license Use `--init-license` instead.
    15 timing config:load:file:/Users/apple/.npmrc Completed in 2ms
    16 timing config:load:user Completed in 2ms
    17 timing config:load:file:/Users/apple/.nvm/versions/node/v16.3.0/etc/npmrc Completed in 0ms
    18 timing config:load:global Completed in 1ms
    19 timing config:load:validate Completed in 1ms
    20 timing config:load:credentials Completed in 1ms
    21 timing config:load:setEnvs Completed in 1ms
    22 timing config:load Completed in 13ms
    23 timing npm:load:configload Completed in 13ms
    24 timing npm:load:setTitle Completed in 25ms
    25 timing npm:load:setupLog Completed in 0ms
    26 timing npm:load:cleanupLog Completed in 2ms
    27 timing npm:load:configScope Completed in 0ms
    28 timing npm:load:projectScope Completed in 0ms
    29 timing npm:load Completed in 43ms
    30 timing config:load:flatten Completed in 3ms
    31 timing arborist:ctor Completed in 1ms
    32 timing arborist:ctor Completed in 0ms
    33 timing idealTree:init Completed in 14ms
    34 timing idealTree:userRequests Completed in 5ms
    35 silly idealTree buildDeps
    36 silly fetch manifest @jest/core@^27.0.1
    37 http fetch GET 200 https://registry.npmjs.org/@jest%2fcore 73ms (from cache)
    38 silly placeDep ROOT @jest/core@ OK for: npm-bug-test@1.0.0 want: ^27.0.1
    39 timing idealTree:#root Completed in 85ms
    40 timing idealTree:node_modules/@jest/core Completed in 0ms
    41 timing idealTree:buildDeps Completed in 86ms
    42 timing idealTree:fixDepFlags Completed in 1ms
    43 timing idealTree Completed in 107ms
    44 timing command:install Completed in 119ms
    45 verbose type range
    46 verbose stack @jest/core: No matching version found for @jest/core@^27.0.1.
    46 verbose stack     at module.exports (/Users/apple/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
    46 verbose stack     at /Users/apple/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
    46 verbose stack     at async Arborist.[nodeFromEdge] (/Users/apple/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:946:19)
    46 verbose stack     at async Arborist.[buildDepStep] (/Users/apple/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:892:11)
    46 verbose stack     at async Arborist.buildIdealTree (/Users/apple/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
    46 verbose stack     at async Promise.all (index 1)
    46 verbose stack     at async Arborist.reify (/Users/apple/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:135:5)
    46 verbose stack     at async Install.install (/Users/apple/.nvm/versions/node/v16.3.0/lib/node_modules/npm/lib/install.js:137:5)
    47 verbose cwd /Users/apple/Sites/Projects/npm-bug-test
    48 verbose Darwin 16.7.0
    49 verbose argv "/Users/apple/.nvm/versions/node/v16.3.0/bin/node" "/Users/apple/.nvm/versions/node/v16.3.0/bin/npm" "i" "@jest/core@^27.0.1"
    50 verbose node v16.3.0
    51 verbose npm  v7.11.2
    52 error code ETARGET
    53 error notarget No matching version found for @jest/core@^27.0.1.
    54 error notarget In most cases you or one of your dependencies are requesting
    54 error notarget a package version that doesn't exist.
    55 verbose exit 1
```

### Expected Behavior

The correct package is installed.

### Steps To Reproduce

1. Init npm – `npm init`
2. Run `npm i @jest/core@^27.0.1`
3. See error

### Environment

- OS: MacOS 10.12
- Node: 16.3.0
- npm: 7.11.2

**Comment by wraithgar** [comment]
@SiddharthShyniben  can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`).

I could not duplicate this w/ `npm@7.16.0`

```sh
~/D/n/scratch $ npm i @jest/core@^27.0.1

added 319 packages, and audited 320 packages in 11s

found 0 vulnerabilities
~/D/n/scratch $ grep jest package.json 
    "@jest/core": "^27.0.4"
```

**Comment by SiddharthShyniben** [comment]
And that is the next problem – I can't seem to be able to install the latest version of npm too.

```console
$ apple ~ >> npm i -g npm@7.16.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for npm@7.16.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2021-06-08T02_52_06_956Z-debug.log
```

Even using `nvm` only installs `7.11.2`

**Comment by SiddharthShyniben** [comment]
I had this same issue before, I was not able to install the latest version of `npm` (See #2975)

**Comment by SiddharthShyniben** [comment]
**I get a 404 at <https://registry.npmjs.org/npm/7.11.6>**

I don't know why but the registry isn't updated here in my place. Should I file a new issue saying that the registry won't update?

**Comment by wraithgar** [comment]
`7.11.6` is not a published version of npm.

```sh
$ npm info npm versions|tail -4
  '7.9.0',         '7.10.0',          '7.11.0',        '7.11.1',
  '7.11.2',        '7.12.0',          '7.12.1',        '7.13.0',
  '7.14.0',        '7.15.0',          '7.15.1',        '7.16.0'
```

If you continue to have issues with the npm registry itself, you may want to fill out the form on the support page: https://www.npmjs.com/support

**Comment by SiddharthShyniben** [comment]
Just going to drop this here: this happened because I had `preffer-offline` set to true in my configuration. Hope it helps anyone.
