### ISSUE TITLE
[BUG] 403 Forbidden when installing npm package from private repo

### ISSUE THREAD

**Issue by sforcier** [npm/cli#3492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot install npm modules hosted in our private jFrog Artifactory as of npm 7.19.0. I've tried with npm 7.18.1 and it works fine, but with 7.19.0 I get the error log listed in the steps to reproduce.

### Expected Behavior

The command should complete successfully.

### Steps To Reproduce

1. execute the command: `npm i -D @private/promise-util`
2. Observe error at cli (some PII is redacted)
```
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://artifactory.redacted.com:443/artifactory/api/npm/private-npm-local/@private%2fpromise-util - forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Local\npm-cache\_logs\2021-07-01T15_18_03_761Z-debug.log
```

3. Observe error in log (some PII is redacted):
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i',
0 verbose cli   '-D',
0 verbose cli   '@private/promise-util'
0 verbose cli ]
1 info using npm@7.19.0
2 info using node@v14.15.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\username\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\git\test-ssm-param\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\username\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\username\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 12ms
19 timing npm:load:configload Completed in 13ms
20 timing npm:load:setTitle Completed in 1ms
21 timing npm:load:setupLog Completed in 0ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 1ms
25 timing npm:load Completed in 17ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 0ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 10ms
30 timing idealTree:userRequests Completed in 2ms
31 silly idealTree buildDeps
32 silly fetch manifest @private/promise-util@*
33 http fetch GET 403 https://artifactory.redacted.com/artifactory/api/npm/private-npm-local/@private%2fpromise-util 433ms (cache skip)
34 silly placeDep ROOT @private/promise-util@ OK for: test-ssm-param@1.0.0 want: *
35 timing idealTree:#root Completed in 440ms
36 timing idealTree:node_modules/@private/promise-util Completed in 0ms
37 timing idealTree:buildDeps Completed in 440ms
38 timing idealTree:fixDepFlags Completed in 0ms
39 timing idealTree Completed in 453ms
40 timing command:install Completed in 467ms
41 verbose stack HttpErrorGeneral: 403 Forbidden - GET https://artifactory.redacted.com:443/artifactory/api/npm/private-npm-local/@private%2fpromise-util - forbidden
41 verbose stack     at C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:95:15
41 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
41 verbose stack     at async Arborist.[nodeFromEdge] (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:936:19)
41 verbose stack     at async Arborist.[buildDepStep] (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:882:11)
41 verbose stack     at async Arborist.buildIdealTree (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:218:7)
41 verbose stack     at async Promise.all (index 1)
41 verbose stack     at async Arborist.reify (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:134:5)
41 verbose stack     at async Install.install (C:\Users\username\AppData\Roaming\npm\node_modules\npm\lib\install.js:150:5)
42 verbose statusCode 403
43 verbose pkgid @private/promise-util@*
44 verbose cwd C:\git\test-ssm-param
45 verbose Windows_NT 10.0.19042
46 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-D" "@private/promise-util"
47 verbose node v14.15.0
48 verbose npm  v7.19.0
49 error code E403
50 error 403 403 Forbidden - GET https://artifactory.redacted.com:443/artifactory/api/npm/private-npm-local/@private%2fpromise-util - forbidden
51 error 403 In most cases, you or one of your dependencies are requesting
51 error 403 a package version that is forbidden by your security policy, or
51 error 403 on a server you do not have access to.
52 verbose exit 1
``` 

### Environment

- OS: Windows 10
- Node: 14.15.0
- npm: 7.19.0

**Comment by wraithgar** [comment]
Are you sure that it consistently works in `7.18.1` and only fails in `7.19.0`? I only ask because nothing changed in those versions that has anything to do with auth.

**Comment by sforcier** [comment]
It's the weirdest thing, yesterday and the day before it was consistently a problem and was *only* broken in 7.19.0. Today I have no problem with 7.19.0 or 7.19.1... must be something on my end, sorry for the bother.
