### ISSUE TITLE
cannot read property 'match' of undefined 

### ISSUE THREAD

**Issue by harika-c** [npm/cli#3601]
getting the below error while doing a  sequelize.sync() : 

TypeError: Cannot read property 'match' of undefined
    at D:\emconsole_api_aws\node_modules\sequelize\lib\dialects\postgres\query.js:148:36
    at Array.map (<anonymous>)
    at D:\emconsole_api_aws\node_modules\sequelize\lib\dialects\postgres\query.js:139:48
    at tryCatcher (D:\emconsole_api_aws\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\emconsole_api_aws\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\emconsole_api_aws\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\emconsole_api_aws\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\emconsole_api_aws\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\emconsole_api_aws\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\emconsole_api_aws\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\emconsole_api_aws\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\emconsole_api_aws\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:464:21)

i deleted node_modules and package_lock.json file and did npm install . Issue still exists 
upgraded npm version to > 7 as well 
my npm version is 7.20.3
node version is v14.17.4

**Comment by ljharb** [comment]
You’ll need to file this on sequelize; it has nothing to do with npm.
