### ISSUE TITLE
[BUG] `npm install` installs the wrong things

### ISSUE THREAD

**Issue by danieltroger** [npm/cli#3606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I install parcel parcel fails to run with this error:

```
@parcel/workers: Expected constructor 2.0.0-nightly.793+91287030:BundleGraph to be registered with serializer to deserialize

  Error: Expected constructor 2.0.0-nightly.793+91287030:BundleGraph to be registered with serializer to deserialize
  at /private/tmp/parcel-fukd/node_modules/@parcel/core/lib/serializer.js:228:15
  at memoizedFn (/private/tmp/parcel-fukd/node_modules/@parcel/core/lib/serializer.js:100:13)
  at mapObject (/private/tmp/parcel-fukd/node_modules/@parcel/core/lib/serializer.js:173:16)
  at restoreDeserializedObject (/private/tmp/parcel-fukd/node_modules/@parcel/core/lib/serializer.js:222:10)
  at deserialize (/private/tmp/parcel-fukd/node_modules/@parcel/core/lib/serializer.js:258:10)
  at Child.handleRequest (/private/tmp/parcel-fukd/node_modules/@parcel/workers/lib/child.js:204:31)
  at Child.messageListener (/private/tmp/parcel-fukd/node_modules/@parcel/workers/lib/child.js:108:19)
  at ThreadsChild.onMessage (/private/tmp/parcel-fukd/node_modules/@parcel/workers/lib/child.js:84:12)
  at ThreadsChild.handleMessage (/private/tmp/parcel-fukd/node_modules/@parcel/workers/lib/threads/ThreadsChild.js:59:10)
  at MessagePort.<anonymous> (/private/tmp/parcel-fukd/node_modules/@parcel/workers/lib/threads/ThreadsChild.js:53:61)
⠋ Bundling...
```

Apparently the issue is
> [Is it not a bug in npm? parcel depends on a pinned @parcel/core nightly. Why is it installing an rc version? It works properly with Yarn...](https://github.com/parcel-bundler/parcel/issues/6675#issuecomment-892057014)

So parcel depends on a pinned package and npm is installing the wrong version.

### Expected Behavior

NPM installs the right version and parcel works like it should.

### Steps To Reproduce

1. In the environment listed at the end of https://github.com/parcel-bundler/parcel/issues/6675
2. Download the .zip file from https://github.com/parcel-bundler/parcel/issues/6675
3. Run `npm install` and `npm run build`
```

@parcel/workers: Expected constructor 2.0.0-nightly.793+91287030:BundleGraph to be registered with serializer to deserialize

  Error: Expected constructor 2.0.0-nightly.793+91287030:BundleGraph to be registered with serializer to deserialize
  at /private/tmp/parcel-fukd/node_modules/@parcel/core/lib/serializer.js:228:15
  at memoizedFn (/private/tmp/parcel-fukd/node_modules/@parcel/core/lib/serializer.js:100:13)
  at mapObject (/private/tmp/parcel-fukd/node_modules/@parcel/core/lib/serializer.js:173:16)
  at restoreDeserializedObject (/private/tmp/parcel-fukd/node_modules/@parcel/core/lib/serializer.js:222:10)
  at deserialize (/private/tmp/parcel-fukd/node_modules/@parcel/core/lib/serializer.js:258:10)
  at Child.handleRequest (/private/tmp/parcel-fukd/node_modules/@parcel/workers/lib/child.js:204:31)
  at Child.messageListener (/private/tmp/parcel-fukd/node_modules/@parcel/workers/lib/child.js:108:19)
  at ThreadsChild.onMessage (/private/tmp/parcel-fukd/node_modules/@parcel/workers/lib/child.js:84:12)
  at ThreadsChild.handleMessage (/private/tmp/parcel-fukd/node_modules/@parcel/workers/lib/threads/ThreadsChild.js:59:10)
  at MessagePort.<anonymous> (/private/tmp/parcel-fukd/node_modules/@parcel/workers/lib/threads/ThreadsChild.js:53:61)
```

### Environment

- OS: macOS 10.15.7 (19H1217)
- Node: 16.6.0
- npm: 7.19.1

**Comment by simllll** [comment]
We experience something similar when a package-lock is existing.
The first npm install works perfectly fine, but the 2nd npm install or npm ci results into ERESOLVE overriding peer dependency issues and it seems indeed like wrong packages are installed (our eslint throws weird error messages and so on).

This is only happening with npm 7.20.3.. earlier versions do not have this issue. Right now this is especially a problem on our CI pipeline, as we use the latest npm version there. We have a quite big monorepo in use with the workspace feature.

**Comment by suits-at** [comment]
> We experience something similar when a package-lock is existing.
> The first npm install works perfectly fine, but the 2nd npm install or npm ci results into ERESOLVE overriding peer dependency issues and it seems indeed like wrong packages are installed (our eslint throws weird error messages and so on).
> 
> This is only happening with npm 7.20.3.. earlier versions do not have this issue. Right now this is especially a problem on our CI pipeline, as we use the latest npm version there. We have a quite big monorepo in use with the workspace feature.

This is the regarding debug log
[2021-08-04T09_40_43_512Z-debug.log](https://github.com/npm/cli/files/6930343/2021-08-04T09_40_43_512Z-debug.log)

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/applicant-overview-components@1.1.20
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN packages/applicant-overview-components
npm WARN   @hokify/applicant-overview-components@1.1.19
npm WARN   node_modules/@hokify/applicant-overview-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/b2b-job-stats-overview-components@1.1.19
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/b2b-job-stats-overview-components@1.1.19
npm WARN packages/b2b-job-stats-overview-components
npm WARN   @hokify/b2b-job-stats-overview-components@1.1.18
npm WARN   node_modules/@hokify/b2b-job-stats-overview-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/b2b-relation-stats-components@1.1.19
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/b2b-relation-stats-components@1.1.19
npm WARN packages/b2b-relation-stats-components
npm WARN   @hokify/b2b-relation-stats-components@1.1.18
npm WARN   node_modules/@hokify/b2b-relation-stats-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/chat-components@1.1.17
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/chat-components@1.1.17
npm WARN packages/chat-components
npm WARN   @hokify/chat-components@1.1.16
npm WARN   node_modules/@hokify/chat-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/email-templates@2.1.19
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/email-templates@2.1.19
npm WARN packages/email-templates
npm WARN   @hokify/email-templates@2.1.18
npm WARN   node_modules/@hokify/email-templates
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/file-preview-components@1.0.16
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/file-preview-components@1.0.16
npm WARN packages/file-preview-components
npm WARN   @hokify/file-preview-components@1.0.15
npm WARN   node_modules/@hokify/file-preview-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/hokifycv-components@1.1.18
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/hokifycv-components@1.1.18
npm WARN packages/hokifycv-components
npm WARN   @hokify/hokifycv-components@1.1.17
npm WARN   node_modules/@hokify/hokifycv-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/invoice-components@2.0.21
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/invoice-components@2.0.21
npm WARN packages/invoice-components
npm WARN   @hokify/invoice-components@2.0.20
npm WARN   node_modules/@hokify/invoice-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/job-poster-components@1.1.19
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/job-poster-components@1.1.19
npm WARN packages/job-poster-components
npm WARN   @hokify/job-poster-components@1.1.18
npm WARN   node_modules/@hokify/job-poster-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/legacy-invoice-components@1.1.19
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/legacy-invoice-components@1.1.19
npm WARN packages/legacy-invoice-components
npm WARN   @hokify/legacy-invoice-components@1.1.18
npm WARN   node_modules/@hokify/legacy-invoice-components
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/login-stack@1.1.17
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/login-stack@1.1.17
npm WARN packages/login-stack
npm WARN   @hokify/login-stack@1.1.16
npm WARN   node_modules/@hokify/login-stack
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hokify/pwa-core@1.1.19
npm WARN Found: @hokify/shared-components@1.1.16
npm WARN node_modules/@hokify/shared-components
npm WARN   @hokify/shared-components@"^1.1.17" from @hokify/applicant-overview-components@1.1.20
npm WARN   packages/applicant-overview-components
npm WARN     @hokify/applicant-overview-components@1.1.19
npm WARN     node_modules/@hokify/applicant-overview-components
npm WARN 
npm WARN Could not resolve dependency:
npm WARN @hokify/shared-components@"^1.1.17" from @hokify/pwa-core@1.1.19
npm WARN packages/pwa-core
npm WARN   @hokify/pwa-core@1.1.18
npm WARN   node_modules/@hokify/pwa-core
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/company-app - Not found
npm ERR! 404 
npm ERR! 404  'company-app@^1.1.20' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sebi/.npm/_logs/2021-08-04T09_40_43_512Z-debug.log

```

**Comment by simllll** [comment]
This gets quite serious, have to explciity stick to npm 7.20.2 now.
on production I suddenly got: `Error: Cannot find module 'promise.any'`, due to npm 7.20.3 in the build pipeline

**Comment by danieltroger** [comment]
I figured that npm is dead / unmaintained. The last triaged issue is from the beginning of june.

I just switched to yarn berry which is incredibly fast and works superb. Can recommend!

**Comment by folknor** [comment]
I think the problem @simllll is describing is different. I have the same problem (original ticket description) with npm 7.20.2, 7.19, and 7.0.0. I've not tried npm 6.14.14 or earlier.

Even with full nukes of `node_modules` and `package-lock.json` and full reinstall of `node_modules` using the 3 different npm version.

**Comment by nlf** [comment]
we've made a lot of changes to peer dependency handling since this issue was opened. can any of you who are still experiencing this problem try installing npm@8.5.3 and let us know if it resolves your problem?

**Comment by folknor** [comment]
@nlf Seems to work now using npm 8.7.0. I think this ticket can be closed.

**Comment by nlf** [comment]
closing as we've received a report that things are working. if this is incorrect please feel free to either reopen this issue or open a new issue for us

**Comment by Junior-22** [comment]
Hi, I have just encountered a very similar problem

**Environment**
- Edition:	Windows 10 Home
- Version:	21H1
- OS build: 19043.1706
- Experience: Windows Feature Experience Pack 120.2212.4170.0

- Node: 16.14.2
- npm: 8.12.2
- Parcel: 2.0.0-rc.0
- @parcel/transformer-sass: 2.0.0-rc.0


</body>
</html>

I get this error message from my console "Error: Expected constructor 2.0.0-rc.0:BundleGraph to be registered with serializer to deserialize"

How do I solve this so I can get my app working again?

**Comment by josheppinette** [comment]
I was receiving this error. It was not due to npm. It was due to having mismatched parcel dependencies. i.e. anything `@parcel/*` should have the same version as `parcel`.
