### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning when run inside a missing directory

### ISSUE THREAD

**Issue by cinderblock** [npm/cli#3704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, you can get `npm@7` to crash with unhandled promise rejection by running it inside a directory that has been removed, since Linux doesn't "protect" directories that are "in-use".

I realize this is a rare case but `npm@6` doesn't have this problem.

```log
(node:183) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:130:28)
    at process.cwd (/usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/usr/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:92:19)
    at new <anonymous> (/usr/lib/node_modules/npm/lib/npm.js:83:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/npm.js:71:30)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:183) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:183) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected Behavior

Usage printed or an error that doesn't include an `UnhandledPromiseRejectionWarning`

### Steps To Reproduce

On a Linux machine, with npm@7 installed globally

```bash
mkdir test
cd test
rmdir ../test
npm
```

### Environment

- OS: Ubuntu 20
- Node: v14.17.4
- npm: 7.21.1

**Comment by wraithgar** [comment]
This is no longer an unhandled promise rejection, now just a good old error.

```sh
$ npm
Error: ENOENT: no such file or directory, uv_cwd
```
