### ISSUE TITLE
[BUG] NPM is not installed with a node / NPM commands dont work

### ISSUE THREAD

**Issue by 5XS** [npm/cli#3746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

When I run the command, it gives me an error. I checked PATH, npm was there.
I checked `C:\Users\%username%\AppData\Roaming`, it was empty.
I tried to reinstall it many times, looked for a solution on the Internet, but it did not help. I hope you can help.

### Expected Behavior

I wanted to run the npm command.

### Steps To Reproduce

1. Install nodejs
2. Open cmd.exe
3. Run any npm command
```
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (D:\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (D:\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (D:\nodejs\node_modules\npm\node_modules\make-fetch-happen\lib\agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (D:\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (D:\nodejs\node_modules\npm\node_modules\socks-proxy-agent\dist\index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (D:\nodejs\node_modules\npm\node_modules\make-fetch-happen\lib\agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

### Environment

- OS: Windows 10 x64
- Node: 16.9.1
- npm: 7.21.1

**Comment by ljharb** [comment]
How did you install node?

**Comment by 5XS** [comment]
> How did you install node?

from msi file

**Comment by MahdiForoughi** [comment]
Try install it independently from npm website or maybe another version and test it again... at least this solution can helps us to know about it that this problem is specific to this version or not!

**Comment by 5XS** [comment]
It fixed itself when reinstalling..
