### ISSUE TITLE
Always Reproducible "Maximum call stack size exceeded" npm install error

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#377]
Original bug ticket: [https://npm.community/t/1645](https://npm.community/t/1645)
      Originally filed: 2018-08-23T18:30:48.880Z

**Comment by DullReferenceException** [comment]
This is happening on `6.14.6` after a recent upgrade. From debug logs:

```
94 verbose stack RangeError: Maximum call stack size exceeded
94 verbose stack     at RegExp.test (<anonymous>)
94 verbose stack     at isDepOptional (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:425:27)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:441:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
94 verbose stack     at failedDependency (/home/jpage/.nvm/versions/node/v12.18.1/lib/node_modules/npm/lib/install/deps.js:457:9)
```
