### ISSUE TITLE
[BUG] npx not working on docker using root

### ISSUE THREAD

**Issue by gengjiawen** [npm/cli#3773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```console
/bin/sh: 1: cargo: Permission denied
Error: Command failed: cargo install cargo-workspaces
/bin/sh: 1: cargo: Permission denied

    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.<anonymous> (/pwd/scripts/bump_cargo_packages.ts:6:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/pwd/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/pwd/node_modules/ts-node/src/index.ts:1313:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  status: 127,
  signal: null,
}
```

### Expected Behavior

script run successfully.

### Steps To Reproduce

```
git clone https://github.com/gengjiawen/monkey-rust
cd monkey-rust
docker run -v $PWD:/pwd -w /pwd gengjiawen/node-build bash -c "yarn && npx ts-node scripts/bump_cargo_packages.ts"
```

I have fallback to 
```
docker run -v $PWD:/pwd -w /pwd gengjiawen/node-build bash -c "yarn && node node_modules/.bin/ts-node scripts/bump_cargo_packages.ts"
```

### Environment

OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
Node: 16.9.1 - /usr/local/bin/node
npm: 7.24.0 - /usr/local/bin/npm

**Comment by rashkov** [comment]
Have you seen https://github.com/npm/cli/issues/3110

As of npm CLI v7, "When npm is run as root, scripts are always run with the effective uid and gid of the working directory owner." https://docs.npmjs.com/cli/v7/using-npm/scripts#user

**Comment by wraithgar** [comment]
This is the intended behavior in v7 and v8, as per the docs link above.

**Comment by robertsLando** [comment]
I have created https://github.com/npm/cli/issues/4811 please go to upvote it so maybe it get noticed by maintainers

**Comment by gengjiawen** [comment]
I have switch to pnpm to fix this. Have fun. `pnpx` is the equalient.

**Comment by papb** [comment]
@wraithgar Would you consider a feature request of a flag that allows overriding this behavior so that `root` is used? Or even a flag that allows us to specify which user we want?

**Comment by wraithgar** [comment]
There is an ongoing discussion about this already in the rfc repo https://github.com/npm/rfcs/issues/546
