### ISSUE TITLE
[BUG] npm installation broken when installing from source(on Linux Ubuntu 20.04.3 LTS)

### ISSUE THREAD

**Issue by lfortin** [npm/cli#3795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have installed Node v16.9.1 from source.

When I try to run npm, I get these errors:
```
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

### Expected Behavior

I have installed Node v16.0.0 from source and there was no issue running npm:

```
> npm -v
7.10.0
```

### Steps To Reproduce

On Linux Ubuntu 20.04.3 LTS,

Installing Node.js v16.9.1 from source:

```
tar -zxvf node-v16.9.1.tar.gz
cd node-v16.9.1
./configure
make
sudo make install
```

Then, executing npm:

`npm -v`

### Environment

- OS: Linux Ubuntu 20.04.3 LTS
- Node: 16.9.1
- npm: ?

**Comment by ParadoxInfinite** [comment]
Hey @lfortin,
I've build and installed v16.9.1 from source `node-v16.9.1.tar.gz` and also installed `node-v16.9.1-linux-x64.tar.gz`, the linux specific binary on WSL (Ubuntu 20.04.2 LTS on Windows 10 x86_64). I had no issue running `npm -v` with either of them.

Could you check if your tar file is not corrupted and also try the binaries, unless you necessarily want to build the source yourself.

**Comment by axkibe** [comment]
I got the same issue, tar file is not broken it's the same as on another machine, has to do with something else preinstalled or what to version to come from.

**Comment by axkibe** [comment]
Needs a workaround!

**Comment by axkibe** [comment]
rm -rf /usr/local/lib/node_modules/
make install
(as root)
did the trick. It must have been some global module from there (or file from previous install in core modules)

**Comment by lfortin** [comment]
Thanks @axkibe for the help. It worked out for me as well.

Also, thanks @ParadoxInfinite for the reply.

**Comment by daniel-moya** [comment]
It worked for me as well, thanks @axkibe 👍🏽
