### ISSUE TITLE
[BUG] JavaScript heap out of memory error on `npm i package-build-stats`

### ISSUE THREAD

**Issue by KartikSoneji** [npm/cli#3814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to install the package `package-build-stats` on Windows results in npm crashing.

```console
> npm i package-build-stats --max-old-space-size 4096
[######............] / idealTree:socket.io-parser: sill placeDep ROOT to-array@0.1.4 OK for: socket.io-client@2.4.0 want: 0.1.4
<--- Last few GCs --->

[20172:0000020B1E29A660]  1185785 ms: Scavenge 2016.9 (2079.9) -> 2002.8 (2080.7) MB, 3.5 / 0.0 ms  (average mu = 0.353, current mu = 0.301) allocation failure
[20172:0000020B1E29A660]  1187947 ms: Mark-sweep 2017.7 (2080.7) -> 1991.1 (2080.7) MB, 2116.8 / 0.0 ms  (average mu = 0.347, current mu = 0.341) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF75464E98F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
 2: 00007FF7545DDD76 v8::internal::wasm::WasmCode::safepoint_table_offset+65446
 3: 00007FF7545DEC2D node::OnFatalError+301
 4: 00007FF754F2529E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF754F0FBDD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF754D9020C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF754D9CE99 v8::internal::Heap::PublishPendingAllocations+1161
 8: 00007FF754D99E4A v8::internal::Heap::PageFlagsAreConsistent+2842
 9: 00007FF754D8CCBF v8::internal::Heap::CollectGarbage+1983
10: 00007FF754D8AF10 v8::internal::Heap::AllocateExternalBackingStore+2000
11: 00007FF754DA88E0 v8::internal::FreeListManyCached::Reset+1408
12: 00007FF754DA8F95 v8::internal::Factory::AllocateRaw+37
13: 00007FF754DBAC4E v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray+46
14: 00007FF754DBD8DA v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller+74
15: 00007FF754DBDB33 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithMap+35
16: 00007FF754BC8CE1 v8::internal::HashTable<v8::internal::NameDictionary,v8::internal::NameDictionaryShape>::New<v8::internal::Isolate>+113
17: 00007FF754BC89F6 v8::internal::BaseNameDictionary<v8::internal::NameDictionary,v8::internal::NameDictionaryShape>::New<v8::internal::Isolate>+22
18: 00007FF754DB400F v8::internal::Factory::NewNameDictionary+31
19: 00007FF754C19772 v8::internal::JSGlobalProxy::IsDetached+7218
20: 00007FF754C1A772 v8::internal::JSObject::MigrateToMap+290
21: 00007FF754C1AD17 v8::internal::JSObject::NormalizeProperties+183
22: 00007FF754BF97BE v8::internal::LookupIterator::Delete+142
23: 00007FF754C11B3E v8::internal::JSObject::DefinePropertyOrElementIgnoreAttributes+2430
24: 00007FF754AD9204 v8::internal::Runtime::DeleteObjectProperty+164
25: 00007FF754ADBBDA v8::internal::Runtime::GetObjectProperty+8490
26: 00007FF754FB1FA1 v8::internal::SetupIsolateDelegate::SetupHeap+491537
27: 0000020B201E1CF6
```

### Expected Behavior

The package to install successfully

### Steps To Reproduce

Run:
```console
> md foo
> cd foo
> npm i package-build-stats
```
npm will crash with the stacktrace as mentioned above.
Note: only seems to be an issue on Windows, could not replicate crash on Linux.

### Environment

- OS: Windows 10 Pro 21H1, Build 19043.1237
- Node: 16.9.1
- npm: 7.24.1

**Comment by lukekarrys** [comment]
@KartikSoneji Were you able to get the package to install successfully on Linux?

I just tried on macOS and while I could not replicate the crash I did encounter an infinite loop (#3787). The fix for this is going out today and I'm wondering if the infinite loop is what causes the out of memory error on Windows. I'd recommend trying this again once the release today goes out (`v7.25.0`).

**Comment by KartikSoneji** [comment]
@lukekarrys yes, the package installed fine on Linux (ubuntu 20.04).
I tried out `v7.25.0` (bb0b2da6c0275dd8c9eda894452ce45b2e8c4c51), and it no longer crashes but throws this error:

```console
> node ..\local-npm i package-build-stats
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path C:\Users\Kartik\Desktop\npm-bug\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\Kartik\Desktop\npm-bug\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\Kartik\\Desktop\\npm-bug\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.9.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Kartik\Desktop\npm-bug\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Kartik\Desktop\npm-bug\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Kartik\Desktop\npm-bug\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Kartik\Desktop\npm-bug\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Kartik\Desktop\npm-bug\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Kartik\Desktop\npm-bug\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Kartik\Desktop\npm-bug\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Kartik\Desktop\npm-bug\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Kartik\Desktop\npm-bug\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Kartik\Desktop\npm-bug\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Kartik\Desktop\npm-bug\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Kartik\Desktop\npm-bug\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Program Files\Python39\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Program Files\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kartik\\Desktop\\npm-bug\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\Kartik\Desktop\npm-bug\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.9.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
```

**Comment by lukekarrys** [comment]
Thanks for trying that @KartikSoneji. That looks like a different error now. `node-sass` uses `node-gyp` which requires some extra dependencies to be installed on Windows. Have you tried following the steps here: https://github.com/nodejs/node-gyp#on-windows?

**Comment by KartikSoneji** [comment]
Ah ha, found the issue:
The [`package-build-stats`](https://github.com/pastelsky/package-build-stats) package uses [`"node-sass": "^4.14.1"`](https://github.com/pastelsky/package-build-stats/blob/e67df579ac186b610910373ba4fdb2bd2ad46ebb/package.json#L87) which in turn depends on [`"node-gyp": "^3.8.0"`](https://github.com/sass/node-sass/blob/0d6c3cc36a5362e83529d901484b0bbf3e96de81/package.json#L67)

Which fails with:
<details>
<summary><code>node ..\local-npm i node-sass@4.14.1</code></summary>
```console
> node ..\local-npm i node-sass@4.14.1
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path C:\Users\Kartik\Desktop\npm-bug\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\Kartik\Desktop\npm-bug\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\Kartik\\Desktop\\npm-bug\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.9.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "C:\Program Files\Python39\python.exe" in the PATH
npm ERR! gyp verb `which` succeeded C:\Program Files\Python39\python.exe C:\Program Files\Python39\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Program Files\Python39\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kartik\\Desktop\\npm-bug\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\Kartik\Desktop\npm-bug\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.9.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
```
</details>

Looking at the readme for `node-gyp@3.8.0`, it only supports Python 2.
> [Install Python 2.7 (v3.x.x is not supported)](https://github.com/nodejs/ode-gyp/tree/9a404d6d36dcf9c7be2ae9963019c4d89bbb9155#option-2)

I'll look into fixing this in the original package's repository, thanks for the help.

**Comment by KartikSoneji** [comment]
Looks like there already is a PR that will fix this: https://github.com/pastelsky/package-build-stats/pull/42
