### ISSUE TITLE
[BUG] <title> publish 400 bad request

### ISSUE THREAD

**Issue by Jcanno** [npm/cli#3823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to publish a new package but gone 400 error without reason, and I can publish a package which exists in `npm` successfully at the same time.

with log below:
```
0 verbose cli [
0 verbose cli   '/Users/liqing/.nvm/versions/node/v15.4.0/bin/node',
0 verbose cli   '/Users/liqing/.nvm/versions/node/v15.4.0/bin/npm',
0 verbose cli   'publish'
0 verbose cli ]
1 info using npm@7.0.15
2 info using node@v15.4.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/Users/liqing/.nvm/versions/node/v15.4.0/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/liqing/Desktop/github/hack-ajax/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/liqing/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/Users/liqing/.nvm/versions/node/v15.4.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session 5bd953267f83fde1
20 timing npm:load Completed in 19ms
21 verbose publish [ '.' ]
22 notice
23 notice 📦  hack-ajax@0.0.1
24 notice === Tarball Contents ===
25 notice 1.1kB LICENSE
25 notice 982B  README.md
25 notice 3.5kB dist/index.js
25 notice 3.2kB es/index.js
25 notice 937B  package.json
25 notice 1.0kB types/enums.d.ts
25 notice 787B  types/index.d.ts
26 notice === Tarball Details ===
27 notice name:          hack-ajax
27 notice version:       0.0.1
27 notice filename:      hack-ajax-0.0.1.tgz
27 notice package size:  4.0 kB
27 notice unpacked size: 11.5 kB
27 notice shasum:        94aee8dc150f47b39670844a918677fcec5f06b2
27 notice integrity:     sha512-W/+d+M+NeqdaQ[...]UbEX6kAc/PVig==
27 notice total files:   7
28 notice
29 http fetch PUT 400 https://registry.npmjs.org/hack-ajax 638ms
30 timing command:publish Completed in 709ms
31 verbose stack Error: 400 Bad Request - PUT https://registry.npmjs.org/hack-ajax - Bad Request
31 verbose stack     at /Users/liqing/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:123:15
31 verbose stack     at async publish (/Users/liqing/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/libnpmpublish/publish.js:43:12)
31 verbose stack     at async publish_ (/Users/liqing/.nvm/versions/node/v15.4.0/lib/node_modules/npm/lib/publish.js:105:5)
31 verbose stack     at async publish (/Users/liqing/.nvm/versions/node/v15.4.0/lib/node_modules/npm/lib/publish.js:44:19)
32 verbose statusCode 400
33 verbose pkgid hack-ajax@0.0.1
34 verbose cwd /Users/liqing/Desktop/github/hack-ajax
35 verbose Darwin 19.6.0
36 verbose argv "/Users/liqing/.nvm/versions/node/v15.4.0/bin/node" "/Users/liqing/.nvm/versions/node/v15.4.0/bin/npm" "publish"
37 verbose node v15.4.0
38 verbose npm  v7.0.15
39 error code E400
40 error 400 Bad Request - PUT https://registry.npmjs.org/hack-ajax - Bad Request
41 verbose exit 1
```

### Expected Behavior

publish successfully

### Environment

- OS: mac OS 10.15.6
- Node: v15.4.0
- npm: v7.0.15

**Comment by ljharb** [comment]
Can you try npm 7 latest?

**Comment by Jcanno** [comment]
> Can you try npm 7 latest?

same result with `npm@7.24.1`

```
0 verbose cli [
0 verbose cli   '/Users/liqing/.nvm/versions/node/v15.4.0/bin/node',
0 verbose cli   '/Users/liqing/.nvm/versions/node/v15.4.0/bin/npm',
0 verbose cli   'publish'
0 verbose cli ]
1 info using npm@7.24.1
2 info using node@v15.4.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/Users/liqing/.nvm/versions/node/v15.4.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/liqing/Desktop/github/hack-ajax/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/liqing/.npmrc Completed in 2ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/Users/liqing/.nvm/versions/node/v15.4.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 13ms
19 timing npm:load:configload Completed in 14ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 4ms
23 timing npm:load:cleanupLog Completed in 3ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 2ms
26 timing npm:load Completed in 26ms
27 verbose publish [ '.' ]
28 notice
29 notice 📦  hack-ajax@0.0.1
30 notice === Tarball Contents ===
31 notice 1.1kB LICENSE
31 notice 982B  README.md
31 notice 3.5kB dist/index.js
31 notice 3.2kB es/index.js
31 notice 937B  package.json
31 notice 1.0kB types/enums.d.ts
31 notice 787B  types/index.d.ts
32 notice === Tarball Details ===
33 notice name:          hack-ajax
33 notice version:       0.0.1
33 notice filename:      hack-ajax-0.0.1.tgz
33 notice package size:  3.9 kB
33 notice unpacked size: 11.5 kB
33 notice shasum:        31e65406167d84607a8a008c81b50fae1b62cf2d
33 notice integrity:     sha512-E4Ss/TGj+W7TI[...]gXBhc3cBhjfyQ==
33 notice total files:   7
34 notice
35 timing command:publish Completed in 730ms
36 verbose stack HttpErrorGeneral: 400 Bad Request - PUT https://registry.npmjs.org/hack-ajax - Bad Request
36 verbose stack     at /Users/liqing/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
36 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:93:5)
36 verbose stack     at async publish (/Users/liqing/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/libnpmpublish/publish.js:43:12)
36 verbose stack     at async Publish.publish (/Users/liqing/.nvm/versions/node/v15.4.0/lib/node_modules/npm/lib/publish.js:120:7)
37 verbose statusCode 400
38 verbose pkgid hack-ajax@0.0.1
39 verbose cwd /Users/liqing/Desktop/github/hack-ajax
40 verbose Darwin 19.6.0
41 verbose argv "/Users/liqing/.nvm/versions/node/v15.4.0/bin/node" "/Users/liqing/.nvm/versions/node/v15.4.0/bin/npm" "publish"
42 verbose node v15.4.0
43 verbose npm  v7.24.1
44 error code E400
45 error 400 Bad Request - PUT https://registry.npmjs.org/hack-ajax - Bad Request
46 verbose exit 1

```

**Comment by Jcanno** [comment]
I guess there is problem with my package name, I just change package name from `hack-ajax` to `request-fun`, then I can publish successfully. Is `hack-ajax` package name invalid?

**Comment by ljharb** [comment]
Maybe the word "hack" is banned?

**Comment by Jcanno** [comment]
> Maybe the word "hack" is banned?

Yes,  maybe `npm cli` can offer more helpful information to debug. It's too difficult to solve in the case.

Just close the issue.
