### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by tekumara** [npm/cli#3827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
$ npm -g install
npm ERR! Cannot read properties of undefined (reading 'name')

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-02T14_28_50_151Z-debug.log
```

```
$ cat /root/.npm/_logs/2021-10-02T14_28_50_151Z-debug.log
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', '-g', 'install' ]
1 info using npm@7.24.0
2 info using node@v16.10.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/workdir/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 13ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 8ms
29 timing idealTree:userRequests Completed in 5ms
30 silly idealTree buildDeps
31 silly placeDep ROOT undefined@ OK for:  want: file:../../workdir
32 timing idealTree:#root Completed in 6ms
33 timing idealTree:node_modules/undefined Completed in 0ms
34 timing idealTree:buildDeps Completed in 7ms
35 timing idealTree:fixDepFlags Completed in 0ms
36 timing idealTree Completed in 21ms
37 timing command:install Completed in 50ms
38 verbose stack TypeError: Cannot read properties of undefined (reading 'name')
38 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:279:30
38 verbose stack     at Array.some (<anonymous>)
38 verbose stack     at Arborist.filter (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:279:12)
38 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-actual.js:358:39
38 verbose stack     at Array.filter (<anonymous>)
38 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-actual.js:358:12
38 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
38 verbose stack     at async Arborist.[loadActualActually] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-actual.js:177:5)
38 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:147:5)
38 verbose stack     at async Install.install (/usr/lib/node_modules/npm/lib/install.js:170:5)
39 verbose cwd /workdir
40 verbose Linux 5.10.47-linuxkit
41 verbose argv "/usr/bin/node" "/usr/bin/npm" "-g" "install"
42 verbose node v16.10.0
43 verbose npm  v7.24.0
44 error Cannot read properties of undefined (reading 'name')
45 verbose exit 1
```

### Steps To Reproduce

_package.json_
```
{
    "devDependencies": {
        "pyright": "1.1.106"
    }
}
```

### Environment

- OS: Debian GNU/Linux 11 (bullseye)
- Node: v16.10.0
- npm: v7.24.0

**Comment by ljharb** [comment]
I’m confused; you’re running `npm install -g` with no other arguments, inside the package dir?

If you’re trying to install the packages’ deps, you’d use `npm install`, and if you’re trying to make it globally available you’d run `npm link`. What’s your intended goal?

**Comment by tekumara** [comment]
Thanks for the explanation @ljharb! So the error message means I'm missing a package argument. This wasn't obvious to me as a newbie.
