### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by ShipmasterKyle** [npm/cli#4044]
```
npm ERR! Linux 4.14.243-18084-g7bc10658733d
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

I'm trying to use the manual method to install BetterDiscord but I keep getting this error.

**Comment by ljharb** [comment]
Node 4 and npm 3 are both very very obsolete and unsupported. I’d suggest trying node 14, 16, or 17.

**Comment by ShipmasterKyle** [comment]
How would I do that? Tried running `sudo apt install nodejs` and it says 4 is the newest version.
`nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.2).`

**Comment by ljharb** [comment]
Don’t install node with apt. Download it from the website, or use something like nvm, nave, or n to install it.
