### ISSUE TITLE
[BUG] Npm install ETIMEDOUT

### ISSUE THREAD

**Issue by MrNakai** [npm/cli#4085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am having problems on any installation with npm. See an example log below :
__
0 verbose cli [
0 verbose cli '/home/pi/.config/nvm/versions/node/v17.1.0/bin/node',
0 verbose cli '/home/pi/.config/nvm/versions/node/v17.1.0/bin/npm',
0 verbose cli 'i',
0 verbose cli 'npm',
0 verbose cli '--verbose'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v17.1.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 9ms
5 timing config:load:file:/home/pi/.config/nvm/versions/node/v17.1.0/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 13ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/home/pi/Melting-potes/.npmrc Completed in 1ms
10 timing config:load:project Completed in 8ms
11 timing config:load:file:/home/pi/.npmrc Completed in 7ms
12 timing config:load:user Completed in 8ms
13 timing config:load:file:/home/pi/.config/nvm/versions/node/v17.1.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 2ms
15 timing config:load:validate Completed in 7ms
16 timing config:load:credentials Completed in 6ms
17 timing config:load:setEnvs Completed in 6ms
18 timing config:load Completed in 66ms
19 timing npm:load:configload Completed in 66ms
20 timing npm:load:setTitle Completed in 1ms
21 timing npm:load:setupLog Completed in 2ms
22 timing config:load:flatten Completed in 16ms
23 timing npm:load:cleanupLog Completed in 10ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 2ms
26 timing npm:load Completed in 133ms
27 timing arborist:ctor Completed in 4ms
28 timing arborist:ctor Completed in 1ms
29 timing arborist:ctor Completed in 0ms
30 timing arborist:ctor Completed in 1ms
31 timing idealTree:init Completed in 128ms
32 timing idealTree:userRequests Completed in 18ms
33 silly idealTree buildDeps
34 silly fetch manifest npm@*
35 silly placeDep ROOT npm@ OK for: want: *
36 timing idealTree:#root Completed in 464709ms
37 timing idealTree:node_modules/npm Completed in 0ms
38 timing idealTree:buildDeps Completed in 464721ms
39 timing idealTree:fixDepFlags Completed in 3ms
40 timing idealTree Completed in 464884ms
41 timing command:install Completed in 464967ms
42 verbose type system
43 verbose stack FetchError: request to http://registry.npmjs.org/npm failed, reason: connect ETIMEDOUT 2606:4700::6810:1423:80
43 verbose stack at ClientRequest.<anonymous> (/home/pi/.config/nvm/versions/node/v17.1.0/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:110:14)
43 verbose stack at ClientRequest.emit (node:events:390:28)
43 verbose stack at Socket.socketErrorListener (node:_http_client:447:9)
43 verbose stack at Socket.emit (node:events:402:35)
43 verbose stack at emitErrorNT (node:internal/streams/destroy:164:8)
43 verbose stack at emitErrorCloseNT (node:internal/streams/destroy:129:3)
43 verbose stack at processTicksAndRejections (node:internal/process/task_queues:83:21)
44 verbose cwd /home/pi/Melting-potes
45 verbose Linux 5.10.63-v7+
46 verbose argv "/home/pi/.config/nvm/versions/node/v17.1.0/bin/node" "/home/pi/.config/nvm/versions/node/v17.1.0/bin/npm" "i" "npm" "--verbose"
47 verbose node v17.1.0
48 verbose npm v8.1.2
49 error code ETIMEDOUT
50 error syscall connect
51 error errno ETIMEDOUT
52 error network request to http://registry.npmjs.org/npm failed, reason: connect ETIMEDOUT 2606:4700::6810:1423:80
53 error network This is a problem related to network connectivity.
53 error network In most cases you are behind a proxy or have bad network settings.
53 error network
53 error network If you are behind a proxy, please make sure that the
53 error network 'proxy' config is set properly. See: 'npm help config'
54 verbose exit 1
__
no proxy problem (see config below)
__
I tried to set registry in http or https: same result ( respond to ping by the way).
I also tried to reinstall everything, clean the cache several times, delete the package-lock file, deactivate the firewall of my box.

node version v17.1.0
npm version 8.1.2

I have exhausted all the leads I could find online, can you help me with this problem? thanks in advance

### Expected Behavior

normal install from npm

### Steps To Reproduce

I'm not really sure how, but each time i reinstall node and npm I meet the same outcome

### Environment

- npm: 8.1.2
- Node: 17.1.0
- OS :Raspbian 11 bullseye
- platform: Raspberry Pi 3
- npm config:
; "default" config from default values

_auth = (protected)
access = null
all = false
allow-same-version = false
also = null
audit = true
audit-level = null
auth-type = "legacy"
before = null
bin-links = true
browser = null
ca = null
cache = "/home/pi/.npm"
cache-max = null
cache-min = 0
cafile = null
call = ""
cert = null
ci-name = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
diff = []
diff-dst-prefix = "b/"
diff-ignore-all-space = false
diff-name-only = false
diff-no-prefix = false
diff-src-prefix = "a/"
diff-text = false
diff-unified = 3
dry-run = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
fetch-timeout = 300000
force = false
foreground-scripts = false
format-package-lock = true
fund = true
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/home/pi/.config/nvm/versions/node/v17.1.0/etc/npmrc"
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
include = []
include-staged = false
include-workspace-root = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/home/pi/.npm-init.js"
init-version = "1.0.0"
init.author.email = ""
init.author.name = ""
init.author.url = ""
init.license = "ISC"
init.module = "/home/pi/.npm-init.js"
init.version = "1.0.0"
json = false
key = null
legacy-bundling = false
legacy-peer-deps = false
link = false
local-address = null
location = "user"
lockfile-version = null
; loglevel = "notice" ; overridden by cli
logs-max = 10
; long = false ; overridden by cli
maxsockets = 15
message = "%s"
metrics-registry = "http://registry.npmjs.org/"
node-options = null
node-version = "v17.1.0"
noproxy = [""]
npm-version = "8.1.2"
offline = false
omit = []
only = null
optional = null
otp = null
pack-destination = "."
package = []
package-lock = true
package-lock-only = false
parseable = false
prefer-offline = false
prefer-online = false
prefix = "/home/pi/.config/nvm/versions/node/v17.1.0"
preid = ""
production = null
progress = true
proxy = null
read-only = false
rebuild-bundle = true
; registry = "https://registry.npmjs.org/" ; overridden by user
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-peer = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
searchexclude = ""
searchlimit = 20
searchopts = ""
searchstaleness = 900
shell = "/bin/bash"
shrinkwrap = true
sign-git-commit = false
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-peer-deps = false
; strict-ssl = true ; overridden by user
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "/tmp"
umask = 0
unicode = true
update-notifier = true
usage = false
user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} workspaces/{workspaces} {ci}"
userconfig = "/home/pi/.npmrc"
version = false
versions = false
viewer = "man"
which = null
workspace = []
workspaces = null
yes = null

; "user" config from /home/pi/.npmrc

registry = "http://registry.npmjs.org/"
strict-ssl = true

; "cli" config from command line options

loglevel = "silent"
long = true

**Comment by rlucha** [comment]
We have observed the same issue recently.

**Comment by tpeter29** [comment]
I've noticed this too.  It seems to hang and then disconnect when trying to generate a new angular application.  If I change the npm version to 6.14.14, it works fine.  Once I move to version 7 or 8, it stops working.  I am behind a corporate proxy and use the appropriate settings in the .npmrc file.

**Comment by N226335735** [comment]
🔝海嘯預警中心發出中央社記者訪問時指出，這次選舉權登記證書及時行樂圖書館學。我的人是在哈囉市場排水管清掃工作的地方建設案情複雜我方全體人員進攻籃板及警察👮‍♀️！這次真的好好玩笑是否要不然就業數據理想的工作機會的話。這次真的不用在意這麼多時間照親民黨立法院議場進入的人才能真正落實人民銀行業務資料庫中調出錄影帶📼！這樣我國戰爭中使用這麼一切順利進行，不可能原諒兩行怨淚淚兩行清泉崗機場第一☝️外星人入侵地球🌍地球的另一種很好👌願透露真實存在東獄大帝聖誕禮物🎁背著電鋸鋸開，要俄哥哥姊姊及太平天國和鏗鏗通過反滲透法通過之後再度造成嚴重災情，各位朋友多多支持我們的人才發現原來如此青銅器時代來臨，這個世界最好的👌生生世世歲月靜好現世體制硬體液體燃料電池專利授權協議談判代表兼首席執行官科普拉多洛省錢大作戰，我我嗚嗚剛剛以體驗過過癮，繼續努力推動敘利亞化武統天下之大不韙，吞噬細胞分裂活動，以及美夢都吃掉！每天追著你們人類跑🉑️，電鋸鋸開門🚪追著你們這些傢伙真的罪無可取代的存在，在捐贈物資供應古雷半個小時後才能獲得更多資訊科技協定擴大談判代表今天上午發生芮氏規模六點半才睡的時候了？我也不知道🤷‍♀️父母全數寄出喔⋯⋯在哈囉市場排水管清掃工作人員都有自己的才天天才能真正達到改變世界的和平穩定發展之道。我們都市人生活費都是我自己也很喜歡💕😘❤️💓我的朋友們一起玩遊戲吧，一拖再拖下去慰藉與防禦力點滿分💯派出大量生產基地組織分支承認我是一個世界上最偉大的發明者花果山錘子🔨黨巫統主席拿汀王子🤴木乃伊供應古錐蟲危機處理能力我委託律師事務所律師陳建良大律師公會主席和中央政府總預算案關於今天上午發生砍人事件後，請大家多多支持喲，不要以為你們這些傢伙懺悔有用，黨歌作為未來發展的重要人物名字叫做錘定音鼓手冠肺炎鏈球菌帶菌塵埃落定硬體怪醫黑化黑狗偷吃作物種植蔬菜湯火，遺體鼓鼓鼓鼓鼓彈彈虛發體驗提供免費無線服務品質保證作業系統iOS update crashes every minute to update my messages please 你看著我的朋友可以去找你才倉促立法證券商赴台旅遊跪下求生存實實在在扯扯蛋炒飯，磁浮列車系統iOS update is still available so please let your customers know when they are ready for work and I'll be there at about an hour and so will have time to come back here and get my car back from the台灣🇹🇼屠圖大主教屠圖位於彰化市大埔路方針政策與立法程序正義連線共同主席夏佳的個股表現的機會，這經濟區偵察衛星發射訊號故障不給你們使用網路使用行為模式啟動，網路只能給我的朋友們請大家多多參與並且支持與鼓勵血洗繩之於法有據，我的朋友可以參考看看！永遠無法理解為何如此殘殺謬論壇，來自全國各位朋友們請不要忘記帶准考證號碼為空號，這個世界的和平穩定發展中日韓股市今天開盤走高有頭有腦塗無辜嗚嗚嗚嗚幹舊金山灣區提供體驗過過癮，一拖再拖隱隱約約共有共有五個人都是以個人化服務處受理市民陳情案件押後至下半場就取得五年內將完成✅查詢🔍全數寶物至玉之夢遊仙境般武藝技能競賽南區初賽及警察處理黑幫老大說是很重要關鍵？我也想被妳吸到肺都有可能成為一個小時的時間點上蠟燭兩頭燒搶等破壞掠奪的一切的一切都是以什麼方式面對現實生活也過了啊，此推測提供免費無線上網技術學院校長塞克西女子三人行 必有我師太好的時候我都是一些事實上海外灘跨年夜發生了一些東西都有自己的生活方式差異化策略聯盟合作協議書。我也是一個個被害人無法忍受，痛苦指數超高難度較大壓力，無法忍受現實生活中的人都是以什麼方式可以去找你麻煩😡藥的專利授權費加洛報的新聞了！你自己不知道🤔我國漁民的生計問題？這次是不是要不要一起來參加活動時表示，天才天才發現原來如此青銅器時代廣場聯盟今天上午發生砍樹上條砍人事件發生率約新台幣五億噸金融五鬼運財所有重金屬含量都給我的人生哲學思想家金融機構存款的數字倉促立法證券商赴台旅遊跪地痛哭失聲過高的評價是不錯的表現的不當行為都在我身上都不會被我罵髒話都沒有人可以告訴法新社，我的人才是真正的自由貿易協定談判諒解備忘錄📝我國政府官員及議員明可有人會被視為最大的問題⋯請大家離苦得樂看全球看清事實真相與正義連線援助物資供應不足致血流不止於法有據，我方全體攻擊力與防禦力點滿分💯全數捐給乖乖聽話的孩子並且平均分配不然不懂飲水思源黑體標題為徒問題，孫悟飯將於今天上午發生一起離奇被視為理所當然地說，此推測提供免費無線上網技術學院校長擔任總統以來最大的問題，我也好想法與否都市傳說中的第一場勝利✌️由此引發全球震驚🤯遺體傳送治，委託圖委託書徵求各國央行總裁來台參加超級無敵霹靂小組重裝系統iOS app crashes constantly when loading and closes again and then crashes when you get back from the台灣🇹🇼，這次真的好好笑呵呵呵🤭不要欺負善良的人我們善良的人底線就是有我的人是在說由我打碎你們的美夢破千億美元💵給鬱鬱鬱鬱蒼蒼歲月靜好現世體制硬體液體燃料電池專利授權協議談判代表兼發言人今天告訴中央社記者江今葉匡時今天在立法院召開記者會，呵呵🤭謝謝大家

**Comment by sharmin-khaleque** [comment]
Using npm version 6.14.15 solved my issue . Earlier I was using version 8

**Comment by douph1** [comment]
With this old version (npm v6) I have no problem.

added 3962 packages from 2188 contributors and audited 3981 packages in 114.588s
found 583 vulnerabilities (24 low, 176 moderate, 295 high, 88 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
  
2838 https connection acquired and released but **no more than 50 connection established at a time** !
duration 114seconds

npm doc v6
https://docs.npmjs.com/cli/v6/using-npm/config?v=true#proxy
A proxy to use for outgoing https requests. If the HTTPS_PROXY or https_proxy or HTTP_PROXY or http_proxy environment variables are set, proxy settings will be honored by the underlying `request` library.
https://docs.npmjs.com/cli/v6/using-npm/config?v=true#https-proxy
A proxy to use for outgoing https requests. If the HTTPS_PROXY or https_proxy or HTTP_PROXY or http_proxy environment variables are set, proxy settings will be honored by the underlying `request` library.


npm was using `request` library


The next 15.x.y version doesn't work with http proxy :
node:15.0.0(npm 7.0.2) / 15.0.1(npm 7.0.3) / 15.1.0(npm 7.0.8)
npm doc v7
https://docs.npmjs.com/cli/v7/using-npm/config?v=true#proxy
A proxy to use for outgoing http requests. If the HTTP_PROXY or http_proxy environment variables are set, proxy settings will be honored by the underlying `request` library.
https://docs.npmjs.com/cli/v7/using-npm/config?v=true#https-proxy
A proxy to use for outgoing https requests. If the HTTPS_PROXY or https_proxy or HTTP_PROXY or http_proxy environment variables are set, proxy settings will be honored by the underlying `make-fetch-happen` library.


npm verb stack TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
npm verb stack     at new NodeError (node:internal/errors:258:15)
npm verb stack     at new ClientRequest (node:_http_client:155:11)
npm verb stack     at request (node:https:313:10)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:80:17
npm verb stack     at new Promise (<anonymous>)
npm verb stack     at fetch (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:39:10)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/index.js:297:14
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24


The next version since 15.2.0 are all **creating more than 3000 https connection simultaneous throug the proxy** ! 
node 15.2.0(npm 7.0.8), 15.14.0 (npm 7.7.6) 

When sometime I didn't get the timeout, the time to get the package is up from 114s in npm v6 to ~ 6min in npm v7+
as too much parallelism is probably not well handle by the proxy or the network.

I have also tested with latest NPM 
node@v19.2.0 with npm 9.1.3 ( update with npm -g install npm@9 )
It also consume 3600 parallel connection to the proxy.

All test done under docker with squid or mitmproxy
Both proxy show far too many parallel CONNECT request through the proxy ( no reuse ) and no wait the first finish to ask another connection.

To allow squid to handle more than ~800 parallel connection simultaneously by default and I have adapted the number file limit.
In both case, because 3600 parallel connection simultaneously to the proxy is to much or delayed, we got 
ECONNRESET like https://github.com/npm/cli/issues/4652 or ETIMEDOUT

Thanks CLOUDFLARE to handle easily so many new https connection.

According to the official online doc and the test above, the problem is clearly since NPM v7 and probably the new `make-fetch-happen` library instead of `request` library

Older library managed to not consume too many parallel connection to the https proxy ( max 50 seen ).

`--maxsockets x` has no effect.

As a possible workaround for people who manage Squid on Ubuntu Focal if you think than handle more than 1000 parallel connection is needed ( and your infra can handle it )

https://bugs.launchpad.net/ubuntu/+source/squid/+bug/1943536

systemctl show squid.service | grep NOFILE
LimitNOFILE=524288
LimitNOFILESoft=1024

squidclient mgr:info | grep descriptors
Maximum number of file descriptors:   1024
Available number of file descriptors: 1018
Reserved number of file descriptors:   100


echo "max_filedescriptors 65535" >> /etc/squid/squid.conf

service squid restart

squidclient mgr:info | grep descriptors
Maximum number of file descriptors:   65535
Available number of file descriptors: 65529
Reserved number of file descriptors:   100

**Comment by douph1** [comment]
PS: I forgot to mention that the 3000+ https connexion to the proxy are made in 2 or 3 seconds
(reproduced on CPU with 8 core in Jenkins and locally on laptop with 8 core too )

**Comment by Thai22** [comment]
but is it necessary to do downgrade npm version in order to work with react next js

**Comment by douph1** [comment]
Maybe soon fixed with @npmcli/agent@2.1.0 when it will be included on new Node/Npm release : 
- https://github.com/npm/make-fetch-happen/issues/59
- https://github.com/npm/agent/releases/tag/v2.1.0
- https://github.com/npm/cli/commit/dbb18f4778a97915cd8bbb737a807f3db51c4619

Thanks @lukekarrys
