### ISSUE TITLE
[BUG] npm install unsupported protocol error

### ISSUE THREAD

**Issue by ocbrollingpaper** [npm/cli#4087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have initiated svelte kit project in repo, but when I try to install packages I get the following error:

```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@8.1.4
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\\cybernite.org\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 14ms
19 timing npm:load:configload Completed in 14ms
20 timing npm:load:setTitle Completed in 1ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 23ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 16ms
30 timing idealTree:userRequests Completed in 0ms
31 silly idealTree buildDeps
32 silly fetch manifest @fontsource/fira-mono@^4.5.0
33 http fetch GET 200 https://registry.npmjs.org/@fontsource%2ffira-mono 1846ms (cache revalidated)
34 silly fetch manifest @lukeed/uuid@^2.0.0
35 http fetch GET 200 https://registry.npmjs.org/@lukeed%2fuuid 1777ms (cache revalidated)
36 silly fetch manifest cookie@^0.4.1
37 http fetch GET 200 https://registry.npmjs.org/cookie 43ms (cache revalidated)
38 silly fetch manifest @sveltejs/adapter-auto@next
39 http fetch GET 200 https://registry.npmjs.org/@sveltejs%2fadapter-auto 1978ms (cache revalidated)
40 silly fetch manifest @sveltejs/kit@next
41 http fetch GET 200 https://registry.npmjs.org/@sveltejs%2fkit 396ms (cache revalidated)
42 silly fetch manifest svelte@^3.34.0
43 http fetch GET 200 https://registry.npmjs.org/svelte 62ms (cache revalidated)
44 silly fetch manifest eslint@^7.32.0
45 http fetch GET 200 https://registry.npmjs.org/eslint 44ms (cache revalidated)
46 silly fetch manifest eslint-config-prettier@^8.3.0
47 http fetch GET 200 https://registry.npmjs.org/eslint-config-prettier 32ms (cache revalidated)
48 silly fetch manifest eslint-plugin-svelte3@^3.2.1
49 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-svelte3 43ms (cache revalidated)
50 silly fetch manifest prettier@^2.4.1
51 http fetch GET 200 https://registry.npmjs.org/prettier 37ms (cache revalidated)
52 silly fetch manifest prettier-plugin-svelte@^2.4.0
53 http fetch GET 200 https://registry.npmjs.org/prettier-plugin-svelte 41ms (cache revalidated)
54 silly placeDep ROOT @fontsource/fira-mono@4.5.0 OK for: cybernite.org@0.0.1 want: ^4.5.0
55 silly placeDep ROOT @lukeed/uuid@2.0.0 OK for: cybernite.org@0.0.1 want: ^2.0.0
56 silly placeDep ROOT @sveltejs/adapter-auto@1.0.0-next.0 OK for: cybernite.org@0.0.1 want: next
57 silly placeDep ROOT @sveltejs/kit@1.0.0-next.199 OK for: cybernite.org@0.0.1 want: next
58 silly placeDep ROOT svelte@3.44.2 OK for: @sveltejs/kit@1.0.0-next.199 want: ^3.44.0
59 silly placeDep ROOT cookie@0.4.1 OK for: cybernite.org@0.0.1 want: ^0.4.1
60 silly placeDep ROOT eslint@7.32.0 OK for: cybernite.org@0.0.1 want: ^7.32.0
61 silly placeDep ROOT eslint-config-prettier@8.3.0 OK for: cybernite.org@0.0.1 want: ^8.3.0
62 silly placeDep ROOT eslint-plugin-svelte3@3.2.1 OK for: cybernite.org@0.0.1 want: ^3.2.1
63 silly placeDep ROOT prettier@2.4.1 OK for: cybernite.org@0.0.1 want: ^2.4.1
64 silly placeDep ROOT prettier-plugin-svelte@2.5.0 OK for: cybernite.org@0.0.1 want: ^2.4.0
65 silly fetch manifest @lukeed/csprng@^1.0.0
66 timing idealTree Completed in 6376ms
67 timing command:install Completed in 6392ms
68 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
68 verbose stack     at unsupportedURLType (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:246:15)
68 verbose stack     at fromURL (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:306:13)
68 verbose stack     at Function.resolve (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:76:12)
68 verbose stack     at C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1034:38
68 verbose stack     at Array.map (<anonymous>)
68 verbose stack     at visit (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1033:56)
68 verbose stack     at visitNode (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:57:25)
68 verbose stack     at next (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:44:19)
68 verbose stack     at depth (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:82:10)
68 verbose stack     at depth (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\treeverse\lib\depth.js:27:12)
69 verbose cwd C:\Users\\cybernite.org
70 verbose Windows_NT 10.0.22000
71 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
72 verbose node v16.13.0
73 verbose npm  v8.1.4
74 error code EUNSUPPORTEDPROTOCOL
75 error Unsupported URL Type "workspace:": workspace:*
76 verbose exit 1

```

I am sorry for creating this issue, it might be mistake on my part, but with previous version of NPM it works like a charm. I purged cache, reinstalled node and it still persists.

Current workaround is to use yarn as package manager, but I cba typing yarn instead of npm. While I understand error and what causes is to happen, I don't know how to fix it since im frontend/js newbie (i hate working with frontend)

Note, I have removed my username from paths in log because of privacy 🤣 

### Expected Behavior

npm should install packages without any errors

### Steps To Reproduce

1. npm: 8.1.4
2. config below
3. Run 'npm init svelte@next idk-kev' after it is initialized run 'npm install'
4. And see the errors in files above

### Environment

- npm: 8.1.4
- Node: 16.13
- OS: Windows 10
- platform: x64
- npm config: 
```ini
; "builtin" config from C:\Users\\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\\cybernite.org
; HOME = C:\Users\
; Run `npm config ls -l` to show all defaults.
```

**Comment by ocbrollingpaper** [comment]
Found fix, it was package that was causing error, not npm itself

**Comment by patricknwanah** [comment]
Nice so what was the fix?

**Comment by ocbrollingpaper** [comment]
> Nice so what was the fix?

It was svelte kit adapter :)
and I was using ssh for git and for some reason it only accepted http
