### ISSUE TITLE
[BUG] npm whoami seems ot ignore --registery arg

### ISSUE THREAD

**Issue by dprslt** [npm/cli#4090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Trying to use `release-it` to publish a package on a private registry.

When looking at the logs `release-it` apply the current proccess
- `npm ping --registry https://private-gitlab-server/api/v4/projects/000/packages/npm/`
- `npm whoami --registry https://private-gitlab-server/api/v4/projects/000/packages/npm/`
- `npm show <mypackage>@latest version --registry https://private-gitlab-server/api/v4/projects/000/packages/npm/`

The `npm whoami` command failed with the following error
```
ERROR Not authenticated with npm. Please `npm login` and try again.
```

When running the command manualy, i got the following output

```shell
❯ npm whoami --registry https://private-gitlab-server/api/v4/projects/000/packages/npm/ --verbose
npm verb cli [
npm verb cli   '/Users/dprslt/.nvm/versions/node/v14.18.1/bin/node',
npm verb cli   '/Users/dprslt/.nvm/versions/node/v14.18.1/bin/npm',
npm verb cli   'whoami',
npm verb cli   '--registry',
npm verb cli   'https://private-gitlab-server/api/v4/projects/000/packages/npm/',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@8.1.4
npm info using node@v14.18.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/Users/dprslt/.nvm/versions/node/v14.18.1/lib/node_modules/npm/npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 3ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/dprslt/Projects/prepare-pkg-version/.npmrc Completed in 2ms
npm timing config:load:project Completed in 3ms
npm timing config:load:file:/Users/dprslt/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/Users/dprslt/.nvm/versions/node/v14.18.1/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 11ms
npm timing npm:load:configload Completed in 11ms
npm timing npm:load:setTitle Completed in 18ms
npm timing npm:load:setupLog Completed in 0ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 40ms
npm timing command:whoami Completed in 711ms
npm verb stack HttpErrorGeneral: 401 Unauthorized - GET https://registry.npmjs.org/-/whoami - Unauthorized
npm verb stack     at /Users/dprslt/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm verb stack     at async module.exports (/Users/dprslt/.nvm/versions/node/v14.18.1/lib/node_modules/npm/lib/utils/get-identity.js:21:26)
npm verb stack     at async Whoami.exec (/Users/dprslt/.nvm/versions/node/v14.18.1/lib/node_modules/npm/lib/commands/whoami.js:10:22)
npm verb stack     at async module.exports (/Users/dprslt/.nvm/versions/node/v14.18.1/lib/node_modules/npm/lib/cli.js:65:5)
npm verb statusCode 401
```
It looks like npm tried to contact the base registry without using the one specified by the `--registry` arg.

I've tried to run `npm publish` manualy and it works fine

### Expected Behavior

nvm should run the nvm command on the given registry

### Steps To Reproduce

Run `npm whoami` with a `--registry` arg pointing on a private gitlab registry

### Environment

- npm: 8.1.4 and npm 6
- Node: 14.8.1
- OS: MacOs
- platform: x64
- npm config:
```ini
; copy and paste output from `npm config ls` here
//private-gitlab-server/api/v4/projects/000/packages/npm/:_authToken = (protected) 
```

**Comment by wraithgar** [comment]
This appears to have been fixed

```sh
$ npm whoami --registry https://npm.pkg.github.com
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://npm.pkg.github.com/-/whoami - Permission denied
```

**Comment by dparker2** [comment]
@wraithgar i am seeing this in both NPM v6 and NPM v9:
```
$ npm whoami --registry https://gitlab.com/api/v4/projects/<project id omitted>/packages/npm/
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://registry.npmjs.org/-/whoami - Unauthorized
```

Which version was it fixed in?

`ping` also secretly ends up pinging `npmjs.org`:
```
$ npm ping --registry https://gitlab.com/api/v4/projects/<project id>/packages/npm/ --verbose
...
npm notice PING https://gitlab.com/api/v4/projects/<project id>/packages/npm/
npm http fetch GET 200 https://registry.npmjs.org/-/ping 2621ms (cache updated)
npm notice PONG 2623ms
npm verb exit 0
npm info ok
```

**Comment by ljharb** [comment]
Does ping even support the registry arg?
