### ISSUE TITLE
twilio-cli encountered an unexpected error[BUG] <title>

### ISSUE THREAD

**Issue by natashanewton** [npm/cli#4190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

C:\PAL\plugin-activity-handler-main>twilio flex:plugins:deploy --major --changelog "Activity" -l debug
[DEBUG] Config File: C:\Users\Administrator\.twilio-cli\config.json
[DEBUG] Using profile: pal_uat
[DEBUG] Using Plugins CLI version 4.2.2
[DEBUG] Using Flex Plugins Config File: C:\Users\Administrator\.twilio-cli\flex\plugins.json
[DEBUG] Using flex-plugin-scripts version 4.2.2
Using profile pal_uat (ACd4349a9496d548720934311d54f5f987)

[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://flex-api.twilio.com/v1/Configuration
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/2.36.0 @twilio/cli-core/5.33.0 (win32 ia32) twilio-node/3.72.0 node/v14.16.1 flex:plugins:deploy keytar
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 23 Dec 2021 16:34:53 GMT","content-type":"application/json; charset=utf-8","content-length":"6619","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ44ecb540246cc548321496a007775866","twilio-request-duration":"0.020","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"flex-api.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZS6706e39930e7ba9793b1539d2859328c
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/2.36.0 @twilio/cli-core/5.33.0 (win32 ia32) twilio-node/3.72.0 node/v14.16.1 flex:plugins:deploy keytar
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 23 Dec 2021 16:34:55 GMT","content-type":"application/json; charset=utf-8","content-length":"863","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQd547cf431b7bd4e0e7d03a0dc1afe8f1","twilio-request-duration":"0.029","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://flex-api.twilio.com/v1/Configuration
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/2.36.0 @twilio/cli-core/5.33.0 (win32 ia32) twilio-node/3.72.0 node/v14.16.1 flex:plugins:deploy keytar
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 23 Dec 2021 16:34:56 GMT","content-type":"application/json; charset=utf-8","content-length":"6619","connection":"close","twilio-concurrent-requests":"2","twilio-request-id":"RQ0d9d9c0787224a956b3edb9608f42dbb","twilio-request-duration":"0.025","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"flex-api.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZS6706e39930e7ba9793b1539d2859328c
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/2.36.0 @twilio/cli-core/5.33.0 (win32 ia32) twilio-node/3.72.0 node/v14.16.1 flex:plugins:deploy keytar
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 23 Dec 2021 16:34:57 GMT","content-type":"application/json; charset=utf-8","content-length":"863","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ4915fe690139292f7e32e5a4411d953a","twilio-request-duration":"0.021","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZS6706e39930e7ba9793b1539d2859328c/Environments
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: twilio-cli/2.36.0 @twilio/cli-core/5.33.0 (win32 ia32) twilio-node/3.72.0 node/v14.16.1 flex:plugins:deploy keytar
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 23 Dec 2021 16:34:58 GMT","content-type":"application/json; charset=utf-8","content-length":"24965","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ366eabcff9fbf2560c14c6fa8cf2e87a","twilio-request-duration":"0.047","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
- Validating deployment of plugin plugin-activity-handler
0 pending HTTP requests - max concurrent requests allowed is 5
Making a GET to https://flex-api.twilio.com/v1/PluginService/Plugins/plugin-activity-handler
Request errored with data
{
  "code": 20404,
  "message": "The requested resource /PluginService/Plugins/plugin-activity-handler was not found",
  "more_info": "https://www.twilio.com/docs/errors/20404",
  "status": 404
}
√ Validating deployment of plugin plugin-activity-handler
- Compiling a production build of plugin-activity-handler
Checking Flex plugin project directory
Building Flex plugin bundle
Compiling a production build...

Plugin plugin-activity-handler was successfully compiled.

2 files were compiled:
         51.5 KB         build/plugin-activity-handler.js
         0.1 KB          build/plugin-activity-handler.js.map
√ Compiling a production build of plugin-activity-handler
Making GET request to https://flex-api.twilio.com/v1/Configuration
Making GET request to https://serverless.twilio.com/v1/Services/ZS6706e39930e7ba9793b1539d2859328c
Making GET request to https://serverless.twilio.com/v1/Services/ZS6706e39930e7ba9793b1539d2859328c/Environments
Making GET request to https://serverless.twilio.com/v1/Services/ZS6706e39930e7ba9793b1539d2859328c/Environments
Making POST request to https://serverless.twilio.com/v1/Services/ZS6706e39930e7ba9793b1539d2859328c/Environments with data {"UniqueName":"plugin-activity-handler","DomainSuffix":"nm6fm"}
[DEBUG] Found command "flex:plugins:deploy" plugin: @twilio-labs/plugin-flex
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/flex-plugin-builder/issues"
[DEBUG] Request post to Environments failed with status 400 and message Environments are limited to less than or equal to 25
[DEBUG] Error: Request post to Environments failed with status 400 and message Environments are limited to less than or equal to 25
    at Http.<anonymous> (C:\Users\Administrator\.twilio-cli\node_modules\flex-plugin-scripts\dist\clients\http.js:162:27)
    at step (C:\Users\Administrator\.twilio-cli\node_modules\flex-plugin-scripts\dist\clients\http.js:52:23)
    at Object.next (C:\Users\Administrator\.twilio-cli\node_modules\flex-plugin-scripts\dist\clients\http.js:33:53)
    at C:\Users\Administrator\.twilio-cli\node_modules\flex-plugin-scripts\dist\clients\http.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Administrator\.twilio-cli\node_modules\flex-plugin-scripts\dist\clients\http.js:23:12)
    at Http.onError (C:\Users\Administrator\.twilio-cli\node_modules\flex-plugin-scripts\dist\clients\http.js:151:48)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

### Expected Behavior

Deploy the plugin successfully

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node:
- OS:
- platform:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment]
This looks like a problem with the twilio-cli, not npm.
