### ISSUE TITLE
[QUESTION](libnpmpublish) 404 Not Found 

### ISSUE THREAD

**Issue by lake2** [npm/cli#4250]
# What / Why

my code：
```
const lib = require('libnpmpublish');
const pack = require('libnpmpack');
const path = require('path');

const resolve = (...str) => path.resolve(__dirname, ...str);

const pkg = require(resolve('./dist/package.json'));

async function run() {
    const tarball = await pack(resolve('./dist/'));

    await lib.publish(pkg, tarball, {
        access: true,
        token: 'XXX',
    });
}

run();
```

result:
```
(node:22460) UnhandledPromiseRejectionWarning: HttpErrorGeneral: 404 Not Found - PUT https://registry.npmjs.org/@sqlflow%2ftest - Not found
    at D:\VS Code\sqlflow_frontend\package\node_modules\npm-registry-fetch\check-response.js:134:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.publish (D:\VS Code\sqlflow_frontend\package\node_modules\libnpmpublish\publish.js:43:12)
    at async run (D:\VS Code\sqlflow_frontend\package\publish\index.js:12:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Where

* npm package @sqlflow/test
* https://registry.npmjs.org/@sqlflow%2ftest

**Comment by ruyadorno** [comment]
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).

**Comment by jsumners** [comment]
Closing a valid issue because it doesn't follow a template is not cool.

Issue: trying to publish a module that does not yet exist by using an automation token result in a 404 unless using the `forceAuth` hack described above. The docs for `libnpmpublish` _seem_ to indicate that providing `{ token: 'an-automation-token' }` will result in that automation token being used for publishing, but that does not happen.

**Comment by ljharb** [comment]
@jsumners its not valid if the template isn’t filled out - that’s what it’s there for.
