### ISSUE TITLE
[BUG] DNS resolution only uses the first address of registry.npmjs.org

### ISSUE THREAD

**Issue by progval** [npm/cli#4378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
$ node-v17.4.0-linux-x64/bin/npm i -g left-pad
npm ERR! code ENETUNREACH
npm ERR! syscall connect
npm ERR! errno ENETUNREACH
npm ERR! request to https://registry.npmjs.org/left-pad failed, reason: connect ENETUNREACH 104.16.22.35:443 - Local (0.0.0.0:0)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thelounge-code/.npm/_logs/2022-02-05T20_40_47_083Z-debug-0.log


$ cat /home/thelounge-code/.npm/_logs/2022-02-05T20_40_47_083Z-debug-0.log
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/home/thelounge-code/node-v17.4.0-linux-x64/bin/npm',
0 verbose cli   'i',
0 verbose cli   '-g',
0 verbose cli   'left-pad'
0 verbose cli ]
1 info using npm@8.3.1
2 info using node@v12.22.5
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/thelounge-code/node-v17.4.0-linux-x64/lib/node_modules/npm/npmrc Completed in 16ms
6 timing config:load:builtin Completed in 17ms
7 timing config:load:cli Completed in 6ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/thelounge-code/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 2ms
16 timing config:load:setEnvs Completed in 2ms
17 timing config:load Completed in 32ms
18 timing npm:load:configload Completed in 32ms
19 timing npm:load:setTitle Completed in 1ms
20 timing config:load:flatten Completed in 4ms
21 timing npm:load:display Completed in 7ms
22 verbose logfile /home/thelounge-code/.npm/_logs/2022-02-05T20_40_47_083Z-debug-0.log
23 timing npm:load:logFile Completed in 9ms
24 timing npm:load:timers Completed in 0ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load Completed in 50ms
27 timing arborist:ctor Completed in 2ms
28 timing idealTree:init Completed in 10ms
29 timing idealTree:userRequests Completed in 4ms
30 silly idealTree buildDeps
31 silly fetch manifest left-pad@*
32 silly placeDep ROOT left-pad@ OK for:  want: *
33 timing idealTree:#root Completed in 70199ms
34 timing idealTree:node_modules/left-pad Completed in 0ms
35 timing idealTree:buildDeps Completed in 70207ms
36 timing idealTree:fixDepFlags Completed in 1ms
37 timing idealTree Completed in 70223ms
38 timing command:i Completed in 70245ms
39 verbose type system
40 verbose stack FetchError: request to https://registry.npmjs.org/left-pad failed, reason: connect ENETUNREACH 104.16.22.35:443 - Local (0.0.0.0:0)
40 verbose stack     at ClientRequest.<anonymous> (/home/thelounge-code/node-v17.4.0-linux-x64/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:110:14)
40 verbose stack     at ClientRequest.emit (events.js:314:20)
40 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:427:9)
40 verbose stack     at TLSSocket.emit (events.js:326:22)
40 verbose stack     at emitErrorNT (internal/streams/destroy.js:92:8)
40 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
40 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
41 verbose cwd /home/thelounge-code
42 verbose Linux 5.10.0-11-cloud-amd64
43 verbose argv "/usr/bin/node" "/home/thelounge-code/node-v17.4.0-linux-x64/bin/npm" "i" "-g" "left-pad"
44 verbose node v12.22.5
45 verbose npm  v8.3.1
46 error code ENETUNREACH
47 error syscall connect
48 error errno ENETUNREACH
49 error request to https://registry.npmjs.org/left-pad failed, reason: connect ENETUNREACH 104.16.22.35:443 - Local (0.0.0.0:0)
50 verbose exit 1
51 timing npm Completed in 70677ms
52 verbose unfinished npm timer reify 1644093647499
53 verbose unfinished npm timer reify:loadTrees 1644093647515
54 verbose code 1
55 error A complete log of this run can be found in:
55 error     /home/thelounge-code/.npm/_logs/2022-02-05T20_40_47_083Z-debug-0.log
```

### Expected Behavior

NPM should try the other addresses returned by getaddrinfo

### Steps To Reproduce

Option 1 (slightly harder, but gives a clearer error):

1. Add these DNS resolvers: https://nat64.net/
2. Disable IPv4 (eg. with `sudo ip r del default`)
3. run `npm install`

Option 2 (simpler, but makes npm hang forever instead of showing an error):

1. Add an invalid route to the IP address in the first A record of (eg. at the time I am writing this, for me, this is `104.16.22.35`, so I can do it with: `sudo ip r add 104.16.22.35 dev lo`)
2. run `npm install`

### Environment

- npm: 8.3.1
- Node.js: v17.4.0
- OS Name: Debian 11
- System Model Name: Scaleway Stardust
- npm config:
```ini
; node bin location = /usr/bin/node
; cwd = /home/thelounge-code
; HOME = /home/thelounge-code
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
@progval Thanks for filing this! Since this is working as intended, can you please open an [RFC issue](https://github.com/npm/rfcs) with some details on how you could/would like to see this changed?

We currently use node core behavior, and do not manage DNS resolution within the npm CLI.
