### ISSUE TITLE
[BUG] .npmrc doesn't seem to use authToken from env

### ISSUE THREAD

**Issue by cam-narzt** [npm/cli#4407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`~/.npmrc`:
```
npm_package_config_puppeteer_skip_download=true
puppeteer_skip_download=true
//registry.npmjs.com/:_authToken=$NPM_TOKEN
```

bash shell:
```
$ export NPM_TOKEN=npm_REST_OF_THE_TOKEN_HERE_I_PROMISE_IT_IS_CORRECT
$ npm whoami -ddd
npm verb cli [
npm verb cli   '/usr/local/Cellar/node/17.4.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'whoami',
npm verb cli   '-ddd'
npm verb cli ]
npm info using npm@8.5.0
npm info using node@v17.4.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:/Users/camdennarzt/Developer/Javascript/woofmark/.npmrc Completed in 0ms
npm timing config:load:project Completed in 4ms
npm timing config:load:file:/Users/camdennarzt/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 14ms
npm timing npm:load:configload Completed in 14ms
npm timing npm:load:setTitle Completed in 6ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 6ms
npm verb logfile /Users/camdennarzt/.npm/_logs/2022-02-13T00_10_38_147Z-debug-0.log
npm timing npm:load:logFile Completed in 5ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 31ms
npm timing command:whoami Completed in 1ms
npm verb stack Error: This command requires you to be logged in.
npm verb stack     at needsAuthError (/usr/local/lib/node_modules/npm/lib/utils/get-identity.js:4:17)
npm verb stack     at module.exports (/usr/local/lib/node_modules/npm/lib/utils/get-identity.js:37:11)
npm verb stack     at Whoami.exec (/usr/local/lib/node_modules/npm/lib/commands/whoami.js:11:28)
npm verb stack     at Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:146:22)
npm verb stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:66:5)
npm verb cwd /Users/camdennarzt/Developer/Javascript/woofmark
npm verb Darwin 20.6.0
npm verb argv "/usr/local/Cellar/node/17.4.0/bin/node" "/usr/local/bin/npm" "whoami" "-ddd"
npm verb node v17.4.0
npm verb npm  v8.5.0
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm verb exit 1
npm timing npm Completed in 138ms
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/camdennarzt/.npm/_logs/2022-02-13T00_10_38_147Z-debug-0.log
```

If i write the token into `~/.npmrc` explicitly, then i can publish, but `npm whoami` still doesn't work. I also tried putting curly braces around `NPM_TOKEN` in `~/.npmrc` but that didn't make a difference.

### Expected Behavior

the docs say i should be able to use an env var to provide the auth token to npm

### Steps To Reproduce

see current behaviour above, however bash version is `GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin20.6.0)`

### Environment

- npm: 8.5.0
- Node.js: 17.4.0
- OS Name: macOS 11.6.3
- System Model Name: Macbook Pro
- npm config:
```ini
; "builtin" config from /usr/local/lib/node_modules/npm/npmrc

prefix = "/usr/local" 

; "user" config from /Users/camdennarzt/.npmrc

//registry.npmjs.com/:_authToken = (protected) 
npm_package_config_puppeteer_skip_download = true 
puppeteer_skip_download = true 

; node bin location = /usr/local/Cellar/node/17.4.0/bin/node
; cwd = /Users/camdennarzt/Developer/Javascript/woofmark
; HOME = /Users/camdennarzt
; Run `npm config ls -l` to show all defaults.
```

**Comment by HanabishiRecca** [comment]
Use `${NPM_TOKEN}`.

**Comment by cam-narzt** [comment]
@HanabishiRecca 

> I also tried putting curly braces around `NPM_TOKEN` in `~/.npmrc` but that didn't make a difference.

**Comment by HanabishiRecca** [comment]
@cam-narzt, yeah.
Actually you also use wrong url. There should be `registry.npmjs.org`, not `com`.
https://docs.npmjs.com/cli/v8/commands/npm-token#registry

This example should work:
```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```

**Comment by cam-narzt** [comment]
thank you that did it!

**Comment by ilatypov** [comment]
It worked for me after replacing `_authToken` with `_auth` because I am using JFrog's `Base64(USER:ENCRYPTED_PASSWORD)` for the value.  (I can pass it indirectly via an environment variable and refer to it as `${MY_JFROG_BASE64_USER_PASS}`.
