### ISSUE TITLE
[BUG] getaddrinfo EAI_AGAIN yourip

### ISSUE THREAD

**Issue by Alien10123** [npm/cli#4515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I try to install a package in npm I get this error (I am trying to install the serverless package):

```
npm ERR! code EAI_AGAIN
npm ERR! syscall getaddrinfo
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/serverless failed, reason: getaddrinfo EAI_AGAIN yourip
```
This is the debug logs file:

```
0 verbose cli [
0 verbose cli   '/home/alien10/.nvm/versions/node/v17.3.1/bin/node',
0 verbose cli   '/home/alien10/.nvm/versions/node/v17.3.1/bin/npm',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   'serverless'
0 verbose cli ]
1 info using npm@8.1.3
2 info using node@v17.3.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/alien10/.nvm/versions/node/v17.3.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/alien10/.npmrc Completed in 4ms
11 timing config:load:user Completed in 4ms
12 timing config:load:file:/home/alien10/.nvm/versions/node/v17.3.1/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 1ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 14ms
18 timing npm:load:configload Completed in 15ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 1ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 21ms
26 timing arborist:ctor Completed in 1ms
27 timing idealTree:init Completed in 5ms
28 timing idealTree:userRequests Completed in 2ms
29 silly idealTree buildDeps
30 silly fetch manifest serverless@*
31 silly placeDep ROOT serverless@ OK for:  want: *
32 timing idealTree:#root Completed in 70030ms
33 timing idealTree:node_modules/serverless Completed in 0ms
34 timing idealTree:buildDeps Completed in 70032ms
35 timing idealTree:fixDepFlags Completed in 1ms
36 timing idealTree Completed in 70041ms
37 timing command:install Completed in 70053ms
38 verbose type system
39 verbose stack FetchError: request to https://registry.npmjs.org/serverless failed, reason: getaddrinfo EAI_AGAIN yourip
39 verbose stack     at ClientRequest.<anonymous> (/home/alien10/.nvm/versions/node/v17.3.1/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:110:14)
39 verbose stack     at ClientRequest.emit (node:events:390:28)
39 verbose stack     at onerror (/home/alien10/.nvm/versions/node/v17.3.1/lib/node_modules/npm/node_modules/agent-base/dist/src/index.js:117:21)
39 verbose stack     at callbackError (/home/alien10/.nvm/versions/node/v17.3.1/lib/node_modules/npm/node_modules/agent-base/dist/src/index.js:136:17)
39 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
40 verbose cwd /home/alien10/Desktop/Sam Coding/codeyverse-next
41 verbose Linux 5.13.0-30-generic
42 verbose argv "/home/alien10/.nvm/versions/node/v17.3.1/bin/node" "/home/alien10/.nvm/versions/node/v17.3.1/bin/npm" "install" "-g" "serverless"
43 verbose node v17.3.1
44 verbose npm  v8.1.3
45 error code EAI_AGAIN
46 error syscall getaddrinfo
47 error errno EAI_AGAIN
48 error request to https://registry.npmjs.org/serverless failed, reason: getaddrinfo EAI_AGAIN yourip
49 verbose exit 1
```

It works on windows (I use ubuntu for coding and windows for gaming because I have a duel booted system). I have tried changing my dns like every website or issue says to do says to do but that doesn't work. When I do `ping registry.npmjs.org` I get the error `Destination unreachable: Address unreachable`. When I go to registry.npmjs.org or registry.npmjs.org/serverless in my browser it works. Idk why it doesn't work in the command line. And changing myhosts file doesn't work. For now I will just have to set everything up on windows until it works.

### Expected Behavior

It should just install the serverless package when I do `npm i -g serverless`.

### Steps To Reproduce

In Ubuntu just try install a package.

### Environment

- npm: 8.5.1
- Node.js: 17.6.0
- OS Name: Ubuntu
- System Model Name: An Asus laptop.
- npm config:
```ini
; node bin location = /home/my user/.nvm/versions/node/v17.6.0/bin/node
; cwd = /home/my user/Desktop/Coding/codeyverse-next
; HOME = /home/my user
; Run `npm config ls -l` to show all defaults.```

**Comment by ljharb** [comment]
The error message says v8.1.3, altho your issue claims v8.5.1. Do you get the same output on v8.5.3?

**Comment by Alien10123** [comment]
@ljharb I ran it once then check the version and saw that it was v8.1.3 so I change my node version to the latest with nvm so that it changed the npm version and I got the same result. So it doesn't v8.5.1 either.

**Comment by nlf** [comment]
the `EAI_AGAIN` error indicates a problem with dns resolution, this isn't something we can really do anything about within npm itself. the resolution not working with `ping` but working in browsers is likely because several browsers handle dns themselves instead of relying entirely on the underlying host.

unfortunately the only fix for this one is determining what's wrong with your host's dns resolution and fixing that. if `ping` works, then `npm` should work too.

**Comment by Alien10123** [comment]
Changing my dns and switching networks worked.
