### ISSUE TITLE
[BUG] <title>Error while installing firebase-tools

### ISSUE THREAD

**Issue by Supriya1659** [npm/cli#4682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm trying to install firebase-tools in nodejs by using the command 
   npm install firebase-tools
But it is showing and error like this

Error: Cannot find module 'semver'
Require stack:
- C:\Users\894796\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\894796\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js:3:16)    
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\894796\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\lib\\bin\\firebase.js'
  ]
}

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 7.6.3
- Node.js:  14.15.4
- OS Name: Windows 10
- System Model Name: Hp
- npm config:
```ini
; copy and paste output from `npm config ls` here
```"builtin" config from C:\Users\894796\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\894796\\AppData\\Roaming\\npm" 

; "cli" config from command line options

omit = []
user-agent = "npm/7.6.3 node/v14.15.4 win32 x64"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\894796\Documents\JULY21 - NOVEMBER21-feb22\Reactjs-Mastering redux-udemy\ageteller
; HOME = C:\Users\894796
; Run `npm config ls -l` to show all defaults.

**Comment by darcyclarke** [comment]
**Closing:** we do not support/triage third-party libraries or tooling bugs; Please file an issue with the relevant project itself (ref. https://github.com/firebase/firebase-tools#firebase-cli---)
