### ISSUE TITLE
npm ERR! cb() never called

### ISSUE THREAD

**Issue by xvimaluenda** [npm/cli#491]
Hello,

I'm runnig a CI on Azure and I get this error.

Context:
Node V **11.8.0**
Npm **6.5.0**

**Detailed error message**
C:\windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\node\11.8.0\x64\npm.cmd install typescript@3.7.2"
**Unhandled rejection Error: Integrity check failed**:
  Wanted: sha512-woUdsPk68RIUeGOFYtPwxZ/Li2cuJvpq8m+CWVpQTXZQao/LAspfV2zBfYAwpkDSqlVGjYQyUiNxotQtoY2Stw==
   Found: sha512-A5ZjGXf2i2YRIZRKYqAH09g/SIcSFw43/2HSvyisDFYeSVAkfeV5AAQ/CHC0LofYaqYsxpb6wixU0H93fqxqFg==
    at checksumError (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\cacache\lib\content\write.js:157:13)
    at write (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\cacache\lib\content\write.js:35:22)
    at putData (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\cacache\put.js:29:10)
    at Object.x.put (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\cacache\locales\en.js:28:37)
    at readFileAsync.then.data (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\pacote\lib\fetchers\file.js:38:28)
    at tryCatcher (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
    at C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\hostedtoolcache\windows\node\11.8.0\x64\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

I undestand that an error is comming from a package's checksum but I'm not able to find if error comes from typescript package or it is comming from another one.
I already tried targetting some others versions of typescript.
Same npm command (in similar context: TS version, etc...) is running on another project in same CI chain.

An idea to resolve.

**Comment by green3g** [comment]
I'm getting this too. 

```
[Pipeline] sh
+ npm install
(node:5848) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\method.js:29:9)
(node:5848) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\method.js:29:9)
(node:5848) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\method.js:29:9)
(node:5848) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\method.js:29:9)
(node:5848) Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\method.js:29:9)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```

Windows Server 2016. 

```
C:\Users\groemhildt>npm --version
6.13.0

C:\Users\groemhildt>node --version
v12.10.0
```

**Comment by xvimaluenda** [comment]
I found my-self.
Problem comes from a local module, built in the same pipeline, I must unisntall it and reinstall. and everithing goes ok.

**Comment by green3g** [comment]
@xvimaluenda what module?
