### ISSUE TITLE
npm install nexus binary auth failed 401

### ISSUE THREAD

**Issue by belief-cyf** [npm/cli#5015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

1、npm config set sass_binary_site https://privat-nexus-demo/repository/raw-group
2、For safety reasons ，nexus Anonymous access is not allowed
3、npm install
4、> node-sass@7.0.1 install /home/jenkins/agent/workspace/xxx/55/node_modules/node-sass
  > node scripts/install.js
  Downloading binary from https://privat-nexus-demo/repository/raw-group/v7.0.1/linux-x64-72_binding.node
  Cannot download "https://privat-nexus-demo/repository/raw-group/v7.0.1/linux-x64-72_binding.node":
  HTTP error 401 Unauthorized

5、i have set the correct account password。 I can directly access the package address through the browser and enter the account password to download。

### Expected Behavior

install success

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:6.14.12
- Node.js:12.22.1
- OS Name:linux x64
- System Model Name:
- npm config:
```
metrics-registry = "https://xxxx/repository/xxx/"
--
scope = ""
user-agent = "npm/6.14.12 node/v12.22.1 linux x64 ci/jenkins"
; userconfig /root/.npmrc
always-auth = true
cache = "/home/jenkins/agent/caches/xxxx/xxx/.npm/cache"
registry = "https://xxxxx/repository/xxxx/"
sass_binary_site = "https://privat-nexus-demo/repository/raw-group"
; node bin location = /usr/local/bin/node
; cwd = /home/jenkins/agent/workspace/xxxxx/55
; HOME = /root
; "npm config ls -l" to show all defaults.


```

**Comment by belief-cyf** [comment]
Other NPM packages can be downloaded normally，The same nexus。

**Comment by belief-cyf** [comment]
When I use：
npm info using npm@8.3.0
--
npm info using node@v17.3.1


error log：
```
npm info run node-sass@7.0.1 postinstall node_modules/node-sass node scripts/build.js
npm info run node-sass@7.0.1 postinstall { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 2088ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 145442ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:390:28)
npm verb stack     at maybeClose (node:internal/child_process:1062:16)
npm verb stack     at Socket.<anonymous> (node:internal/child_process:448:11)
npm verb stack     at Socket.emit (node:events:390:28)
npm verb stack     at Pipe.<anonymous> (node:net:687:12)
npm verb pkgid node-sass@7.0.1
npm verb cwd /home/jenkins/agent/workspace/xxxxxx/57
npm verb Linux 4.18.0-305.10.2.el8_4.x86_64
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v17.3.1
npm verb npm  v8.3.0
npm ERR! code 1
npm ERR! path /home/jenkins/agent/workspace/xxxxxx/57/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /home/jenkins/agent/workspace/xxxxx/57/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/home/jenkins/agent/workspace/xxxxx/57/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.3.1 \| linux \| x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.9.2"
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 17.3.1
npm ERR! gyp verb command install [ '17.3.1' ]
npm ERR! gyp verb install input version string "17.3.1"
--
npm ERR! gyp verb install installing version: 17.3.1
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version not already installed, continuing with install 17.3.1
npm ERR! gyp verb ensuring nodedir is created /root/.cache/node-gyp/17.3.1
npm ERR! gyp verb created nodedir /root/.cache
npm ERR! gyp http GET https://nodejs.org/download/release/v17.3.1/node-v17.3.1-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp verb command remove [ '17.3.1' ]
npm ERR! gyp verb remove using node-gyp dir: /root/.cache/node-gyp
npm ERR! gyp verb remove removing target version: 17.3.1
npm ERR! gyp verb remove removing development files for version: 17.3.1
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v17.3.1/node-v17.3.1-headers.tar.gz failed, reason: connect ETIMEDOUT 104.20.23.46:443
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (/home/jenkins/agent/workspace/xxxxxx/57/node_modules/minipass-fetch/lib/index.js:110:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:442:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:402:35)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:164:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Linux 4.18.0-305.10.2.el8_4.x86_64
npm ERR! gyp ERR! command "/usr/local/bin/node" "/home/jenkins/agent/workspace/xxxxxx/57/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/jenkins/agent/workspace/xxxxxxx/57/node_modules/node-sass
npm ERR! gyp ERR! node -v v17.3.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
npm verb exit 1
npm timing npm Completed in 146455ms
npm verb unfinished npm timer reify 1655187470876
npm verb unfinished npm timer reify:build 1655187480512
npm verb unfinished npm timer build 1655187480513
npm verb unfinished npm timer build:deps 1655187480514
npm verb unfinished npm timer build:run:postinstall 1655187482622
npm verb unfinished npm timer build:run:postinstall:node_modules/node-sass 1655187482622
npm verb code 1
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/agent/caches/xxxx/xxxx/xxxx/cache/_logs/2022-06-14T06_17_49_869Z-debug-0.log
errMsg:hudson.AbortException: script returned exit code 1


```

**Comment by fritzy** [comment]
This appears to be a problem with a specific registry or configuration thereof. I am unable to reproduce this with `npm@8.13.1` and the public registry.

```sh
projects/scratchpad/test6 via ⬢ v16.15.0 took 3s 
❯ npm i node-sass@7.0.1
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 240 packages, and audited 241 packages in 3s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
