### ISSUE TITLE
[BUG] Cannot read properties of null (reading 'parent')

### ISSUE THREAD

**Issue by mykola-mokhnach** [npm/cli#5047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

After switching the package to use peer dependencies NPM started showing weird errors in the console:

```
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --save-exact --global-style --no-package-lock appium-xcuitest-driver --json' failed with code 1.

STDOUT:


STDERR:
npm ERR! Cannot read properties of null (reading 'parent')
{
  "error": {
    "code": null,
    "summary": "Cannot read properties of null (reading 'parent')",
    "detail": ""
  }
}

```

The original CI job URL: https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=22042&view=logs&j=7e827989-f55d-590a-d77d-7047b94f51b2&t=27c7b387-8d59-5d33-b298-5b14b88f552c&l=21

### Expected Behavior

The package should be installed without errors

### Steps To Reproduce

npm install -g appium@next
appium driver install xcuitest

### Environment

- npm: 8.x (latest from Azure CI)
- Node.js: 16.x (latest from Azure CI)
- OS Name: macOS 12
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by mykola-mokhnach** [comment]
Most likely the exception happens in https://github.com/npm/arborist/blob/main/lib/arborist/load-virtual.js#L228-L236
Thanks @jlipps for investigating it

**Comment by RSM-SBA** [comment]
here a log from npm

`84 timing reifyNode:node_modules/appium-xcuitest-driver/node_modules/appium-xcuitest-driver Completed in 2ms
85 timing arborist:ctor Completed in 0ms
86 timing reify:rollback:createSparse Completed in 224ms
87 timing reify:rollback:retireShallow Completed in 0ms
88 timing command:install Completed in 5580ms
89 verbose stack TypeError: Cannot read properties of null (reading 'parent')
89 verbose stack at Arborist.[resolveLinks] (/usr/local/Cellar/node@16/16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:229:24)
89 verbose stack at Arborist.[loadFromShrinkwrap] (/usr/local/Cellar/node@16/16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:103:29)
89 verbose stack at Arborist.loadVirtual (/usr/local/Cellar/node@16/16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:75:35)`

**Comment by htmlin** [comment]
I have the same problem with npm v8.5.5
It's okay to fall back to v8.1.2
