### ISSUE TITLE
[BUG] Why can't I use my

### ISSUE THREAD

**Issue by Aaronuo** [npm/cli#5143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

root@XX:~# npm install npm@latest -g
TypeError: invalid options argument
    at optsArg (/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/node_modules/mkdirp/index.js:11:10)
    at Conf.afterUser (/usr/share/npm/lib/config/core.js:156:7)
    at Object.onceWrapper (events.js:286:20)
    at Conf.emit (events.js:198:13)
    at ConfigChain._resolve (/usr/lib/nodejs/config-chain/index.js:281:34)
    at ConfigChain.add (/usr/lib/nodejs/config-chain/index.js:259:10)
    at Conf.add (/usr/share/npm/lib/config/core.js:343:27)
    at Conf.<anonymous> (/usr/share/npm/lib/config/core.js:319:25)
    at ReadFileContext.callback (/usr/lib/nodejs/graceful-fs/graceful-fs.js:78:16)
/usr/share/npm/lib/npm.js:61
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/share/npm/lib/npm.js:61:13)
    at process.errorHandler (/usr/share/npm/lib/utils/error-handler.js:208:18)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:497:27)

### Expected Behavior

It can download the latest version of npm.

### Steps To Reproduce

1,run "sudo apt-get node.js"
2,run "sudo apt-get npm"
3,run "npm install npm@latest -g"
4,see this error

### Environment

- npm:5.8.0
- Node.js:v10.24.0
- OS Name:Debian GNU/Linux 10 (buster)
- System Model Name:Server

**Comment by ljharb** [comment]
don't install node with apt; don't install npm separately (it comes with node); npm 5 and node 10 are both EOL.

**Comment by Aaronuo** [comment]
Oh! thanks
