### ISSUE TITLE
[BUG] Crash on conflict

### ISSUE THREAD

**Issue by lahdekorpi** [npm/cli#5151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
npm ERR! Cannot read properties of null (reading 'edgesOut')

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2022-07-12T14_15_56_150Z-debug-0.log
```

```
87 verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
87 verbose stack     at [loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1359:38)
87 verbose stack     at async [buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:976:11)
87 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
87 verbose stack     at async Promise.all (index 1)
87 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
87 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:145:5)
87 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:78:5)
88 verbose cwd /tmp/crash
89 verbose Linux 5.15.0-40-generic
90 verbose node v18.4.0
91 verbose npm  v8.13.2
92 error Cannot read properties of null (reading 'edgesOut')
```

### Expected Behavior

Expected to see errors about conflicting versions.

### Steps To Reproduce

Steps to reproduce:
```bash
mkdir crash
cd crash
npm install @nestjs/platform-express@8
npm install @nestjs/core
```

### Environment

- npm: 8.13.2
- Node.js: v18.4.0
- OS Name: Ubuntu 22.04 LTS

**Comment by initbar** [comment]
Seconded. I'm seeing this same issue through `@nestjs/platform-express@^9.0.0` and `@nestjs/core@^8.0.0`.

### Environment

- npm: 8.5.0
- Node.js: v16.14.2
- OS Name: Mac 12.4

**Comment by gk-bbai** [comment]
Still happening here in 2025.  We had this issue with `@vitest/ui@^3.1.1`.
