### ISSUE TITLE
[BUG] TypeError: Cannot read properties of null (reading 'addRole')

### ISSUE THREAD

**Issue by BeapX** [npm/cli#5184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

TypeError: Cannot read properties of null (reading 'addRole')
    at Client.<anonymous> (C:\Users\Andrei\Desktop\discordbot_rank\index.js:62:28)      
    at Client.emit (node:events:527:28)
    at MessageCreateHandler.handle (C:\Users\Andrei\Desktop\discordbot_rank\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Andrei\Desktop\discordbot_rank\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\Andrei\Desktop\discordbot_rank\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Andrei\Desktop\discordbot_rank\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Andrei\Desktop\discordbot_rank\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (C:\Users\Andrei\Desktop\discordbot_rank\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (node:events:527:28)

### Expected Behavior

it should add a role whenever i level up on discord.

### Steps To Reproduce

i dont know

### Environment

- npm: 8.11.0
- Node.js: 16.16.0
- OS Name: visual studio code
- npm config:
```ini
; copy and paste output from `npm config ls` here

; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\Andrei\\AppData\\Roaming\\npm"

; "global" config from C:\Users\Andrei\AppData\Roaming\npm\etc\npmrc

registry = "http://registry.npmjs.org/"

; "user" config from C:\Users\Andrei\.npmrc

http-proxy = "http://112.115.63.236:1709"
https-proxy = "http://112.115.63.236:1709/"
strict-ssl = false

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.16.0
; npm local prefix = C:\Users\Andrei\Desktop\discordbot_rank
; npm version = 8.11.0
; cwd = C:\Users\Andrei\Desktop\discordbot_rank
; HOME = C:\Users\Andrei
; Run `npm config ls -l` to show all defaults.

**Comment by ljharb** [comment]
That error is coming from your own JS file, not from npm.
