### ISSUE TITLE
npm verb stack Error: Integrity checksum failed when using sha1

### ISSUE THREAD

**Issue by visualjeff** [npm/cli#5237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have tried with a number of versions of NPM **including the latest**.

```
npm verb stack Error: Integrity checksum failed when using sha1: wanted sha1-23hhKSU8tujq5UwvsF+HCvZnW64=sha512-Egb0oFEga6f+nSgasH3E0M405Pzn6y3/9tOVanv/DLfa1YBIgcv90L18YyWnvXkRbIM17v5Kv6IT2N6g1x5tvQ==sha512-Egb0oFEga6f+nSgasH3E0M405Pzn6y3/9tOVanv/DLfa1YBIgcv90L18YyWnvXkRbIM17v5Kv6IT2N6g1x5tvQ==sha512-Egb0oFEga6f+nSgasH3E0M405Pzn6y3/9tOVanv/DLfa1YBIgcv90L18YyWnvXkRbIM17v5Kv6IT2N6g1x5tvQ== but got sha1-23hhKSU8tujq5UwvsF+HCvZnW64=.
npm verb stack     at RegistryFetcher.manifest (/agent/_work/_tool/node/16.13.2/x64/lib/node_modules/npm/node_modules/pacote/lib/registry.js:152:35)
npm verb stack     at async Arborist.[nodeFromEdge] (/agent/_work/_tool/node/16.13.2/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1108:19)
npm verb stack     at async Arborist.[buildDepStep] (/agent/_work/_tool/node/16.13.2/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:976:11)
npm verb stack     at async Arborist.buildIdealTree (/agent/_work/_tool/node/16.13.2/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
npm verb stack     at async Promise.all (index 1)
npm verb stack     at async Arborist.reify (/agent/_work/_tool/node/16.13.2/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
npm verb stack     at async Install.exec (/agent/_work/_tool/node/16.13.2/x64/lib/node_modules/npm/lib/commands/install.js:145:5)
npm verb stack     at async module.exports (/agent/_work/_tool/node/16.13.2/x64/lib/node_modules/npm/lib/cli.js:78:5)
npm verb cwd /agent/_work/1/s
npm verb Linux 3.10.0-1160.11.1.el7.x86_64
npm verb node v16.13.2
npm verb npm  v8.13.2

```

### Expected Behavior

A completed npm install.
It's been working for months.

### Steps To Reproduce

1. Install node (Azure task) set to v16.13.2
2. npm install npm@8.13.2
3. npm install -g gatsby-cli
4. npm install --force --verbose 

### Environment

- npm: v8.13.2
- Node.js: v16.13.2
- OS Name: Linux 3.10.0-1160.11.1.el7.x86_64
- System Model Name:  ???
- npm config:
```
2022-07-30T00:13:12.5107612Z _auth = (protected) 
2022-07-30T00:13:12.5108471Z access = null 
2022-07-30T00:13:12.5109437Z all = false 
2022-07-30T00:13:12.5111189Z allow-same-version = false 
2022-07-30T00:13:12.5112335Z also = null 
2022-07-30T00:13:12.5123378Z audit = true 
2022-07-30T00:13:12.5125041Z audit-level = null 
2022-07-30T00:13:12.5126133Z auth-type = "legacy" 
2022-07-30T00:13:12.5127084Z before = null 
2022-07-30T00:13:12.5128253Z bin-links = true 
2022-07-30T00:13:12.5129099Z browser = null 
2022-07-30T00:13:12.5129772Z ca = null 
2022-07-30T00:13:12.5130502Z cache = "/home/AzDevOps/.npm" 
2022-07-30T00:13:12.5131468Z cache-max = null 
2022-07-30T00:13:12.5132227Z cache-min = 0 
2022-07-30T00:13:12.5133001Z cafile = null 
2022-07-30T00:13:12.5133587Z call = "" 
2022-07-30T00:13:12.5134186Z cert = null 
2022-07-30T00:13:12.5135087Z ci-name = "azure-pipelines" 
2022-07-30T00:13:12.5135774Z cidr = null 
2022-07-30T00:13:12.5136345Z color = true 
2022-07-30T00:13:12.5137079Z commit-hooks = true 
2022-07-30T00:13:12.5137654Z depth = null 
2022-07-30T00:13:12.5138283Z description = true 
2022-07-30T00:13:12.5138845Z dev = false 
2022-07-30T00:13:12.5139349Z diff = [] 
2022-07-30T00:13:12.5140092Z diff-dst-prefix = "b/" 
2022-07-30T00:13:12.5140946Z diff-ignore-all-space = false 
2022-07-30T00:13:12.5141745Z diff-name-only = false 
2022-07-30T00:13:12.5142531Z diff-no-prefix = false 
2022-07-30T00:13:12.5143480Z diff-src-prefix = "a/" 
2022-07-30T00:13:12.5144258Z diff-text = false 
2022-07-30T00:13:12.5145023Z diff-unified = 3 
2022-07-30T00:13:12.5145682Z dry-run = false 
2022-07-30T00:13:12.5146187Z editor = "vi" 
2022-07-30T00:13:12.5146848Z engine-strict = false 
2022-07-30T00:13:12.5147507Z fetch-retries = 2 
2022-07-30T00:13:12.5148185Z fetch-retry-factor = 10 
2022-07-30T00:13:12.5148900Z fetch-retry-maxtimeout = 60000 
2022-07-30T00:13:12.5149651Z fetch-retry-mintimeout = 10000 
2022-07-30T00:13:12.5150371Z fetch-timeout = 300000 
2022-07-30T00:13:12.5150917Z force = false 
2022-07-30T00:13:12.5151587Z foreground-scripts = false 
2022-07-30T00:13:12.5152310Z format-package-lock = true 
2022-07-30T00:13:12.5153045Z fund = true 
2022-07-30T00:13:12.5153550Z git = "git" 
2022-07-30T00:13:12.5154233Z git-tag-version = true 
2022-07-30T00:13:12.5154764Z global = false 
2022-07-30T00:13:12.5155443Z global-style = false 
2022-07-30T00:13:12.5156078Z globalconfig = "/agent/_work/_tool/node/16.13.2/x64/etc/npmrc" 
2022-07-30T00:13:12.5156729Z heading = "npm" 
2022-07-30T00:13:12.5157448Z https-proxy = null 
2022-07-30T00:13:12.5158119Z if-present = false 
2022-07-30T00:13:12.5158794Z ignore-scripts = false 
2022-07-30T00:13:12.5159354Z include = [] 
2022-07-30T00:13:12.5160035Z include-staged = false 
2022-07-30T00:13:12.5160754Z include-workspace-root = false 
2022-07-30T00:13:12.5161464Z init-author-email = "" 
2022-07-30T00:13:12.5162149Z init-author-name = "" 
2022-07-30T00:13:12.5162994Z init-author-url = "" 
2022-07-30T00:13:12.5163689Z init-license = "ISC" 
2022-07-30T00:13:12.5164451Z init-module = "/home/AzDevOps/.npm-init.js" 
2022-07-30T00:13:12.5165187Z init-version = "1.0.0" 
2022-07-30T00:13:12.5165746Z init.author.email = "" 
2022-07-30T00:13:12.5166296Z init.author.name = "" 
2022-07-30T00:13:12.5166866Z init.author.url = "" 
2022-07-30T00:13:12.5167429Z init.license = "ISC" 
2022-07-30T00:13:12.5168252Z init.module = "/home/AzDevOps/.npm-init.js" 
2022-07-30T00:13:12.5168892Z init.version = "1.0.0" 
2022-07-30T00:13:12.5169625Z install-links = false 
2022-07-30T00:13:12.5170644Z json = false 
2022-07-30T00:13:12.5171174Z key = null 
2022-07-30T00:13:12.5171912Z legacy-bundling = false 
2022-07-30T00:13:12.5172870Z legacy-peer-deps = false 
2022-07-30T00:13:12.5173483Z link = false 
2022-07-30T00:13:12.5174229Z local-address = null 
2022-07-30T00:13:12.5174828Z location = "user" 
2022-07-30T00:13:12.5175572Z lockfile-version = null 
2022-07-30T00:13:12.5176170Z loglevel = "notice" 
2022-07-30T00:13:12.5176900Z logs-dir = null 
2022-07-30T00:13:12.5177624Z logs-max = 10 
2022-07-30T00:13:12.5178245Z ; long = false ; overridden by cli
2022-07-30T00:13:12.5178868Z maxsockets = 15 
2022-07-30T00:13:12.5179455Z message = "%s" 
2022-07-30T00:13:12.5180302Z metrics-registry = "https://registry.npmjs.org/" 
2022-07-30T00:13:12.5181146Z node-options = null 
2022-07-30T00:13:12.5181944Z node-version = "v16.13.2" 
2022-07-30T00:13:12.5182562Z noproxy = [""] 
2022-07-30T00:13:12.5183473Z npm-version = "8.13.2" 
2022-07-30T00:13:12.5184046Z offline = false 
2022-07-30T00:13:12.5184566Z omit = [] 
2022-07-30T00:13:12.5185305Z omit-lockfile-registry-resolved = false 
2022-07-30T00:13:12.5185889Z only = null 
2022-07-30T00:13:12.5186420Z optional = null 
2022-07-30T00:13:12.5186944Z otp = null 
2022-07-30T00:13:12.5187668Z pack-destination = "." 
2022-07-30T00:13:12.5188294Z package = [] 
2022-07-30T00:13:12.5189043Z package-lock = true 
2022-07-30T00:13:12.5189875Z package-lock-only = false 
2022-07-30T00:13:12.5190463Z parseable = false 
2022-07-30T00:13:12.5191169Z prefer-offline = false 
2022-07-30T00:13:12.5191936Z prefer-online = false 
2022-07-30T00:13:12.5192603Z prefix = "/agent/_work/_tool/node/16.13.2/x64" 
2022-07-30T00:13:12.5193513Z preid = "" 
2022-07-30T00:13:12.5194004Z production = null 
2022-07-30T00:13:12.5194521Z progress = false 
2022-07-30T00:13:12.5195073Z proxy = null 
2022-07-30T00:13:12.5195948Z read-only = false 
2022-07-30T00:13:12.5196762Z rebuild-bundle = true 
2022-07-30T00:13:12.5197456Z registry = "https://registry.npmjs.org/" 
2022-07-30T00:13:12.5198130Z save = true 
2022-07-30T00:13:12.5199004Z save-bundle = false 
2022-07-30T00:13:12.5199848Z save-dev = false 
2022-07-30T00:13:12.5200688Z save-exact = false 
2022-07-30T00:13:12.5201497Z save-optional = false 
2022-07-30T00:13:12.5202327Z save-peer = false 
2022-07-30T00:13:12.5203446Z save-prefix = "^" 
2022-07-30T00:13:12.5204273Z save-prod = false 
2022-07-30T00:13:12.5204887Z scope = "" 
2022-07-30T00:13:12.5205720Z script-shell = null 
2022-07-30T00:13:12.5206317Z searchexclude = "" 
2022-07-30T00:13:12.5206958Z searchlimit = 20 
2022-07-30T00:13:12.5207581Z searchopts = "" 
2022-07-30T00:13:12.5208233Z searchstaleness = 900 
2022-07-30T00:13:12.5208872Z shell = "/bin/bash" 
2022-07-30T00:13:12.5209437Z shrinkwrap = true 
2022-07-30T00:13:12.5210419Z sign-git-commit = false 
2022-07-30T00:13:12.5211295Z sign-git-tag = false 
2022-07-30T00:13:12.5212205Z sso-poll-frequency = 500 
2022-07-30T00:13:12.5213336Z sso-type = "oauth" 
2022-07-30T00:13:12.5214197Z strict-peer-deps = false 
2022-07-30T00:13:12.5215074Z strict-ssl = true 
2022-07-30T00:13:12.5215732Z tag = "latest" 
2022-07-30T00:13:12.5216521Z tag-version-prefix = "v" 
2022-07-30T00:13:12.5217141Z timing = false 
2022-07-30T00:13:12.5217764Z tmp = "/tmp" 
2022-07-30T00:13:12.5218385Z umask = 0 
2022-07-30T00:13:12.5219013Z unicode = true 
2022-07-30T00:13:12.5219929Z update-notifier = true 
2022-07-30T00:13:12.5220624Z usage = false 
2022-07-30T00:13:12.5221781Z user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} workspaces/{workspaces} {ci}" 
2022-07-30T00:13:12.5222902Z userconfig = "/home/AzDevOps/.npmrc" 
2022-07-30T00:13:12.5223547Z version = false 
2022-07-30T00:13:12.5224231Z versions = false 
2022-07-30T00:13:12.5224940Z viewer = "man" 
2022-07-30T00:13:12.5225636Z which = null 
2022-07-30T00:13:12.5226248Z workspace = [] 
2022-07-30T00:13:12.5226840Z workspaces = null 
2022-07-30T00:13:12.5227790Z workspaces-update = true 
2022-07-30T00:13:12.5228403Z yes = null 
```

**Comment by visualjeff** [comment]
When the dependencies are installed they are pulled from an ADO Artifact feed.

**Comment by visualjeff** [comment]
The project being built doesn't currently have a package-lock.json

**Comment by visualjeff** [comment]
Off-shore team checked in a yarn.lock file and removed the package-lock.json and somehow that caused a problem.  Even though the build was using NPM commands.  Not sure why?

**Solutions was:**
In a ADO build script task remove node_modules and yarn.lock and the build proceeded forward to complete.

I have since communicated to the off-shore team informing them not to use yarn and to update their .gitignore file.
