### ISSUE TITLE
[BUG] registry.npmjs.org times out / 503 on unpublish of a private package

### ISSUE THREAD

**Issue by lxe** [npm/cli#5398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have a private/prefixed package that has over 4K versions (because reasons) published to `registry.npmjs.org` 

Attempting to unpublish a version yields a timeout and an eventual 503 from the registry server (see below).

Attempting to publish more versions also yields an error.

I think our package caused the npm registry to somehow misbehave. 

Log redacted to remove package name:

```
❯ DEBUG=* ~/cli/bin/npm-cli.js unpublish $PRIVATE_PACKAGE@VERSION --verbose

npm verb cli /Users/aleksey/.asdf/installs/nodejs/16.13.2/bin/node /Users/aleksey/cli/bin/npm-cli.js
npm info using npm@8.18.0
npm info using node@v16.13.2
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/Users/aleksey/cli/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/aleksey/go/src/github.com/opendoor-labs/code/js/.npmrc Completed in 0ms
npm timing config:load:project Completed in 2ms
npm timing config:load:file:/Users/aleksey/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/Users/aleksey/.asdf/installs/nodejs/16.13.2/.npm/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 7ms
npm timing npm:load:configload Completed in 7ms
npm timing npm:load:mkdirpcache Completed in 0ms
npm timing npm:load:mkdirplogs Completed in 1ms
npm verb title npm unpublish $PRIVATE_PACKAGE@VERSION
npm verb argv "unpublish" "$PRIVATE_PACKAGE@VERSION" "--loglevel" "verbose"
npm timing npm:load:setTitle Completed in 5ms
npm timing config:load:flatten Completed in 1ms
npm timing npm:load:display Completed in 4ms
npm verb logfile logs-max:10 dir:/Users/aleksey/.npm/_logs
npm verb logfile /Users/aleksey/.npm/_logs/2022-08-25T20_44_37_739Z-debug-0.log
npm timing npm:load:logFile Completed in 2ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 19ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] create, timeout 300001ms +0ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 1, finished: 1) free +9s
npm http fetch GET 200 https://registry.npmjs.org/$PACKAGE?write=true 9231ms (cache updated)
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] reset timeout to 300001ms +571msms (cache updated)
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 2, finished: 1) reuse on addRequest, timeout 300001ms +1ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 2, finished: 2) free +8s (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/$PACKAGE?write=true 8112ms (cache updated)
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] reset timeout to 300001ms +1s
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 3, finished: 2) reuse on addRequest, timeout 300001ms +0ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 3, finished: 3) free +1m (cache updated)
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] reset timeout to 300001ms +10s12ms (cache updated)
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 4, finished: 3) reuse on addRequest, timeout 300001ms +1ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 4, finished: 4) free +1m (cache updated)
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 4, finished: 4) timeout after 15000ms, listeners 2, defaultTimeoutListenerCount 3, hasHttpRequest false, HttpRequest timeoutListenerCount 0 +15s
  agentkeepalive timeout listeners: onTimeout, onTimeout +0ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] is free, destroy quietly +1ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 4, finished: 4) close, isError: false +1ms
  agentkeepalive sock[1#registry.npmjs.org:443::::::::true:::::::::::::] create, timeout 300001ms +45s112ms (cache updated)
  agentkeepalive sock[1#registry.npmjs.org:443::::::::true:::::::::::::](requests: 1, finished: 1) free +59s(cache updated)
npm http fetch PUT 503 https://registry.npmjs.org/$PACKAGE/-rev/3523-c22f54df436f6fa2f4925dc8c0784dea 253638ms attempt #3
npm timing command:unpublish Completed in 272027ms
npm verb stack HttpErrorGeneral: 503 Service Unavailable - PUT https://registry.npmjs.org/$PACKAGE/-rev/3523-c22f54df436f6fa2f4925dc8c0784dea - Service Unavailable
npm verb stack     at /Users/aleksey/cli/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm verb stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb stack     at async unpublish (/Users/aleksey/cli/workspaces/libnpmpublish/lib/unpublish.js:90:7)
npm verb stack     at async otplease (/Users/aleksey/cli/lib/utils/otplease.js:3:12)
npm verb stack     at async Unpublish.exec (/Users/aleksey/cli/lib/commands/unpublish.js:133:7)
npm verb stack     at async module.exports (/Users/aleksey/cli/lib/cli.js:78:5)
npm verb statusCode 503
npm verb pkgid $PRIVATE_PACKAGE@VERSION
npm verb cwd /Users/aleksey/go/src/github.com/opendoor-labs/code/js
npm verb Darwin 21.6.0
npm verb node v16.13.2
npm verb npm  v8.18.0
npm ERR! code E503
npm ERR! 503 Service Unavailable - PUT https://registry.npmjs.org/$PACKAGE/-rev/3523-c22f54df436f6fa2f4925dc8c0784dea - Service Unavailable
npm verb exit 1
npm timing npm Completed in 272056ms
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aleksey/.npm/_logs/2022-08-25T20_44_37_739Z-debug-0.log
```
  
  

### Expected Behavior

The version should be unpublished.

### Steps To Reproduce

See Above

### Environment

```
npm info using npm@8.18.0
npm info using node@v16.13.2
```
Darwin

**Comment by MylesBorins** [comment]
Hey @lxe this kind of ticket should be submitted to support via npmjs.com/support, repository is specifically for managing the CLI not the registry.

It looks like we have something internal tracking this already so I'm going to close this. Support will reach out to you directly through any existing tickets
