### ISSUE TITLE
[BUG] npm publish with unexisted tag by custom scripts may causing ETARGET: No matching version found

### ISSUE THREAD

**Issue by modten** [npm/cli#5531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Runing these command with following `package.json` and scripts

```sh
npm publish --tag beta --dry-run
or
npm publish --tag beta12345 --dry-run
```

### package.json
```json
{
  "name": "test-npx",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "install:pnpm": "npx --verbose pnpm install",
    "install:webpack": "npx --verbose webpack -v",
    "prepublishOnly": "./install.sh"
  }
}
```

### install.sh
```sh
npm run install:pnpm
```

### Expected Behavior

Command should exit with no errors

But received ETARGET

```
npm verb stack pnpm: No matching version found for pnpm@beta12345.
npm verb stack     at module.exports (/Users/shinn/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm verb stack     at RegistryFetcher.manifest (/Users/shinn/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
npm verb stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb stack     at async getManifest (/Users/shinn/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:32:22)
npm verb stack     at async missingFromTree (/Users/shinn/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:60:22)
npm verb stack     at async /Users/shinn/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:155:32
npm verb stack     at async Promise.all (index 0)
npm verb stack     at async exec (/Users/shinn/.nvm/versions/node/v16.14.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:153:3)
npm verb stack     at async module.exports (/Users/shinn/.nvm/versions/node/v16.14.0/lib/node_modules/npm/lib/cli.js:79:5)
npm verb cwd /Users/shinn/TmpProjects/test-npx
npm verb Darwin 21.6.0
npm verb node v16.14.0
npm verb npm  v8.19.2
npm ERR! code ETARGET
npm ERR! notarget No matching version found for pnpm@beta12345.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm verb exit 1
npm timing npm Completed in 496ms
npm verb code 1
```

### Steps To Reproduce

Run

```sh
npm publish --tag beta --dry-run
or
npm publish --tag beta12345 --dry-run
```

### Environment

- npm: 8.19.2
- Node.js: 16.14.0
- OS Name: macOS Monterey 12.5
- System Model Name:
- npm config:

**Comment by modten** [comment]
`flatOptions.defaultTag` will be `beta` in the child process, so npm cannot found `pnpm@beta`

https://github.com/npm/cli/blob/e5761b9adafe8607ad68baa9599ad4eb228bc6be/lib/commands/exec.js#L60

**Comment by lukekarrys** [comment]
Can you try `npm@9.0.1`? I'm able to reproduce on `8.19.2` but it works for me on `9.0.1`.

**Comment by modten** [comment]
9.0.1 works, tks.
