### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by NitinIsFit** [npm/cli#5658]
```js
~ $ npm install colors
npm ERR! code EJSONPARSE
npm ERR! path /data/data/com.termux/files/home/package.json
npm ERR! JSON.parse Unexpected end of JSON input while parsing "\n"
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-10-09T09_56_32_390Z-debug-0.log
```

log file
```js
0 verbose cli /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/bin/npm
1 info using npm@8.19.2
2 info using node@v18.7.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 8ms
5 timing config:load:file:/data/data/com.termux/files/usr/lib/node_modules/npm/npmrc Completed in 5ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 8ms
8 timing config:load:env Completed in 2ms
9 timing config:load:project Completed in 8ms
10 timing config:load:file:/data/data/com.termux/files/home/.npmrc Completed in 8ms
11 timing config:load:user Completed in 8ms
12 timing config:load:file:/data/data/com.termux/files/usr/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 2ms
14 timing config:load:validate Completed in 2ms
15 timing config:load:credentials Completed in 4ms
16 timing config:load:setEnvs Completed in 3ms
17 timing config:load Completed in 53ms
18 timing npm:load:configload Completed in 54ms
19 timing npm:load:mkdirpcache Completed in 4ms
20 timing npm:load:mkdirplogs Completed in 2ms
21 verbose title npm install colors
22 verbose argv "install" "colors"
23 timing npm:load:setTitle Completed in 4ms
24 timing config:load:flatten Completed in 11ms
25 timing npm:load:display Completed in 17ms
26 verbose logfile logs-max:10 dir:/data/data/com.termux/files/home/.npm/_logs
27 verbose logfile /data/data/com.termux/files/home/.npm/_logs/2022-10-09T09_56_32_390Z-debug-0.log
28 timing npm:load:logFile Completed in 48ms
29 timing npm:load:timers Completed in 1ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 136ms
32 timing arborist:ctor Completed in 3ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing idealTree Completed in 5ms
36 timing command:install Completed in 59ms
37 verbose stack JSONParseError: Unexpected end of JSON input while parsing "\n"
37 verbose stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/read-package-json-fast/index.js:11:61
37 verbose stack     at async Arborist.buildIdealTree (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:208:7)
37 verbose stack     at async Promise.all (index 1)
37 verbose stack     at async Arborist.reify (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
37 verbose stack     at async Install.exec (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/commands/install.js:145:5)
37 verbose stack     at async module.exports (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/cli.js:78:5)
38 verbose cwd /data/data/com.termux/files/home
39 verbose Linux 4.9.186-perf-g131f907
40 verbose node v18.7.0
41 verbose npm  v8.19.2
42 error code EJSONPARSE
43 error path /data/data/com.termux/files/home/package.json
44 error JSON.parse Unexpected end of JSON input while parsing "\n"
45 error JSON.parse Failed to parse JSON data.
45 error JSON.parse Note: package.json must be actual JSON, not just JavaScript.
46 verbose exit 1
47 timing npm Completed in 538ms
48 verbose unfinished npm timer reify 1665309392855
49 verbose unfinished npm timer reify:loadTrees 1665309392893
50 verbose unfinished npm timer idealTree:init 1665309392897
51 verbose code 1
52 error A complete log of this run can be found in:
52 error     /data/data/com.termux/files/home/.npm/_logs/2022-10-09T09_56_32_390Z-debug-0.log
```

**Comment by fritzy** [comment]
It sounds like your project's `package.json` is formatted incorrectly. It needs to be a proper JSON file.
See https://docs.npmjs.com/cli/v8/configuring-npm/package-json

In the future, please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
