### ISSUE TITLE
[BUG] Installing globally package from https github fails

### ISSUE THREAD

**Issue by jairo-bc** [npm/cli#5699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Installing globally package directly from github (by https) cause an error, stating that it is unable to find a package. 
Example: 
`npm i -g https://github.com/sass/node-sass`

Note: installing w/o (-g) option works well.
We are using node-sass fork https://github.com/bigcommerce-labs/node-sass, which has the same kind of error (unable to find package), but you can try with the latest node-sass as well. I believe it's related to _install_ step in` package.json`

Errors:
```
➜  test npm i -g https://github.com/sass/node-sass
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /Users/jairobc/.nvm/versions/node/v14.20.1/bin/node /Users/jairobc/.nvm/versions/node/v14.20.1/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/jairobc/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/jairobc/.npm/_cacache/tmp/git-cloneYMv8pa
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c -- node scripts/install.js
npm ERR! npm ERR! internal/modules/cjs/loader.js:905
npm ERR! npm ERR!   throw err;
npm ERR! npm ERR!   ^
npm ERR! npm ERR!
npm ERR! npm ERR! Error: Cannot find module 'make-fetch-happen'
npm ERR! npm ERR! Require stack:
npm ERR! npm ERR! - /Users/jairobc/.npm/_cacache/tmp/git-cloneYMv8pa/scripts/install.js
npm ERR! npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
npm ERR! npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
npm ERR! npm ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
npm ERR! npm ERR!     at require (internal/modules/cjs/helpers.js:101:18)
npm ERR! npm ERR!     at Object.<anonymous> (/Users/jairobc/.npm/_cacache/tmp/git-cloneYMv8pa/scripts/install.js:8:11)
npm ERR! npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR! npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR! npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
npm ERR! npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
npm ERR! npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR! npm ERR!   requireStack: [
npm ERR! npm ERR!     '/Users/jairobc/.npm/_cacache/tmp/git-cloneYMv8pa/scripts/install.js'
npm ERR! npm ERR!   ]
npm ERR! npm ERR! }
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/jairobc/.npm/_logs/2022-10-14T17_29_16_969Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jairobc/.npm/_logs/2022-10-14T17_29_08_473Z-debug-0.log
```

### Expected Behavior

Able to install package globally from github. 

### Steps To Reproduce

1. In this environment Node 14 + npm 8
2. With this config...
3. Run 'npm i -g https://github.com/sass/node-sass'
4. See error` Cannot find module 'make-fetch-happen'`

### Environment

- npm: 8.19.2
- Node.js: 14.20.1
- OS Name: macOS 12.5.1
- System Model Name:  Macbook Pro
- npm config:
```ini
; "user" config from /Users/jairobc/.npmrc

@bigcommerce-labs:registry = "https://npm.pkg.github.com/"
//npm.pkg.github.com/:_authToken = (protected)
//registry.npmjs.org/:_authToken = (protected)

; node bin location = /Users/jairobc/.nvm/versions/node/v14.20.1/bin/node
; node version = v14.20.1
; npm local prefix = /Users/jairobc/test
; npm version = 8.19.2
; cwd = /Users/jairobc/test
; HOME = /Users/jairobc
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
Many packages simply aren't installable from a git repo, because they have a build process. Git is for development, not consumption, and so it's best to install packages from a registry. For your fork, that means you'd publish it (ideally under a scope).

**Comment by wraithgar** [comment]
This is a known issue w/ git installs not running prepare. https://github.com/npm/cli/issues/4148
