### ISSUE TITLE
[BUG]  Cannot read properties of undefined (reading 'description')

### ISSUE THREAD

**Issue by vrubezhny** [npm/cli#5961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

For some dependencies in a project's package.json a TypeError occurs when `npm ll -a` is executed.
For example,, if package.json contains the following dependenciy:
```
{
  "dependencies": {
    "ws": "8.11.0"
  }
}
```
the following error occurs when executing `npm ll -a`:
```
$ npm --version
8.19.2
$ npm ll -a
npm ERR! Cannot read properties of undefined (reading 'description')

npm ERR! A complete log of this run can be found in:
npm ERR!   ~`.npm/_logs/2022-12-13T20_36_19_543Z-debug-0.log
```
while the log file contains the following stacktrace:
```
9 verbose stack TypeError: Cannot read properties of undefined (reading 'description')
39 verbose stack     at getHumanOutputItem (~/.nvm/versions/node/v18.12.1/lib/node_modules/npm/lib/commands/ls.js:339:35)
39 verbose stack     at visit (~/.nvm/versions/node/v18.12.1/lib/node_modules/npm/lib/commands/ls.js:160:15)
39 verbose stack     at visitNode (~/.nvm/versions/node/v18.12.1/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:37:25)
39 verbose stack     at next (~/.nvm/versions/node/v18.12.1/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:23:19)
39 verbose stack     at ~/.nvm/versions/node/v18.12.1/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:25:31
39 verbose stack     at async LL.exec (~/.nvm/versions/node/v18.12.1/lib/node_modules/npm/lib/commands/ls.js:122:20)
39 verbose stack     at async module.exports (~/.nvm/versions/node/v18.12.1/lib/node_modules/npm/lib/cli.js:78:5)
```

### Expected Behavior

Full dependency tree to be printed for a project

### Steps To Reproduce

1. Tested on Linux with NPM v.8.19.2
2. With a project that has a dependency like the following:
```
{
  "dependencies": {
    "ws": "8.11.0"
  }
}
```
3. Run 'npm ll -a'
4. See error...

### Environment

- npm: 8.19.2
- Node.js: v18.12.1
- OS Name:Fedora Linux 36 (Workstation Edition)

**Comment by pniederlag** [comment]
this is a quite annoying bug that seems to affect almost any nodejs/npm version

node 15.14.0 npm 7.7.6
node 16.20.0 npm 8.19.4
node 18.16.0 npm 9.5.1
node 20.5.1   npm 9.8.0

anything we can do to get this fixed? #5962 seems good to me

**Comment by Chardrazle** [comment]
Still present on v11.  E.g. (with package as demonstrated by OP):
```
$ node --version
v20.17.0
$ npm --version
11.0.0
$ npm i ws
$ npm ls --all --long
npm error Cannot read properties of undefined (reading 'description')
```

**Comment by tomchiverton** [comment]
npm ls -a seems to be a good workaround. IDK what ll vs ls means other than one working and one not

**Comment by NBardelot** [comment]
Still present in npm v11.11:

```bash
npm list --global --depth=Infinity foo # technically works but does not recurse correctly into submodules
npm list --global --depth=Infinity --long foo # throws the error
npm list --global --depth=Infinity --json foo # technically works but does not recurse correctly into submodules
npm list --global --depth=Infinity --long --json foo # technically works but does not recurse correctly into submodules
```
