### ISSUE TITLE
[BUG] NPM error when installing package (forever)

### ISSUE THREAD

**Issue by ChrisDTrtl** [npm/cli#608]
# What / Why
Getting an NPM error when I attempt to install the 'forever' package:
`npm install forever` or `npm install forever -g`
npm-debug.log file is attached. I'm afraid I likely don't know enough to supply more information with prompting. 

```
ubuntu@ip-172-31-30-230:~/reportingnode/Am
[npm-debug.log](https://github.com/npm/cli/files/3972975/npm-debug.log)
zReportingNode$ npm install forever
npm ERR! Linux 4.15.0-1032-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "forever"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/reportingnode/AmzReportingNode/npm-debug.log
```

## When
  * First experienced today, have not updated NPM recently. 

## Where
* On ubuntu on AWS EC2 instance
### Current Behavior
* Package does not correctly install

### Steps to Reproduce
* Attempt to install package.

### Expected Behavior
* Package should be installed

**Comment by cvPriyanka** [comment]
Hi,

Facing the same issue. While trying to do npm install
Please find the log below

build	18-Dec-2019 12:08:34	[ERROR] npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! Linux 3.10.0-327.18.2.el7.x86_64
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! argv "../node" "../node/node_modules/npm/bin/npm-cli.js" "install"
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! node v5.0.0
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! npm  v3.5.0
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! code EMISSINGARG
build	18-Dec-2019 12:08:36	[ERROR] 
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror Error: Missing required argument #1
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     at andLogAndFinish (../node/node_modules/npm/lib/fetch-package-metadata.js:31:3)
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     at fetchPackageMetadata (../node/node_modules/npm/lib/fetch-package-metadata.js:51:22)
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     at resolveWithNewModule (../node/node_modules/npm/lib/install/deps.js:456:12)
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     at ../node/node_modules/npm/lib/install/deps.js:457:7
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     at ..node/node_modules/npm/node_modules/iferr/index.js:13:50
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     at ../node/node_modules/npm/lib/fetch-package-metadata.js:37:12
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     at addRequestedAndFinish (../node/node_modules/npm/lib/fetch-package-metadata.js:82:5)
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     at returnAndAddMetadata (../node/node_modules/npm/lib/fetch-package-metadata.js:117:7)
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     at pickVersionFromRegistryDocument (../node/node_modules/npm/lib/fetch-package-metadata.js:134:20)
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     at ../node/node_modules/npm/node_modules/iferr/index.js:13:50
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror This is an error with npm itself. Please report this error at:
build	18-Dec-2019 12:08:36	[ERROR] npm ERR! typeerror     <http://github.com/npm/npm/issues>

**Comment by bbroereES** [comment]
Same issue; Node v5.12.0, npm v3.8.6

**Comment by ljharb** [comment]
@bbroereES and if you upgrade npm to the latest v6?

**Comment by bbroereES** [comment]
@ljharb Unfortunately not an option in this case :)

**Comment by ljharb** [comment]
@bbroereES given the security issues in older npm versions (and node 5, which has been EOL for a very long time), i'd strongly suggest you find a way to make it an option :-)

**Comment by bbroereES** [comment]
@ljharb That is what I am working on, but in the meantime I just want to be able to keep my (private) platform running ;)

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
