### ISSUE TITLE
[BUG] npm publish get 400 Bad Request without any useful information

### ISSUE THREAD

**Issue by guoyunhe** [npm/cli#6090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Errors:

```
npm ERR! code E400
npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/@guoyunhe%2fdownload - Bad Request

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guo/.npm/_logs/2023-01-26T08_50_54_429Z-debug-0.log
```

Logs:

```
0 verbose cli /usr/bin/node18 /usr/bin/npm18
1 info using npm@8.19.3
2 info using node@v18.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib64/node_modules/npm18/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/guo/git/download2/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/guo/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 6ms
19 timing npm:load:configload Completed in 6ms
20 timing npm:load:mkdirpcache Completed in 2ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm publish
23 verbose argv "publish" "--access" "public"
24 timing npm:load:setTitle Completed in 0ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 3ms
27 verbose logfile logs-max:10 dir:/home/guo/.npm/_logs
28 verbose logfile /home/guo/.npm/_logs/2023-01-26T08_50_54_429Z-debug-0.log
29 timing npm:load:logFile Completed in 2ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 13ms
33 verbose publish [ '.' ]
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 notice
37 notice 📦  @guoyunhe/download@1.0.0
38 notice === Tarball Contents ===
39 notice 64B    CHANGELOG.md       
39 notice 35.1kB LICENSE            
39 notice 786B   README.md          
39 notice 3.2kB  dist/cjs/index.js  
39 notice 495B   dist/dts/index.d.ts
39 notice 1.4kB  dist/esm/index.js  
39 notice 1.4kB  package.json       
40 notice === Tarball Details ===
41 notice name:          @guoyunhe/download                      
41 notice version:       1.0.0                                   
41 notice filename:      @guoyunhe/download-1.0.0.tgz            
41 notice package size:  14.7 kB                                 
41 notice unpacked size: 42.5 kB                                 
41 notice shasum:        a84dbc1209c524eca93f044f36d7cb8c39da2749
41 notice integrity:     sha512-wyNLFV3T9QBpF[...]eeyuSiAdIFtmg==
41 notice total files:   7                                       
42 notice
43 notice Publishing to https://registry.npmjs.org/
44 http fetch PUT 401 https://registry.npmjs.org/@guoyunhe%2fdownload 1422ms
45 http fetch PUT 400 https://registry.npmjs.org/@guoyunhe%2fdownload 766ms
46 timing command:publish Completed in 13192ms
47 verbose stack HttpErrorGeneral: 400 Bad Request - PUT https://registry.npmjs.org/@guoyunhe%2fdownload - Bad Request
47 verbose stack     at /usr/lib64/node_modules/npm18/node_modules/npm-registry-fetch/lib/check-response.js:95:15
47 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
47 verbose stack     at async publish (/usr/lib64/node_modules/npm18/node_modules/libnpmpublish/lib/publish.js:43:12)
47 verbose stack     at async otplease (/usr/lib64/node_modules/npm18/lib/utils/otplease.js:30:14)
47 verbose stack     at async Publish.exec (/usr/lib64/node_modules/npm18/lib/commands/publish.js:120:7)
47 verbose stack     at async module.exports (/usr/lib64/node_modules/npm18/lib/cli.js:78:5)
48 verbose statusCode 400
49 verbose pkgid @guoyunhe/download@1.0.0
50 verbose cwd /home/guo/git/download2
51 verbose Linux 6.1.7-1-default
52 verbose node v18.13.0
53 verbose npm  v8.19.3
54 error code E400
55 error 400 Bad Request - PUT https://registry.npmjs.org/@guoyunhe%2fdownload - Bad Request
56 verbose exit 1
57 timing npm Completed in 13216ms
58 verbose code 1
59 error A complete log of this run can be found in:
59 error     /home/guo/.npm/_logs/2023-01-26T08_50_54_429Z-debug-0.log
```

### Expected Behavior

Should give some useful tips...

### Steps To Reproduce

1. Clone https://github.com/guoyunhe/download
2. npm install
3. npm run build
4. npm publish --access=public
5. See errors...

### Environment

- npm: 8.19.3
- Node.js: 18.13.0
- OS Name: openSUSE Tumbleweed
- System Model Name: DIY PC
- npm config:
```ini
; "user" config from /home/guo/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /usr/bin/node18
; node version = v18.13.0
; npm local prefix = /home/guo/git/download2
; npm version = 8.19.3
; cwd = /home/guo/git/download2
; HOME = /home/guo
; Run `npm config ls -l` to show all defaults.
```

**Comment by guoyunhe** [comment]
I renamed my package from `@guoyunhe/download` to `@guoyunhe/downloader`. And then successfully published.

Is "download" a forbidden word? Why? Make no sense for me.

Still, npm should give some helpful error messages. Otherwise, users can only guessing what the forbidden words are...

**Comment by wraithgar** [comment]
npm can only respond w/ the message that the registry returns.  registry support issues can be filed at https://www.npmjs.com/support
