### ISSUE TITLE
Surprising behavior using @npmcli/config

### ISSUE THREAD

**Issue by niktekusho** [npm/cli#6120]
Hello!

I'm trying to use `@npmcli/config` to programmatically set up some npm `init-` properties for the current user (so the relevant file is `~/.npmrc`).
I'm running into weird behavior, which I don't know if it's to be expected or not.

```
node -v
v14.21.2
npm -v
6.14.17
```

This is an example file (`index.js`):

```js
const Config = require('@npmcli/config');
const {homedir} = require('os');

const red = '\u001B[31m';
const reset = '\u001B[0m';

async function saveConfig() {
	const npmConfig = new Config({
		definitions: Config.typeDefs,
		npmPath: homedir()
	});

	await npmConfig.load();

	const registry = npmConfig.find('registry');
	
	if (registry == null) {
		console.log(`Function will throw ${red}TypeError [ERR_INVALID_URL]: Invalid URL: undefined${reset} at save('user')`);
	} else {
		console.log('Function will run correctly');
	}

	const author = `cool user ${Math.ceil(Math.random()*1000)}`;
	console.log(`Setting init author = ${author}`);

	npmConfig.set('init-author-name', author, 'user');

	await npmConfig.save('user');
};

saveConfig()
	.then(() => console.log('Success!'))
	.catch(console.error);

```

Included `package.json`:

```json
{
  "scripts": {
    "test": "node index.js"
  },
  "dependencies": {
    "@npmcli/config": "^6.1.2"
  }
}
```

If I run the `index.js` file via `npm test` I get the expected output:

```
$ npm test

> @ test /<redacted>/npm-config-issue
> node index.js

Function will run correctly
Setting init author = cool user 400
Success!
```

`~/.npmrc` file is also correctly updated.

If I run the `index.js` file via `node index.js` (apparently the exact same command), I get surprising output:

```
$ node index.js 
Function will throw TypeError [ERR_INVALID_URL]: Invalid URL: undefined at save('user')
Setting init author = cool user 955
TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at new NodeError (internal/errors.js:322:7)
    at onParseError (internal/url.js:270:9)
    at new URL (internal/url.js:346:5)
    at module.exports (/<redacted>/npm-config-issue/node_modules/@npmcli/config/lib/nerf-dart.js:13:18)
    at Config.save (/<redacted>/npm-config-issue/node_modules/@npmcli/config/lib/index.js:725:22)
    at saveConfig (/<redacted>/npm-config-issue/index.js:28:18) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
```

The `registry` property seems to be inherited from the environment `npmConfig('registry') === 'env'` when executed via `npm test`). Does this mean the `registry` needs to be configured manually when not using the `npm` cli?

**Comment by niktekusho** [comment]
I found a workaround to make my function work correctly even without npm CLI's environment (not proud of it in the slightest :sweat_smile: )

```js
const {homedir} = require('os');
const {join} = require('path');
const Config = require('@npmcli/config');

const red = '\u001B[31m';
const yellow = '\u001B[33m';
const reset = '\u001B[0m';

async function saveConfig() {
	const env = process.env;

	const isRunningThroughNpm = Object.keys(env)
		.findIndex(key => key.startsWith('npm')) !== -1;
	if (isRunningThroughNpm) {
		console.log('Function seems to be running through npm CLI');
	} else {
		console.log('Function seems to be running without npm CLI');
		console.log(`${yellow}Will inject minimal required properties to make the function work${reset}`);
		// Could use ??= syntax with Node >= 15...
		
		// Prevents TypeError [ERR_INVALID_URL]: Invalid URL: undefined
		// at new NodeError (internal/errors.js:322:7)
		// at onParseError (internal/url.js:270:9)
		// at new URL (internal/url.js:346:5)
		// at module.exports (/<redacted>/npm-config-example/node_modules/@npmcli/config/lib/nerf-dart.js:13:18)
		if (!env['npm_config_registry']) {
			env['npm_config_registry'] = 'https://registry.npmjs.org/';
		}
		
		// Prevents TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
		// at new NodeError (internal/errors.js:322:7)
		// at validateString (internal/validators.js:124:11)
		// at dirname (path.js:1248:5)
		// at Config.save (/<redacted>/npm-config-example/node_modules/@npmcli/config/lib/index.js:739:17)
		if (!env['npm_config_userconfig']) {
			env['npm_config_userconfig'] = join(homedir(), '.npmrc');
		}
	}

	const npmConfig = new Config({
		definitions: Config.typeDefs,
		npmPath: homedir(),
		env
	});

	await npmConfig.load();

	const registry = npmConfig.find('registry');
	
	if (registry == null) {
		console.log(`Function will throw ${red}TypeError [ERR_INVALID_URL]: Invalid URL: undefined${reset} at save('user')`);
	} else {
		console.log('Function will run correctly');
	}

	const author = `cool user ${Math.ceil(Math.random()*1000)}`;
	console.log(`Setting init author = ${author}`);

	npmConfig.set('init-author-name', author, 'user');

	await npmConfig.save('user');
};

saveConfig()
	.then(() => console.log('Success!'))
	.catch(console.error);

```

What puzzles me is that README says:

https://github.com/npm/cli/blob/706b3d3f227de43a095263926d2eef2b4e4cf2a9/workspaces/config/README.md?plain=1#L9-L23

so I'm confused if the defaults for these "required" properties are appropriately handled in `@npmcli/config` or if the "exceptions" in the README are not up-to-date.

**Comment by nlf** [comment]
the problem here is that as of today `@npmcli/config` cannot be used as an entirely standalone module. the definitions used by this module are stored outside of that package and as part of the cli instead, see: https://github.com/npm/cli/blob/latest/lib/utils/config/definitions.js

this is mentioned in the first lines of the segment of the README you linked above.

we plan to make `@npmcli/config` functional for use cases like yours in the future by bringing all of the necessary information together into one place. in the mean time, your workaround is reasonable.
