### ISSUE TITLE
[BUG] npm ls screeches at unmet dependencies when using --install-strategy=linked

### ISSUE THREAD

**Issue by bnb** [npm/cli#6125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

when you install with `npm i --install-strategy=linked` in a workspace, `npm ls` outputs confusing information that points to some missing tree information/something along those lines.

### Expected Behavior

when you install with `npm i --install-strategy=linked` npm ls should not have unmet/extraneous dependencies.

### Steps To Reproduce

1. `git clone https://github.com/cutenode/nodevu`
2. `cd nodevu`
3. `npm i --install-strategy=linked`
4. `npm ls`

result:
```
⚑ npm ls
npm ERR! code ELSPROBLEMS
npm ERR! missing: @nodevu/aliases@file:/home/bnb/GitHub/cutenode/nodevu/aliases, required by nodevu@0.0.1
npm ERR! missing: @nodevu/core@file:/home/bnb/GitHub/cutenode/nodevu/core, required by nodevu@0.0.1
npm ERR! missing: @nodevu/earliest@file:/home/bnb/GitHub/cutenode/nodevu/earliest, required by nodevu@0.0.1
npm ERR! missing: @nodevu/parsefiles@file:/home/bnb/GitHub/cutenode/nodevu/parsefiles, required by nodevu@0.0.1
npm ERR! missing: @nodevu/ranges@file:/home/bnb/GitHub/cutenode/nodevu/ranges, required by nodevu@0.0.1
npm ERR! missing: @nodevu/static@file:/home/bnb/GitHub/cutenode/nodevu/static, required by nodevu@0.0.1
npm ERR! missing: @nodevu/translate@file:/home/bnb/GitHub/cutenode/nodevu/translate, required by nodevu@0.0.1
npm ERR! extraneous: aliases@npm:@nodevu/aliases@0.0.2 /home/bnb/GitHub/cutenode/nodevu/node_modules/aliases
npm ERR! extraneous: core@npm:@nodevu/core@0.0.4 /home/bnb/GitHub/cutenode/nodevu/node_modules/core
npm ERR! extraneous: earliest@npm:@nodevu/earliest@0.0.3 /home/bnb/GitHub/cutenode/nodevu/node_modules/earliest
npm ERR! extraneous: parsefiles@npm:@nodevu/parsefiles@0.0.3 /home/bnb/GitHub/cutenode/nodevu/node_modules/parsefiles
npm ERR! extraneous: ranges@npm:@nodevu/ranges@0.0.3 /home/bnb/GitHub/cutenode/nodevu/node_modules/ranges
npm ERR! extraneous: static@npm:@nodevu/static@0.0.4 /home/bnb/GitHub/cutenode/nodevu/node_modules/static
npm ERR! extraneous: translate@npm:@nodevu/translate@0.0.1 /home/bnb/GitHub/cutenode/nodevu/node_modules/translate
nodevu@0.0.1 /home/bnb/GitHub/cutenode/nodevu
├── UNMET DEPENDENCY @nodevu/aliases@file:/home/bnb/GitHub/cutenode/nodevu/aliases
├── UNMET DEPENDENCY @nodevu/core@file:/home/bnb/GitHub/cutenode/nodevu/core
├── UNMET DEPENDENCY @nodevu/earliest@file:/home/bnb/GitHub/cutenode/nodevu/earliest
├── UNMET DEPENDENCY @nodevu/parsefiles@file:/home/bnb/GitHub/cutenode/nodevu/parsefiles
├── UNMET DEPENDENCY @nodevu/ranges@file:/home/bnb/GitHub/cutenode/nodevu/ranges
├── UNMET DEPENDENCY @nodevu/static@file:/home/bnb/GitHub/cutenode/nodevu/static
├── UNMET DEPENDENCY @nodevu/translate@file:/home/bnb/GitHub/cutenode/nodevu/translate
├── aliases@npm:@nodevu/aliases@0.0.2 extraneous -> ./aliases
├── core@npm:@nodevu/core@0.0.4 extraneous -> ./core
├── earliest@npm:@nodevu/earliest@0.0.3 extraneous -> ./earliest
├── parsefiles@npm:@nodevu/parsefiles@0.0.3 extraneous -> ./parsefiles
├── ranges@npm:@nodevu/ranges@0.0.3 extraneous -> ./ranges
├── static@npm:@nodevu/static@0.0.4 extraneous -> ./static
└── translate@npm:@nodevu/translate@0.0.1 extraneous -> ./translate


npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bnb/.npm/_logs/2023-02-03T00_54_06_662Z-debug-0.log
```

`/home/bnb/.npm/_logs/2023-02-03T00_54_06_662Z-debug-0.log`
```
0 verbose cli /home/bnb/.local/share/fnm/node-versions/v19.1.0/installation/bin/node /mnt/wslg/runtime-dir/fnm_multishells/681_1675385432319/bin/npm
1 info using npm@9.4.1
2 info using node@v19.1.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/bnb/.local/share/fnm/node-versions/v19.1.0/installation/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/bnb/GitHub/cutenode/nodevu/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/bnb/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/bnb/.local/share/fnm/node-versions/v19.1.0/installation/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 6ms
17 timing npm:load:configload Completed in 6ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm ls
21 verbose argv "ls"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 2ms
25 verbose logfile logs-max:10 dir:/home/bnb/.npm/_logs/2023-02-03T00_54_06_662Z-
26 verbose logfile /home/bnb/.npm/_logs/2023-02-03T00_54_06_662Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 15ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 verbose shrinkwrap failed to load node_modules/.package-lock.json missing from lockfile: node_modules/.store/standard@17.0.0-SLwiIdzDi84glnVv6phNxQ/node_modules/standard
35 timing command:ls Completed in 659ms
36 verbose stack Error: missing: @nodevu/aliases@file:/home/bnb/GitHub/cutenode/nodevu/aliases, required by nodevu@0.0.1
36 verbose stack missing: @nodevu/core@file:/home/bnb/GitHub/cutenode/nodevu/core, required by nodevu@0.0.1
36 verbose stack missing: @nodevu/earliest@file:/home/bnb/GitHub/cutenode/nodevu/earliest, required by nodevu@0.0.1
36 verbose stack missing: @nodevu/parsefiles@file:/home/bnb/GitHub/cutenode/nodevu/parsefiles, required by nodevu@0.0.1
36 verbose stack missing: @nodevu/ranges@file:/home/bnb/GitHub/cutenode/nodevu/ranges, required by nodevu@0.0.1
36 verbose stack missing: @nodevu/static@file:/home/bnb/GitHub/cutenode/nodevu/static, required by nodevu@0.0.1
36 verbose stack missing: @nodevu/translate@file:/home/bnb/GitHub/cutenode/nodevu/translate, required by nodevu@0.0.1
36 verbose stack extraneous: aliases@npm:@nodevu/aliases@0.0.2 /home/bnb/GitHub/cutenode/nodevu/node_modules/aliases
36 verbose stack extraneous: core@npm:@nodevu/core@0.0.4 /home/bnb/GitHub/cutenode/nodevu/node_modules/core
36 verbose stack extraneous: earliest@npm:@nodevu/earliest@0.0.3 /home/bnb/GitHub/cutenode/nodevu/node_modules/earliest
36 verbose stack extraneous: parsefiles@npm:@nodevu/parsefiles@0.0.3 /home/bnb/GitHub/cutenode/nodevu/node_modules/parsefiles
36 verbose stack extraneous: ranges@npm:@nodevu/ranges@0.0.3 /home/bnb/GitHub/cutenode/nodevu/node_modules/ranges
36 verbose stack extraneous: static@npm:@nodevu/static@0.0.4 /home/bnb/GitHub/cutenode/nodevu/node_modules/static
36 verbose stack extraneous: translate@npm:@nodevu/translate@0.0.1 /home/bnb/GitHub/cutenode/nodevu/node_modules/translate
36 verbose stack     at LS.exec (/home/bnb/.local/share/fnm/node-versions/v19.1.0/installation/lib/node_modules/npm/lib/commands/ls.js:203:9)
36 verbose stack     at async module.exports (/home/bnb/.local/share/fnm/node-versions/v19.1.0/installation/lib/node_modules/npm/lib/cli.js:134:5)
37 verbose cwd /home/bnb/GitHub/cutenode/nodevu
38 verbose Linux 5.15.79.1-microsoft-standard-WSL2
39 verbose node v19.1.0
40 verbose npm  v9.4.1
41 error code ELSPROBLEMS
42 error missing: @nodevu/aliases@file:/home/bnb/GitHub/cutenode/nodevu/aliases, required by nodevu@0.0.1
42 error missing: @nodevu/core@file:/home/bnb/GitHub/cutenode/nodevu/core, required by nodevu@0.0.1
42 error missing: @nodevu/earliest@file:/home/bnb/GitHub/cutenode/nodevu/earliest, required by nodevu@0.0.1
42 error missing: @nodevu/parsefiles@file:/home/bnb/GitHub/cutenode/nodevu/parsefiles, required by nodevu@0.0.1
42 error missing: @nodevu/ranges@file:/home/bnb/GitHub/cutenode/nodevu/ranges, required by nodevu@0.0.1
42 error missing: @nodevu/static@file:/home/bnb/GitHub/cutenode/nodevu/static, required by nodevu@0.0.1
42 error missing: @nodevu/translate@file:/home/bnb/GitHub/cutenode/nodevu/translate, required by nodevu@0.0.1
42 error extraneous: aliases@npm:@nodevu/aliases@0.0.2 /home/bnb/GitHub/cutenode/nodevu/node_modules/aliases
42 error extraneous: core@npm:@nodevu/core@0.0.4 /home/bnb/GitHub/cutenode/nodevu/node_modules/core
42 error extraneous: earliest@npm:@nodevu/earliest@0.0.3 /home/bnb/GitHub/cutenode/nodevu/node_modules/earliest
42 error extraneous: parsefiles@npm:@nodevu/parsefiles@0.0.3 /home/bnb/GitHub/cutenode/nodevu/node_modules/parsefiles
42 error extraneous: ranges@npm:@nodevu/ranges@0.0.3 /home/bnb/GitHub/cutenode/nodevu/node_modules/ranges
42 error extraneous: static@npm:@nodevu/static@0.0.4 /home/bnb/GitHub/cutenode/nodevu/node_modules/static
42 error extraneous: translate@npm:@nodevu/translate@0.0.1 /home/bnb/GitHub/cutenode/nodevu/node_modules/translate
43 verbose exit 1
44 timing npm Completed in 687ms
45 verbose code 1
46 error A complete log of this run can be found in:
46 error     /home/bnb/.npm/_logs/2023-02-03T00_54_06_662Z-debug-0.log
```

### Environment

- npm: 9.4.1
- Node.js: v19.1.0
- OS Name: Windows 11
- npm config:
```ini
; "user" config from /home/bnb/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; "project" config from /home/bnb/GitHub/cutenode/nodevu/.npmrc

package-lock = false 

; node bin location = /home/bnb/.local/share/fnm/node-versions/v19.1.0/installation/bin/node
; node version = v19.1.0
; npm local prefix = /home/bnb/GitHub/cutenode/nodevu
; npm version = 9.4.1
; cwd = /home/bnb/GitHub/cutenode/nodevu
; HOME = /home/bnb
; Run `npm config ls -l` to show all defaults.```

**Comment by bnb** [comment]
Worth noting: passing `--install-strategy=linked` to `npm ls` does not fix this.

**Comment by manzoorwanijk** [comment]
@owlstronaut I think this should now be fixed now after #9608
