### ISSUE TITLE
[BUG] npm v9.5.0 is known not to run on Node.js v18.14.2

### ISSUE THREAD

**Issue by StephanBijzitter** [npm/cli#6214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [ ] I am using the latest npm

### Current Behavior

> I know that I ticked "I am using the latest npm" and that is incorect. I cannot update to the latest version (due to this issue) and I cannot create this issue without ticking the box.

This is what happens with `npm -v` on nodejs `18.14.2` (latest LTS at time of writing):
```
ERROR:
C:\Users\Steph\AppData\Roaming\nvm\v18.14.2\node_modules\npm\node_modules\@npmcli\arborist:1
../../workspaces/arborist
^

SyntaxError: Unexpected token '.'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\Steph\AppData\Roaming\nvm\v18.14.2\node_modules\npm\lib\npm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

ERROR: npm v9.5.0 is known not to run on Node.js v18.14.2. You'll need to upgrade
to a newer Node.js version in order to use this version of npm. This version of
npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You
can find the latest version at https://nodejs.org/.
```

### Expected Behavior

I would assume to see npm print its version

### Steps To Reproduce

1. Windows 11, NodeJS 18.14.2 installed using NVM
3. `npm -v`

### Environment

- npm: 9.5.0, if the error message is right
- Node.js: 18.14.2
- OS Name: windows 11
- System Model Name: A lenovo laptop
- npm config: none
```ini
ERROR: npm v9.5.0 is known not to run on Node.js v18.14.2. You'll need to upgrade
to a newer Node.js version in order to use this version of npm. This version of
npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You
can find the latest version at https://nodejs.org/.

ERROR:
C:\Users\Steph\AppData\Roaming\nvm\v18.14.2\node_modules\npm\node_modules\@npmcli\arborist:1
../../workspaces/arborist
^

SyntaxError: Unexpected token '.'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\Steph\AppData\Roaming\nvm\v18.14.2\node_modules\npm\lib\npm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

ERROR: npm v9.5.0 is known not to run on Node.js v18.14.2. You'll need to upgrade
to a newer Node.js version in order to use this version of npm. This version of
npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You
can find the latest version at https://nodejs.org/.

ERROR:
C:\Users\Steph\AppData\Roaming\nvm\v18.14.2\node_modules\npm\node_modules\@npmcli\arborist:1
../../workspaces/arborist
^

SyntaxError: Unexpected token '.'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\Steph\AppData\Roaming\nvm\v18.14.2\node_modules\npm\lib\npm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
```

**Comment by ljharb** [comment]
This is nvm-windows, I presume, not actual nvm? What version of nvm-windows are you running?

**Comment by nlf** [comment]
to elaborate on @ljharb's comment, some older versions of nvm-windows worked by downloading a zip archive of our repository and extracting that to "install" npm. the problem with that is we've introduced symlinks into our git repo. within the zip archive, symlinks are represented as normal files with their content being the path they should be a symlink to. that's why you're seeing the `Unexpected token` message.

the fix here is to update nvm-windows to the newest version, then use that newest version to reinstall.

**Comment by liudonghua123** [comment]
I have the same problems. I use nvm `1.1.7`. I will update my nvm to the current latest `1.1.10` and try again.

**Comment by liudonghua123** [comment]
After I update `nvm`, I tried to reinstall `node 18.14.2`, the installed npm is `9.2.0` and it works now.

```
C:\Users\Liu.D.H>nvm uninstall 18.14.2
Uninstalling node v18.14.2... done
C:\Users\Liu.D.H>nvm install 18.14.2
Downloading node.js version 18.14.2 (64-bit)...
Extracting node and npm...
Complete
npm v9.5.0 installed successfully.


Installation complete. If you want to use this version, type

nvm use 18.14.2

C:\Users\Liu.D.H>nvm use 18.14.2
Now using node v18.14.2 (64-bit)

C:\Users\Liu.D.H>node -v
v18.14.2

C:\Users\Liu.D.H>npm -v
9.2.0

C:\Users\Liu.D.H>
```
