### ISSUE TITLE
EMISSINGARG? ("This is an error with npm itself. Please report this error at: "...)

### ISSUE THREAD

**Issue by gtoal** [npm/cli#6240]
I don't know anything about node or npm, I'm just trying to install and run a program 'nectarjs' to get a start on the conversion of some old Javascript code to C ... your 'npm' package failed with an error asking that I submit a report, so here it is. No followup necessary, I'll go and install the program the old fashioned way from source like I should have done in the first place.
```

gtoal@linux:~/src/splines/bezierjs$ npm i -g nectarjs
npm ERR! Linux 4.15.0-167-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "nectarjs"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0-167-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "nectarjs"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
WARN engine strip-comments@2.0.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine eslint@7.32.0: wanted: {"node":"^10.12.0 || >=12.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"})

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gtoal/src/splines/bezierjs/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '-g', 'nectarjs' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData nectarjs
8 silly fetchNamedPackageData nectarjs
9 silly mapToRegistry name nectarjs
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/nectarjs
13 verbose request uri https://registry.npmjs.org/nectarjs
14 verbose request no auth needed
15 info attempt registry request try #1 at 4:08:08 PM
16 verbose request id 1ced011b986cb852
17 http request GET https://registry.npmjs.org/nectarjs
18 http 200 https://registry.npmjs.org/nectarjs
19 verbose headers { date: 'Fri, 10 Mar 2023 22:08:08 GMT',
19 verbose headers   'content-type': 'application/json',
19 verbose headers   'transfer-encoding': 'chunked',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'cf-ray': '7a5edfe658ba3aaa-DFW',
19 verbose headers   'access-control-allow-origin': '*',
19 verbose headers   'cache-control': 'public, max-age=300',
19 verbose headers   etag: 'W/"1d96dec0bfdfa7e91cb74b5159d612be"',
19 verbose headers   'last-modified': 'Mon, 20 Jun 2022 23:36:41 GMT',
19 verbose headers   vary: 'accept-encoding, accept',
19 verbose headers   'cf-cache-status': 'MISS',
19 verbose headers   'x-amz-replication-status': 'COMPLETED',
19 verbose headers   server: 'cloudflare',
19 verbose headers   'content-encoding': 'gzip' }
20 silly get cb [ 200,
20 silly get   { date: 'Fri, 10 Mar 2023 22:08:08 GMT',
20 silly get     'content-type': 'application/json',
20 silly get     'transfer-encoding': 'chunked',
20 silly get     connection: 'keep-alive',
20 silly get     'cf-ray': '7a5edfe658ba3aaa-DFW',
20 silly get     'access-control-allow-origin': '*',
20 silly get     'cache-control': 'public, max-age=300',
20 silly get     etag: 'W/"1d96dec0bfdfa7e91cb74b5159d612be"',
20 silly get     'last-modified': 'Mon, 20 Jun 2022 23:36:41 GMT',
20 silly get     vary: 'accept-encoding, accept',
20 silly get     'cf-cache-status': 'MISS',
20 silly get     'x-amz-replication-status': 'COMPLETED',
20 silly get     server: 'cloudflare',
20 silly get     'content-encoding': 'gzip' } ]
21 verbose get saving nectarjs to /home/gtoal/.npm/registry.npmjs.org/nectarjs/.cache.json
22 silly install normalizeTree
23 silly loadCurrentTree Finishing
24 silly loadIdealTree Starting
25 silly install loadIdealTree
26 silly cloneCurrentTree Starting
27 silly install cloneCurrentTreeToIdealTree
28 silly cloneCurrentTree Finishing
29 silly loadShrinkwrap Starting
30 silly install loadShrinkwrap
31 silly loadShrinkwrap Finishing
32 silly loadAllDepsIntoIdealTree Starting
33 silly install loadAllDepsIntoIdealTree
34 silly resolveWithNewModule nectarjs@0.7.115 checking installable status
35 silly cache add args [ 'nectarjs', null ]
36 verbose cache add spec nectarjs
37 silly cache add parsed spec Result {
37 silly cache add   raw: 'nectarjs',
37 silly cache add   scope: null,
37 silly cache add   name: 'nectarjs',
37 silly cache add   rawSpec: '',
37 silly cache add   spec: 'latest',
37 silly cache add   type: 'tag' }
38 silly addNamed nectarjs@latest
39 verbose addNamed "latest" is being treated as a dist-tag for nectarjs
40 info addNameTag [ 'nectarjs', 'latest' ]
41 silly mapToRegistry name nectarjs
42 silly mapToRegistry using default registry
43 silly mapToRegistry registry https://registry.npmjs.org/
44 silly mapToRegistry uri https://registry.npmjs.org/nectarjs
45 verbose addNameTag registry:https://registry.npmjs.org/nectarjs not in flight; fetching
46 verbose get https://registry.npmjs.org/nectarjs not expired, no request
47 silly addNameTag next cb for nectarjs with tag latest
48 silly addNamed nectarjs@0.7.115
49 verbose addNamed "0.7.115" is a plain semver version for nectarjs
50 silly mapToRegistry name nectarjs
51 silly mapToRegistry using default registry
52 silly mapToRegistry registry https://registry.npmjs.org/
53 silly mapToRegistry uri https://registry.npmjs.org/nectarjs
54 verbose addRemoteTarball https://registry.npmjs.org/nectarjs/-/nectarjs-0.7.115.tgz not in flight; adding
55 verbose addRemoteTarball [ 'https://registry.npmjs.org/nectarjs/-/nectarjs-0.7.115.tgz',
55 verbose addRemoteTarball   '2de4c2fa7997aeea49fac4cdd32d762cc6984bb9' ]
56 info retry fetch attempt 1 at 4:08:09 PM
57 info attempt registry request try #1 at 4:08:09 PM
58 http fetch GET https://registry.npmjs.org/nectarjs/-/nectarjs-0.7.115.tgz
59 http fetch 200 https://registry.npmjs.org/nectarjs/-/nectarjs-0.7.115.tgz
60 silly fetchAndShaCheck shasum 2de4c2fa7997aeea49fac4cdd32d762cc6984bb9
61 verbose addTmpTarball /tmp/npm-4112-531f942b/registry.npmjs.org/nectarjs/-/nectarjs-0.7.115.tgz not in flight; adding
62 verbose addTmpTarball already have metadata; skipping unpack for nectarjs@0.7.115
63 silly cache afterAdd nectarjs@0.7.115
64 verbose afterAdd /home/gtoal/.npm/nectarjs/0.7.115/package/package.json not in flight; writing
65 verbose afterAdd /home/gtoal/.npm/nectarjs/0.7.115/package/package.json written
66 silly fetchNamedPackageData @babel/core
67 silly mapToRegistry name @babel/core
68 silly mapToRegistry scope (from package name) @babel
69 verbose mapToRegistry no registry URL found in name for scope @babel
70 silly mapToRegistry using default registry
71 silly mapToRegistry registry https://registry.npmjs.org/
72 silly mapToRegistry uri https://registry.npmjs.org/@babel%2fcore
73 silly fetchNamedPackageData @babel/generator
74 silly mapToRegistry name @babel/generator
75 silly mapToRegistry scope (from package name) @babel
76 verbose mapToRegistry no registry URL found in name for scope @babel
77 silly mapToRegistry using default registry
78 silly mapToRegistry registry https://registry.npmjs.org/
79 silly mapToRegistry uri https://registry.npmjs.org/@babel%2fgenerator
80 silly fetchNamedPackageData babel-plugin-minify-dead-code-elimination
81 silly mapToRegistry name babel-plugin-minify-dead-code-elimination
82 silly mapToRegistry using default registry
83 silly mapToRegistry registry https://registry.npmjs.org/
84 silly mapToRegistry uri https://registry.npmjs.org/babel-plugin-minify-dead-code-elimination
85 silly fetchNamedPackageData babel-plugin-minify-guarded-expressions
86 silly mapToRegistry name babel-plugin-minify-guarded-expressions
87 silly mapToRegistry using default registry
88 silly mapToRegistry registry https://registry.npmjs.org/
89 silly mapToRegistry uri https://registry.npmjs.org/babel-plugin-minify-guarded-expressions
90 silly fetchNamedPackageData babel-plugin-remove-unused-vars
91 silly mapToRegistry name babel-plugin-remove-unused-vars
92 silly mapToRegistry using default registry
93 silly mapToRegistry registry https://registry.npmjs.org/
94 silly mapToRegistry uri https://registry.npmjs.org/babel-plugin-remove-unused-vars
95 silly fetchNamedPackageData eslint
96 silly mapToRegistry name eslint
97 silly mapToRegistry using default registry
98 silly mapToRegistry registry https://registry.npmjs.org/
99 silly mapToRegistry uri https://registry.npmjs.org/eslint
100 silly fetchNamedPackageData strip-comments
101 silly mapToRegistry name strip-comments
102 silly mapToRegistry using default registry
103 silly mapToRegistry registry https://registry.npmjs.org/
104 silly mapToRegistry uri https://registry.npmjs.org/strip-comments
105 silly fetchNamedPackageData typescript
106 silly mapToRegistry name typescript
107 silly mapToRegistry using default registry
108 silly mapToRegistry registry https://registry.npmjs.org/
109 silly mapToRegistry uri https://registry.npmjs.org/typescript
110 verbose request uri https://registry.npmjs.org/@babel%2fcore
111 verbose request no auth needed
112 info attempt registry request try #1 at 4:08:10 PM
113 http request GET https://registry.npmjs.org/@babel%2fcore
114 verbose request uri https://registry.npmjs.org/@babel%2fgenerator
115 verbose request no auth needed
116 info attempt registry request try #1 at 4:08:10 PM
117 http request GET https://registry.npmjs.org/@babel%2fgenerator
118 verbose request uri https://registry.npmjs.org/babel-plugin-minify-dead-code-elimination
119 verbose request no auth needed
120 info attempt registry request try #1 at 4:08:10 PM
121 http request GET https://registry.npmjs.org/babel-plugin-minify-dead-code-elimination
122 verbose request uri https://registry.npmjs.org/babel-plugin-minify-guarded-expressions
123 verbose request no auth needed
124 info attempt registry request try #1 at 4:08:10 PM
125 http request GET https://registry.npmjs.org/babel-plugin-minify-guarded-expressions
126 verbose request uri https://registry.npmjs.org/babel-plugin-remove-unused-vars
127 verbose request no auth needed
128 info attempt registry request try #1 at 4:08:10 PM
129 http request GET https://registry.npmjs.org/babel-plugin-remove-unused-vars
130 verbose request uri https://registry.npmjs.org/eslint
131 verbose request no auth needed
132 info attempt registry request try #1 at 4:08:10 PM
133 http request GET https://registry.npmjs.org/eslint
134 verbose request uri https://registry.npmjs.org/strip-comments
135 verbose request no auth needed
136 info attempt registry request try #1 at 4:08:10 PM
137 http request GET https://registry.npmjs.org/strip-comments
138 http 200 https://registry.npmjs.org/@babel%2fcore
139 verbose headers { date: 'Fri, 10 Mar 2023 22:08:10 GMT',
139 verbose headers   'content-type': 'application/json',
139 verbose headers   'transfer-encoding': 'chunked',
139 verbose headers   connection: 'keep-alive',
139 verbose headers   'cf-ray': '7a5edff3ce113aaa-DFW',
139 verbose headers   'access-control-allow-origin': '*',
139 verbose headers   age: '115',
139 verbose headers   'cache-control': 'public, max-age=300',
139 verbose headers   etag: 'W/"c3ecc5abe23136720d734ad63a953a83"',
139 verbose headers   'last-modified': 'Mon, 20 Feb 2023 15:31:24 GMT',
139 verbose headers   vary: 'accept-encoding, accept',
139 verbose headers   'cf-cache-status': 'HIT',
139 verbose headers   'x-amz-replication-status': 'PENDING',
139 verbose headers   'x-amz-server-side-encryption': 'AES256',
139 verbose headers   server: 'cloudflare',
139 verbose headers   'content-encoding': 'gzip' }
140 silly get cb [ 200,
140 silly get   { date: 'Fri, 10 Mar 2023 22:08:10 GMT',
140 silly get     'content-type': 'application/json',
140 silly get     'transfer-encoding': 'chunked',
140 silly get     connection: 'keep-alive',
140 silly get     'cf-ray': '7a5edff3ce113aaa-DFW',
140 silly get     'access-control-allow-origin': '*',
140 silly get     age: '115',
140 silly get     'cache-control': 'public, max-age=300',
140 silly get     etag: 'W/"c3ecc5abe23136720d734ad63a953a83"',
140 silly get     'last-modified': 'Mon, 20 Feb 2023 15:31:24 GMT',
140 silly get     vary: 'accept-encoding, accept',
140 silly get     'cf-cache-status': 'HIT',
140 silly get     'x-amz-replication-status': 'PENDING',
140 silly get     'x-amz-server-side-encryption': 'AES256',
140 silly get     server: 'cloudflare',
140 silly get     'content-encoding': 'gzip' } ]
141 verbose get saving @babel/core to /home/gtoal/.npm/registry.npmjs.org/_40babel_252fcore/.cache.json
142 verbose stack Error: Missing required argument #1
142 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
142 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
142 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
142 verbose stack     at /usr/share/npm/lib/install/deps.js:457:7
142 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
142 verbose stack     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
142 verbose stack     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
142 verbose stack     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
142 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
142 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
143 verbose cwd /home/gtoal/src/splines/bezierjs
144 error Linux 4.15.0-167-generic
145 error argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "nectarjs"
146 error node v8.10.0
147 error npm  v3.5.2
148 error code EMISSINGARG
149 error typeerror Error: Missing required argument #1
149 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
149 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
149 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
149 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
149 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
149 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
149 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
149 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
149 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
149 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
150 error typeerror This is an error with npm itself. Please report this error at:
150 error typeerror     <http://github.com/npm/npm/issues>
151 verbose exit [ 1, true ]

```

**Comment by ljharb** [comment]
That's node 8 and npm 3, both of which are many years obsolete and unsupported. If you installed node from apt, that's your problem - never do that :-)

**Comment by gtoal** [comment]
That's annoying - it's what you get by default on an installation of Ubuntu 18.04.6 LTS which is kept up to date :-(  I guess the 5 years of standard support are up.  OK, thanks.
