### ISSUE TITLE
[BUG] Can't publish package

### ISSUE THREAD

**Issue by Olian04** [npm/cli#6260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I've published multiple versions of this library before, and any version at or before 0.3.0 can be found and installed. However any version at or after 0.4.0 can't. The CLI manages to publish the package, and I get a verification email telling me that the new version was published. However I can't install the version, and I can't find it on the website.

__Terminal output when publishing and installing__
![image](https://user-images.githubusercontent.com/5493406/225576023-b1099f13-f720-40ee-800c-66427e92136c.png)

__Versions found on npmjs.com__
![image](https://user-images.githubusercontent.com/5493406/225575291-39efd689-9780-4d76-95c2-2440764007dc.png)

__Verification email__
![image](https://user-images.githubusercontent.com/5493406/225575708-c09e850d-4987-4891-b9a5-1eba441df86f.png)

__Log file from the failed install__
```log
0 verbose cli C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node.exe C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node_modules\npm\bin\npm-cli.js
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node_modules\npm\npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\rift9\Documents\projects\simply-reactive-web\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\rift9\.npmrc Completed in 2ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 9ms
17 timing npm:load:configload Completed in 9ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm i simply-reactive-web@0.4.5
21 verbose argv "i" "simply-reactive-web@0.4.5"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 4ms
24 timing npm:load:display Completed in 4ms
25 verbose logfile logs-max:10 dir:C:\Users\rift9\AppData\Local\npm-cache\_logs\2023-03-16T09_25_13_460Z-
26 verbose logfile C:\Users\rift9\AppData\Local\npm-cache\_logs\2023-03-16T09_25_13_460Z-debug-0.log
27 timing npm:load:logFile Completed in 6ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 23ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 2 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 105ms
35 timing idealTree:userRequests Completed in 3ms
36 silly idealTree buildDeps
37 silly fetch manifest simply-reactive-web@0.4.5
38 timing arborist:ctor Completed in 0ms
39 http fetch GET 200 https://registry.npmjs.org/simply-reactive-web 920ms (cache miss)
40 silly placeDep ROOT simply-reactive-web@ OK for: simply-reactive-web@0.4.5 want: 0.4.5
41 timing idealTree:#root Completed in 926ms
42 timing idealTree:node_modules/simply-reactive-web Completed in 0ms
43 timing idealTree:buildDeps Completed in 928ms
44 timing idealTree:fixDepFlags Completed in 1ms
45 timing idealTree Completed in 1040ms
46 timing command:i Completed in 1047ms
47 verbose type version
48 verbose stack simply-reactive-web: No matching version found for simply-reactive-web@0.4.5.
48 verbose stack     at module.exports (C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node_modules\npm\node_modules\npm-pick-manifest\lib\index.js:209:23)
48 verbose stack     at RegistryFetcher.manifest (C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node_modules\npm\node_modules\pacote\lib\registry.js:119:22)
48 verbose stack     at async [nodeFromEdge] (C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1059:19)
48 verbose stack     at async [buildDepStep] (C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:929:11)
48 verbose stack     at async Arborist.buildIdealTree (C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:207:7)
48 verbose stack     at async Promise.all (index 1)
48 verbose stack     at async Arborist.reify (C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
48 verbose stack     at async Install.exec (C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node_modules\npm\lib\commands\install.js:146:5)
48 verbose stack     at async module.exports (C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node_modules\npm\lib\cli.js:134:5)
49 verbose cwd C:\Users\rift9\Documents\projects\simply-reactive-web
50 verbose Windows_NT 10.0.19045
51 verbose node v18.15.0
52 verbose npm  v9.5.0
53 error code ETARGET
54 error notarget No matching version found for simply-reactive-web@0.4.5.
55 error notarget In most cases you or one of your dependencies are requesting
55 error notarget a package version that doesn't exist.
56 verbose exit 1
57 timing npm Completed in 1097ms
58 verbose unfinished npm timer reify 1678958713506
59 verbose unfinished npm timer reify:loadTrees 1678958713510
60 verbose code 1
61 error A complete log of this run can be found in:
61 error     C:\Users\rift9\AppData\Local\npm-cache\_logs\2023-03-16T09_25_13_460Z-debug-0.log
```

### Expected Behavior

I expect for either `npm publish` to fail if the error lies there, or for the package to be installable since `npm publish` succeeded.

### Steps To Reproduce

I don't know how to reproduce the error on another system.

### Environment

- npm: 9.5.0
- Node.js: 18.15.0
- OS Name: Windows 10 (build 19045.2604)
- System Model Name: Micro-Star International Co., Ltd (MS-7b17)
- npm config:
```ini
; "user" config from C:\Users\rift9\.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = C:\Users\rift9\.nvm\versions\node\v18.15.0\bin\node.exe
; node version = v18.15.0
; npm local prefix = C:\Users\rift9\Documents\projects\simply-reactive-web   
; npm version = 9.5.0
; cwd = C:\Users\rift9\Documents\projects\simply-reactive-web
; HOME = C:\Users\rift9
; Run `npm config ls -l` to show all defaults.
```

**Comment by await-ovo** [comment]
I have the same problem, `npm publish` works, but `npm view `still shows `404`

**Comment by junghyeonsu** [comment]
I'm having the exact same issue.

**Comment by daphnesmit** [comment]
Same!

**Comment by skarnl** [comment]
Same issue here 😞

**Comment by fritzy** [comment]
There was an incident with the registry. This should be resolved now. https://status.npmjs.org/incidents/486c00gg9wt4
