### ISSUE TITLE
[BUG] npm server should return 401 for unauthentication rather than 404

### ISSUE THREAD

**Issue by AnnAngela** [npm/cli#6264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I tried to deprecate a misnamed package but forgot to login-in, I got this error message:
```log
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.6.2
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 4ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 5ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/data/MoegirlPediaInterfaceCodes/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/annangela/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 3ms
14 timing config:load:global Completed in 3ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 24ms
17 timing npm:load:configload Completed in 25ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm deprecate baidu-aip-sdk-unoffical Rename to [baidu-aip-sdk-unofficial](https://www.npmjs.com/package/baidu-aip-sdk-unofficial)
21 verbose argv "deprecate" "baidu-aip-sdk-unoffical" "Rename to [baidu-aip-sdk-unofficial](https://www.npmjs.com/package/baidu-aip-sdk-unofficial)" "--registry" "https://registry.npmjs.org/"
22 timing npm:load:setTitle Completed in 3ms
23 timing config:load:flatten Completed in 5ms
24 timing npm:load:display Completed in 6ms
25 verbose logfile logs-max:10 dir:/home/annangela/.npm/_logs/2023-03-17T03_54_36_669Z-
26 verbose logfile /home/annangela/.npm/_logs/2023-03-17T03_54_36_669Z-debug-0.log
27 timing npm:load:logFile Completed in 10ms
28 timing npm:load:timers Completed in 1ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 52ms
31 silly logfile start cleaning logs, removing 1 files
32 silly logfile done cleaning log files
33 http fetch GET 200 https://registry.npmjs.org/baidu-aip-sdk-unoffical?write=true 448ms (cache updated)
34 http fetch PUT 404 https://registry.npmjs.org/baidu-aip-sdk-unoffical 401ms
35 timing command:deprecate Completed in 856ms
36 verbose stack HttpErrorGeneral: 404 Not Found - PUT https://registry.npmjs.org/baidu-aip-sdk-unoffical - Not found
36 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
36 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
36 verbose stack     at async otplease (/usr/local/lib/node_modules/npm/lib/utils/otplease.js:4:12)
36 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:134:5)
37 verbose statusCode 404
38 verbose pkgid baidu-aip-sdk-unoffical@*
39 verbose cwd /data/MoegirlPediaInterfaceCodes
40 verbose Linux 4.4.0-19041-Microsoft
41 verbose node v18.15.0
42 verbose npm  v9.6.2
43 error code E404
44 error 404 Not Found - PUT https://registry.npmjs.org/baidu-aip-sdk-unoffical - Not found
45 error 404
46 error 404  'baidu-aip-sdk-unoffical@*' is not in this registry.
47 error 404
47 error 404 Note that you can also install from a
48 error 404 tarball, folder, http url, or git url.
49 verbose exit 1
50 timing npm Completed in 936ms
51 verbose code 1
52 error A complete log of this run can be found in:
52 error     /home/annangela/.npm/_logs/2023-03-17T03_54_36_669Z-debug-0.log
```
Which suggests that the package isn't exist, but the true problem is that I haven't logged in.

After logging in, every thing became right.

### Expected Behavior

The error message should discloused that the real problem is unauthentication, not existence of package. The server should return 401 or sth rather than 404.

### Steps To Reproduce

1. Run `npm deprecate "baidu-aip-sdk-unoffical" "Rename to [baidu-aip-sdk-unofficial](https://www.npmjs.com/package/baidu-aip-sdk-unofficial)" --registry=https://registry.npmjs.org/`

### Environment

- npm: `9.6.2`
- Node.js: `v18.15.0`
- OS Name: `Ubuntu 22.04.2 LTS`
- System Model Name: WSL in Windows 10 21H2 19044.1889 x64
- npm config:
```ini
; "global" config from /usr/local/etc/npmrc

https-proxy = "http://127.0.0.1:1307/" 
noproxy = ["mirrors.cloud.tencent.com"] 
proxy = "http://127.0.0.1:1307/" 
registry = "https://mirrors.cloud.tencent.com/npm/" 

; node bin location = /usr/local/bin/node
; node version = v18.15.0
; npm local prefix = /data/MoegirlPediaInterfaceCodes
; npm version = 9.6.2
; cwd = /data/MoegirlPediaInterfaceCodes
; HOME = /home/annangela
; Run `npm config ls -l` to show all defaults.
```
Please note that I have configured `https://registry.npmjs.org/` in the command's `registry` option.

**Comment by wraithgar** [comment]
This is intentional for security reasonss.  If the response for this unauthenticated request was a 401 it would reveal that the private package existed.

**Comment by AnnAngela** [comment]
> This is intentional for security reasonss. If the response for this unauthenticated request was a 401 it would reveal that the private package existed.

But I think at least the npm should warn the user that they are unauthenticated.
