### ISSUE TITLE
[BUG] <title>Abort Installing

### ISSUE THREAD

**Issue by Krish9848** [npm/cli#6320]
Creating a new React app in D:\Todo\todo.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

Aborting installation.
Unexpected error. Please report it as a bug:
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at spawn (D:\Todo\node_modules\cross-spawn\index.js:12:24)
    at D:\Todo\node_modules\create-react-app\createReactApp.js:383:19
    at new Promise (<anonymous>)
    at install (D:\Todo\node_modules\create-react-app\createReactApp.js:334:10)
    at D:\Todo\node_modules\create-react-app\createReactApp.js:461:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  syscall: 'spawn'
}

Deleting generated file... package.json
Deleting todo/ from D:\Todo
Done.

**Comment by Krish9848** [comment]
how an i fix it
