### ISSUE TITLE
[BUG] null not handled by broken npm

### ISSUE THREAD

**Issue by jelmd** [npm/cli#6492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm is unusable (unable to `npm update`) because of un-handled null properties:
```
npm ERR! Cannot read properties of null (reading 'edgesOut')
...
66 silly fetch manifest styled-components@>= 2
67 silly fetch manifest react@>= 16.8.0
68 silly fetch manifest react-dom@>= 16.8.0
69 silly fetch manifest react-is@>= 16.8.0
70 http fetch GET 200 https://registry.npmjs.org/react-is 11ms (cache stale)
71 timing idealTree Completed in 621ms
72 timing command:update Completed in 627ms
73 verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
73 verbose stack     at [loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1307:38)
73 verbose stack     at async [loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1315:11)
73 verbose stack     at async [buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
73 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
73 verbose stack     at async Promise.all (index 1)
73 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
73 verbose stack     at async Update.exec (/usr/lib/node_modules/npm/lib/commands/update.js:64:5)
73 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:134:5)
74 verbose cwd ...
```

### Expected Behavior

`npm update` should go through w/o any error.

### Steps To Reproduce

Try this `package.json`:
```json
{
    "name": "foobar",
    "description": "Test",
    "repository": "https://github.com/x/y",
    "bugs": {
        "url": "https://github.com/x/y/issues"
    },
    "author": "Foo Bar <foobar@do.main>",
    "contributors": [],
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "db": "NODE_OPTIONS='--no-warnings --loader ts-node/esm' nodemon --watch scripts scripts/db.ts",
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "lint": "next lint",
        "clean": "rm -rf .next",
        "realclean": "rm -rf .next node_modules package-lock.json"
    },
    "dependencies": {
        "@next-auth/prisma-adapter": "^1.0.6",
        "@prisma/client": "^4.14.1",
        "next": "13.4.3",
        "nodemailer": "^6.9.2",
        "react": "18.2.0",
        "react-dom": "18.2.0"
    },
    "devDependencies": {
        "@styled-icons/material": "^10.47.0",
        "@styled-icons/fa-solid": "^10.47.0",
        "@types/busboy": "^1.5.0",
        "@types/node": "20.2.3",
        "@types/nodemailer": "^6.4.8",
        "@types/react": "18.2.6",
        "@types/react-dom": "18.2.4",
        "eslint": "8.41.0",
        "eslint-config-next": "13.4.3",
        "prisma": "^4.14.1",
        "typescript": "5.0.4"
    }
}
```
and run `npm i` or `npm update`.

### Environment

- npm:9.5.1
- Node.js: v18.16.0
- OS Name: Linux (Ubuntu 20.04)
- System Model Name: amd64
- npm config:
```ini
prefer-offline = true 
```

**Comment by jelmd** [comment]
Just in case for reproduction - cleanup the cache, too, e.g. run `rm -rf ~/.npm/_cacache/` !

**Comment by wraithgar** [comment]
https://github.com/npm/cli/issues/4787
https://github.com/npm/cli/issues/5151

**Comment by jelmd** [comment]
BTW: solved the problem with this patch (not sure, whether this is ok, but at least allowed me going back to back work ;-)):
```patch
--- /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js.orig	2023-04-12 05:45:24.000000000 +0200
+++ /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js	2023-05-24 18:15:49.699840640 +0200
@@ -1304,6 +1304,11 @@
         continue
       }
 
+		var x = node.parent.edgesOut.get(edge.name);
+		//console.log('\nedge.name=\n', edge.name, '\n', x );
+		if (!x)
+			continue;
+	
       const parentEdge = node.parent.edgesOut.get(edge.name)
       const { isProjectRoot, isWorkspace } = node.parent.sourceReference
       const isMine = isProjectRoot || isWorkspace
```
