### ISSUE TITLE
[BUG] 429 error when unpublishing and not logged in

### ISSUE THREAD

**Issue by SimonSiefke** [npm/cli#6683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When not logged in an trying to unpublish a package, the cli hangs for for 72783ms before showing an error 429 Too Many Requests.

I tried multiple times and it was always the same behaviour: Nothing happens for a while, then a 429 error.

Npm Debug Log: 

```
0 verbose cli /home/simon/.nvm/versions/node/v18.17.0/bin/node /home/simon/.nvm/versions/node/v18.17.0/bin/npm
1 info using npm@9.6.7
2 info using node@v18.17.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/simon/.nvm/versions/node/v18.17.0/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/simon/.cache/repos/termterm/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/simon/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/simon/.nvm/versions/node/v18.17.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 12ms
17 timing npm:load:configload Completed in 12ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm unpublish termterm@0.0.0-dev
21 verbose argv "unpublish" "termterm@0.0.0-dev"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 3ms
25 verbose logfile logs-max:10 dir:/home/simon/.npm/_logs/2023-07-28T19_52_47_461Z-
26 verbose logfile /home/simon/.npm/_logs/2023-07-28T19_52_47_461Z-debug-0.log
27 timing npm:load:logFile Completed in 7ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 25ms
31 silly unpublish args[0] termterm@0.0.0-dev
32 silly unpublish spec Result {
32 silly unpublish   type: 'version',
32 silly unpublish   registry: true,
32 silly unpublish   where: undefined,
32 silly unpublish   raw: 'termterm@0.0.0-dev',
32 silly unpublish   name: 'termterm',
32 silly unpublish   escapedName: 'termterm',
32 silly unpublish   scope: undefined,
32 silly unpublish   rawSpec: '0.0.0-dev',
32 silly unpublish   saveSpec: null,
32 silly unpublish   fetchSpec: '0.0.0-dev',
32 silly unpublish   gitRange: undefined,
32 silly unpublish   gitCommittish: undefined,
32 silly unpublish   gitSubdir: undefined,
32 silly unpublish   hosted: undefined
32 silly unpublish }
33 silly logfile start cleaning logs, removing 2 files
34 silly logfile done cleaning log files
35 http fetch GET 200 https://registry.npmjs.org/termterm?write=true 1871ms (cache updated)
36 http fetch GET 200 https://registry.npmjs.org/termterm?write=true 384ms (cache updated)
37 http fetch PUT 429 https://registry.npmjs.org/termterm/-rev/26-02fc3a546ed613565d3a7d6769d07f31 70400ms attempt #3
38 timing command:unpublish Completed in 72684ms
39 verbose stack HttpErrorGeneral: 429 Too Many Requests - PUT https://registry.npmjs.org/termterm/-rev/26-02fc3a546ed613565d3a7d6769d07f31
39 verbose stack     at /home/simon/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
39 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
39 verbose stack     at async unpublish (/home/simon/.nvm/versions/node/v18.17.0/lib/node_modules/npm/node_modules/libnpmpublish/lib/unpublish.js:90:7)
39 verbose stack     at async otplease (/home/simon/.nvm/versions/node/v18.17.0/lib/node_modules/npm/lib/utils/otplease.js:4:12)
39 verbose stack     at async Unpublish.exec (/home/simon/.nvm/versions/node/v18.17.0/lib/node_modules/npm/lib/commands/unpublish.js:137:7)
39 verbose stack     at async module.exports (/home/simon/.nvm/versions/node/v18.17.0/lib/node_modules/npm/lib/cli.js:89:5)
40 verbose statusCode 429
41 verbose pkgid termterm@0.0.0-dev
42 verbose cwd /home/simon/.cache/repos/termterm
43 verbose Linux 6.2.0-26-generic
44 verbose node v18.17.0
45 verbose npm  v9.6.7
46 error code E429
47 error 429 Too Many Requests - PUT https://registry.npmjs.org/termterm/-rev/26-02fc3a546ed613565d3a7d6769d07f31
48 verbose exit 1
49 timing npm Completed in 72783ms
50 verbose code 1
51 error A complete log of this run can be found in: /home/simon/.npm/_logs/2023-07-28T19_52_47_461Z-debug-0.log
```

### Expected Behavior

When not logged in and trying to unpublish a package, a message should be displayed that the user is not logged in. 

After running npm login, I was asked for a one time password on the website, which I entered. After that, unpublishing the package worked as expected.

### Steps To Reproduce

1. Be logged out
2. Try to unpublish a package
3. The cli does nothing for 70 seconds
4. The cli shows an error 429 Too Many Requests.

### Environment

- npm: 9.6.7
- Node.js: 18.17.0
- OS Name: Ubuntu 23.04
- System Model Name: Xiaomi Air
- npm config:
```ini
; "user" config from /home/simon/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
audit = false 
fund = false 
progress = false 
update-notifier = false 

; node bin location = /home/simon/.nvm/versions/node/v20.3.1/bin/node
; node version = v20.3.1
; npm local prefix = /home/simon
; npm version = 9.6.7
; cwd = /home/simon
; HOME = /home/simon
; Run `npm config ls -l` to show all defaults.

```

**Comment by kchindam-infy** [comment]
**Closing:** this looks to be similar if not a duplicate of an existing issue, https://github.com/npm/cli/issues/8208. If you believe your instance is unique, please provide further clarifying details.
