### ISSUE TITLE
[BUG] <npm crashes when trying to install/uninstall pacakges>

### ISSUE THREAD

**Issue by Raid5594** [npm/cli#669]
# npm crashes when trying to install/uninstall pacakges

I get the following error, when installing the package
Tried to remove npm folder and cache, didn't help

npm install eciesjs 
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #2: Expected object but got null
npm ERR! typeerror     at prepareAction (/usr/local/lib/node_modules/npm/lib/install/actions.js:183:3)
npm ERR! typeerror     at actionsToRun.reduce (/usr/local/lib/node_modules/npm/lib/install/actions.js:152:16)
npm ERR! typeerror     at Array.reduce (<anonymous>)
npm ERR! typeerror     at runSerial (/usr/local/lib/node_modules/npm/lib/install/actions.js:150:29)
npm ERR! typeerror     at doReverseSerial (/usr/local/lib/node_modules/npm/lib/install/actions.js:146:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
npm ERR! typeerror     at withInit.nodeify (/usr/local/lib/node_modules/npm/lib/install/actions.js:131:5)
npm ERR! typeerror     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR! typeerror     at Promise.successAdapter [as _fulfillmentHandler0] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeify.js:23:30)
npm ERR! typeerror     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
npm ERR! typeerror     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
npm ERR! typeerror     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
npm ERR! typeerror     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm ERR! typeerror     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Raid/.npm/_logs/2020-01-08T15_25_45_613Z-debug.log

**Comment by DanielRuf** [comment]
Hi @Raid5594,

Please provide your npm and node versions so we can reproduce it.

`node -v`
`npm -v`

**Comment by ronhupa** [comment]
I am getting the same error when I install a new package. 
```
node -v - v12.16.0
npm -v 6.13.4
```

**Comment by DanielRuf** [comment]
Can not repdoruce on Ubuntu:

```
npm-issue-993 npm install eciesjs

> secp256k1@4.0.0 install /home/druf/Schreibtisch/npm-issue-993/node_modules/secp256k1
> node-gyp-build || exit 0

npm WARN saveError ENOENT: no such file or directory, open '/home/druf/Schreibtisch/npm-issue-993/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/druf/Schreibtisch/npm-issue-993/package.json'
npm WARN @angular/animation@4.0.0-beta.8 requires a peer of @angular/core@4.0.0-beta.8 but none is installed. You must install peer dependencies yourself.
npm WARN npm-issue-993 No description
npm WARN npm-issue-993 No repository field.
npm WARN npm-issue-993 No README data
npm WARN npm-issue-993 No license field.

+ eciesjs@0.3.5
added 15 packages from 105 contributors and audited 24 packages in 4.495s
found 0 vulnerabilities
```

**Comment by ronhupa** [comment]
I encountered this issue when I pulled my code from SVN. There were missing components and inconsistencies in the package.json reason I cannot install a new npm. 

I resolved this by excluding nodes/components and the package.json in SVN.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
