### ISSUE TITLE
[BUG] npm ERR! Cannot read properties of undefined (reading 'isStream')

### ISSUE THREAD

**Issue by mahfuzkhan12** [npm/cli#6696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ERR! Cannot read properties of undefined (reading 'isStream')
Can't install any node packages

Full error - 
npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@9.8.0
npm info using node@v20.5.0
npm verb title npm install
npm verb argv "install" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/home/mahfuz/.npm/_logs/2023-08-07T05_59_47_571Z-
npm verb logfile /home/mahfuz/.npm/_logs/2023-08-07T05_59_47_571Z-debug-0.log
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/win32-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/win32-ia32
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/win32-arm64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/sunos-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/openbsd-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/netbsd-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/linux-s390x
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/linux-riscv64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/linux-ppc64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/linux-mips64el
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/linux-loong64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/linux-ia32
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/linux-arm64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/linux-arm
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/freebsd-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/freebsd-arm64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/darwin-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/darwin-arm64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/android-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/android-arm64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/android-arm
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/fsevents
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/win32-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/win32-ia32
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/win32-arm64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/sunos-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/openbsd-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/netbsd-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/linux-s390x
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/linux-riscv64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/linux-ppc64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/linux-mips64el
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/linux-loong64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/linux-ia32
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/linux-arm64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/linux-arm
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/freebsd-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/freebsd-arm64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/darwin-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/darwin-arm64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/android-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/android-arm64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/android-arm
npm verb audit error TypeError: Cannot read properties of undefined (reading 'isStream')
npm verb audit error     at new Body (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:43:18)
npm verb audit error     at new Request (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/request.js:51:5)
npm verb audit error     at makeFetchHappen (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/index.js:9:19)
npm verb audit error     at doFetch (/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/index.js:108:15)
npm verb audit error     at async [getReport] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:335:21)
npm verb audit error     at async AuditReport.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19)
npm verb audit error  TypeError: Cannot read properties of undefined (reading 'isStream')
npm verb audit error     at new Body (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:43:18)
npm verb audit error     at new Request (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/request.js:51:5)
npm verb audit error     at makeFetchHappen (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/index.js:9:19)
npm verb audit error     at doFetch (/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/index.js:108:15)
npm verb audit error     at async [getReport] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:335:21)
npm verb audit error     at async AuditReport.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:106:19)
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/hpagent
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@types/yauzl
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/@esbuild/linux-x64
npm verb reify failed optional dependency /home/mahfuz/app_d/farrer_watch/node_modules/vite/node_modules/@esbuild/linux-x64
npm verb stack TypeError: Cannot read properties of undefined (reading 'isStream')
npm verb stack     at new Body (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:43:18)
npm verb stack     at new Request (/usr/lib/node_modules/npm/node_modules/minipass-fetch/lib/request.js:51:5)
npm verb stack     at makeFetchHappen (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/index.js:9:19)
npm verb stack     at doFetch (/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/index.js:108:15)
npm verb cwd /home/mahfuz/app_d/farrer_watch
npm verb Linux 5.15.0-78-generic
npm verb node v20.5.0
npm verb npm  v9.8.0
npm ERR! Cannot read properties of undefined (reading 'isStream')
npm verb exit 1
npm verb unfinished npm timer reify 1691387987664
npm verb unfinished npm timer reify:unpack 1691387987896
npm verb unfinished npm timer reifyNode:web/frontend/node_modules/scheduler 1691387987896
npm verb unfinished npm timer reifyNode:web/frontend/node_modules/react-router-dom 1691387987896
npm verb unfinished npm timer reifyNode:web/frontend/node_modules/react-dom 1691387987896
npm verb unfinished npm timer reifyNode:web/frontend/node_modules/react 1691387987896
npm verb unfinished npm timer reifyNode:web/frontend/node_modules/@shopify/polaris 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/zod-to-json-schema 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/zod 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/zip-stream 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/yoga-wasm-web 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/yocto-queue 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/yn 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/yauzl 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/yarn 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/yargs-parser 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/yaml 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/yallist 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/xmlchars 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/xml-name-validator 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/ws 1691387987897
npm verb unfinished npm timer reifyNode:node_modules/write-f

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by BAKFR** [comment]
I've got this bug when trying a `npm install foobar` on an empty project.

This is from a system install on Gentoo


npm config:
```
; node bin location = /usr/bin/node
; node version = v20.6.1
; npm local prefix = /home/bak/tmp
; npm version = 9.8.1
; cwd = /home/bak/tmp
; HOME = /home/bak
; Run `npm config ls -l` to show all defaults.
```


Full log: [2023-12-07T14_49_12_036Z-debug-0.log](https://github.com/npm/cli/files/13601581/2023-12-07T14_49_12_036Z-debug-0.log)

The relevant part:
```
TypeError: Cannot read properties of undefined (reading 'isStream')
      at new Body (/usr/lib64/node_modules/npm/node_modules/minipass-fetch/lib/body.js:43:18)
      at new Request (/usr/lib64/node_modules/npm/node_modules/minipass-fetch/lib/request.js:51:5)
      at makeFetchHappen (/usr/lib64/node_modules/npm/node_modules/make-fetch-happen/lib/index.js:9:19)
      at doFetch (/usr/lib64/node_modules/npm/node_modules/npm-registry-fetch/lib/index.js:108:15)
      at async RegistryFetcher.packument (/usr/lib64/node_modules/npm/node_modules/pacote/lib/registry.js:87:19)
      at async RegistryFetcher.manifest (/usr/lib64/node_modules/npm/node_modules/pacote/lib/registry.js:118:23)
```

**Comment by BAKFR** [comment]
I've found the problem:
the npm system install is inconsistent: there is a `minipass` 3.3.6 inside the `node_modules` of `minipass-fetch` 3.0.3, but it should be v5

`jq '.version, .dependencies' < /usr/lib64/node_modules/npm/node_modules/minipass-fetch/package.json`

```json
"3.0.3"
{
  "minipass": "^5.0.0",
  "minipass-sized": "^1.0.3",
  "minizlib": "^2.1.2"
}
```


`jq '.version' < /usr/lib64/node_modules/npm/node_modules/minipass-fetch/node_modules/minipass/package.json`

```json
"3.3.6"
```

----
It may be specific to Gentoo. @mahfuzkhan12 on which OS did you get this error ? 

In my case, I suspect the nodejs system upgrade does not cleanup all obsolete files.

**Comment by BAKFR** [comment]
After more thought, i'm 95% sure of what's happened.

I used `npm install -g npm` in the past, leading to the creation of `/usr/lib64/node_modules/npm/node_modules/minipass-fetch`.
When I did a system update, it installed the new npm version in its usual path:  `/usr/lib64/node_modules/npm`.
However, this action **didn't** remove the npm `node_modules` content, but instead did overwrite the file, thus preserving the folder `/usr/lib64/node_modules/npm/node_modules/minipass-fetch/node_modules/minipass`.

The recent npm version use the different path  `/usr/lib64/node_modules/npm/node_modules/minipass` for this dependency. 

When resolving dependencies with nodejs, the old version takes priority: old `minipass` is nested inside `minipass-fetch`. new `minipass` is at the same level.

----
I believe this bug is not specific to Gentoo.

Quick fix : uninstall system npm, remove `/usr/lib64/node_modules/npm` if the folder is still there, then reinstall npm.


Bug #6665 is a duplicate of this one.

**Comment by yjeanrenaud** [comment]
it is not specicific to Gentoo. Had this on debian, too

**Comment by pekingPow** [comment]
> Quick fix : uninstall system npm, remove `/usr/lib64/node_modules/npm` if the folder is still there, then reinstall npm.

Similar issue on Mint 20.
This solution worked for me:

1. Uninstall npm:
`sudo apt-get remove npm`

2. Remove npm directory:
`sudo rm -rf /usr/lib/node_modules/npm  # This path might vary`

3. Reinstall npm:
```
nvm install node  # Installs the latest version of Node.js and npm
nvm use node
```

4. Verify installation:
`npm -v`

5. Reinstall project dependencies:
```
cd /path/to/your/project
npm install
```

**Comment by milaninfy** [comment]
**Closing** I believe this issue might have been fixed on latest since recent versions have some fixes and improvements.
If issue persist feel free to create new issue or reopen this.
