### ISSUE TITLE
missing lru-cache

### ISSUE THREAD

**Issue by br4nnigan** [npm/cli#6852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

whatever I do, I get this error:

```
npm --version
/usr/lib/node_modules/npm/lib/es6/validate-engines.js:31
    throw err
    ^

TypeError: LRU is not a constructor
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/semver/classes/range.js:188:15)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/semver/functions/satisfies.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.6.1
```
/usr/lib/node_modules/npm/node_modules/lru-cache exists though. How can this technically be possible?

When I comment the affected lines, everything seens to work fine, it's just cache after all I guess.

I reinstalled npm using pacman, didn't help. I tried to verify in a fresh manjaro install, everything works fine...  using my little trick above I naively tried `/usr/lib/node_modules/npm > npm i lru-cache`, but that fails with some 404 error. `sudo npm i -g lru-cache` worked, but does not solve the problem.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 10.1.0
- Node.js: 20.6.1
- OS Name: Manjaro Linux
- System Model Name: eh?
- npm config:
```ini
; copy and paste output from `npm config ls` here
; node bin location = /usr/bin/node
; node version = v20.6.1
; npm local prefix = /usr/lib/node_modules/npm
; npm version = 10.1.0
; cwd = /usr/lib/node_modules/npm/node_modules
; HOME = /home/xxx

```

**Comment by lukekarrys** [comment]
This seems like a duplicate of https://github.com/npm/cli/issues/6785 although with a different package manager. I'm not able to debug specific distros/package managers. Can you try the steps outlined in that issue and see if it works for you as well?

**Comment by br4nnigan** [comment]
> This seems like a duplicate of #6785 although with a different package manager. I'm not able to debug specific distros/package managers. Can you try the steps outlined in that issue and see if it works for you as well?

It is indeed the same issue and the fix works. Thanks you very much, much appreciated. Have a great day!
