### ISSUE TITLE
[BUG] Dependencies with local file dependencies result in invalid lockfiles

### ISSUE THREAD

**Issue by cascornelissen** [npm/cli#6860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Installing a dependency that contains a local file dependency works but results in an invalid (?) `package-lock.json`. Installing the same dependency again results in the following error:

```
npm ERR! Cannot set properties of null (setting 'peer')
```

### Expected Behavior

Installing and re-installing/updating dependencies that contain local file dependencies works without issues.

### Steps To Reproduce

I've set up an example package at [cascornelissen/test-npm-package](https://github.com/cascornelissen/test-npm-package). All it contains is a single local file dependency that's in the subdirectory of the repository.

1. Setup: `mkdir ./test-npm && cd ./test-npm && npm init -y`
3. Install the dependency the first time (this works): `npm install github:cascornelissen/test-npm-package`
4. Install the same dependency again (this fails): `npm install github:cascornelissen/test-npm-package`

**install-links**
The steps above assume the [`install-links` option](https://docs.npmjs.com/cli/v8/commands/npm-install#install-links) is set to `false` (which is the current default value). It does work when executing the `npm install` command with `--install-links=true`.

**Error**
The stack trace (included below) refers to [this line in `calc-dep-flags.js`](https://github.com/npm/cli/blob/aa6728b1d003f0fc620b074ba0396a3e07f2db6a/workspaces/arborist/lib/calc-dep-flags.js#L101) where it's assumed that `node.target` exists but it does not in this scenario. I've tried patching in a check to make sure `node.target` exists but this happens in at least 5 different places, both in this file and in other files, so my assumption then became that the target _should_ exist.
<details><summary>Stack trace</summary>
<pre>
0 verbose cli /opt/homebrew/Cellar/node/20.5.0/bin/node /opt/homebrew/bin/npm
1 info using npm@10.1.0
2 info using node@v20.5.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/cas/projects/test-npm/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/cas/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 4ms
17 timing npm:load:configload Completed in 4ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm i github:cascornelissen/test-npm-package
22 verbose argv "i" "github:cascornelissen/test-npm-package" "--install-links" "false"
23 timing npm:load:setTitle Completed in 2ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/Users/cas/.npm/_logs/2023-10-03T08_25_44_046Z-
26 verbose logfile /Users/cas/.npm/_logs/2023-10-03T08_25_44_046Z-debug-0.log
27 timing npm:load:logFile Completed in 5ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 20ms
31 timing arborist:ctor Completed in 1ms
32 timing idealTree:init Completed in 7ms
33 silly logfile start cleaning logs, removing 1 files
34 timing arborist:ctor Completed in 0ms
35 silly logfile done cleaning log files
36 timing idealTree:userRequests Completed in 1100ms
37 silly idealTree buildDeps
38 silly fetch manifest test-npm-package@github:cascornelissen/test-npm-package
39 silly placeDep ROOT test-npm-package@ REPLACE for: test-npm@1.0.0 want: github:cascornelissen/test-npm-package
40 timing idealTree:#root Completed in 666ms
41 timing idealTree:node_modules/test-npm-package Completed in 0ms
42 timing idealTree:buildDeps Completed in 668ms
43 timing idealTree Completed in 1775ms
44 timing command:i Completed in 1778ms
45 verbose stack TypeError: Cannot set properties of null (setting 'peer')
45 verbose stack     at visit (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:101:54)
45 verbose stack     at visitNode (/opt/homebrew/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:58:25)
45 verbose stack     at next (/opt/homebrew/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:44:19)
45 verbose stack     at depth (/opt/homebrew/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:83:10)
45 verbose stack     at depth (/opt/homebrew/lib/node_modules/npm/node_modules/treeverse/lib/depth.js:27:12)
45 verbose stack     at unsetFlag (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:96:5)
45 verbose stack     at /opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:63:7
45 verbose stack     at Map.forEach (<anonymous>)
45 verbose stack     at calcDepFlagsStep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:41:17)
45 verbose stack     at visit (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:12:20)
46 verbose cwd /Users/cas/projects/test-npm
47 verbose Darwin 22.6.0
48 verbose node v20.5.0
49 verbose npm  v10.1.0
50 error Cannot set properties of null (setting 'peer')
51 verbose exit 1
52 timing npm Completed in 1924ms
53 verbose unfinished npm timer reify 1696321544192
54 verbose unfinished npm timer reify:loadTrees 1696321544193
55 verbose unfinished npm timer idealTree:fixDepFlags 1696321545968
56 verbose code 1
57 error A complete log of this run can be found in: /Users/cas/.npm/_logs/2023-10-03T08_25_44_046Z-debug-0.log
</pre>
</details> 

**Lockfile**
Looking into the lockfile I noticed there's a package listed at `node_modules/test-npm-package/subdependency` which contains no data.

```
"node_modules/test-npm-package": {
  "resolved": "git+ssh://git@github.com/cascornelissen/test-npm-package.git#0ae7cc600e142043e0ad819dcc045c4a2a9899ec",
  "dependencies": {
    "test-npm-package-subdependency": "file:subdependency"
  }
},
"node_modules/test-npm-package-subdependency": {
  "resolved": "node_modules/test-npm-package/subdependency",
  "link": true
},
"node_modules/test-npm-package/subdependency": {}
```

For good measure, here's what the same part of the lockfile looks like with `--install-links` set to `true`.

```
"node_modules/test-npm-package": {
  "resolved": "git+ssh://git@github.com/cascornelissen/test-npm-package.git#0ae7cc600e142043e0ad819dcc045c4a2a9899ec",
  "dependencies": {
    "test-npm-package-subdependency": "file:subdependency"
  }
},
"node_modules/test-npm-package-subdependency": {
  "resolved": "file:node_modules/test-npm-package/subdependency"
}
```

**Conclusion**
To me it feels like there's an issue in the generation of the lockfile, `node_modules/test-npm-package/subdependency` should be pointing to _something_, no? I'll investigate a bit further but wanted to create this ticket already, since maybe someone with more contextual knowledge has an answer.

**Related issues**
* https://github.com/npm/cli/issues/6405 might be related but it's about devDependencies
* https://github.com/npm/cli/issues/6430 seems to have a similar use-case but it's about a different property
* https://github.com/npm/cli/issues/6622 reports the same error but mentions deleting `node_modules/` works as a workaround, which doesn't work in this scenario
* https://github.com/npm/cli/issues/5007 is probably the closest match but...
  * a lot of the earlier comments are about workspace-related configurations, this scenario is not using workspaces.
  * for a part of the commenters the bug seems to have been solved in `8.16.0`

### Environment

- npm: `10.1.0`
- Node.js: `20.5.0`
- OS Name: macOS Mojave (also confirmed on Windows 11 with WSL)
- System Model Name: Macbook Pro
- npm config:
```ini
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew"

; "user" config from /Users/cas/.npmrc

; node bin location = /opt/homebrew/Cellar/node/20.5.0/bin/node
; node version = v20.5.0
; npm local prefix = /Users/cas/projects/test-npm
; npm version = 10.1.0
; cwd = /Users/cas/projects/test-npm
; HOME = /Users/cas
; Run `npm config ls -l` to show all defaults.
```

**Comment by cascornelissen** [comment]
After going down this rabbit hole for a bit, I've found that commenting out the following line results in an install that passes. Not sure why just yet, but I did want to document the end of this rabbit hole 🐇 

https://github.com/npm/cli/blob/aa6728b1d003f0fc620b074ba0396a3e07f2db6a/workspaces/arborist/lib/node.js#L1178

The `node.replace()` method is called when placing the dependency on this line where I'm assuming it's trying to replace the old dependency with the new dependency.

https://github.com/npm/cli/blob/aa6728b1d003f0fc620b074ba0396a3e07f2db6a/workspaces/arborist/lib/place-dep.js#L387

----

I've also tried the different install-strategies:

| | `hoisted` (default) | `nested` | `shallow` | `linked` (experimental) |
|-|--------|--------|--------|--------|
|First install| ✅  | ✅  | ✅  | 💥 fails on `target` being undefined at [isolated-reifier.js#L405](https://github.com/npm/cli/blob/aa6728b1d003f0fc620b074ba0396a3e07f2db6a/workspaces/arborist/lib/arborist/isolated-reifier.js#L405) |
|Second install| 💥  | ✅  | ✅  |  |

**Comment by mknj** [comment]
Similar behaviour without installing the same package twice. Tested with different node and npm versions on debian latest.

```bash
mkdir testingworkspaces
cd testingworkspaces
npm init -y
npm pkg set workspaces[]=appa
npm pkg set workspaces[]=appb
npm pkg set workspaces[]=lib1
npm pkg set workspaces[]=lib2
npm pkg set workspaces[]=sharedlib
npm pkg set scripts.buildA="npm run build -w sharedlib -w lib1 -w appb" # build appA and its deps
mkdir lib1
mkdir lib2
mkdir appa
mkdir appb
mkdir sharedlib
for x in lib* app* sharedlib ;do pushd $x;npm init -y;popd;done
cd appa
npm i ../lib1
cd ../appb
npm i ../lib2 # npm ERR! Cannot set properties of null (setting 'dev')
```

**Comment by owlstronaut** [comment]
I've validated that this was failing when this issue was created, but was fixed sometime between then and 11.2.0. Closing

<details>
  <summary>test script</summary>
```
#!/bin/bash

# Test the EXACT reproduction case from issue #6860 comment
# This demonstrates the issue failing in npm 10.1.0 and working in npm 11.2.0
# Reproduction steps from: https://github.com/npm/cli/issues/6860#issuecomment-1978281157

echo "=========================================="
echo "Issue #6860 Reproduction Test"
echo "=========================================="
echo
echo "Testing the exact workspace scenario that failed in npm 10.1.0"
echo "Commands from issue comment:"
echo "mkdir testingworkspaces && cd testingworkspaces"
echo "npm init -y && npm pkg set workspaces[]=appa && npm pkg set workspaces[]=appb"
echo "npm pkg set workspaces[]=lib1 && npm pkg set workspaces[]=lib2 && npm pkg set workspaces[]=sharedlib"
echo "mkdir lib1 lib2 appa appb sharedlib"
echo "for x in lib* app* sharedlib ;do pushd \$x;npm init -y;popd;done"
echo "cd appa && npm i ../lib1"
echo "cd ../appb && npm i ../lib2  # <-- This failed with 'Cannot set properties of null (setting dev)'"
echo

test_npm_version() {
    local VERSION=$1
    local EXPECTED_RESULT=$2
    
    echo "=========================================="
    echo "Testing with npm $VERSION"
    echo "=========================================="
    
    # Clean up any previous test
    rm -rf /tmp/issue-6860-test-$VERSION
    mkdir -p /tmp/issue-6860-test-$VERSION
    cd /tmp/issue-6860-test-$VERSION
    
    echo "Setting up workspace structure..."
    
    # Execute the exact commands from the issue comment
    mkdir testingworkspaces
    cd testingworkspaces
    npx npm@$VERSION init -y --silent
    npx npm@$VERSION pkg set workspaces[]=appa
    npx npm@$VERSION pkg set workspaces[]=appb
    npx npm@$VERSION pkg set workspaces[]=lib1
    npx npm@$VERSION pkg set workspaces[]=lib2
    npx npm@$VERSION pkg set workspaces[]=sharedlib
    npx npm@$VERSION pkg set scripts.buildA="npm run build -w sharedlib -w lib1 -w appb"
    
    mkdir lib1 lib2 appa appb sharedlib
    
    # Initialize each workspace (using pushd/popd as in original)
    for x in lib1 lib2 appa appb sharedlib; do
        pushd $x > /dev/null
        npx npm@$VERSION init -y --silent
        popd > /dev/null
    done
    
    echo "Workspace structure created successfully"
    echo
    echo "Step 1: cd appa && npm i ../lib1"
    
    cd appa
    npx npm@$VERSION i ../lib1 --silent
    
    if [ $? -eq 0 ]; then
        echo "PASS: appa installed lib1 successfully"
    else
        echo "FAIL: appa could not install lib1"
        return 1
    fi
    
    echo
    echo "Step 2: cd ../appb && npm i ../lib2"
    echo "NOTE: This is the critical command that failed in the original issue"
    
    cd ../appb
    npx npm@$VERSION i ../lib2 2>/dev/null
    
    local RESULT=$?
    echo
    
    if [ $RESULT -eq 0 ]; then
        echo "RESULT: appb installed lib2 successfully"
        if [ "$EXPECTED_RESULT" = "FAIL" ]; then
            echo "STATUS: UNEXPECTED - Issue did not reproduce (may have been patched)"
        else
            echo "STATUS: EXPECTED - Working as intended"
        fi
    else
        echo "RESULT: appb failed to install lib2"
        if [ "$EXPECTED_RESULT" = "FAIL" ]; then
            echo "STATUS: EXPECTED - Issue reproduced successfully"
            echo "ERROR: Should show 'Cannot set properties of null (setting dev)'"
        else
            echo "STATUS: UNEXPECTED - Issue has regressed"
        fi
    fi
    
    return $RESULT
}

# Test npm 10.1.0 (should fail)
test_npm_version "10.1.0" "FAIL"
NPM_10_RESULT=$?

echo
echo

# Test npm 11.2.0 (should work)  
test_npm_version "11.2.0" "PASS"
NPM_11_RESULT=$?

echo
echo "=========================================="
echo "FINAL SUMMARY"
echo "=========================================="
echo "npm 10.1.0 result: $([ $NPM_10_RESULT -eq 0 ] && echo "PASSED (unexpected)" || echo "FAILED (as expected)")"
echo "npm 11.2.0 result: $([ $NPM_11_RESULT -eq 0 ] && echo "PASSED (as expected)" || echo "FAILED (unexpected)")"
echo
echo "This demonstrates that issue #6860 was resolved between npm 10.1.0 and 11.2.0"
echo "The exact workspace scenario that caused 'Cannot set properties of null (setting dev)'"
echo "now works correctly in newer npm versions."
echo "=========================================="
```
</details>
