### ISSUE TITLE
[BUG] "Cannot read property 'match' of undefined" when doing npm audit fix

### ISSUE THREAD

**Issue by wolfy1339** [npm/cli#703]
# What / Why

> Running `npm audit fix` makes npm crash.
<details>
<pre>
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'audit',
1 verbose cli   'fix'
1 verbose cli ]
2 info using npm@6.13.6
3 info using node@v13.1.0
4 verbose npm-session ab17f89929670339
5 timing audit submit Completed in 3136ms
6 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits 3184ms
7 timing audit body Completed in 66ms
8 verbose audit installing [
8 verbose audit   'postcss-loader>postcss-load-config>cosmiconfig>js-yaml@3.13.1',
8 verbose audit   'fork-ts-checker-webpack-plugin-alt>chokidar>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'react-dev-utils>fork-ts-checker-webpack-plugin>chokidar>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'webpack>watchpack>chokidar>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'babel-jest>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>jest-config>babel-jest>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-jasmine2>jest-runtime>jest-config>babel-jest>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-runtime>jest-config>babel-jest>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>jest-config>babel-jest>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>babel-jest>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>babel-jest>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>babel-jest>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runner>jest-jasmine2>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runner>jest-jasmine2>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-jasmine2>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>jest-jasmine2>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>jest-jasmine2>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>jest-jasmine2>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runner>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runner>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>@jest/test-sequencer>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>jest-config>@jest/test-sequencer>jest-runner>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>jest-config>@jest/test-sequencer>jest-runner>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runner>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runner>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>jest-config>@jest/test-sequencer>jest-runner>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>jest-config>@jest/test-sequencer>jest-runner>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runner>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runner>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>jest-config>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-runtime>jest-config>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>jest-config>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>jest-jasmine2>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>jest-config>jest-environment-jsdom>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-jasmine2>jest-runtime>jest-config>jest-environment-jsdom>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-runtime>jest-config>jest-environment-jsdom>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>jest-config>jest-environment-jsdom>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>jest-environment-jsdom>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>jest-environment-jsdom>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>jest-environment-jsdom>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>jest-config>jest-environment-node>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-jasmine2>jest-runtime>jest-config>jest-environment-node>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-runtime>jest-config>jest-environment-node>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>jest-config>jest-environment-node>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>jest-environment-node>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>jest-environment-node>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>jest-environment-node>@jest/environment>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runner>jest-jasmine2>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runner>jest-jasmine2>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-jasmine2>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>jest-jasmine2>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>jest-jasmine2>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>jest-jasmine2>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runner>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runner>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>@jest/test-sequencer>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/transform>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>jest-config>@jest/test-sequencer>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-jasmine2>jest-runtime>jest-config>@jest/test-sequencer>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-runtime>jest-config>@jest/test-sequencer>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>jest-config>@jest/test-sequencer>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>@jest/test-sequencer>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>jest-config>@jest/test-sequencer>jest-runner>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>jest-config>@jest/test-sequencer>jest-runner>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runner>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runner>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runner>jest-jasmine2>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runner>jest-jasmine2>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-jasmine2>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>jest-jasmine2>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>jest-jasmine2>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>jest-jasmine2>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runner>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runner>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runner>jest-config>@jest/test-sequencer>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-config>@jest/test-sequencer>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>jest-config>@jest/test-sequencer>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   'jest>jest-cli>@jest/core>jest-runtime>jest-haste-map>anymatch>micromatch>braces>snapdragon>base>cache-base>set-value@2.0.1',
8 verbose audit   ... 12903 more items
8 verbose audit ]
9 silly install loadCurrentTree
10 silly install readLocalPackageData
11 timing stage:loadCurrentTree Completed in 2466ms
12 silly install loadIdealTree
13 silly install cloneCurrentTreeToIdealTree
14 timing stage:loadIdealTree:cloneCurrentTree Completed in 24ms
15 silly install loadShrinkwrap
16 timing stage:rollbackFailedOptional Completed in 1ms
17 timing stage:runTopLevelLifecycles Completed in 2698ms
18 verbose stack TypeError: Cannot read property 'match' of undefined
18 verbose stack     at tarballToVersion (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:87:20)
18 verbose stack     at inflatableChild (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:99:22)
18 verbose stack     at C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:55:12
18 verbose stack     at tryCatcher (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
18 verbose stack     at Object.gotValue (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)
18 verbose stack     at Object.gotAccum (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)
18 verbose stack     at Object.tryCatcher (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
18 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
18 verbose stack     at Promise._settlePromise (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
18 verbose stack     at Promise._settlePromiseCtx (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:611:10)
18 verbose stack     at _drainQueueStep (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
18 verbose stack     at _drainQueue (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
18 verbose stack     at Async._drainQueues (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
18 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\<user>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
18 verbose stack     at processImmediate (internal/timers.js:439:21)
19 verbose cwd C:\Users\<user>\Desktop\Programming\github-notification-service\dashboard
20 verbose Windows_NT 10.0.18363
21 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<user>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "audit" "fix"
22 verbose node v13.1.0
23 verbose npm  v6.13.6
24 error Cannot read property 'match' of undefined
25 verbose exit [ 1, true ]
</pre>
</details>

## When

* All the time

## Where

* https://github.com/hellomouse/GNS/tree/master/dashboard

### Current Behavior

* n/a

### Steps to Reproduce

* git clone --depth=1 https://github.com/hellomouse/GNS/
* cd dashboard
* npm audit fix

### Expected Behavior

* For it to not throw an error and work properly.

## Who

* @npm/cli-team

## References

* n/a

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.
