### ISSUE TITLE
[BUG] linked install: TypeError: Cannot read properties of undefined (reading 'isProjectRoot')

### ISSUE THREAD

**Issue by selfisekai** [npm/cli#7067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
53 warn reify The "linked" install strategy is EXPERIMENTAL and may contain bugs.
54 timing reify:diffTrees Completed in 23ms
55 silly reify moves {}
56 timing reify:retireShallow Completed in 0ms
57 timing reify:createSparse Completed in 159ms
58 timing reify:rollback:createSparse Completed in 282ms
59 timing reify:rollback:retireShallow Completed in 0ms
60 timing command:ci Completed in 1601ms
61 verbose stack TypeError: Cannot read properties of undefined (reading 'isProjectRoot')
61 verbose stack     at [addOmitsToTrashList] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:490:16)
61 verbose stack     at [reifyPackages] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:251:29)
61 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:170:5)
61 verbose stack     at async CI.exec (/usr/lib/node_modules/npm/lib/commands/ci.js:87:5)
61 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli-entry.js:61:5)
62 verbose cwd /home/lauren/aports/testing/bruno/src/bruno-1.4.0
63 verbose Linux 6.6.4-1-lts
64 verbose node v20.10.0
65 verbose npm  v10.2.5
66 error Cannot read properties of undefined (reading 'isProjectRoot')
67 verbose exit 1
68 timing npm Completed in 1793ms
```

### Expected Behavior

successfully installing dependencies

### Steps To Reproduce

1. clone https://github.com/usebruno/bruno/releases/tag/v1.4.0
2. `npm ci --ignore-scripts --install-strategy=linked --omit=dev`

### Environment

- npm: 10.2.5
- Node.js: v20.10.0
- OS Name: Alpine Linux edge
- System Model Name: x86_64 PC
- npm config:
```ini
; "builtin" config from /usr/lib/node_modules/npm/npmrc

globalignorefile = "/etc/npmignore" 
prefix = "/usr/local" 
python = "/usr/bin/python3" 

; node bin location = /usr/bin/node
; node version = v20.10.0
; npm local prefix = /home/lauren/aports/testing/bruno/src/bruno-1.4.0
; npm version = 10.2.5
; cwd = /home/lauren/aports/testing/bruno/src/bruno-1.4.0
; HOME = /home/lauren
; Run `npm config ls -l` to show all defaults.
```

**Comment by owlstronaut** [comment]
Fixed by https://github.com/npm/cli/pull/8996
