### ISSUE TITLE
[BUG] Local path `peerDependencies` behave like `dependencies`

### ISSUE THREAD

**Issue by DanKaplanSES** [npm/cli#7171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

App depends on Lib. Lib has a peerDependency on `jsdom`.

I believe App's `jsdom` stack traces should come from `app-package` because `jsdom` is a _peerDependency_ of `lib-package`. That is not the case:

```
C:\MyPackages\jsdom-sandbox\lib-package\node_modules\jsdom\lib\api.js:321
        throw new TypeError("resources must be an instance of ResourceLoader");
              ^

TypeError: resources must be an instance of ResourceLoader
    at resourcesToResourceLoader (C:\MyPackages\jsdom-sandbox\lib-package\node_modules\jsdom\lib\api.js:321:15)
    at transformOptions (C:\MyPackages\jsdom-sandbox\lib-package\node_modules\jsdom\lib\api.js:263:46)
    at new JSDOM (C:\MyPackages\jsdom-sandbox\lib-package\node_modules\jsdom\lib\api.js:34:15)
    at JSDOM.fromFile (C:\MyPackages\jsdom-sandbox\lib-package\node_modules\jsdom\lib\api.js:152:12)
```

Explicitly adding `jsdom` as a dependency to `app-package` makes no difference.

### Expected Behavior

```
C:\MyPackages\jsdom-sandbox\app-package\node_modules\jsdom\lib\api.js:321
        throw new TypeError("resources must be an instance of ResourceLoader");
              ^

TypeError: resources must be an instance of ResourceLoader
    at resourcesToResourceLoader (C:\MyPackages\jsdom-sandbox\app-package\node_modules\jsdom\lib\api.js:321:15)
    at transformOptions (C:\MyPackages\jsdom-sandbox\app-package\node_modules\jsdom\lib\api.js:263:46)
    at new JSDOM (C:\MyPackages\jsdom-sandbox\app-package\node_modules\jsdom\lib\api.js:34:15)
    at JSDOM.fromFile (C:\MyPackages\jsdom-sandbox\app-package\node_modules\jsdom\lib\api.js:152:12)
```

### Steps To Reproduce

1. Git clone https://github.com/DanKaplanSES/jsdom-sandbox/tree/local-path-peer-dependencies-reproducible
2. `cd local-path-peer-dependencies-reproducible`
3. `./setup.sh`
4. `./npma.sh run exec`

This is related to #5108 

### Environment

- npm: 10.3.0
- Node.js: 20.10.0
- OS Name: Windows
- System Model Name: 10
- npm config:
```ini
; "builtin" config from C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\myuser\\AppData\\Roaming\\npm"

; "user" config from C:\cygwin64\home\myuser\.npmrc

//registry.npmjs.org/:_authToken = (protected)
registry = "https://registry.npmjs.org/"
script-shell = "C:\\cygwin64\\bin\\bash.exe"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.10.0
; npm local prefix = C:\my-projects\jsdom-sandbox
; npm version = 10.3.0
; cwd = C:\my-projects\jsdom-sandbox
; HOME = C:\cygwin64\home\myuser
; Run `npm config ls -l` to show all defaults.
```

**Comment by DanKaplanSES** [comment]
This is an issue in `yarn` too. Fortunately, [a comment provides a workaround that works in both package managers](https://github.com/yarnpkg/yarn/issues/8105#issuecomment-832160947):

> for those wondering; I ran into the same issue and used [yalc](https://github.com/wclr/yalc) to fix my problem.

**Comment by kchindam-infy** [comment]
This issue can be resolved by using --install-links during npm install. Eg: npm i --install -links.  --install-links option helps in installing the local dependenciesas packages instead of creating a symlink in the node_modules of app-package. Ref: https://docs.npmjs.com/cli/v8/commands/npm-install

**Comment by DanKaplanSES** [comment]
That worked for me!

There's no documentation about using `--install-links` without an argument. Does that make it true or false?

---

That said, why should `--install-links` change the behavior of `peerDependencies`? That still seems like a bug to me: whether lib is a symlink or not, `peerDependencies` should act like `peerDependencies`, no?

**Comment by kchindam-infy** [comment]
No argument in this case is equivalent to true.
'npm i --install-links' is equivalent to 'npm i --install-links=true'

**Comment by DanKaplanSES** [comment]
@kchindam-infy Thanks for the help! 

[The latest documentation](https://docs.npmjs.com/cli/v11/commands/npm-install#install-links) says: 

> When set file: protocol dependencies will be packed and installed as regular dependencies instead of creating a symlink. This option has no effect on workspaces.

I may lack some fundamental terminology, but I don't feel like the information you've provided is documented:

1. "regular dependencies" is ambiguous. I thought it meant, "As opposed to `devDependencies`, `peerDependencies`, etc." It seems like it meant, "As opposed to file: protocol dependencies." 
2. ~"When set..." is incorrect: There are three ways to set this flag (`--install-links=true`, `--install-links`, and `--install-links=false`), and this behavior doesn't apply to all three.~ (This point was more pedantic than I realized when I wrote it. I don't think it's relevant to the big picture.)

---

In addition, this still feels like a bug to me, or at the very least, something that should be thoroughly documented because there are portions of [the `peerDependencies` documentation](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#peerdependencies) that are incorrect for certain values of `--install-links`.

![Image](https://github.com/user-attachments/assets/68bec26c-da4c-4308-9a1a-e80d29494200)

When `--install-links=false` or unset:

3. The peerDependency *is not* installed alongside the host `app-package`
4. The dependency graph does not look like this. I did an `npm list` in `app-package` directory and there is no `jsdom` dependency:
    dankaplanses-app-package@0.0.1 app-package
    ├── @prettier/sync@0.3.0
    ├── @types/jasmine@5.1.7
    ├── @types/jquery@3.5.32
    ├── @types/jsdom@21.1.7
    ├── eslint-config-prettier@9.1.0
    ├── eslint-plugin-no-floating-promise@1.0.2
    ├── eslint-plugin-prettier@5.2.3
    ├── eslint@8.57.1
    ├── jasmine@5.6.0
    ├── jsdom-configurable-resource-loader@0.0.8
    ├── lib-package@npm:dankaplanses-lib-package@0.0.1 -> .\..\lib-package
    └── prettier@3.5.3
5. `peerDependencies` are not being installed

**Comment by DanKaplanSES** [comment]
@kchindam-infy Apologies for the ping, but I still have this question:

> Why should `--install-links` change the behavior of `peerDependencies`? That still seems like a bug to me: whether lib is a symlink or not, `peerDependencies` should act like `peerDependencies`, no?

This caused a major problem for me recently that I have thoroughly documented here: https://github.com/jsdom/jsdom/issues/3884#issue-3092363535
