### ISSUE TITLE
[BUG] [DEP0170] DeprecationWarning for git+ssh:// dependencies#tag

### ISSUE THREAD

**Issue by DeepzUa** [npm/cli#7319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

[DEP0170](https://nodejs.org/api/deprecations.html#DEP0170) is active

I seen issue #6869, but instead of commit hash, i use #tag

``` json
{
  "dependencies": {
    "something-private": "git+ssh://git@gitlab.example.com:group/project.git#tag"
  }
}
```

### Environment

- npm: 10.5.0
- Node.js: 20.12.0
- OS Name: Windows 10
- System Model Name:

**Comment by lzsheng** [comment]
the same error~~
npm: 10.5.0
Node.js: 20.12.1
OS Name: MacOS 12.6

**Comment by gokulb9993** [comment]
Same error for me as well.

**Comment by kyleclough** [comment]
Same error here:
npm: 10.5.0
Node.js: 20.12.2

**Comment by wraithgar** [comment]
Where are you seeing this? What command are you running?

I can not reproduce this

```sh
~/D/n/s/triage $ npm i

added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
~/D/n/s/triage $ npm pkg get dependencies
{
  "@gar/promisify": "git+ssh://git@github.com:wraithgar/gar-promisify.git#main"
}
```

**Comment by wraithgar** [comment]
Tags make no difference either

```sh
~/D/n/s/triage $ npm i

added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
~/D/n/s/triage $ npm pkg get dependencies
{
  "@gar/promisify": "git+ssh://git@github.com:wraithgar/gar-promisify.git#v1.1.3"
}
```

**Comment by Guihgo** [comment]
same here

**Comment by earonesty** [comment]
here's a trace... 
```
(node:56977) [DEP0170] DeprecationWarning: The URL ssh://git@github.com:puzzlefin/sqcache-node.git is invalid. Future versions of Node.js will throw an error.
    at getHostname (node:url:516:17)
    at Url.parse (node:url:384:14)
    at urlParse (node:url:141:13)
    at GitResolver.<anonymous> (/home/erik/.nvm/versions/node/v20.11.1/lib/node_modules/yarn/lib/cli.js:37285:19)
    at Generator.next (<anonymous>)
    at step (/home/erik/.nvm/versions/node/v20.11.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/erik/.nvm/versions/node/v20.11.1/lib/node_modules/yarn/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/home/erik/.nvm/versions/node/v20.11.1/lib/node_modules/yarn/lib/cli.js:5539:28)
    at GitResolver.<anonymous> (/home/erik/.nvm/versions/node/v20.11.1/lib/node_modules/yarn/lib/cli.js:307:12)
```

this is a YARN issue, not an npm issue

**Comment by wraithgar** [comment]
If someone has a reproducible case for this please open a new issue w/ steps on how to reproduce.  Adding comments to this issue is not going to help.
