### ISSUE TITLE
Error after upgrading generic-pool from 2.4.2 to 3.7.1

### ISSUE THREAD

**Issue by akhilareddy09** [npm/cli#749]
I've upgraded generic-pool from the version 2.4.2 to 3.7.1 after which I'm facing the following issue

Exception has occurred: TypeError
TypeError: Cannot read property 'create' of undefined
    at module.exports (..\node_modules\generic-pool\lib\factoryValidator.js:2:22)
    at new Pool (..\node_modules\generic-pool\lib\Pool.js:47:5)
    at Object.<anonymous> (......)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

**Comment by ljharb** [comment]
Then you’ll need to file an issue on that package.

**Comment by DanielRuf** [comment]
Please report this at https://github.com/coopernurse/node-pool/issues and close this here.
