### ISSUE TITLE
[BUG] Throw err 'package/lib/cli/validate-engines.js:31'

### ISSUE THREAD

**Issue by bourbonut** [npm/cli#7510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
~> npm
fish: Unknown command: npm
~> curl https://www.npmjs.com/install.sh | sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3755  100  3755    0     0  39946      0 --:--:-- --:--:-- --:--:-- 39946
fetching: https://registry.npmjs.org/npm/-/npm-10.7.0.tgz
removing existing npm
/tmp/npm.22228/package/lib/cli/validate-engines.js:31
    throw err
    ^

TypeError: args.at is not a function
    at process.<anonymous> (/tmp/npm.22228/package/lib/utils/display.js:91:21)
    at process.emit (events.js:412:35)
    at Object.verbose (/tmp/npm.22228/package/node_modules/proc-log/lib/index.js:68:22)
    at module.exports (/tmp/npm.22228/package/lib/cli/entry.js:25:7)
    at module.exports (/tmp/npm.22228/package/lib/cli/validate-engines.js:39:10)
    at module.exports (/tmp/npm.22228/package/lib/cli.js:4:31)
    at Object.<anonymous> (/tmp/npm.22228/package/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
failed!
```

### Steps To Reproduce

Run command : `curl https://www.npmjs.com/install.sh | sh`

### Environment

- Node.js: `v14.21.3`
- OS Name: Ubuntu 20.04
- System Model Name: MSI Prestige

**Comment by wraithgar** [comment]
That version of Node.js is not currently supported.  The latest npm requires `18.17.0` or newer

**Comment by weboson** [comment]
I moved the application to WSL (Ubuntu), also installed NVM (0.40.3 for Ubuntu) Node 14.18.2 (node ​​v14.18.2 (npm v6.14.15)) version and everything worked (without errors).
