### ISSUE TITLE
[BUG] OpenBSD usage failure

### ISSUE THREAD

**Issue by g2px1** [npm/cli#7696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm using OpenBSD 7.5 (latest as for now). NodeJS installed via pkg_add (Node.js v18.19.1). Any npm's command ends with provided result. 

For example `npm -v` or `doas npm -v`:
```
/usr/local/lib/node_modules/npm/lib/es6/validate-engines.js:31
    throw err
    ^

TypeError: Minipass is not a constructor
    at LogFiles.on (/usr/local/lib/node_modules/npm/lib/utils/log-file.js:59:23)
    at new LogFiles (/usr/local/lib/node_modules/npm/lib/utils/log-file.js:41:10)
    at <instance_members_initializer> (/usr/local/lib/node_modules/npm/lib/npm.js:52:14)
    at new Npm (/usr/local/lib/node_modules/npm/lib/npm.js:75:15)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli-entry.js:17:15)
    at module.exports (/usr/local/lib/node_modules/npm/lib/es6/validate-engines.js:39:10)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:4:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

Node.js v18.19.1
```

### Expected Behavior

Correctly working npm

### Steps To Reproduce

1.
```bash
doas pkg_add node
```
2. 
```bash
npm -v
```

### Environment

- npm: `npm -v` doesn't work
- Node.js: 18.19.1
- OS Name: OpenBSD
- System Model Name: hw.product=X99
- npm config:  `npm config ls` doesn't work

**Comment by wraithgar** [comment]
This appears to be an issue with `pkg_add`, it has installed an invalid setup for npm itself.  You may want to try a [direct download](https://github.com/npm/cli?tab=readme-ov-file#direct-download) installation, or use a different node installation process.
