### ISSUE TITLE
[BUG] cannot build from working copy

### ISSUE THREAD

**Issue by boneskull** [npm/cli#7780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am following the instructions in [`CONTRIBUTING.md`](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md), but one of the build scripts fails (guessing `scripts/dependency-graph.js`):

```
❯ node ./scripts/resetdeps.js
INFO spawn git status
On branch latest
Your branch is up to date with 'origin/latest'.

nothing to commit, working tree clean
INFO spawn git checkout node_modules/
Updated 1354 paths from the index
INFO spawn node . i --ignore-scripts --no-audit --no-fund
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 819 packages, and changed 12 packages in 4s
INFO spawn node . rebuild --ignore-scripts
rebuilt dependencies successfully
INFO spawn node . run dependencies --ignore-scripts

> npm@10.8.3 dependencies
> node scripts/bundle-and-gitignore-deps.js && node scripts/dependency-graph.js

INFO spawn git ls-files --cached --ignored --exclude-standard /Users/boneskull/projects/npm/cli/node_modules
INFO spawn git rm node_modules/@isaacs/cliui/build/index.cjs --force
rm 'node_modules/@isaacs/cliui/build/index.cjs'
INFO spawn git rm node_modules/@isaacs/cliui/build/index.d.cts --force
rm 'node_modules/@isaacs/cliui/build/index.d.cts'
INFO spawn git rm node_modules/@isaacs/cliui/build/lib/index.js --force
rm 'node_modules/@isaacs/cliui/build/lib/index.js'
INFO spawn git rm node_modules/make-fetch-happen/lib/cache/entry.js --force
rm 'node_modules/make-fetch-happen/lib/cache/entry.js'
INFO spawn git rm node_modules/make-fetch-happen/lib/cache/errors.js --force
rm 'node_modules/make-fetch-happen/lib/cache/errors.js'
INFO spawn git rm node_modules/make-fetch-happen/lib/cache/index.js --force
rm 'node_modules/make-fetch-happen/lib/cache/index.js'
INFO spawn git rm node_modules/make-fetch-happen/lib/cache/key.js --force
rm 'node_modules/make-fetch-happen/lib/cache/key.js'
INFO spawn git rm node_modules/make-fetch-happen/lib/cache/policy.js --force
rm 'node_modules/make-fetch-happen/lib/cache/policy.js'
INFO spawn git rm node_modules/smart-buffer/build/smartbuffer.js --force
rm 'node_modules/smart-buffer/build/smartbuffer.js'
INFO spawn git rm node_modules/smart-buffer/build/utils.js --force
rm 'node_modules/smart-buffer/build/utils.js'
INFO spawn git rm node_modules/socks/build/client/socksclient.js --force
rm 'node_modules/socks/build/client/socksclient.js'
INFO spawn git rm node_modules/socks/build/common/constants.js --force
rm 'node_modules/socks/build/common/constants.js'
INFO spawn git rm node_modules/socks/build/common/helpers.js --force
rm 'node_modules/socks/build/common/helpers.js'
INFO spawn git rm node_modules/socks/build/common/receivebuffer.js --force
rm 'node_modules/socks/build/common/receivebuffer.js'
INFO spawn git rm node_modules/socks/build/common/util.js --force
rm 'node_modules/socks/build/common/util.js'
INFO spawn git rm node_modules/socks/build/index.js --force
rm 'node_modules/socks/build/index.js'
INFO spawn git ls-files --cached --ignored --exclude-standard /Users/boneskull/projects/npm/cli/node_modules
Wrote to node_modules/.gitignore
node:internal/modules/cjs/loader:1251
  throw err;
  ^

Error: Cannot find module './cache/policy.js'
Require stack:
- /Users/boneskull/projects/npm/cli/node_modules/make-fetch-happen/lib/fetch.js
- /Users/boneskull/projects/npm/cli/node_modules/make-fetch-happen/lib/index.js
- /Users/boneskull/projects/npm/cli/node_modules/npm-registry-fetch/lib/index.js
- /Users/boneskull/projects/npm/cli/node_modules/pacote/lib/remote.js
- /Users/boneskull/projects/npm/cli/node_modules/pacote/lib/git.js
- /Users/boneskull/projects/npm/cli/node_modules/pacote/lib/fetcher.js
- /Users/boneskull/projects/npm/cli/node_modules/pacote/lib/index.js
- /Users/boneskull/projects/npm/cli/node_modules/@npmcli/metavuln-calculator/lib/index.js
- /Users/boneskull/projects/npm/cli/workspaces/arborist/lib/audit-report.js
- /Users/boneskull/projects/npm/cli/workspaces/arborist/lib/arborist/index.js
- /Users/boneskull/projects/npm/cli/workspaces/arborist/lib/index.js
- /Users/boneskull/projects/npm/cli/scripts/dependency-graph.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:126:16)
    at Object.<anonymous> (/Users/boneskull/projects/npm/cli/node_modules/make-fetch-happen/lib/fetch.js:6:21)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/boneskull/projects/npm/cli/node_modules/make-fetch-happen/lib/fetch.js',
    '/Users/boneskull/projects/npm/cli/node_modules/make-fetch-happen/lib/index.js',
    '/Users/boneskull/projects/npm/cli/node_modules/npm-registry-fetch/lib/index.js',
    '/Users/boneskull/projects/npm/cli/node_modules/pacote/lib/remote.js',
    '/Users/boneskull/projects/npm/cli/node_modules/pacote/lib/git.js',
    '/Users/boneskull/projects/npm/cli/node_modules/pacote/lib/fetcher.js',
    '/Users/boneskull/projects/npm/cli/node_modules/pacote/lib/index.js',
    '/Users/boneskull/projects/npm/cli/node_modules/@npmcli/metavuln-calculator/lib/index.js',
    '/Users/boneskull/projects/npm/cli/workspaces/arborist/lib/audit-report.js',
    '/Users/boneskull/projects/npm/cli/workspaces/arborist/lib/arborist/index.js',
    '/Users/boneskull/projects/npm/cli/workspaces/arborist/lib/index.js',
    '/Users/boneskull/projects/npm/cli/scripts/dependency-graph.js'
  ]
}

Node.js v22.7.0
ERRO Error: command failed
ERRO     at promiseSpawn (/Users/boneskull/projects/npm/cli/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
ERRO     at spawn (/Users/boneskull/projects/npm/cli/scripts/util.js:72:66)
ERRO     at /Users/boneskull/projects/npm/cli/scripts/util.js:119:10
ERRO     at main (/Users/boneskull/projects/npm/cli/scripts/resetdeps.js:24:9)
ERRO     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
ERRO     at async run (/Users/boneskull/projects/npm/cli/scripts/util.js:172:17)
ERRO cmd: node
ERRO args: . run dependencies --ignore-scripts
ERRO code: 1
```

### Expected Behavior

It should succeed 😄 

### Steps To Reproduce

1. `gh repo clone npm/cli`
2. `cd cli`
3. `node ./scripts/resetdeps.js`

### Environment

- npm: v10.8.3 (via `nvm`)
- Node.js: v22.7.0
- OS Name: macOS Sonoma 14.6.1
- System Model Name: MBP 2023 (M2 Pro)
- npm config:
```ini
; "user" config from /Users/boneskull/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; "project" config from /Users/boneskull/projects/npm/cli/.npmrc

package-lock = true

; node bin location = /opt/homebrew/Cellar/nvm/0.40.0/versions/node/v22.7.0/bin/node
; node version = v22.7.0
; npm local prefix = /Users/boneskull/projects/npm/cli
; npm version = 10.8.3
; cwd = /Users/boneskull/projects/npm/cli
; HOME = /Users/boneskull
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment]
for some reason It's installing and getting setup fine in my system ( MBP M1 Pro with 22.7 and 10.8.3 ). Could you please try to clone and run it at different location ? ( I know it's not related where it's installed but just in case.. )

**Comment by boneskull** [comment]
So, after cloning again and re-running the script, I noticed that it's actually deleting those files (you should see this in the original example):

```
INFO spawn git ls-files --cached --ignored --exclude-standard /Users/boneskull/projects/npm/cli/node_modules
INFO spawn git rm node_modules/@isaacs/cliui/build/index.cjs --force
rm 'node_modules/@isaacs/cliui/build/index.cjs'
INFO spawn git rm node_modules/@isaacs/cliui/build/index.d.cts --force
rm 'node_modules/@isaacs/cliui/build/index.d.cts'
INFO spawn git rm node_modules/@isaacs/cliui/build/lib/index.js --force
rm 'node_modules/@isaacs/cliui/build/lib/index.js'
INFO spawn git rm node_modules/make-fetch-happen/lib/cache/entry.js --force
rm 'node_modules/make-fetch-happen/lib/cache/entry.js'
INFO spawn git rm node_modules/make-fetch-happen/lib/cache/errors.js --force
rm 'node_modules/make-fetch-happen/lib/cache/errors.js'
INFO spawn git rm node_modules/make-fetch-happen/lib/cache/index.js --force
rm 'node_modules/make-fetch-happen/lib/cache/index.js'
INFO spawn git rm node_modules/make-fetch-happen/lib/cache/key.js --force
rm 'node_modules/make-fetch-happen/lib/cache/key.js'
INFO spawn git rm node_modules/make-fetch-happen/lib/cache/policy.js --force
rm 'node_modules/make-fetch-happen/lib/cache/policy.js'
INFO spawn git rm node_modules/smart-buffer/build/smartbuffer.js --force
rm 'node_modules/smart-buffer/build/smartbuffer.js'
INFO spawn git rm node_modules/smart-buffer/build/utils.js --force
rm 'node_modules/smart-buffer/build/utils.js'
INFO spawn git rm node_modules/socks/build/client/socksclient.js --force
rm 'node_modules/socks/build/client/socksclient.js'
INFO spawn git rm node_modules/socks/build/common/constants.js --force
rm 'node_modules/socks/build/common/constants.js'
INFO spawn git rm node_modules/socks/build/common/helpers.js --force
rm 'node_modules/socks/build/common/helpers.js'
INFO spawn git rm node_modules/socks/build/common/receivebuffer.js --force
rm 'node_modules/socks/build/common/receivebuffer.js'
INFO spawn git rm node_modules/socks/build/common/util.js --force
rm 'node_modules/socks/build/common/util.js'
INFO spawn git rm node_modules/socks/build/index.js --force
rm 'node_modules/socks/build/index.js'
```

I don't know why, but that's why `cache/policy.js` does not exist.  After the failure, the working copy looks like this:

```shell
❯ git status
On branch latest
Your branch is up to date with 'origin/latest'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    node_modules/@isaacs/cliui/build/index.cjs
	deleted:    node_modules/@isaacs/cliui/build/index.d.cts
	deleted:    node_modules/@isaacs/cliui/build/lib/index.js
	deleted:    node_modules/make-fetch-happen/lib/cache/entry.js
	deleted:    node_modules/make-fetch-happen/lib/cache/errors.js
	deleted:    node_modules/make-fetch-happen/lib/cache/index.js
	deleted:    node_modules/make-fetch-happen/lib/cache/key.js
	deleted:    node_modules/make-fetch-happen/lib/cache/policy.js
	deleted:    node_modules/smart-buffer/build/smartbuffer.js
	deleted:    node_modules/smart-buffer/build/utils.js
	deleted:    node_modules/socks/build/client/socksclient.js
	deleted:    node_modules/socks/build/common/constants.js
	deleted:    node_modules/socks/build/common/helpers.js
	deleted:    node_modules/socks/build/common/receivebuffer.js
	deleted:    node_modules/socks/build/common/util.js
	deleted:    node_modules/socks/build/index.js
```

**Comment by boneskull** [comment]
I'm thinking my global `.gitignore` might be the problem.

**Comment by boneskull** [comment]
Yes.  It contained `build`.

**Comment by boneskull** [comment]
(If there's anything to be done here, it might be providing `git ls-files` a flag that says "do not consider user-or-system-level gitignore files"--if such a thing exists)
