### ISSUE TITLE
[BUG] An error (or not)

### ISSUE THREAD

**Issue by ghost** [npm/cli#932]
I tried to install the  **react-native-cli** globaly as sudo, but it's return an error. So, i reinstall the NPM and NodeJS but the error persists.

My O.S.: Ubuntu 19.04

> npm ERR! Linux 5.3.0-28-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "react-native-cli"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! code EMISSINGARG
> 
> npm ERR! typeerror Error: Missing required argument #1
> npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
> npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
> npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
> npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
> npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
> npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
> npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
> npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
> npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
> npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
> npm ERR! typeerror This is an error with npm itself. Please report this error at:
> npm ERR! typeerror     <http://github.com/npm/npm/issues>
> npm ERR! Linux 5.3.0-28-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "react-native-cli"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! code EMISSINGARG
> 
> npm ERR! typeerror Error: Missing required argument #1
> npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
> npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
> npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
> npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
> npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
> npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
> npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
> npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
> npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
> npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
> npm ERR! typeerror This is an error with npm itself. Please report this error at:
> npm ERR! typeerror     <http://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/eike/npm-debug.log

My npm-debug.log: https://pastebin.com/KYtSbdE7

**Comment by ghost** [comment]
So, i discovered my npm and nodejs version is so old and in a update i solved it.
