### ISSUE TITLE
Invalid package name "buffer 2"

### ISSUE THREAD

**Issue by perazzo** [npm/cli#959]
If I try to install any package, it is returning the error:

```
Unhandled rejection Error: Invalid package name "buffer 2": name can only contain URL-friendly characters
    at invalidPackageName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:82:15)
    at Result.setName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:118:11)
    at new Result (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:107:23)
    at Function.resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:54:15)
    at computeVersionSpec (/usr/local/lib/node_modules/npm/lib/install/deps.js:311:21)
    at Installer.normalizeCurrentTree (/usr/local/lib/node_modules/npm/lib/install.js:404:68)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at iferr (/usr/local/lib/node_modules/npm/lib/install.js:362:5)
    at a (/usr/local/lib/node_modules/npm/node_modules/iferr/iferr.js:3:64)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:27:18)
    at exports.getAllMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:219:3)
    at Installer.loadArgMetadata (/usr/local/lib/node_modules/npm/lib/install.js:360:3)
    at /usr/local/lib/node_modules/npm/lib/install.js:695:16
    at BB.join.then (/usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:34:16)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```

**Comment by w3dg** [comment]
it is highly likely that the package with that name doesn't exist. i was able to find package called 'buffer2' or 'buffer-2' but no 'buffer 2'.

**Comment by ljharb** [comment]
A space is invalid in package names.

**Comment by debopamgupta** [comment]
ah yes that also makes sense!
