### ISSUE TITLE
[BUG] Maximum call stack exceeded

### ISSUE THREAD

**Issue by sfreitas9** [npm/cli#985]
# What / Why
Received Maximum call stack exceeded error

## When
March 5, 2020

## Where
* n/a

### Current Behavior
get error:
Unhandled rejection RangeError: Maximum call stack size exceededill install loadIdealTree
    at Array.forEach (<anonymous>)
    at copyModuleList (/Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:22:15)
    at copyTree (/Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:14:3)
    at /Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:23:20
    at Array.forEach (<anonymous>)
    at copyModuleList (/Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:22:15)
    at copyTree (/Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:15:3)
    at /Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:23:20
    at Array.forEach (<anonymous>)
    at copyModuleList (/Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:22:15)
    at copyTree (/Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:14:3)
    at /Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:23:20
    at Array.forEach (<anonymous>)
    at copyModuleList (/Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:22:15)
    at copyTree (/Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:15:3)
    at /Users/s0f0204/.nvm/versions/node/v10.16.0/lib/node_modules/npm/lib/install/copy-tree.js:23:20

npm ERR! cb() never called!

### Steps to Reproduce
run `npm i` in my project directory

### Expected Behavior
successfully install packages

## Who

* n/a

## References

* n/a

**Comment by DanielRuf** [comment]
Hi @sfreitas9,

what is your current npm version?

**Comment by sfreitas9** [comment]
Typically 6.9.0, but sometimes I use 6.13.4.

 

I ended up blowing away the directory and reinstalling everything and it worked.

**Comment by DanielRuf** [comment]
Thanks for the feedback.

Ok so it seems this issue is resolved?
If this is the case please close it.

**Comment by sfreitas9** [comment]
I blew away the directory and started over and it worked.  closing this issue
